### ISSUE TITLE
After changing (insert, delete) the list of available search engines, the list stays the same. 

### ISSUE THREAD

**Issue by Codereamp** [mozilla-mobile/focus-android#4735] opened 2021-03-18 20:32 UTC
## Steps to reproduce
- Go to Settings-Search-Search engine "Add another search engine" 
- Add valid search engine 
- Tap "Save"
- See the message "New search engine added"
(Alternative action can be deleting existing search engines)

### Expected behavior
- New list should contain the newly created item (or list without removed items)

### Actual behavior
- The list stays the same (until forced restart)

### Device information
Meizu M6 Note

* Android device: Android 7.1.2
* Focus version: 8.13.1(build #350532255 86.0-20210222142601)

**Comment by ebalazs-sv** [comment] 2021-03-19 06:29
This issue is reproducible on Focus 8.14.0 with Pixel 2 (Android 9).

**Comment by lobontiumira** [comment] 2021-04-21 09:32
Reproducible on Focus 8.15.1 with Samsung Galaxy Note 8 (Android 9).
Cannot remove any of the existing search engines. Cannot restore the default search engine.

**Comment by ebalazs-sv** [comment] 2021-05-05 11:15
This issue is reproducible on Focus 8.15.3 GV 88 with Huawei P9 Lite (Android 7).

**Comment by edaigle** [comment] 2021-06-04 16:40
I can no longer reproduce this on the current dev build from main - search engines seem to be added/removed as expected.

**Comment by lobontiumira** [comment] 2021-07-08 13:05
Still reproducible on 8.17.0 build with OnePlus 5T (Android 10).

**Comment by lobontiumira** [comment] 2021-07-27 13:41
I was not able to reproduce this issue.
I was able to delete search engines, and to add new ones, to delete the new ones added, to restore the default search engines.
Tested on the 8.18.0-rc.1 build with HTC 10 (Android 8), Google Pixel (Android 10), and Samsung Galaxy Tab A6 (Android 5.1.1).
I'm closing it.

**Closed by lobontiumira** 2021-07-27 13:41 UTC
Labels: bug
