### ISSUE TITLE
The app is blocked in some inconsistent state when closed too fast after clean up

### ISSUE THREAD

**Issue by MikkCZ** [mozilla-mobile/focus-android#2006] opened 2017-12-18 10:01 UTC
STR:
1. Open any website and do some browsing (e.g. open Google, search "test", visit a link)
1. Tab the clear (trash bin) icon and the Android home button fast in the order.
1. Open the app again. Now it's in some inconsistent state, where:
-- The area for content is blank.
-- The address bar still contains the last URL.
-- The address bar does not react on any actions (the app is unusable).
-- The only way out of it is to close the app from the Android multitasking mode.

I can reproduce this for the last few BuddyBuilds (currently build #13481449).

**Comment by mcomella** [comment] 2017-12-19 20:50
I was able to reproduce.

I think this might be happening because we're listening to several observers at once which may get into an inconsistent state when we both trash can and go home. I think we can fix this by trying to make each of these interactions transactional (if it's possible).

**Comment by MikkCZ** [comment] 2017-12-20 13:36
Btw. I have tested with Stealth mode off now. The result is the same, but in the Android multitasking view I also see the last page content there.

**Comment by ekager** [comment] 2018-08-30 17:04
Should be closed in #3251

**Closed by ekager** 2018-08-30 17:04 UTC
Labels: P3
