### ISSUE TITLE
Regression: blank About screen with latest update

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/focus-android#4299] opened 2019-06-18 06:28 UTC
Today I received a update from Firefox Klar 8.0.6 to 8.0.15 via Google Play Store. After this update the About screen no longer works whit GeckoView enabled.

### Steps to reproduce

1. install Firefox Klar / Focus 8.0.15
2. make sure that GeckoView is enabled, it works without GeckoView
3. open the About page

### Expected behavior

You see the content of the About page.

### Actual behavior

You can see the title bar with the back arrow, but the content area is white and without content.

### Device information

* Android device: HTC U11 / Android 8.0
* Focus version: Firefox Klar 8.0.15 with GeckoView enabled

**Comment by arjav2002** [comment] 2019-06-18 07:19
Is Klar not available for Android 6?

**Comment by cadeyrn** [comment] 2019-06-18 07:34
Please don't misuse my bug report for totally unrelated questions, thank you.

**Comment by arjav2002** [comment] 2019-06-18 07:49
Does this issue occur with a repo build?

**Comment by arjav2002** [comment] 2019-06-18 07:52
Could you post a link to the install? I can't find it.

**Comment by arjav2002** [comment] 2019-06-18 07:55
Klar is not available in my country. Which one are you in so that I can use a proxy?

**Comment by arjav2002** [comment] 2019-06-18 07:56
This issue has been fixed in Version 9.0 Build 11

**Comment by arjav2002** [comment] 2019-06-18 07:59
I am not able to reproduce the issue on cloning the repo and building it. Version 9.0 (Build 11)

**Comment by cadeyrn** [comment] 2019-06-18 07:59
This issue is not about version 9.0 but 8.0.15 which is distributed via the Google Play Store.

**Comment by arjav2002** [comment] 2019-06-18 08:01
Then it was probably fixed in Version 9.0 which is not yet up on Google Play Store?

**Comment by arjav2002** [comment] 2019-06-18 08:08
I'm very sorry, but could you please tell me how to look at specifically that branch in Android Studio? The clone link seems to be the same as the master branch. I've already cloned the master branch.

**Comment by arjav2002** [comment] 2019-06-18 09:54
How do I make sure that GeckoView is enabled?

**Comment by cadeyrn** [comment] 2019-06-18 10:14
Enter focus:test into the address bar, press enter und enable the "Use new renderer?" toggle.

**Comment by cadeyrn** [comment] 2019-06-18 21:57
Last good revision: 1c1b6638dad7e0f38e8543aad98520ed8f755eea
First bad revision: ac974e132b79c007c49336545b320b5cfad851de

Caused by: https://github.com/mozilla-mobile/focus-android/commit/ac974e132b79c007c49336545b320b5cfad851de

To be more precise: It's caused by the switch from GV Nightly 68.0.20190520095418 to GV Beta 68.0.20190604110028. Reverting only this change from the mentioned commit "fixes" the issue.

**Comment by cadeyrn** [comment] 2019-06-18 22:09
I further bisected. It works with latest revision from v8 branch and GV downgraded to GV Beta 20190520141152. GV Beta 68.0.20190527103257 is the first GV version which causes this bug.

I hope this helps.

**Closed** 2019-09-20 17:52 UTC
