### ISSUE TITLE
Integrate HTTPS Everywhere

### ISSUE THREAD

**Issue by zekooooo** [mozilla-mobile/focus-android#4577] opened 2020-06-23 17:42 UTC
HTTPS Everywhere is a Firefox addon by EFF which automatically redirects all HTTPS-capable websites from http:// to https://

Integrating this addon or implementing it in FF Focus/Klar would go a great way toward the security of users on public Wifi and on ISPs in authoritarian countries. It would also save already security-savvy users from having to prepend "https://" to the URL when typing in a domain manually.

**Comment by cadeyrn** [comment] 2020-06-23 17:48
Firefox Focus has no add-on support at all so it's not possible to integrate this (or every other) add-on. And to be honest I don't think that add-on support is in scope for Firefox Focus. Firefox Focus is limited by design, Fenix is a more feature-rich browser with add-on support - and it already supports HTTPS Everywhere.

**Comment by 4ut0-M-4t** [comment] 2020-06-25 21:59
@**zekooooo**, you can incert `user_pref("dom.security.https_only_mode", true)` in your `prefs.js` file or create hardened `user.js` with the help of [this guide](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.6-Firefox-Android).

**Comment by zekooooo** [comment] 2020-07-01 17:29
@cadeyrn - Focus/Klar is at 180MB the biggest browser I have on my device. The only difference between it and other FF browsers is that it doesn't lag with JS disabled. Therefore I don't see bloat as a reason why a security feature like this shouldn't be implemented.

@4ut0-M-4t - Thanks for the suggestion! Are you sure that this is possible on Focus/Klar on an unrooted phone?

**Comment by cadeyrn** [comment] 2020-07-01 17:37
Fenix has a bigger file size than Focus but I don't know why you mention me and talk about file size and "bloat" because my comment was not about these things at all.

**Comment by zekooooo** [comment] 2020-07-02 18:45
Cadeyrn sorry I thought it was normal etiquette - you said something to me and I wrote a belated response to you.

You were talking about scope and what is the programmers' intent behind Focus, Preview etc. I'm talking about what the practical differences are for a regular user like me. Non-WebView and non-GeckoView Firefox is simply too damn slow with any script blocker on old and/or non-flagship phones. Hence my extra interest in improving the security of Focus/Klar's GeckoView.

Re: addon thing, I'm aware that Focus/Klar doesn't support addons, so it can't be added like Pocket to the desktop browser. However the functionality can  still be replicated by writing the code from scratch, in the worst case. Of course, it would be more work than just adding an add-on. Is there anything beyond scope as a reason why this security add-on functionality shouldn't be added to Mozilla's only fast Android web engine?

**Comment by J0WI** [comment] 2020-08-10 18:35
[Duplicate](https://github.com/mozilla-mobile/focus-android/issues/1383#issuecomment-331847040) of #596

**Comment by samiuljoy** [comment] 2020-08-27 08:38
> @**zekooooo**, you can incert `user_pref("dom.security.https_only_mode", true)` in your `prefs.js` file or create hardened `user.js` with the help of [this guide](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.6-Firefox-Android).

Is it possible to pull and push the files using **adb**. This is super fascinating! Imagine using *adb* to tweak prefs.js/user.js without root!

**Comment by lobontiumira** [comment] 2022-03-18 09:18
Currently, in the latest Focus builds, the user has the HTTPS-Only mode available in three-dot menu - Settings - Privacy & Security - Security section.
I'll close this ticket.

**Closed by lobontiumira** 2022-03-18 09:18 UTC
