### ISSUE TITLE
"Entendi" button is not functional on "Cookies permission" popup 

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla-mobile/focus-android#6034] opened 2021-12-10 10:35 UTC
## Steps to reproduce
1. Navigate to https://www.mercadolivre.com.br/
2. Scroll down the page to view the entire "Cookies permission" popup. 
3. Tap "Entendi" button.
4. Observe behavior.

### Expected behavior
The popup is dismiss and the site can be browsed.

### Actual behavior
Nothing happens, the popup remains displayed.

### Device information

* Android device: Google Pixel 5 (Android 11) - 1080 x 2340 pixels, 19.5:9 ratio (~432 ppi density) 
* Focus version: Firefox Focus 95.1.0 (🦎 95.0-20211129150630) 

### Note:
1. The issue is not reproducible on Firefox Nightly.
2. The issue is still reproducible on Firefox Focus regardless of the ETP status.
4. This was previously reported here: https://github.com/webcompat/web-bugs/issues/96249
5. Gif attached.

![BtnBroken](https://user-images.githubusercontent.com/12184325/145560325-d6806526-303a-4ada-8685-a08561ad7800.gif)

**Comment by ionutbedregeanu** [comment] 2021-12-23 10:26
@softvision-oana-arbuzov You can still reproduce this?

**Comment by lobontiumira** [comment] 2021-12-23 13:15
I was not able to reproduce this issue on the RC 95.2.0 build with Google Pixel (Android 10).
I'll close this ticket.
@softvision-oana-arbuzov feel free to re-open if this issue occurs on your device.
Thank you!

**Closed by lobontiumira** 2021-12-23 13:15 UTC

**Comment by softvision-oana-arbuzov** [comment] 2021-12-23 15:39
@ionutbedregeanu I can't reproduce it either.
 
**Tested with:**
Browser / Version: Firefox Focus Release 95.2.0 (🦎 95.0-20211215221728), Firefox Focus Nightly 97.0 (🦎 97.0a1-20211222092845) 
Operating System: Google Pixel 5 (Android 12) - 1080 x 2340 pixels, 19.5:9 ratio (~432 ppi density), Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density)
