### ISSUE TITLE
Via VPN: Focus can't download any files

### ISSUE THREAD

**Issue by jerryn70** [mozilla-mobile/focus-android#1571] opened 2017-10-27 08:17 UTC
When VPN is ON focus can't download any files. Apk, mp4 , jpg etc all types.
Save image option also not working.

Focus version 2.2
Android version 7.1.1

**Comment by pocmo** [comment] 2017-10-27 08:49
Can you elaborate a bit more what steps you follow and at what point something doesn't work? I just tried to reproduce it on my device; but it just works.

**Comment by jerryn70** [comment] 2017-10-27 09:01
When i long press on a image it shows save image option. But when i click save image option nothing happens. Normally the app should download the image when we click on that option. 

I have reinstalled the app and check still same issue. All permission are correctly granted

**Comment by pocmo** [comment] 2017-10-27 09:02
Can you check whether Focus has the "Storage" permission. I wonder if you have ever denied the permission and checked "Do not ask again"? I think in this case we might not show any hint to the user that we are unable to download the image.

**Comment by pocmo** [comment] 2017-10-27 09:04
> I have reinstalled the app and check still same issue. All permission are correctly granted

Did Focus prompt for the Storage permission before doing nothing?

**Comment by jerryn70** [comment] 2017-10-27 09:06
Yes, focus asked permission and I have granted .

**Comment by jerryn70** [comment] 2017-11-02 10:17
I think Its a android 7  related bug. When vpn is enabled we can't download any files from play store Firefox focus etc. If vpn is disabled everything is working great.

**Comment by pocmo** [comment] 2017-11-02 10:27
@jerryn70 Thank you for investigating! And just to be sure: Is this for *all* images? Or only on specific pages?

**Comment by pocmo** [comment] 2017-11-02 10:28
@jerryn70 And: Are downloads working over VPN?

**Comment by jerryn70** [comment] 2017-11-02 10:35
Downloading is not working with all type of images. And download is not working with apk,mp4,mp3  etc. 

Nothing can be downloaded with focus if VPN is ON. 

I need to turn off VPN to download . 

I have tested brave browser, but brave has no such problems.

**Comment by pocmo** [comment] 2017-11-02 11:20
Thank you, @jerryn70. I guess with that we can try to reproduce this with other VPNs and see if we can reproduce this.

Do you have experience using the Android development tools, especially logcat? It might be helpful to get the device log of a "failed download" to see what happens behind the scenes:
https://developer.android.com/studio/command-line/logcat.html

**Comment by jerryn70** [comment] 2017-11-10 09:11
Focus uses androids inbuilt download manager to download files and Brave uses its own download manager.   I have tried some other apps that uses androids inbuilt download manger and found that they are also not able to download files.



We need an inbuilt download manager to solve this issue.

**Comment by jerryn70** [comment] 2017-12-14 06:28
Can we have something like this to solve this issue ? Or option to download via other browser (browser name) or using 3rd party download manager
![](https://i.imgur.com/Gb2BOn0.jpg)
![](https://i.imgur.com/nUciUyj.jpg)

**Comment by mcomella** [comment] 2017-12-19 22:58
> Can we have something like this to solve this issue ?

Unfortunately, we triaged this to a P5 which means we'd take a patch for it but the team would like to focus on higher priority issues in the near future (e.g. we don't know how many of our users use Focus exclusively with VPNs).

> Or having an option to download via 'other browser' (browser name) or using 3rd party download manager

While I'm not sure if this fixes your use case (I apologize but I'm short on time and can't read the full backscroll), you can choose to open a particular page with another browser/app, from there you can click on the download you'd like to make.

**Comment by SubhrajyotiSen** [comment] 2018-08-03 06:16
I tried using Proton VPN with the latest 6.3 nightly and I was able to download images.

**Comment by youri--** [comment] 2018-08-16 16:04
Still can't download when VPN is on, but the only reason VPN is even on, is because I use DNS66, which is a DNS-based adblocker which uses VPN to change DNS lookups for blacklisted domains.

As soon as I pause DNS66, the VPN is closed and downloading works again.

With DNS66 I can block a lot more than just by using Focus. It's a great combination. Hope this gets fixed.

**Comment by lobontiumira** [comment] 2021-09-28 14:24
@jerryn70, @youri-- are you able to reproduce this issue on the 92.1.1 RC build?
Thank you!

**Comment by youri--** [comment] 2021-09-28 14:36
> @jerryn70, @youri-- are you able to reproduce this issue on the 92.1.1 RC build? Thank you!

Whoops, my apologies, forgot to comment with an update. This was fixed for me a long time ago (and still working fine). At one point I switched from DNS66 to Blokada, but they both operate on the same principle, routing DNS requests through a local VPN tunnel.. At some point after an update, Focus downloads just started working. They've been working fine ever since. At least a year, possibly quite a bit longer. But even though I'm still on the same phone, I've also since upgraded Android from 9 to 10, and then to 11. Pretty sure when I had difficulties I was on A9 and I've been on A10 since about December 2019. I think it started to work after a Focus update, though it could've been an Android update. Sorry I can't be of more help.

**Comment by jerryn70** [comment] 2021-09-28 14:59
@lobontiumira sorry now am not using this browser. I think the issue has been fixed according to @youri s comment. So maybe we can close this issue.

**Comment by sebilm** [comment] 2021-09-28 17:12
I just tried it on my Galaxy S7 with version 92.1.1 in conjunction with Blokada and it worked. Previously it did not work on this smartphone with Blokada VPN. So I think, it is fixed.

**Comment by lobontiumira** [comment] 2021-09-29 05:54
Thank you all for the quick responses.
I'll close this issue based on your comments.

**Closed by lobontiumira** 2021-09-29 05:54 UTC
Labels: bug, help wanted, P5
