### ISSUE TITLE
Open with "Firefox with TP on"

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#2038] opened 2018-01-08 15:37 UTC
Enhancement Request: Great app... my default browser...I would like to regularly "Open With" URL from Focus to "Firefox Private Tab" to preserve Tracking Protection. I know "Chrome Incognito Tab" can be spawned from some programs, I think it would be great for similar feature in Firefox. I would use it regularly from Focus.  Thanks.

**Comment by Biskvit** [comment] 2018-01-15 10:10
Sounds like an interesting idea. However, if Firefox (be it stable, beta, nightly, dev, or fennec) is not detected, the option should probably be hidden as to not clutter the 3-dot menu any further.
The first time a version supporting this is ran, or on the first run of Firefox Focus ever, the user should be notified about this possibility in the introduction -- this option shouldn't be totally buried and obscure. It should get some toggles in the app settings, too. For example, some people may want to open the page they were browsing in an ordinary tab, not a private one.

**Comment by pocmo** [comment] 2018-02-22 17:21
@bbinto Duplicate of #195? For #195 we landed code in Firefox to open a private tab from a third-party app.

We should make sure that we are not annoying users. Imagine switching to the full browser because something doesn't work in Focus or you want to use your cookies etc. and then you end up in a private tab again.

**Closed** 2018-03-16 14:43 UTC
