### ISSUE TITLE
nimbus_initial_fetch is generating Invalid State errors

### ISSUE THREAD

**Issue by ionutbedregeanu** [mozilla-mobile/focus-android#7256] opened 2022-06-21 13:24 UTC
### Prerequisites:
- Have a Focus for Android build with the following modifications:
      - The following lines added to local.properties:
     nimbus.remote-settings.url = https://settings.stage.mozaws.net
     debuggable = true
      - A new “.nimbus” file (in the same location as local.properties) containing the following line: https://settings.stage.mozaws.net/
- Have a Focus for Android Nimbus experiment using the onboarding feature which sets “is-enabled” to true launched to Stage Live.

### Investigation steps:
1. Install the latest build of Firefox Nightly
2. Check if nimbus_initial_fetch metric: 
   - measures correctly the time spent to download the nimbus experiments 
   - is generating Invalid State errors -> One way to check this would be in unit-tests using [https://mozilla.github.io/glean/book/reference/metrics/timespan.html#testgetnumrecordederrors](https://mozilla.github.io/glean/book/reference/metrics/timespan.html#testgetnumrecordederrors)

**Comment by ionutbedregeanu** [comment] 2022-06-23 07:35
Note for QA: Please check if nimbus_initial_fetch:
- doesn't record invalid state errors 
- measures correctly the time spent to download the nimbus experiments

**Comment by heres-maria** [comment] 2022-07-04 14:15
@ionutbedregeanu I have read the available documentation and have the following questions:
- Is there a way for manual QA to reliably verify that nimbus_initial_fetch correctly measures the time spent to download the nimbus experiments? I am unsure how to accurately verify this requirement. 
     -  Are there any logs that we can use to determine when exactly the download starts and ends?
- Could you please provide a list or description of what the possible invalid state errors would look like? 
     - Would they be visible in logcat or the [Glean viewer](https://debug-ping-preview.firebaseapp.com/)?

**Comment by ionutbedregeanu** [comment] 2022-07-05 09:35
1. I searched for some public logs, but I didn't find, so I don't see a way either. Maybe just to give you a debug build with some custom logs
2. Invalid State error is recorded when: start is called multiple times or stop is called without start on timing metrics
https://mozilla.github.io/glean/book/reference/metrics/timespan.html#testgetnumrecordederrors
I'm not sure if they are visible in [Glean viewer](https://debug-ping-preview.firebaseapp.com/), maybe @travis79 can help us with more details here

**Comment by travis79** [comment] 2022-07-05 12:40
I think the only time you would see Nimbus log messages around fetching would be if there was an error encountered. You _could_ make use of the [Nimbus `onExperimentsFetched` Observable](https://github.com/mozilla/application-services/blob/51a2364666d6995577972397f2f39890ab3eb67b/components/nimbus/android/src/main/java/org/mozilla/experiments/nimbus/Nimbus.kt#L217) inside of the application and add your own log messages when the observer is notified.

As to how to reliable verify the measurement: I would definitely include some unit testing to ensure the recording code is working and to protect from regressions. To verify the actual data, I recommend using the [Glean debugging tools](https://mozilla.github.io/glean/book/user/debugging/android.html) to view the data in the log or in the Glean Debug View. You will need to manually trigger a metrics ping once you have some measurements, unless you want to wait a day for Glean to send it on schedule, but you should be able to see the timing data in the ping then. As to what to compare it to for validation? I would recommend a couple of approaches: Get lots of measurements to ensure that they all within a reasonable distance from each other, and are reasonable for a network request with a download of content, and to connect to the experiment endpoint with an independent system (Like Firefox Desktop, looking at devtools for the Network timings) to compare to your measurements in the app. This is very manual, but should only need to be performed once while instrumenting this new metric.

@ionutbedregeanu is correct that using the Glean test function to retrieve the number of errors is a good way to determine if you are raising any during unit tests. For the manual testing, you can just use the Glean debug tools, the errors are just Glean metrics that are sent along in the same ping with the data recording that triggered the error. The Timespan "Invalid State" means you have either started a Timer that was already started, or stopped one that hasn't been started yet. Neither of these errors indicate "corrupted" or bad data, just that the logic of the recording isn't taking care to ensure the timer is active/inactive before calling stop/start on it.

**Comment by ionutbedregeanu** [comment] 2022-07-07 06:49
Just a note: After [this pr](https://github.com/mozilla-mobile/focus-android/pull/7332) nimbus_initial_fetch should be recorded only at fresh install

**Comment by heres-maria** [comment] 2022-07-12 13:07
I have finished the investigation. I am including some of the [results here](https://docs.google.com/spreadsheets/d/18vPYAdrv7bI8HoRCWQry68GOnyJhTF1fButGiMj5tH0/edit?usp=sharing). 

- There were no pings containing “invalid” displayed for any cases.
- The nimbus_initial_fetch metric is registered at the first startup. The values for the latest version of the application seem to not display outliers. The values are close to 2000 milliseconds, both slightly lower and higher values were observed.
- While observing logcat, I intermittently encountered instances where the ping was copied at startups other than the first with the same value as for the initial startup, but I was unable to reproduce it when observing the Glean viewer exclusively. I have filed issue https://github.com/mozilla-mobile/focus-android/issues/7350 for this.
- There was also one instance where the metric was not registered at all at the first startup, but I was unable to reproduce it more than once.
- nimbus_initial_fetch is not registered at all if the first startup was performed with no internet connection. The second startup does not trigger it. @ionutbedregeanu Is this expected?
- The values of nimbus_initial_fetch seem to be roughly the same for cases where experiments are available (5 experiments) as well as when no experiments are available in the collection. @ionutbedregeanu Is this expected?

Final tests performed on Focus Nightly 104.0a1 (Build #361921026 GV 104.0a1-20220710094429) AC: 104.0.20220710143147, 9904639da7, AS: 93.5.0 using Android 9 - Samsung Galaxy S8.

**Comment by ionutbedregeanu** [comment] 2022-07-13 06:38
1. Some experiments are needed from the first run, so in my opinion that scenario without internet connection is expected
2. Maybe we should not record nimbus_initial_fetch if the list is empty even if it doesn't affect the arithmetic mean

**Comment by heres-maria** [comment] 2022-07-25 09:32
Based on the previous comments, I will close this issue as verified fixed.

**Closed by heres-maria** 2022-07-25 09:32 UTC
Labels: QAReady
