### ISSUE TITLE
Consider allowing users to ignore SSL errors via prompt

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#1563] opened 2017-10-26 00:23 UTC
* UX: #1616

---

When there's an SSL error, we currently show:

![screenshot_1508977136](https://user-images.githubusercontent.com/759372/32029328-a4843150-b9a8-11e7-9db0-7e38effb33ec.png)

Desktop browsers often let the user ignore SSL errors, however:

<img width="1105" alt="screen shot 2017-10-25 at 17 02 35" src="https://user-images.githubusercontent.com/759372/32029339-b1d3ae80-b9a8-11e7-9119-762132816a7e.png">

We should consider doing something similar.

One option would be to encourage users to go to a different browser to ignore SSL errors so Focus can try to protect the user. Note: as far as I can tell, we don't cache intermediate CAs, which means we're more likely to get SSL errors than other browsers (investigation in #1338).

Here's the same issue on iOS: https://github.com/mozilla-mobile/focus-ios/issues/238

**Comment by mcomella** [comment] 2018-01-08 22:40
Throwing back to triage because #2039 was filed.

**Comment by vesta0** [comment] 2018-11-14 00:59
Duplicate of #1616

**Closed by vesta0** 2018-11-14 00:59 UTC
Labels: Geckoview🦎, P2, UX, feature, ready for Eng breakdown
