### ISSUE TITLE
Delete Tabs

### ISSUE THREAD

**Issue by Achintya999** [mozilla-mobile/focus-android#1384] opened 2017-09-25 07:21 UTC
There must be a feature to delete tabs currently it will delete all the tabs that are opened but there must be a feature to delete the tab that we wanted to delete.

**Comment by pocmo** [comment] 2017-09-25 10:44
Duplicate of #1362.

Note that by navigating back with the "back" button you'll eventually close the current tab.

**Closed by pocmo** 2017-09-25 10:44 UTC
