### ISSUE TITLE
[L10N] "Your Rights" page cannot be scrolled on certain languages.

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5842] opened 2021-11-10 14:28 UTC
## Steps to reproduce
1. Change your device language to Russian, Spanish.
2. Go to Settings->Mozilla->Your Rights.
3. Try scrolling down on the page on Portrait mode.

### Expected behavior
The use can scroll on the page, to display the entire text.

### Actual behavior
On certain languages, extra rows are added, and the text does not fit on the page. The page cannot be scrolled on Portrait mode.

### Device information
* Android device: Huawei P9 Lite (Android 8), Sony Xperia Z5 (Android 7).
* Focus version: Beta 95.0.0-beta.4 (Build 353140212 GV 95.0-20211109194756).

https://user-images.githubusercontent.com/89388888/141130914-564aec3d-679a-49c8-92e4-50f9b7d6bc23.mp

https://user-images.githubusercontent.com/89388888/141131090-80f12064-5a6e-4e23-9cc4-c6d80cc31c78.mp4

**Comment by lobontiumira** [comment] 2021-12-29 13:12
I was not able to reproduce this issue on the RC 95.2.0 with Sony Xperia Z5 Premium (Android 7.1.1) with Russian, or Spanish.
I'll close this issue.

**Closed by lobontiumira** 2021-12-29 13:12 UTC
Labels: bug, l10n
