### ISSUE TITLE
`ui-test-x86-debug` fails with `unconclusive` test results

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/focus-android#6492] opened 2022-02-22 15:51 UTC
Seems like a recent change (maybe supporting api 30 in tests) will have `ui-test-x86-debug` failing and potentially blocking from merging new PRs including the ones for integrating new AC versions. Eg:
- https://github.com/mozilla-mobile/focus-android/pull/6490
- https://github.com/mozilla-mobile/focus-android/pull/6411
- https://github.com/mozilla-mobile/focus-android/pull/6484

This might need a deeper investigation.
@sv-ohorvath  @AaronMT

**Comment by AaronMT** [comment] 2022-02-22 21:18
Thanks for filing. This is a duplicate of https://github.com/mozilla-mobile/focus-android/issues/6428

I have a ticket open with Google as it's an Firebase Test Lab infrastructure related issue.

> HI Aaron, 
> 
> Thank you for your patience, After speaking with Daming this is a known issue within the Testing Infrastructure team for which there is an active ticket and ongoing investigation. The test matrix ID's you have provided have been noted and the product team has been made aware of your specific case. 
> 
> At this time, there is no mitigation available, and I will continue to provide you with updates as they become available on my end. Please let me know if you have any questions in the meantime. 
> 
> Best, 
> 
> Desmon

**Comment by jonalmeida** [comment] 2022-02-22 22:22
Landing that here: https://github.com/mozilla-mobile/focus-android/pull/6496

**Closed by jonalmeida** 2022-02-22 22:22 UTC
