### ISSUE TITLE
Backspace in URL search bar skips last character if URL autocomplete present

### ISSUE THREAD

**Issue by rickydam** [mozilla-mobile/focus-android#3892] opened 2018-11-13 17:49 UTC
## Steps to reproduce
1. Build `focus-android` in Android Studio or install `Firefox Focus` from the Play Store
2. Open the app
3. Tap on `SKIP` on the top left
4. Type `moz` into the URL search bar (the autocomplete should show `illa.org` highlighted in pink)
5. Press backspace
6. Press backspace again

### Expected behavior
The first backspace erases the `z` and the second backspace erases the `o`.
The URL search bar should now show `m`.

### Actual behavior
The first backspace skips the `z` and the second backspace erases the `o`.
The URL search bar now shows `mz`.

### Device information
* Android device: OnePlus5T, Oreo 8.1.0
* Focus version: 7.0.13 (Latest Play Store version as of Nov 13, 2018) and v8.0 build#11

### Extra information
* Keyboard: Gboard v7.7.12.219989447-release-arm64-v8a (Latest Play Store version as of Nov 13, 2018)
* All my autocorrect options are off except auto-capitalisation.

`Would you like to turn on search suggestions?` pop up by `Firefox Focus` is there and left untouched.

Different but related to closed issue https://github.com/mozilla-mobile/focus-android/issues/778 and closed pull request https://github.com/mozilla-mobile/focus-android/pull/2304

Video: https://drive.google.com/file/d/1vlAPMb1N7O1MdVOzL80ZWMq_mNoCRwB1/view?usp=sharing

**Comment by ekager** [comment] 2018-11-15 01:29
Ah at first I thought this was the same as #778, but now I'm understanding what you're seeing. 

STR:
1. autocomplete is on, type "moz", it autocompletes to mozilla.org
2. Press delete

Expected behavior: 
URL bar says "moz" again with your cursor at the end

Actual behavior: 
URL bar says "moz" with your cursor between 'o' and 'z'

@vesta0 I'm moving this to a P1.

**Comment by sv-ohorvath** [comment] 2018-11-23 14:23
I can still reproduce this on Nightly & Beta 8.0.1 if I turn off everything related to Gboard auto-correct. If they are on, this doesn't happen.
[Recording](https://drive.google.com/file/d/1U1tZZufBvkmKzNzvgyqpnZ5vQgBTfWZi/view?usp=sharing)

**Comment by sblatz** [comment] 2018-11-27 15:32
Note: this only seems to happen if an autocompleted URL is presented.

**Comment by sblatz** [comment] 2018-11-27 18:30
I confirmed this is an android component issue, as I'm able to reproduce on the reference browser. Filed here: https://github.com/mozilla-mobile/reference-browser/issues/294

**Comment by pocmo** [comment] 2018-11-27 18:47
Quick question about the priority: Since this seems to be confirmed for both 8.0 and the already released 7.0.x (and I wouldn't be surprised if earlier versions too): Is this indeed a release blocker?

**Comment by sblatz** [comment] 2018-11-27 19:38
Good point, @pocmo. Pinging @vesta0.

**Comment by vesta0** [comment] 2018-11-27 19:49
@pocmo I agree and removed the label release blocker but this is still high priority. Thanks for looking into it.

**Comment by vesta0** [comment] 2019-01-03 20:02
@Sdaswani @mcomella yes it is. I didn't consider it to be a release blocker but it is definitely high priority and needs to be fixed. Thank you!

**Comment by pocmo** [comment] 2019-01-08 13:34
A patch for that landed in 0.37.0 and is going to be released today. Removing the a-c label.

**Closed** 2019-01-16 16:54 UTC
Labels: In Progress, a-c, bug, size S

**Comment by sv-ohorvath** [comment] 2019-01-18 09:30
Verified as fixed on Nightly 9.0 GV 64.
Devices: Samsung Galaxy S8 (Android 8.0), HTC Desire 820 (Android 6.0.1)
