### ISSUE TITLE
FF Klar has "Send usage data" enabled by default

### ISSUE THREAD

**Issue by KevCui** [mozilla-mobile/focus-android#4510] opened 2020-04-09 15:09 UTC
## Steps to reproduce

- Fresh install FF Klar (Klar not Focus) OR Clear storage of installed FF Klar app
- Open FF Klar -> Top right menu -> Settings -> Privacy & Security
- Scroll down to bottom, the option "Send usage data" is enabled

### Expected behavior

As far as I know, "Send usage data" should be disabled for FF Klar by default.

### Actual behavior

 "Send usage data" is enabled for FF Klar by default.

### Version information

Android app downloaded from Play Store, FF Klar version 8.1.1

**Comment by Meenohara** [comment] 2020-05-04 10:50
Hi can I take this up?

P.S. I am still new to open source code so do not know what "Successfully merging a pull request may close this issue" means

**Comment by licaon-kter** [comment] 2020-06-24 14:26
Seeing this in 8.4.0 F-Droid too :(

**Comment by licaon-kter** [comment] 2020-08-17 08:07
@KevCui Where din you install Klar from?

**Comment by KevCui** [comment] 2020-08-17 08:50
@licaon-kter from Google Play Store

**Comment by licaon-kter** [comment] 2020-08-17 09:21
@jonalmeida Ping?

**Comment by jonalmeida** [comment] 2020-08-21 00:30
Thanks for filing this! I think I found the cause of the problem, a fix should be in for the next release.

**Comment by ebalazs-sv** [comment] 2020-08-21 06:45
Verified as fixed on Focus Klar 8.7.1 GV 80.0 from 8/21 with Pixel 2 (Android 9).
The "Send usage data" is disabled by default.
I will close this issue.

**Closed by ebalazs-sv** 2020-08-21 06:45 UTC
Labels: QAReady
