### ISSUE TITLE
No sound when playing videos

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#2155] opened 2018-02-23 15:01 UTC
STR:

Klar+GeckoView build:

Go to https://olympics.cbc.ca/news/article/canada-play-for-men-hockey-bronze-after-being-stunned-germany.html

Expected behavior: 
Video plays with audio

Actual behavior:
Video plays without audio (tested it in Chrome, worked fine with audio)

**Comment by ekager** [comment] 2018-02-23 16:06
Dupe of #2118

**Closed by ekager** 2018-02-23 16:06 UTC
Labels: Klar+Geckoview
