### ISSUE TITLE
Searching for a string containing non-English letters has false positives

### ISSUE THREAD

**Issue by zekooooo** [mozilla-mobile/focus-android#4566] opened 2020-06-16 22:08 UTC
When I use the text searching function on a webpage and input a string that has a letter with a diacritic, it matches other letters that look the same but have different diacritics or don't have that diacritic. For example if I search for the string "žbun" it also matches "zbun", "źbun" etc.

With short strings the false positives often greatly outnumber the correct results making the search feature useless.

If the string contains a non-English letter, the search should only match that exact letter, not similar ones as well.

On Android 7.0, using Klar 8.4.0 but this problem is not new.

**Comment by lobontiumira** [comment] 2022-03-08 14:38
I was able to reproduce this on the Focus Nightly from 3/8 with Google Pixel (Android 10).

**Comment by lobontiumira** [comment] 2022-07-25 09:40
I was not able to reproduce this anymore on the latest Focus nightly 104.0a1 from 7/25.
Tested with Samsung Galaxy Note 8 (Android 9), and Oppo Reno 6 (Android 12).

![4566](https://user-images.githubusercontent.com/40694158/180747411-501ad1eb-2fb9-44b5-9ccf-f7b6132f8e90.png)


@zekooooo could tou please retry?
Thank you!

**Comment by lobontiumira** [comment] 2022-11-24 08:13
I will close this ticket, because I was not able to reproduce it on the latest builds.

**Closed by lobontiumira** 2022-11-24 08:13 UTC
Labels: bug
