### ISSUE TITLE
unable to upload files on libreoffice bugzilla

### ISSUE THREAD

**Issue by kr1shnas** [mozilla-mobile/focus-android#1157] opened 2017-08-17 07:54 UTC
login https://bugs.documentfoundation.org

on an issue tap "add attachment"
tap "choose"

usually file manager, camera options will pop up
nothing happens

**Comment by kr1shnas** [comment] 2017-08-17 07:55
focus 1.2
os: android 5.1

**Comment by pocmo** [comment] 2017-08-17 07:56
Thanks for reporting!

This is a duplicate of #937.

**Closed by pocmo** 2017-08-17 07:56 UTC
