### ISSUE TITLE
Settings Menu not displayed properly 

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla-mobile/focus-android#1922] opened 2017-12-06 14:43 UTC
Devices:
Nexus 5 (Android 6.0.1)
Nexus 6 (Android 7.1.1)
build: Focus 4.0 Beta Build #3691

Steps to reproduce:

Launch Focus and go to Settings -> Search.
Add a new search engine. Stay a couple of minutes(2-3) and tap back.

Expected results:
All the options are correctly displayed, also when tapping back to Settings Menu.

Actual results:
The options are one above each other. Not reproducible all the time but I observed this behavior leaving the app for a couple of minutes and then switching between options.

See screenshot:
![screenshot_20171206-142412](https://user-images.githubusercontent.com/24588037/33666446-aecabf74-daa2-11e7-9168-4de2c99c8993.png)
![screenshot_20171206-154840](https://user-images.githubusercontent.com/24588037/33666458-b51dfe5e-daa2-11e7-8b22-cb09952f98e6.png)

**Comment by pocmo** [comment] 2017-12-06 15:04
Mhhhh. This looks like backstack shenanigans. In MainActivity we had some problems too and we decided to handle back presses on our own and avoided using the backstack.

**Comment by npark-mozilla** [comment] 2017-12-06 17:47
I saw this once too but couldn't repro it afterwards. I think this happens intermittently, but still, it does look like it's a high priority.  I'll tentatively mark it as a release blocker, @bbinto what do you think?

**Comment by bbinto** [comment] 2017-12-06 18:33
@npark-mozilla release blocker

**Comment by pocmo** [comment] 2017-12-07 11:48
So far I am not able to reproduce this.

**Comment by pocmo** [comment] 2017-12-07 13:43
Finally I'm able to see this... in my case it happened after pressing back from the URL autocomplete form.

**Comment by pocmo** [comment] 2017-12-07 13:47
Looking at the state with uiautomatorviewer I can see that in fact two fragments are visible at the same time.

**Comment by pocmo** [comment] 2017-12-07 16:39
This is a Heisenbug. I haven't been able to ever see it again.

**Comment by pocmo** [comment] 2017-12-07 17:25
The problem seems to come up when a fragment transaction without backstack happens in between transactions with backstack. A good explanation of the issue is this blog posting:
http://www.andreabaccega.com/blog/2015/08/16/how-to-avoid-fragments-overlapping-due-to-backstack-nightmare-in-android/

One way I can reproduce this is by piggybacking on the issue from #1924. We definitely should land the patch from #1924 to fix at least part of the problem. I'll investigate if there are other paths in our settings that execute fragment transactions without backstack.

**Comment by pocmo** [comment] 2017-12-07 19:48
I haven't found any other reason than #1924. This has been merged to master now.

@npark-mozilla @SorinaFlorean Can you try to reproduce this in the latest builds?

**Comment by Jacquester** [comment] 2017-12-07 20:37
@pocmo I was able to reproduce this whilest working on #1923 and #1953 

I'll send a screenshot in a few minutes

**Comment by liuche** [comment] 2017-12-07 22:34
I'm going to close this for now, and flag for QA verification.

**Closed by liuche** 2017-12-07 22:34 UTC
Labels: bug, release-blocker

**Comment by npark-mozilla** [comment] 2017-12-08 15:40
I can't repro this either, even with STRs from #1924 combined
