### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v4.b.u android.support.v4.b.p.e()' on a null object reference

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#456] opened 2017-04-13 09:31 UTC
```
	org​.mozilla​.focus​.fragment	
SourceFile ​ Line 355
UrlInputFragment.dismiss
	
1	org​.mozilla​.focus​.fragment	
SourceFile ​ Line 35
UrlInputFragment.access$300
	
2	org​.mozilla​.focus​.fragment	
SourceFile ​ Line 265
UrlInputFragment$3.onAnimationEnd
	
3	android​.view	
ViewPropertyAnimator.java ​ Line 1121
ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd
	
4	android​.animation	
ValueAnimator.java ​ Line 1153
ValueAnimator.endAnimation
	
5	android​.animation	
ValueAnimator.java ​ Line 1313
ValueAnimator.doAnimationFrame
	
6	android​.animation	
AnimationHandler.java ​ Line 146
AnimationHandler.doAnimationFrame
	
7	android​.animation	
AnimationHandler.java ​ Line 54
AnimationHandler$1.doFrame
```

[View Full Crash Details](https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/crashreport/e634879fbd036e8d44f595084f81434e)

**Comment by ahunt** [comment] 2017-04-13 19:25
This looks like a duplicate of #440, which landed yesterday in:
c0b03c44fcde234f27e234acb6aef30b14afb949

That's available in build >= 1120, so we can probably close this (since it happened in 1103)

**Closed by ahunt** 2017-04-13 19:25 UTC
Labels: bug, v1.0
