### ISSUE TITLE
Klar old version on F-Droid

### ISSUE THREAD

**Issue by woodruffandtheschnibbleofazimuth** [mozilla-mobile/focus-android#4442] opened 2019-11-27 09:25 UTC
Hello everyone,
on F-Droid there is an old and outdated version of Firefox Klar (Version 8.0.15).
I see that there is the code apk updated but on F-Droid is stopped on July.

Thanks!

**Comment by J0WI** [comment] 2020-07-31 13:06
Duplicate of https://github.com/mozilla-mobile/focus-android/issues/1528

**Closed** 2022-02-25 13:19 UTC
