### ISSUE TITLE
Hitting back on a new tab will close the browser, claiming to erase history, when the session still exists

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#1419] opened 2017-09-29 16:07 UTC
STR:
1) Open Focus
2) Visit a page (e.g. kotaku.com)
3) Highlight text, long-press, "Search privately" (in the more menu for me) – search will open in a new tab
4) Hit back.

Expected: the current tab is closed and you move to the initial tab
Actual: The app will be exited and "Your browsing history has been erased" will be displayed. When you click Focus, the first tab (e.g. kotaku.com) is still visible.

Note: the notification for Focus is still shown despite the browsing history erase toast being shown.

**Comment by phunkular** [comment] 2017-09-29 16:46
duplicate of #1334

https://github.com/mozilla-mobile/focus-android/issues/1334

**Comment by pocmo** [comment] 2017-09-29 17:31
Closing as duplicate of #1334

**Closed by pocmo** 2017-09-29 17:31 UTC
Labels: needs triage
