### ISSUE TITLE
Regression of ~250ms on August 19th

### ISSUE THREAD

**Issue by MarcLeclair** [mozilla-mobile/focus-android#7576] opened 2022-08-31 18:35 UTC
On august 19th we see a 250 ms regression 

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/16614353/187753803-f74a318a-2f2c-479b-a7f2-ef096552b70c.png">

Link to the graph: https://earthangel-b40313e5.influxcloud.net/d/7u0o-gdnz/focus-startup-nightly-via-backfill-py?orgId=1

**Comment by Mugurell** [comment] 2022-09-01 05:52
Looking at a longer period it seems like the current numbers are in line with what we had so would be interesting to know what caused the ~250ms dip around August 11th also and then what reverted this gain around August 19th.
![image](https://user-images.githubusercontent.com/11428869/187840522-e7a4b802-feaa-4506-be9c-e302100b89ad.png)

For reference this are the commits merged between August 9-11 - https://github.com/mozilla-mobile/android-components/pulls?q=is%3Apr+is%3Aclosed+merged%3A2022-08-09..2022-08-11+base%3Amain+sort%3Aupdated-asc+
An this are the commits merged between August 18-20 - https://github.com/mozilla-mobile/android-components/pulls?q=is%3Apr+is%3Aclosed+merged%3A2022-08-18..2022-08-20+base%3Amain+sort%3Aupdated-asc+

**Comment by jonalmeida** [comment] 2022-09-03 20:27
@Mugurell what isn't mentioned in the OP comment is that this dip is similar in timeframe to one seen in Fenix as well.

In triage, the reason we decided to file it here was because Focus is a lot less complicated in the codebase so it would be easier to decipher what might have caused the regression (or the dip as you pointed out).

**Comment by mcomella** [comment] 2022-09-14 21:56
Triage: we looked at [the GVE graph](https://treeherder.mozilla.org/perfherder/graphs?highlightAlerts=1&highlightChangelogData=1&highlightCommonAlerts=0&series=mozilla-central,4367239,1,13&series=mozilla-central,4424897,1,13&timerange=5184000&zoom=1659456350510,1661574339290,1528.49594819312,1975.089085448022):
![image](https://user-images.githubusercontent.com/759372/190269929-41cb5426-c847-48be-ab2c-17a013106435.png)

And noticed that there are a series of slow outliers that stop around August 9th and resume on Aug 21, which closely matches what we see in fenix (Aug 10 - Aug 19) so **we concluded the likely cause of this regression was a change in GeckoView that was later removed**. Closing as INVALID.

**Closed by mcomella** 2022-09-14 21:56 UTC
Labels: performance

**Comment by mcomella** [comment] 2022-09-14 22:14
I filed a follow-up bug for platform to identify the root cause of the issue & see if we can ship that improvement to users: https://bugzilla.mozilla.org/show_bug.cgi?id=1790906
