### ISSUE TITLE
"Trackers blocked" status is changed from OFF to ON, for shortcuts, after the browser is closed

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/focus-android#4730] opened 2021-03-18 16:46 UTC
## Steps to reproduce
1. Open a webpage and turn off tracking protection.
2. Select 'Add to Home screen' from the 3 dots menu.
3. Close the browser. 
4. Launch the shortcut.

### Expected behavior
The webpage is loaded, with TP still OFF.

### Actual behavior
The webpage is loaded, with TP ON.

- Not reproducible on Focus - Play Store. 

### Device information
* Android device: Samsung Note 10(Android 11), LG G7 Fit (Android 8.1)
* Focus version: dev build #1186.0.1- 20210310152336

**Comment by pocmo** [comment] 2021-03-19 16:29
This may be caused by the missing GV API to load private tracking protection APIs on startup.

**Comment by ionutbedregeanu** [comment] 2021-06-04 06:00
I would like to work on this ticket

**Comment by ionutbedregeanu** [comment] 2021-06-07 09:13
After some debugging I noticed that tracking exception list is always empty after [add method](https://github.com/mozilla-mobile/android-components/blob/25ecf92f6e2dd627362e3b6e28741e28d7d10acf/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/TrackingProtectionExceptionFileStorage.kt#L82) so I logged a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1714945) for that

**Comment by Amejia481** [comment] 2021-06-07 13:33
Thanks for taking a look @ionutbedregeanu, I think the issue is related to what @pocmo [mentioned](https://github.com/mozilla-mobile/focus-android/issues/4730#issuecomment-802957657), as GeckoView at the moment doesn't allow to add exceptions for private tabs, this will be covered a part of the work on https://github.com/mozilla-mobile/android-components/pull/10316 , https://github.com/mozilla-mobile/focus-android/pull/4899 when [these Gecko View patches land](https://bugzilla.mozilla.org/show_bug.cgi?id=1699480).

**Comment by amedyne** [comment] 2021-07-12 13:50
@Amejia481, Are the GV and AC changes ready?

**Comment by Amejia481** [comment] 2021-07-12 14:29
It was partially covered on https://github.com/mozilla-mobile/focus-android/pull/4899, we noticed that there is a missing part of GV, but they are going to take some time on implementing it, we are trying to do a workaround on to cover it https://github.com/mozilla-mobile/focus-android/pull/4977.

**Comment by mcarare** [comment] 2021-12-08 13:34
For QA: Is this issue still reproducible after #5729? Thank you!

**Comment by lobontiumira** [comment] 2021-12-08 14:10
We have #5245 covering this issue.
We can close this one.

**Closed by lobontiumira** 2021-12-08 14:10 UTC
Labels: bug, P2, QAReady
