### ISSUE TITLE
Settings-"Show home screen tips" option is not displayed all the time

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/focus-android#4506] opened 2020-04-09 09:51 UTC
## Steps to reproduce
1. Open app and go to Settings/Mozilla.
2. Check the "Show home screen tips" toggle.
### Expected behavior
The toggle is displayed.
### Actual behavior
The toggle is not displayed.
### Device information

* Android device: Sony Xperia Z5 (Android 7), Samsung Galaxy S9 (Android 8)
* Focus version: Focus 8.2.0 (Build #340992214) GV: 75.0-20200403170909

Note: 
- After a while, not sure what triggeres, as i did clear data and reinstall the app a couple of times, the option is yet again displayed on same build.
- Did not reproduce the issue with Pixel 2 (Android 9), Motorola G6 Android 8
- When the "Show home screen tips" option is not present/is hidden as option at app level the tips are not displayed as well.

GIF:
![20200409-120349](https://user-images.githubusercontent.com/49859863/78880722-7d8b0a00-7a5e-11ea-8ca6-a6fa14829880.GIF)

**Comment by Diana-Rus** [comment] 2020-04-09 12:03
A few hours later.....with same device and build 😊 .
GIF:
![20200409-144005](https://user-images.githubusercontent.com/49859863/78892998-188ddf00-7a73-11ea-8fca-35a936c719d0.GIF)

**Comment by goforbg** [comment] 2020-05-01 06:37
Unable to reproduce in latest build. 

The code in MozillaSettingsFragment.kt line 25 has the snippet

`        if (!requireContext().isInExperiment(homeScreenTipsExperimentDescriptor)) {
            preferenceScreen.removePreference(findPreference(getString(R.string.pref_key_homescreen_tips)))
        }
`
So I think it's not a bug, it's a server side switch experiment.

**Comment by lobontiumira** [comment] 2022-02-23 08:57
I was not able to reproduce this issue on the latest builds.
Closing the ticket.

**Closed by lobontiumira** 2022-02-23 08:57 UTC
Labels: bug
