### ISSUE TITLE
[webcompat] latimes.com - unable to scroll because of the overlay.

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/focus-android#4440] opened 2019-11-25 01:30 UTC
Report from https://github.com/webcompat/web-bugs/issues/44984

## Steps to reproduce
1. go to https://www.latimes.com/local/lanow/la-me-thanksgiving-traffic-20171122-htmlstory.html

### Expected behavior
being able to scroll.

### Actual behavior
I'm able to reproduce the issue on Focus only, both with TP ON and OFF.
A gray overlay prevents interaction with the page.

### Device information

Tested with:
Browser / Version: Firefox Focus 8.0.24
Operating System: Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density)

**Comment by lobontiumira** [comment] 2022-02-25 13:07
I was not able to reproduce this issue on the lates RC 97.2.0, nor on the latest Focus nightly 99.0a1 from 2/25 with Sony Xperia Z5 Premium (Android 7.1.1), nor with Oppo Find X3 Lite (Android 11).

I'll close this ticket.

**Closed by lobontiumira** 2022-02-25 13:07 UTC
