### ISSUE TITLE
When interchanging app's languages the app's homescreen is not updated with correct translation

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/focus-android#4583] opened 2020-07-01 11:23 UTC
## Steps to reproduce
1. Open app and go to Menu/Settings/General/Language.
2. Choose a language and go back to app's homescreen.
### Expected behavior
The text below the Firefox Focus logo is translated in the chosen language. 
### Actual behavior
The text is not translated. A closing and reopening app will solve the translation. The text will be translated.
### Device information

* Android device: Sony Xperia Z5 (Android 7)
* Focus version:  Focus 8.5.0 with GV: 78

Note: The same goes with the "Search suggestions" dialog box. 
Lanuages: Aragones, Espanol(Mexico), Italian

GIF
![20200701-140919](https://user-images.githubusercontent.com/49859863/86258110-1bf0bc80-bbc3-11ea-8abc-29cba271f631.gif)

**Comment by caugner** [comment] 2020-09-04 00:05
Duplicate of #4517.

**Closed** 2021-03-12 16:04 UTC
Labels: bug
