### ISSUE TITLE
Build with SDK for Android 12 / API 31

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/focus-android#7048] opened 2022-05-18 12:15 UTC
See https://github.com/mozilla-mobile/fenix/issues/21102

**Comment by Mugurell** [comment] 2022-06-07 09:01
With the AC and Fenix changes merged Focus should be updated to.

**Comment by Mugurell** [comment] 2022-06-07 15:12
Closing as a duplicate of https://github.com/mozilla-mobile/focus-android/issues/6223

**Closed by Mugurell** 2022-06-07 15:12 UTC
Labels: Android 11/12 (FADP-8)
