### ISSUE TITLE
Selections for removing search engines is not visible 

### ISSUE THREAD

**Issue by initrd** [mozilla-mobile/focus-android#3296] opened 2018-09-03 16:38 UTC
## Steps to reproduce
1. Open Settings > Search > Installed search engines > Three dot menu > Remove
2. Tap on any search engine

### Expected behavior
The selected search engine should have a different background than the pane

### Actual behavior
The selected search engine has the same background as the pane
In the attachment, a search engine has been selected for removal

### Device information

* Android device: Google Pixel, Android 9.0
* Focus version: 7.0 (Build #322461206 🦎 62.0.20180829133835)

![screenshot_20180903-093237](https://user-images.githubusercontent.com/1941695/44996483-037ad100-af5d-11e8-8f34-54f735591522.png)

**Comment by SubhrajyotiSen** [comment] 2018-09-05 09:59
Related to #3254  and a PR is open in #3277

**Comment by sblatz** [comment] 2018-09-05 18:08
Closing as dupe of #3254.

**Closed by sblatz** 2018-09-05 18:08 UTC
Labels: P4, bug
