### ISSUE TITLE
Images load at 100% zoom in Focus

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/focus-android#1591] opened 2017-10-27 14:18 UTC
Created from [bug 1410264 Comment 0](https://bugzilla.mozilla.org/show_bug.cgi?id=1410264#c0)
--------------------------------------------------------------------------------------------------------------
User Agent: Mozilla/5.0 (Android 7.1.2; Mobile; rv:56.0) Gecko/56.0 Firefox/56.0
Build ID: 20170922214822

Steps to reproduce:

Load an image URL in Firefox Focus

Actual results:

The top-left of the image is displayed at 100% zoom

Expected results:

The image is scaled down to fit the screen.

**Comment by pocmo** [comment] 2017-10-27 15:30
Duplicate of #1016

**Closed by pocmo** 2017-10-27 15:30 UTC
