### ISSUE TITLE
Integrate HTTPS Everywhere

### ISSUE THREAD

**Issue by izaimo** [mozilla-mobile/focus-android#1383] opened 2017-09-24 10:01 UTC
Cannot be Private and Secure without HTTPS Everywhere.

HTTPS upgrades wherever-whenever possible, which means more of your connections are encrypted, protecting your identity, browsing, payments and more.

This can be done by integrating[ HTTPS Everywhere](https://www.eff.org/https-everywhere) by EFF to Focus code. https://github.com/EFForg/https-everywhere

It is the only major thing that is missing on Firefox Focus. Other browsers where HTTPS Everywhere is intergrated: Tor Browser, Brave Browser.

NOTE for early excusers: HTTPS Everywhere does not produce errors if the site you visit does not support HTTPS, it just forces encrypted connections wherever possible. **Example: FACEBOOK.COM is HTTPS by default but FBCDN.NET and other image sources sometimes are not and thus, can be intercepted.**

**Comment by MrGeneric** [comment] 2017-09-24 12:25
If this is feasible it would be a great addition.

**Comment by pocmo** [comment] 2017-09-25 10:57
Duplicate of #596.

**Closed by pocmo** 2017-09-25 10:57 UTC

**Comment by izaimo** [comment] 2017-09-25 10:59
@pocmo #596 not very descriptive.

**Comment by pocmo** [comment] 2017-09-25 11:03
Feel free to copy your comment over if you like. I've flagged the other issue to re-discuss in our bug triage meeting.
