### ISSUE TITLE
typing about:<unreserved word> as URL asks the user to open external browser

### ISSUE THREAD

**Issue by nojunpark** [mozilla-mobile/focus-android#2472] opened 2018-04-17 20:50 UTC
STR:
On Focus browser URL bar, type about:hello or about:help
Expected:
- Show blank page, or 404
Actual:
- Asks the user to open the URL on external browser, but upon opening it, it doesn't do anything either.

**Comment by RomanWuattier** [comment] 2018-04-17 21:08
I attempted this and ran into a crash.
* First I typed `about:hello`
* Then cancel the popup
* Finally click on the warning button in the URL bar

Do you need someone to work on both show a blank page/404 and the crash?

**Comment by ekager** [comment] 2018-04-17 22:12
@RomanWuattier Feel free to work on this issue and maybe file a new issue for the crash with the logcat and STR in case this comment gets lost :)

**Comment by RomanWuattier** [comment] 2018-04-18 11:59
Good news, the crash I was talking about is no more on the development application. It should have been fixed with #2271.
I will work on the original issue.

**Comment by RomanWuattier** [comment] 2018-04-18 13:10
Good news, the crash I was talking about is no more! It has already been fixed in #2390.
I will work on the original issue.

**Comment by pocmo** [comment] 2018-04-20 15:12
Focus itself does not register about:* urls. Instead we use focus:* URLs internally (mostly because we had issues with WebView when using about). Anyhow, Firefox *does* register the about protocol - globally. So in this case we ask whether you want to open this link in another app that does support this protocol we do not know. The behavior here is kind of expected -- I'm not convinced that it's worth special casing "about" in this situation?

**Comment by RomanWuattier** [comment] 2018-04-20 17:11
Okay, that's why `about:` scheme is not present in the localized content.
If it turns out that this behaviour is expected, we probably shouldn't work on it, shouldn't we?

**Comment by lobontiumira** [comment] 2021-10-05 08:58
This issue doesn't reproduce anymore on the latest debug build from main from 10/5, nor on 93.1.1 RC build.
The about:word loads the "Invalid address" page.
Tested with Lenovo Tab M10 (Android 10), and Xiaomi mi4i (Android 5.0.2).

**Closed by lobontiumira** 2021-10-05 08:58 UTC
Labels: P5
