### ISSUE TITLE
 long press and select open in new tab, it does not append the domain name and just crashes the app within a few seconds.

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/focus-android#4212] opened 2019-02-25 04:54 UTC
## Steps to reproduce

**Browser / Version**: Firefox Mobile 65.0
**Operating System**: Android 8.0.0
**Tested Another Browser**: Yes

**Problem type**: Site is not usable
**Description**: Relative links do not work in new tab
**Steps to Reproduce**:
When you click a link on the site which is relative such as /messages, it opens fine when in the same tab. However, if you long press and select open in new tab, it does not append the domain name and just crashes the app within a few seconds. This used to work previously and has only been noticable as of very recently.

### Device information

* Android device: 8.0.0
* Focus version: Gecko view 65

The issue is not reproducible on Firefox Focus 8.0.8 (Build #330452036) and Firefox Nightly 67.0a1 (2019-02-19)

**Tested with:**
Browser / Version: Firefox Focus 8.0.8 (Build #330452036 🦎 65.0.20190125143011)
Operating System: LG G5 (Android 7.0) - 1440 x 2560 pixels (~554 ppi pixel density), Samsung Galaxy S7 Edge (Android 8.0.0) - Resolution 1440 x 2560 pixels (~534 ppi pixel density)

**Comment by karlcow** [comment] 2019-02-25 04:54
Original issue on https://github.com/webcompat/web-bugs/issues/25888

**Comment by arjunkrishnababu96** [comment] 2019-02-25 17:20
I've been having this issue for more than a week.

**Steps to reproduce**
1. Google-search something
2. Long press a search result and click `Open link in new tab`

**Expected behavior**
Link opens in new tab.

**Actual behavior**
about:blank opens in new tab

Also, when you long-press, the full link is not displayed in the pop-up window; only the relative path after the main address is shown. 

> The issue is not reproducible on Firefox Focus 8.0.8 (Build #330452036)

Not true. The issue is reproducible in this exact version of Firefox (which runs on my Android One device).

Also, this was marked as duplicate of webcompat/web-bugs#25888 and closed.
And webcompat/web-bugs#25888 was marked as a duplicate of mozilla-mobile/focus-android#4212 (THIS) and closed. 
(In both issues, the other one was marked as duplicate and was closed).

**Comment by karlcow** [comment] 2019-02-25 22:33
@arjunkrishnababu96 there are two types of Firefox Focus one with a GeckoView engine and one with a Blink engine.

**Comment by arjunkrishnababu96** [comment] 2019-02-26 17:44
@karlcow Oh, okay. I don't know which one mine uses. How do I find out?

**Comment by arjunkrishnababu96** [comment] 2019-02-27 14:01
I uninstalled and reinstalled Firefox Focus (along with a bunch of other apps; I wasn't trying to troubleshoot this specific issue), and guess what, the problem has been solved for me.

FWIW, my user-agent now contains "AppleWebKit" instead.

**Comment by lobontiumira** [comment] 2021-07-05 12:21
I was not able to reproduce this issue on the latest Focus build 8.16.0.
I have tested with Google Pixel (Android 10), and Samsung Galaxy Note 8 (Android 9).

**Closed by lobontiumira** 2021-07-05 12:21 UTC
