### ISSUE TITLE
I cant tap some website

### ISSUE THREAD

**Issue by aohanhongzhi** [mozilla-mobile/focus-android#7641] opened 2022-09-11 12:12 UTC
## Steps to reproduce

when I open some website like https://ddys.tv or https://bing.com

### Expected behavior

I can open next page by tap the link

besides I can open the menu by tap the menu button.

<img src = https://user-images.githubusercontent.com/37319319/189526851-4244c788-1340-496f-81f3-ebe06443febc.jpg width = 45%> <img src = https://user-images.githubusercontent.com/37319319/189526855-9052976a-6457-41c2-ac43-0fc21363844c.jpg width = 45%>

### Actual behavior

I cant open it by tap some link
<img src =https://user-images.githubusercontent.com/37319319/189526874-95f6b040-2cbb-4167-982b-9eec2b579e90.jpg width = 45%>

### Device information

* Android device: ?

Xiaomi 12 Pro

* Focus version: ?

104.0.8

**Comment by mcarare** [comment] 2022-09-12 10:53
I cannot reproduce this on Android 9, Android 10, or Android 13.

**Comment by lobontiumira** [comment] 2022-09-12 12:56
I was not able to reproduce this issue either.
I loaded both sites, and browsed a little - no issues encountered, no blank spaces or black backgrounds.
Tested on the latest RC 104.2.0 build with Samsung Galaxy Note 8 (Android 9), and Xiaomi Mi8 Lite (Android 10).

@aohanhongzhi could you please provide some steps to reproduce, and a short video with the issues encountered?
Thank you!

**Comment by aohanhongzhi** [comment] 2022-09-12 13:01
> I cannot reproduce this on Android 9, Android 10, or Android 13.

I am so sorry for that. when I turn off the `Block JavaScript` , I can open these web pages normally.

**Comment by mcarare** [comment] 2022-09-12 13:26
Thank you, @aohanhongzhi!
I could also reproduce the situation before, with JS blocked, but that is to be expected. Closing this as not a bug.

**Closed by mcarare** 2022-09-12 13:26 UTC
