### ISSUE TITLE
The page menu bar does not stay stuck to the footer of the page if scrolling is performed at instagram.com

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/focus-android#5949] opened 2021-11-26 09:42 UTC
## Preconditions
Test account created.

## Steps to reproduce
1. Access : https://www.instagram.com
2. Log into your account.
3. Scroll the page.
4. Observe the bottom menu navigation bar.

### Expected behavior
The menu has a fixed position.

### Actual behavior
The menu changes the position.

### Device information

* Android device: Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)
* Focus version:  Firefox Focus 94.1.2 (353121860 🦎94.0-20211028161635🦎)

**Notes:**

1. Attaching relevant screenshots:
![scroll focus insta](https://user-images.githubusercontent.com/75027050/143560251-31af300f-9af5-4938-8869-ca03de72952d.gif)
2. See also  : https://github.com/mozilla-mobile/focus-android/issues/5705

**Comment by ionutbedregeanu** [comment] 2021-12-23 10:58
This should be fixed. Let me know if you still reproduce it

**Comment by lobontiumira** [comment] 2021-12-23 13:25
I was not able to reproduce this on RC 95.2.0 using a Google Pixel (Android 10):


https://user-images.githubusercontent.com/40694158/147246840-0e412eba-b5ad-4a39-85af-c481a06d3848.mp4

I'll close this ticket. @softvision-raul-bucata feel free to re-open if this issue still reproduces on your device.

**Closed by lobontiumira** 2021-12-23 13:25 UTC
Labels: dynamic-toolbar
