### ISSUE TITLE
Going to help page shows "Secure connection failed" error

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#403] opened 2017-04-04 15:17 UTC
Open app, and choose "Help" from settings.  This should show the mozilla help page, but instead it shows the error message.

**Comment by ahunt** [comment] 2017-04-04 16:42
Same thing happens if I open support.mozilla.org (in the main browser window), and click on "Firefox". Not reproducible in any other browser.

**Comment by ahunt** [comment] 2017-04-04 16:47
I get the same in chrome release: support.mozilla.org works, but clicking on "Firefox" results in NET::ERR_CERT_AUTHORITY_INVALID. So this looks like either a general Android/WebView bug, or something is wrong with Sumo (Firefox doesn't seem to care though.)

**Comment by npark-mozilla** [comment] 2017-04-04 16:56
I saw similar error on buddybuild device test results - only on 7.0.1, (API 25) accessing any https site directly (with exception of google) on Focus will give me this error. Since I don't have 7.0.1 device, and could not reproduce on sim, I thought it was test flakiness, but maybe it's kind of related.

**Comment by ahunt** [comment] 2017-04-04 17:05
Huh. It turns out I only get this on my 7.1 device, but I can't reproduce on Android 5.

But on Android 5, I get a cert error when opening "support.mozilla.org".

In both failing cases, the cert seems to be for "secured03.lithium.com". (It's possible my phone was opening http: for support.mozilla.org, but then opened https for all further links.)

**Comment by ahunt** [comment] 2017-04-04 17:51
It looks like the issue is actually sumo server configuration, I've filed a bug with more details:
https://bugzilla.mozilla.org/show_bug.cgi?id=1353467

When you first open sumo, it will default to http - which is why I'm not seeing failures until I click on a link.

**Comment by ahunt** [comment] 2017-04-10 21:14
Seems to be fixed - closing this now!

**Closed by ahunt** 2017-04-10 21:14 UTC
Labels: bug, v1.0
