### ISSUE TITLE
Onchange for input type file not working?

### ISSUE THREAD

**Issue by abhinadduri** [mozilla-mobile/focus-android#1134] opened 2017-08-11 17:33 UTC
It seems like Firefox Focus is unable to open files (or register an input onchange event). I have pasted a sample HTML file that does not work on Focus.

```html
<html>
<head>
  <meta charset="UTF-8">
</head>
<body>
<input type="file" id="upload"/>
<script>
let elem = document.getElementById('upload');
elem.addEventListener('change', function() {
  let div = document.createElement('div');
  div.textContent = 'changed';
  document.body.append(div);
})
</script>
</body>
</html>
```

**Comment by pocmo** [comment] 2017-08-11 18:03
This might be a duplicate of #937?

**Comment by bbinto** [comment] 2017-11-21 17:00
closing because of dup.

**Closed by bbinto** 2017-11-21 17:00 UTC
Labels: bug, feature, UX
