### ISSUE TITLE
visited links remembered across sessions

### ISSUE THREAD

**Issue by sinelaw** [mozilla-mobile/focus-android#1777] opened 2017-11-22 06:28 UTC
Version 2.4 on Nexus 5X

1. Go to https://news.ycombinator.com/
2. Visit a link
3. Go back, you see the link in a different color now
4. Close the session / tap the trash can
5. Open the website again, visited link still appears in different color

**Comment by pocmo** [comment] 2017-11-22 09:43
Duplicate of #1220 and #990

**Closed by pocmo** 2017-11-22 09:43 UTC
