### ISSUE TITLE
RFE: Find in Page

### ISSUE THREAD

**Issue by TPS** [mozilla-mobile/focus-android#1331] opened 2017-09-16 13:55 UTC
It seems obvious, but I couldn't find the options in F-droid Klar, nor the RFE here, but I really miss a "Search in page" option!

**Comment by pocmo** [comment] 2017-09-18 10:39
Duplicate of #967

**Closed by pocmo** 2017-09-18 10:39 UTC

**Comment by TPS** [comment] 2017-09-18 12:47
Thanks, @pocmo!  I couldn't find it on my own. 🙇
