### ISSUE TITLE
The application crashes when changing the orientation from a custom tab

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#6440] opened 2022-02-15 14:16 UTC
## Steps to reproduce
1. Go to Settings - General and set Firefox Focus as default browser.
2. Open a custom tab in an external application (e.g. Gmail).
3. Rotate device to change the orientation.
4.  Observe the crash.

### Expected behavior
The application remains stable at all times.
### Actual behavior
The application crashes every time when changing the orientation from a custom tab, when Focus is set as default browser.
### Device information

* Android device:  Google Pixel 6 (Android 12), Lenovo Tab M10 (Android 10).
* Focus version: Firefox Focus Beta 98.0.0-beta 2, Nightly 99.0 (build 360450513 GV 99.0a1-20220212115333).
Note that this is not reproducible on RC 97.1.1. 

https://user-images.githubusercontent.com/89388888/154079513-cc30fb99-97c0-45a4-aa5f-f5ddd7cca0ad.mp4

[Pixel6_Beta_CrashCutomTab.txt](https://github.com/mozilla-mobile/focus-android/files/8069896/Pixel6_Beta_CrashCutomTab.txt)

**Comment by Mugurell** [comment] 2022-02-15 14:22
Seem like the same general STRs as for https://github.com/mozilla-mobile/focus-android/issues/6416. 
Maybe the patch for that would need to be uplifted.

**Comment by amedyne** [comment] 2022-02-15 16:02
@mcarare Let me know what you find out here and if we have to uplift the change to Beta.

**Comment by lobontiumira** [comment] 2022-02-18 14:22
I was not able to reproduce the crash on the Beta 98,0,0-beta,3 build, nor on the latest Focus nightly 99 from 2/18 with Lenovo Tab M10 (Android 10).

**Comment by lobontiumira** [comment] 2022-02-21 11:02
I was not able to reproduce the crash with Oppo Find X3 Lite (Android 11), nor with Lenovo Tab M10 (Android 10), on the latest Focus Nightly build 99.0 (360520510 with GV 99.0a1-20220220070007).
Closing the ticket as verified.

**Closed by lobontiumira** 2022-02-21 11:02 UTC
Labels: bug, crash 🔥
