### ISSUE TITLE
Fingerprint auth can be circumvented with Focus as the default browser.

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#4162] opened 2019-01-20 14:57 UTC
## Steps to reproduce
1. Enable finger print auth support.
2. Open any page and verify switching away/back to Focus shows the fingerprint dialog.
1. Make Focus the default browser.
3. Click a link in any app to have it open in Focus.
4. Use the tab switcher to go to the first website.

### Expected behavior
1. Access to the first tab should be blocked by the finger print dialog.

### Actual behavior
1. You can access everything when you load a new tab.

### Device information

* Android device: Android 9 (Pixel 2)
* Focus version: 9.0 (Build #330191217 :lizard: 65.0.20190114172331)

**Comment by sv-ohorvath** [comment] 2019-01-21 14:57
Dupe of #4063. Please reopen if I'm wrong.

**Closed by sv-ohorvath** 2019-01-21 14:57 UTC
