### ISSUE TITLE
The Exceptions button does not grey out after clearing all exceptions

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/focus-android#5738] opened 2021-10-29 08:47 UTC
## Steps to reproduce
1. Open a few websites and disable ETP in order to add them to the exceptions list;
2. Got to Settings -> Privacy & Security -> Exceptions;
3. Tap the Remove all websites button.

### Expected behavior
After removing all websites from the exceptions list the Exceptions button should become grey.
### Actual behavior
After removing all websites from the exceptions list the Exceptions button can be tapped once more resulting in a flicker before becoming grey.
### Device information

* Android devices: Oppo Find X3 (Android 11), OnePlus 6T (Android 9), Huawei P9 Lite (Android 8)
* Focus version: RC 94.1.1

https://user-images.githubusercontent.com/50983519/139405890-ca9eeb5e-3280-45cf-a930-d601b5a7e5a7.mp4

**Comment by Amejia481** [comment] 2021-11-01 13:29
We are planing it, to land it after 96 cycle starts

**Comment by Amejia481** [comment] 2021-11-03 20:08
This landed on https://github.com/mozilla-mobile/focus-android/commit/96812489c3687e97a0bfcf1016f9555b7cf4f252 we can re-test now.

**Comment by lobontiumira** [comment] 2021-11-05 07:56
Reproducible on Beta 95.0.0-beta.3, and on the latest debug build from main, with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by ionutbedregeanu** [comment] 2021-11-11 15:41
@jeffreygee As Arturo suggested [here](https://github.com/mozilla-mobile/focus-android/pull/5827#pullrequestreview-802748007) I added a callback to know when the removing process ends and the navigation should be done to  Privacy & Security screen
But I'm not sure if a spinner should appears while the exceptions are removed because everything is almost instant and the spinner it will be like a flicker effect.

Should we give up on this ideea or should we add a minimum duration for that spinner?
What do you think?

Also if we decide to add a spinner we need design for that, at this moment we don't have a loader spinner in the app.

**Comment by jeffreygee** [comment] 2021-11-19 04:13
> @jeffreygee As Arturo suggested [here](https://github.com/mozilla-mobile/focus-android/pull/5827#pullrequestreview-802748007) I added a callback to know when the removing process ends and the navigation should be done to Privacy & Security screen But I'm not sure if a spinner should appears while the exceptions are removed because everything is almost instant and the spinner it will be like a flicker effect.
> 
> Should we give up on this ideea or should we add a minimum duration for that spinner? What do you think?
> 
> Also if we decide to add a spinner we need design for that, at this moment we don't have a loader spinner in the app.

hi @ionutbedregeanu  - two things:
1) is the'remove all websites' action removed after a certain number of things are added to exceptions? I added 20+ and the button was removed
2) Re: Arturo's feedback. With the callback, instead of a spinner, do we have an option for the button go into an inactive state until all the exceptions are removed and when complete, go back to the Privacy & Security screen?

**Comment by ionutbedregeanu** [comment] 2021-11-19 09:44
Thanks @jeffreygee for your feedback. I disabled the button while the exceptions are removed and fixed the bug mentioned at point 1

**Comment by lobontiumira** [comment] 2021-12-02 13:53
Verified as fixed on the Focus Nightly 95.0 (build 353361543 GV 96.0a1-20211201050507) with Google Pixel (Android 10).

**Closed by lobontiumira** 2021-12-02 13:53 UTC
Labels: bug, QAReady

**Comment by lobontiumira** [comment] 2021-12-08 10:35
Verified as fixed on the Beta 96.0.0-beta.1 with Sony Xperia Z5 Premium (Android 7.1.1), and Samsung Galaxy Tab A6 (Android 5.1.1).
