### ISSUE TITLE
GeckoView (Focus) fails to load a few pages

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#2814] opened 2018-06-27 18:19 UTC
### Steps to reproduce
- Visit one of the following pages:
  - apple.com
  - https://forecast.weather.gov/MapClick.php?lat=37.777120000000025&lon=-122.41963999999996 (you can visit by going to weather.gov and searching for San Francisco)

### Expected behavior
Page loads

### Actual behavior
Page never loads; url oscillates between about:blank and the page url

### Device information

* Android device: Galaxy S5 (Android 6.0.1)
* Focus version: 6.0 Build #121761205, 62.0.20180622100434

**Comment by pocmo** [comment] 2018-06-28 10:42
I can't reproduce on my Pixel XL (Android 9) - Klar 6.0 / 221771206 / 62.0.20180625100038

**Comment by mcomella** [comment] 2018-06-28 17:15
I just updated and can still reproduce on apple.com (didn't check weather): Focus 6.2 / #121791209 / 62.0.20180625141512.

**Comment by ekager** [comment] 2018-06-28 21:09
Thanks @mcomella . I can't reproduce on any of my devices or emulators, so may need to play with your phone next week...

**Comment by pocmo** [comment] 2018-06-29 09:15
@mcomella Do you have a non-default blocking settings?

**Comment by mcomella** [comment] 2018-07-04 02:19
I don't believe so but I can verify on Tuesday.

**Comment by mcomella** [comment] 2018-07-05 15:17
I cleared app data and can still reproduce.

**Comment by cjdelisle** [comment] 2018-07-10 11:14
This issue is also happening with CryptPad, you can observe it here: https://cryptpad.fr/pad/#/2/pad/view/bYk3eg360vk7PNk0tLi-NslDjlxP0DQtb4eB4X9Lu7Q/present/

**Comment by ekager** [comment] 2018-08-16 00:03
Tested the sites on the devices and they load now. Closing.

**Closed by ekager** 2018-08-16 00:03 UTC
Labels: Klar+Geckoview, bug, testing
