### ISSUE TITLE
Tab counter flickers when switching tabs

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/focus-android#4878] opened 2021-05-11 09:56 UTC
## Steps to reproduce
1. Launch Focus and open several new tabs;
2. Tap the tab counter and switch between tabs;
3. Observe the tab counter;
### Expected behavior
The tab counter is displayed without any visual effects.
### Actual behavior
The tab counter flickers when switching tabs.
![20210511_125047](https://user-images.githubusercontent.com/48799384/117796996-3e7a4a00-b258-11eb-9c1b-20d04c16957c.gif)

### Device information

* Android device: Pixel 2 (Android 9);
* Focus version: #1190 dev build from main
* Not reproducible on Focus 8.15.4

**Comment by gouri-panda** [comment] 2021-05-12 09:23
Hi!, I want to work on this issue.

**Comment by ionutbedregeanu** [comment] 2021-06-07 13:50
I would like to work on this issue

**Comment by Mugurell** [comment] 2021-06-09 12:29
Asked Sebastian about this since it seems that the original intention was to always create a new fragment for a new tab, [as per this code](https://github.com/mozilla-mobile/focus-android/blob/c4f580942d7f81104a1d4e6be3934e92d8f5f591/app/src/main/java/org/mozilla/focus/navigation/MainActivityNavigation.kt#L95-L100), this leading to the flicker issue.

He confirmed this and said that at this point everything expects a new fragment and so moving away from this flow would be a big refactoring effort that is best to be left for later.

Also I see this bug in the old Focus, in a build from the `release` branch so it's not a new regression.

**Comment by pocmo** [comment] 2021-06-09 12:32
Moving to P5 because of this.

**Comment by Mugurell** [comment] 2021-07-07 09:48
Removing from Kanban from now.

**Comment by ionutbedregeanu** [comment] 2022-01-11 13:57
I will close this ticket since the floating button was removed

**Closed by ionutbedregeanu** 2022-01-11 13:57 UTC
Labels: bug, P5
