### ISSUE TITLE
Sharing a link to Focus/Klar from the News Republic app opens the browser inside the app

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#2309] opened 2018-03-15 13:46 UTC
Build:
Focus Beta 4.1
Focus store vers. 4.0.2
Klar+GeckoView 4.1

Devices:
Samsung Galaxy S8 (Android 7.0)
HTC Desire 820 (Android 6.0.1)

STR:
1. Open the News Republic app.
2. Open an article.
3. Tap the share button and select Focus or Klar.

Expected results:
Focus/Klar opens as a standalone app, with the article shared.

Actual results:
For this app, News Republic, when Focus opens, it's inside the NR app. It doesn't launch the Focus app, even if it's already opened.  Explained better in this recording: https://drive.google.com/file/d/1Z2qYAWA02VBjFjFUY4mBdHn2jeHweOqW/view?usp=sharing
Doesn't reproduce with Google news or Amazon apps.

**Comment by pocmo** [comment] 2018-03-15 13:49
Aye. This looks like a bug caused by my work to separate custom tabs from the regular browser.

**Comment by pocmo** [comment] 2018-03-16 11:01
> Aye. This looks like a bug caused by my work to separate custom tabs from the regular browser.

Not a new bug. That's already happening in our existing version. Moving this to the new milestone as today is code freeze.

We might need to force a new task here (e.g. handle the intent in IntentReceiverActivity too and then add the flag to the intent).

**Comment by ekager** [comment] 2018-03-16 18:55
This may be their implementation? If you press share with Twitter, Facebook, or Email, it also launches inside the News Republic app

**Comment by pocmo** [comment] 2018-03-19 08:38
> This may be their implementation? If you press share with Twitter, Facebook, or Email, it also launches inside the News Republic app

Yeah, it kind of is. They should add the NEW_TASK flag on their side. However I wonder if we should force it on our side by letting IntentReceiverActivity receive the share intent, add the flag and then launch MainActivity (like we do not VIEW intents).

**Comment by ekager** [comment] 2018-03-19 18:33
Tried this by adding the send intent filter to IntentReceiverActivity in the manifest and adding a NEW_TASK flag before launching MainActivity in IntentReceiverActivity, and now it launches the intent in Focus AND in the News Republic app. Will we have to remove some intent magic they're trying to do to launch applications within their application?

**Closed** 2018-03-23 16:49 UTC
Labels: bug
