### ISSUE TITLE
Fix Slow Rendering

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#2077] opened 2018-01-31 00:00 UTC
Google Play is reporting slow rendering in Focus, above the bad behavior threshold (data goes back 6 months): https://screenshots.firefox.com/D7DJcn4dSJPtPLfL/play.google.com

Let's fix this up.

**Comment by Sdaswani** [comment] 2018-01-31 00:00
@npark-mozilla can you provide any context here? If not, no worries, @pocmo may have a historical view and/or can cite potential causes.

**Comment by npark-mozilla** [comment] 2018-01-31 16:39
Strange, I didn't really notice the app got much slower - All major news sites with many elements seems to load fast to me.

**Comment by Sdaswani** [comment] 2018-01-31 17:27
@npark-mozilla this stat isn't something new - it's been like this for 6 months at least. So not something you'd notice anecdotally likely. Was just wondering if you had any context about the bad graph I linked to.

**Comment by mcomella** [comment] 2018-02-01 19:09
According to the dashboard, this behavior has actually **gotten better** over time - perhaps they only introduced notifications for "bad behavior" recently?

![screenshot-2018-2-1 android vitals overview - firefox focus the privacy browser - google play console](https://user-images.githubusercontent.com/759372/35697882-4d6c7842-0740-11e8-9178-77338c26199a.png)

Also, it says 16ms is the cutoff but I wonder how this affects WebView-based apps, which I imagine can oftentimes take longer than 16ms to render a frame (e.g. lag when scrolling).

I have a hunch this is not a bug and the app is working as expected.

**Comment by Sdaswani** [comment] 2018-02-01 20:33
interesting thanks @mcomella . do you think it is worthwhile for me or @bbinto to analyze the reviews to see if there is anecdotal reports of slow rendering?

**Comment by mcomella** [comment] 2018-02-02 18:50
@Sdaswani If it's not too time consuming – it's possible the numbers have gotten better because users on some devices stopped using the app when rendering was bad (but maybe users are just getting faster phones or WebView is getting faster).

But I'm not sure we've actually changed anything related to rendering performance (but I haven't looked into what's landed in all of these versions).

**Comment by Sdaswani** [comment] 2018-02-03 06:30
@mcomella i don't see a pattern that supports this issue from looking at the reviews, but let's get together IRL to check out the reviews and see if we can uncover something.

**Comment by pocmo** [comment] 2018-02-20 13:33
Duplicate of #1709. However closing #1709 because there's already some discussion happening here.

**Comment by Sdaswani** [comment] 2018-03-27 18:22
@sdaswani to look at slow rendering stats again.

**Closed** 2022-04-24 10:50 UTC
Labels: testing, P3, wontfix
