### ISSUE TITLE
Find in page

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/focus-android#2073] opened 2018-01-27 18:01 UTC
Can you add this feature to Focus. I miss it so much.

Thank you.

**Comment by GammaBurst101** [comment] 2018-01-28 11:21
I want to volunteer to help but I am a novice in java programming. Can anyone please tell me if this issue is easy enough for me?

**Comment by Sdaswani** [comment] 2018-01-28 22:23
This is a duplicate of https://github.com/mozilla-mobile/focus-android/issues/967 so I'll close. But we understand this is a requested feature so it's something we will look to implement soon.

@GammaBurst101 this is not an _easy_ issue, but there may be some [open source cod](https://github.com/mozilla-mobile/firefox-ios/blob/5c80018d6ba1dca0a5ad7a674c99dee450c9b36b/Client/Assets/FindInPage.js)e you can use for inspiration. We would love your contribution.

**Closed by Sdaswani** 2018-01-28 22:23 UTC

**Comment by GammaBurst101** [comment] 2018-01-29 02:20
Oh, Ok! Thanks for telling me. I will try to find something easy for me.
