### ISSUE TITLE
Activated selection handlers when trying to dismiss Instagram banner

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4257] opened 2019-04-24 15:11 UTC
## Steps to reproduce
1.Go to Bing.com
2.Swipe down and tap the instagram logo of the Quinault Rainforest section(as per the attached video)
3.Tap the 'x'button from the Instagram banner
### Expected behavior
The Banner should be dismissed
### Actual behavior
The selection handlers are activated
https://im3.ezgif.com/tmp/ezgif-3-601178cf848b.gif
### Device information

* Android device: Samsung Note9 (Android 8.1.0)
* Focus version: Focus 8.0.9, GeckoView 68

**Comment by cpeterso** [comment] 2019-04-25 02:03
Thanks for testing, @sv-ohorvath! The video link https://im3.ezgif.com/tmp/ezgif-3-601178cf848b.gif is not working. It reports "404 -image not found".

Also, I see the Quinault Rainforest headline, but I don't see an Instagram logo button. I only see Facebook, WhatsApp, and Skype buttons.

Is this bug also reproducible in Fenix?

**Comment by sv-ohorvath** [comment] 2019-04-25 06:59
Here is the video, sorry for the broken link: https://drive.google.com/file/d/1suehp6V6iltvt078MP3iK-QwhMX8VBjO/view?usp=sharing
The issue doesn't reproduce on Fenix.

**Comment by cpeterso** [comment] 2019-04-25 21:12
Thanks! I recognize this problem. I think it's related to a Gecko bug that also affects Fennec: tapping Instagram's tiny `x` button is too hard and the "missed tap" causes text to be selected.

https://bugzilla.mozilla.org/show_bug.cgi?id=1542381

**Comment by lobontiumira** [comment] 2021-07-06 07:20
Due to the fact that 1542381 issue has been fixed and closed, and this issue no longer can be reproduced on 8.16.0 Focus build with Google Pixel (Android 10), I'll close it.

**Closed by lobontiumira** 2021-07-06 07:20 UTC
Labels: Geckoview🦎, bug
