### ISSUE TITLE
RTL problem in Firefox Focus for Android

### ISSUE THREAD

**Issue by afarsi** [mozilla-mobile/focus-android#1427] opened 2017-10-01 13:11 UTC
Hi there.
I'm testing Firefox Focus For Android via BuddyBuilds. I have latest version of app via it.
My phone's UI language is Persian(Farsi) all of the times. My Firefox Focus languge is Default(Based on OS current language).
In this case:
1-when i open Firefox Focus, it's main menu option(three vertical dots) is in right side of screen and options of main menu are on left side of menu(while they should be on right side and that three dots should be on left side)
2-If i rotate my phone to horizontal status, and again rotate it to vertical status, the main menu option will go to left side of screen! (Now, the main menu is in correct status). 
3-If i got out of app and again come to app, i will see status that describbed in pragraph 1 and again i shoud follow line 2 to make it correct.
4-In addition, when i go to settings, and returen again, i will have a main menu in correct status. It working like pragraph 2
5-If i do a search, and return, nothing will happen and main menu will remain on right side of screen and it's options will remain on left side of menu. (It's incorrect and like paragraph 1).
6-If i go to About/Your rights/Help and return to main window, nothing will happen and menu will remain in incorrect status. (Like pragraph 1).
It's like playing a game for me! and can be like a game for other users!!! Menu game!!

Result: Only going to settings and return or rotate phone screen and return(Auto Rotate option of phone should be enabled), will make menu correct unless you go out out of app and return to it again.

In addtion, in this case(phone language=Persian and Focus language=Default), settings options are in invalid direction They should be RTL but they are LTR. If you want to see correct direction, you can select Persian language in Focus instead of Default. Nothing will happen when i rotate phone,... Only soultion is changing Focus language from default to Persian.

In addtion, if i select Persian language in settings, all of things are correct(From main menu to Settings) and if i go out of app and return and select default language in Focus settings again, all of things **will remain correct** even if i go out of app while it's language is default! Now, If i touch a squre button in that is on buttom side of android os, i will see list of **open apps and i can remove them from memmory** by a recycle bin button. In this case, if i return to Firefox Focus again and it's language is default, i will see anything **incorrrect again**(Like prapgraph 1).
I attached the screenshots, you can see the status.

Note:
1-My device is Huawei Y6 Pro (TIT-AL00)
2-My OS is Android 5.1 (Huawei EMUI 3.1 Lite)
3-Device languge is Persian(Farsi)
4-Firefox Focus Version: 2.0 (Build 2782)
5-In device's developer options, we have an option named Forced RTL (Make RTL dir forced for all apps), it's disabled by default.
6-All of other apps like WhatsApp are getting their language settings from os. But their direction are correct.

Amir Farsi
Member of Persian L10n Team

![screenshot_2017-09-30-15-28-54](https://user-images.githubusercontent.com/19834847/31054718-14cca884-a6c6-11e7-9ec4-4855dda7d042.png)
**Invalid and when Focus language is default**
![screenshot_2017-09-30-15-29-26](https://user-images.githubusercontent.com/19834847/31054720-1fe7b56a-a6c6-11e7-9c21-bba439b5a888.png)
**Invalid and when Focus language is default**
![screenshot_2017-09-30-15-35-59](https://user-images.githubusercontent.com/19834847/31054723-1ffd4308-a6c6-11e7-88b3-da4e3f5f3909.png)
**Correct and when Focus languge is Persian**
![screenshot_2017-09-30-15-36-06](https://user-images.githubusercontent.com/19834847/31054724-20034244-a6c6-11e7-9976-c77f0bfc885d.png)
**Correct and when Focus languge is Persian**
![20170930_153201](https://user-images.githubusercontent.com/19834847/31054726-306ce2ac-a6c6-11e7-8d4c-857d42465b70.jpg)
**Incorrect and when Focus languge is Default and i doesn't rotatted phone's screen**
![20170930_153343](https://user-images.githubusercontent.com/19834847/31054727-30754168-a6c6-11e7-9a51-95b75e7d80cf.jpg)
**Correct and when Focus languge is Persian or Default and i roatated phone's screen or i went to settings and returned**

**Comment by afarsi** [comment] 2017-10-01 13:23
Addititional comment:
When Focus language is default, Focus can't understand language of OS is Persian and as result when i go to help, it shows only a blank white screen. It working correctly when Focus language is Persian.

**Comment by pocmo** [comment] 2017-10-04 08:51
Thank you for this detailed bug report. Such issues are often hard to spot if none of the engineers is using a RTL language. This is something we should look into fixing.

**Comment by Bringoff** [comment] 2017-10-05 16:09
@pocmo I think, "Force RTL layout direction" might be a solution for such cases, in order not to switch to Persian/Arabic/etc for testing purposes. It may be reasonable to configure one of emulators/devices to use this option all the time.

**Comment by afarsi** [comment] 2017-10-06 20:48
@Bringoff I tested this option(Force RTL layout) and in this case(If this option enabled), Focus will work fine with enabled "Force RTL layout direction". But if all of phones this option is disabled by fefault.
In addition, all of my apps (Eg: Firefox Mobile) also are working fine, except Focus.
In addition, we tested focus on two phones with Android 8.0 and Android 6.0(Nexus). On these phones we coudn't detect reported problem. But we tested Focus(Focus that is on Google Play) on a Lg Stylus phone with Android 5.0 and we detected reported bug again.
It seems this bug is on Android 5.0 , 4.0 and lower.

**Comment by afarsi** [comment] 2018-02-02 07:01
Hey, i found same problem in Fiefox for Android(Fennec too). Look at here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1435171

**Comment by lobontiumira** [comment] 2021-09-28 14:18
@afarsi could you please check these RTL situations on your device using the RC 92.1.1 build?
I tested on a Samsung Galaxy Tab A6 (Android 5.1.1) device, and all the issues mentioned above are now fixed.
Thank you!

**Comment by lobontiumira** [comment] 2021-11-22 08:15
Taking into consideration the fact that the reporter has not given any feedback, and I wa not able to reproduce these issues anymore, I'm closing this ticket.
Feel free to open a new one, if you encounter any other issues.
Thank you!

**Closed by lobontiumira** 2021-11-22 08:15 UTC
Labels: l10n, help wanted, P5, 🌐 L10N:RTL
