### ISSUE TITLE
Remote debugging not working on Focus Nighlty and Beta

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#5624] opened 2021-10-14 15:01 UTC
## Steps to reproduce
1. Open Focus, go to Settings>Advanced and enable Remote debugging
2. Connect the device to a computer.
3. Open Firefox desktop and go to about:debugging.
### Expected behavior
The app should be displayed in about:debugging, you should be able to connect to it.
### Actual behavior
Focus Nightly and Beta don't show up, only the debug version.
### Device information

* Android device: Pixel 2, android 9
* Focus version: Nightly 10/14, v94 Beta1

**Comment by sflorean** [comment] 2021-10-20 10:09
Tested on v94 Beta 2 and "Mozilla Nightly - 94.0" is displayed, along with the Fenix beta logo. Devices:
- Pixel 3 (Android 12)
- Samsung Note 10 (Android 11)

**Comment by lobontiumira** [comment] 2021-11-03 15:49
I was able to reproduce this on Beta 95.0.0-beta.1 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by jonalmeida** [comment] 2021-11-16 17:20
I'd like to recommend putting this on the tracking board because it had an affect in solving https://github.com/mozilla-mobile/focus-android/issues/5879 so it may be a problem in the future too.

**Comment by ionutbedregeanu** [comment] 2021-11-24 07:15
It seems that all the builds(debug, nightly, beta) are displayed as "Mozilla Nightly" and sometimes an app restart is required(maybe that's the bug) in order to be displayed.
@lobontiumira Can you please retest it to see if you still reproduce it?

**Comment by lobontiumira** [comment] 2021-11-24 09:26
@ionutbedregeanu it doesn't work even after force closing and re-opening the app (after enabling the "Remote debugging via USB/Wi-Fi" option).
Tested on the latest Focus Nightly build 95.0 (353281028 GV 96.0a1-20211123094249) with Google Pixel (Android 10).

**Comment by ionutbedregeanu** [comment] 2021-11-24 11:55
After this [pr](https://github.com/mozilla-mobile/focus-android/pull/5941) the app should be displayed when remote debugging is enabled.
For the second bug regarding the name and icon which are not updated for every type of build I created a bug in Bugzilla
https://bugzilla.mozilla.org/show_bug.cgi?id=1742792

**Comment by lobontiumira** [comment] 2021-11-25 08:48
Verified as fixed on the Focus Nightly build 95.0 (353291037 GV 96.0a1-20211124035313), and the latest debug build from main, with Google Pixel (Android 10), and Sony Xperia Z5 Premium (Android 7.1.1).
Both Nightly, and debug builds are displayed as Mozilla Nightly for now:

![Screenshot_1](https://user-images.githubusercontent.com/40694158/143408877-efb4dd16-94bf-4168-b4d1-e8625db32274.jpg)

**Closed by lobontiumira** 2021-11-25 08:48 UTC
Labels: bug, QAReady, Beta/Nightly Track (FADP-14)
