### ISSUE TITLE
Cannot return from a failed FB Messenger share intent - app not installed

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#2547] opened 2018-04-27 15:01 UTC
### Steps to reproduce
FB. Messenger app should not be installed on the device.
1. Go to espn.com and open an article.
2. Tap the Facebook Messenger share icon.
3. After the redirect, press back to return to espn.

### Expected behavior
On Fennec, the share icons on espn.com don't respond to tap if the app is not installed.
If you are redirected to an error page, you should be able to return to the initial page by pressing the back button.

### Actual behavior
An error page is displayed. Cannot return back to the espn page.

Build:
Focus Beta v5.0 & Focus 4.1
Device:
Google Pixel (Android 8.1.0)

**Comment by lobontiumira** [comment] 2022-02-22 08:51
I was not able to reproduce this issue on the latest Focus builds.
Closing this ticket.

**Closed by lobontiumira** 2022-02-22 08:51 UTC
Labels: bug, P4
