### ISSUE TITLE
Add an option to block all pop-ups.

### ISSUE THREAD

**Issue by smartfonreddit** [mozilla-mobile/focus-android#1255] opened 2017-08-31 05:14 UTC
Not just pop-up ads, but any popup. It could be a cookie message, a custom message, an email subscription offer etc. The problem is, Focus won't remember that I closed a popup because it wipes cookies and storage that store that information, so if I open another link of the same website few seconds later, it'll show the same large popup again. This makes it somewhat impractical to have Focus as the default browser.

**Comment by pocmo** [comment] 2017-09-04 09:06
This seems to be a duplicate of #1254

**Closed by pocmo** 2017-09-04 09:06 UTC
