### ISSUE TITLE
Unable to scan QR code on gov.uk

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla-mobile/focus-android#6130] opened 2021-12-27 15:59 UTC
## Prerequisites
VPN active pointing to UK

## Steps to reproduce
1. Navigate to https://www.gov.uk/report-covid19-result
2. Tap "Start now" button.
3. Proceed with the form without an account ("Continue without an account" > Myself > England > No > Another reason > Another reason (for example, to follow NHS advice or Government guidance)  > Today, <day month year>).
4. Tap "Scan test strip QR code" button.
5. Observe behavior.

### Expected behavior
"Allow camera use" popup is triggered in order to scan the document. 

### Actual behavior
Nothing happens, "Allow camera use" popup is not triggered.

### Device information

* Android device: Google Pixel 5 (Android 12) - 1080 x 2340 pixels, 19.5:9 ratio (~432 ppi density), Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density)
* Focus version: Firefox Focus Release 95.2.0 (🦎 95.0-20211215221728), Firefox Focus Nightly 97.0 (🦎 97.0a1-20211223093436)

### Notes
1. The issue is not reproducible on Firefox Nightly 97.0a1 (🦎 97.0a1-20211223093436)
2. Gif attached.
![ScanBroken](https://user-images.githubusercontent.com/12184325/147488112-45c4dfcd-12c1-4cdc-9907-191cc0554531.gif)

**Comment by iorgamgabriel** [comment] 2022-01-05 12:11
Site Permission for camera is Blocked in Focus. This should be clarify with  @jeffreygee and @channingcarter .
https://github.com/mozilla-mobile/focus-android/discussions/5830

**Comment by ionutbedregeanu** [comment] 2022-04-05 06:58
It will be addressed by https://github.com/mozilla-mobile/focus-android/issues/6504

**Comment by ionutbedregeanu** [comment] 2022-04-13 10:01
I will add "QAReady" label because it shouldn't be reproducible anymore

**Comment by softvision-oana-arbuzov** [comment] 2022-04-13 15:57
The issue is no longer reproducible on the latest Focus Nightly build.
![image](https://user-images.githubusercontent.com/12184325/163209484-04c59bcc-83fc-4a55-8c7e-c0c6190e6953.png)
![image](https://user-images.githubusercontent.com/12184325/163209537-d53ddf1d-00df-4ba2-bfa6-ed109326fbb0.png)

**Tested with:**
Browser / Version: Firefox Focus Nightly 101.0a1 (🦎 101.0a1-20220412094307) 
Operating System: Google Pixel 5 (Android 12) - 1080 x 2340 pixels, 19.5:9 ratio (~432 ppi density), Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density)

**Closed** 2022-04-14 08:39 UTC
Labels: QAVerified
