### ISSUE TITLE
Cookies and history from "Help" view

### ISSUE THREAD

**Issue by coffeemakr** [mozilla-mobile/focus-android#1449] opened 2017-10-08 10:59 UTC
Related: #1569 Rethink erase strategy

---
I've noticed that the gecko view showing the "Help" (and probable the "Your Rights" and "About" as well) has cookies, history and auto completion history enabled. The history and auto completion seem to be shared with standard tabs (issue 2) while the cookies are kept only for the Help view (issue 1).

In my opinion the cookies, history, and so on should be disabled or at least cleared when exiting the help view.

Steps to initialize:
 1. Open Help
 2. Tap Search
 3. Enter "Google"
 4. Open "Using Lightning with Google Calendar"
 5. Open "Provider for Google Calendar"
 6. Open "discussion forum"
 7. Open "Web"
 8. Now open "cookie test" page with google search
 9. Set a cookie
10. Leave the help with back button

## Issue 1
Repeat the steps above to view if there are cookies left.
Unexpected behaviour: 
  * Autocompletion in google search
  * Cookies left in test page
  * Google search result entry highlighted

Screen record including initializing steps: https://youtu.be/3gOWPdS46x0  

## Issue 2

1. Open google in new tab
2. Tap search
3. Open search result for "cookie test"

Unexpected behaviour: 
  * Autocompletion in google search
  * Google search result entry highlighted

Screen recording: https://youtu.be/6iV1m1RY_uk

**Edit:**  Taking a second try I was able to see the cookie with the "normal browser".

**Comment by pocmo** [comment] 2017-10-09 09:40
Looks like a duplicate of #1306. Thanks for posting this with detailed steps to reproduce!

**Comment by coffeemakr** [comment] 2017-10-09 09:57
Ah yes this seems to be related but only a part of this issue. The other part is that the help view uses cookies and history can't be cleared until a new tab is opened.

**Comment by bbinto** [comment] 2017-10-10 15:38
Revisit next week

**Comment by mcomella** [comment] 2017-11-06 19:23
I landed #1306 so that should be fixed.

However, I verified that the first issue - that the Help WebView shares state with the main browser – is still an issues. We should consider fixing it in, or after, #1569. Note that it'd be impractical to separate them completely when opening Help from the main browser, but it should be fine to separate it from the start screen.

**Comment by pocmo** [comment] 2017-11-07 17:07
Now that we support multiple tabs I wonder if "help" should just open a tab instead of wrapping the help page in a new activity?

**Comment by mcomella** [comment] 2017-11-07 20:20
> Now that we support multiple tabs I wonder if "help" should just open a tab instead of wrapping the help page in a new activity?

This would be less work: it would invalidate this issue because then Help conceptually would be expected to share the session information with other open tabs.

@pocmo Are there other views that rely on a WebView that we should also be concerned about (e.g. the InfoActivity)?

**Comment by pocmo** [comment] 2017-11-08 10:43
@pocmo Are there other views that rely on a WebView that we should also be concerned about (e.g. the InfoActivity)?

The other pages (about/privacy/rights) are internal ones. However they contain links. So you could follow them and then collect cookies etc. on the pages you visit.

**Comment by mcomella** [comment] 2017-11-28 17:53
To summarize the work here. We could either:
1. Open those links in tabs as Sebastian suggests
1. Fix the WebView separation as part of our erase refactor strategy.

1) is much easier to do so I recommend it. I'd imagine this issue would be P3 or a P5.

@bbinto Thoughts? Or should we wait for next week's triage?

**Closed** 2018-07-17 00:50 UTC
Labels: needs investigation
