### ISSUE TITLE
Ability to lock the navigation/menu bar

### ISSUE THREAD

**Issue by kodeo** [mozilla-mobile/focus-android#4459] opened 2020-01-16 21:55 UTC
Firstly may I say that I absolutely love Firefox Focus, it really is the best thing since sliced bread on Android.

The only time I ever reluctantly revert to Chrome is when on a page on which the body is supposed to fill the full screen with height: 100% / 100vh or whatever, as may occur with a game or some other canvas-based endeavor, in which case the the way Focus navigation/menu bar disappears on scroll causes the page to move around as you drag on screen.

Could we please, please have the option to lock the menu bar in place to avoid this? Thanks!

**Comment by abrahm** [comment] 2020-02-25 22:22
This is one of the bigger usability problems I have with firefox focus.

Go to https://jspaint.app and try to draw. It's pretty annoying.

Go to https://wunderground.com. The bottom-floating navigation bar is hidden because of the same behavior.

**Comment by lobontiumira** [comment] 2022-03-02 15:16
I was not able to reproduce this mentioned issues on the https://jspaint.app/, nor on https://www.wunderground.com/ on the latest RC 98.1.0.
I'll close this ticket.

@kodeo feel free to file a new ticket if you encounter any issues.

**Closed by lobontiumira** 2022-03-02 15:16 UTC
