### ISSUE TITLE
Sometimes Text Doesn't Slide Up When Phone is Unlocked

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#2957] opened 2018-07-23 17:22 UTC
![screenshot_20180706-101732](https://user-images.githubusercontent.com/25442310/43092415-ff3d36ee-8e61-11e8-8dcb-949050acee5d.png)

## Steps to reproduce
I can't reliably reproduce, but sometimes when I lock my phone with Focus open, and then unlock, I will get the screenshot above.

### Expected behavior
Text slides up for keyboard

### Actual behavior
See screenshot 

### Device information

* Android device: Pixel 2
* Focus version: GV Nightly (but shouldn't matter)

**Comment by ekager** [comment] 2018-07-31 21:29
The keyboard does slide, but the animation of the text sliding up behind it sometimes does not happen

**Comment by lobontiumira** [comment] 2021-12-07 09:51
I was not able to reproduce this issue on the latest Focus Nightly from 12/7, nor on RC 95.1.0.
I'll close this issue.

**Closed by lobontiumira** 2021-12-07 09:51 UTC
Labels: bug, help wanted
