### ISSUE TITLE
Update icon and branding

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#4650] opened 2020-11-10 20:43 UTC
| Current | Updated |
| --- | --- |
| <img width="246" src="https://user-images.githubusercontent.com/51007/98611328-993cf280-2356-11eb-9d42-2524e9f7a1f3.png"> | <img width="246" src="https://user-images.githubusercontent.com/51007/98611254-73afe900-2356-11eb-8e7f-1fcce2fd679a.png"> |

Source: https://drive.google.com/drive/folders/1m4v_vAtgJasttH2sCy8HiHWolhGB5viN

iOS issue: https://github.com/mozilla-mobile/focus-ios/issues/1750

**Comment by jonichan** [comment] 2020-12-14 19:16
Has this work been completed already? Should we update the Focus assets on SUMO as well?

**Comment by brampitoyo** [comment] 2020-12-15 22:02
Hi @jonichan, as far as I’m aware, the work hasn’t been done on either iOS or Android. I would wait until both issues are picked up and maybe closed before updating the SUMO assets.

**Comment by cadeyrn** [comment] 2020-12-16 20:10
@brampitoyo Could you make the sources public? The access to the Google Drive link is restricted.

**Comment by brampitoyo** [comment] 2020-12-17 04:27
@cadeyrn For sure, I can. It’s done.

**Comment by keunes** [comment] 2021-02-26 07:34
Duplicate of #4435?

**Comment by pocmo** [comment] 2021-03-29 11:39
@brampitoyo I looked at updating the icons. The PNGs look good, but the SVG I cannot import into Android Studio because of some unsupported SVG features. Also online converters like https://svg2vector.com/ seem to fail. For modern Android versions we need it in such an Android vector drawable format (Fenix: https://github.com/mozilla-mobile/fenix/blob/master/app/src/release/res/drawable/ic_launcher_foreground.xml)

**Comment by brampitoyo** [comment] 2021-03-30 01:59
I’ve re-generated an SVG file that should be convertable, and put the result under the `XML` folder. Let me know if this asset can be imported into Android Studio successfully?

If you want to try converting the raw file yourself, it’s under the `SVG` folder.

**Comment by pocmo** [comment] 2021-03-30 09:06
@brampitoyo This one works great. Thank you! We used to have "nightly" and "dev" (for local builds) variations too. Do you have something for those variants too? :)

* Dev (xxxhpdi exmaple)
  * https://github.com/mozilla-mobile/focus-android/blob/master/app/src/debug/res/mipmap-xxxhdpi/ic_launcher.png
  * https://github.com/mozilla-mobile/focus-android/blob/master/app/src/debug/res/mipmap-xxxhdpi/icon_foreground.png
* Nightly (xxxhdpi exmaple)
  * https://github.com/mozilla-mobile/focus-android/blob/master/app/src/nightly/res/mipmap-xxxhdpi/icon_foreground.png
  * https://github.com/mozilla-mobile/focus-android/blob/master/app/src/nightly/res/mipmap-xxxhdpi/icon_background.png
  * https://github.com/mozilla-mobile/focus-android/blob/master/app/src/nightly/res/mipmap-xxxhdpi/ic_launcher.png

**Closed** 2022-04-01 14:17 UTC
Labels: P2
