### ISSUE TITLE
Copy Link Address often gives relative URLs

### ISSUE THREAD

**Issue by alexlamsl** [mozilla-mobile/focus-android#4206] opened 2019-02-17 07:17 UTC
Only happens after updating Firefox Focus this month.

`Copy Link Address` now writes `/path/page.html` to clipboard instead of `http://site.com/path/page.html`

**Comment by thedanielgray** [comment] 2019-02-21 23:35
Yes, the same thing happened to me when copying a link from amazon.com, the copied URL only contained /blablablabla instead of amazon.com/blablablabla

**Comment by lobontiumira** [comment] 2021-07-05 12:15
I was not able to reproduce this issue on the 8.16.0 Focus build using a Google Pixel (Android 10).
I will close this issue.
Feel free to open a new one if you encounter this again.

**Closed by lobontiumira** 2021-07-05 12:15 UTC
