### ISSUE TITLE
Autofill prompt is not displayed under the credentials fields

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6838] opened 2022-04-06 12:15 UTC
## Steps to reproduce
1. Install a password manager app (i.e. Lastpass).
2. Setup the app to have autofill rights (check the app's instructions).
3. In the password manager app, fill up some credentials for some pages (like facebook.com, or linkedin.com).
4. In Focus, go to website that requires credentials (one that has the credentials saved in the password manager app), and tap the login text field.

### Expected behavior
The autofill prompt is displayed below the credentials fields.

### Actual behavior
The autofill prompt is displayed below the credentials fields, sometimes hard to observe by the user.

### Device information
* Android device: Lenovo Tab M10 (Android 10), Oppo Find X3 Lite (Android 11)
* Focus version: Beta 100.0.0-beta.1, Nightly 101.0a1 from 4/6
* Reproducible also on Fenix Beta 100.0.0-beta.2, Nightly 101.0a1 from 4/6
* Not reproducible on Chrome

![autofill](https://user-images.githubusercontent.com/40694158/161972271-a6289e40-a48f-41f5-979a-678acd52b490.png)

**Comment by Mugurell** [comment] 2022-04-07 07:51
This is a GeckoView/layout issue, moving to Bugzilla.

**Comment by Mugurell** [comment] 2022-04-07 07:52
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1763570

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by Mugurell** 2022-04-07 07:52 UTC
Labels: bug

**Comment by cpeterso** [comment] 2022-04-07 17:37
@lobontiumira - I see that you could reproduce this bug in Fenix and Focus 101.0a1. Is this a recent regression? Is this bug reproducible in any earlier versions of Fenix?

**Comment by lobontiumira** [comment] 2022-04-08 08:21
@cpeterso it doesn't reproduce on Focus Nightly 100.0a1 (build 360741707 with GV 100.0a1-20220315091352) with Oppo Find X3 (Android 11).

![Screenshot_2022-04-08-11-19-27-89_11753d9bf2a67eec1c984b8ccb4d0671](https://user-images.githubusercontent.com/40694158/162395569-7118fc0e-af51-495e-ad51-ac1fd8fd6995.jpg)

**Comment by cpeterso** [comment] 2022-04-08 19:43
> Focus version: Beta 100.0.0-beta.1, Nightly 101.0a1 from 4/6
> Reproducible also on Fenix Beta 100.0.0-beta.2, Nightly 101.0a1 from 4/6

> it doesn't reproduce on Focus Nightly 100.0a1 (build 360741707 with GV 100.0a1-20220315091352) from 3/15 with Oppo Find X3 (Android 11).

Thanks for verifying! Since the bug is reproducible in Focus Beta 100.0.0-beta.1 from 4/6 but not in Focus Nightly 100.0a1 from 3/15, then the bug was introduced in Focus Nightly 100.0a1 between 3/15 and 4/4 (when Nightly 100.a1 merged to Beta 100).

Here are all the Gecko and GeckoView code changes between 3/15 and 4/4:

https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=d36030f3adc34dc9b756bc9aefe5b277cbf58553&tochange=1ce63246334ec627d74c38d7acd5b858c781336a

There are a lot, but this bug fix related to "GeckoView Prompts Adjustment" looks suspicious:

https://bugzilla.mozilla.org/show_bug.cgi?id=1712414

I'll ping the developer in Bugzilla.
