### ISSUE TITLE
"Copy link address" not working on Android 10

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/focus-android#4515] opened 2020-05-08 13:53 UTC
## Steps to reproduce
1. Go to cnn.com.
2. Long click one of the links.
3. Tap on "Copy link address".
4. Go to the URL bar and paste the link. 

### Expected behavior
The link is copied and the "Paste" option is displayed.

### Actual behavior
The link is not copied and the "Paste" option is not displayed.

Notes: reproducible also with "Copy image address". 

### Device information
* Android device: Samsung Galaxy Note10 (Android 10).
* Focus version: Focus: 8.3.0, Build ID: 341281936.

![20200508_163805](https://user-images.githubusercontent.com/58466444/81412296-52becf00-914c-11ea-9c78-6ab49c8ba004.gif)

**Comment by partha2000** [comment] 2020-05-13 18:20
@sflorean The bug is not reproducible on my device. Here it properly displays the paste option. I think clicking on the 'clipboard' option on your device will produce the same result as 'paste'.

- Android Device: Xiaomi Redmi Note & pro (Android 9)

**Comment by lobontiumira** [comment] 2022-03-02 14:56
I was not able to reproduce this issue on the latest builds, using the following devices:
* Lenovo Tab M10 (Android 10),
* Google Pixel (Android 10),
* Xiaomi Mi8 Lite (Android 10), and
* Oppo Find X3 Lite (Android 11).

I'll close this ticket.

**Closed by lobontiumira** 2022-03-02 14:56 UTC
Labels: bug
