### ISSUE TITLE
Apostrophe in the error pages replaced with other symbols

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3746] opened 2018-10-25 12:23 UTC
## Steps to reproduce
1.  Type an invalid URL and press Go.
2. Verify point #2 of the error text.

### Expected behavior
"check your device's data or Wi-Fi connection".

### Actual behavior
The apostrophe is replaced with other symbols. 
![screenshot](https://user-images.githubusercontent.com/4037709/47499872-d87c7180-d869-11e8-987d-d4d4a341673a.jpg)

### Device information
* Focus version: 8.0 (#322971210)

**Comment by ekager** [comment] 2018-10-26 23:29
I can reproduce on master. 
@jonalmeida , are you seeing this same issue using AC Error Pages + GV? I don't think we would do anything differently than you all since we've been using the component.

**Comment by jonalmeida** [comment] 2018-10-27 17:06
@ekager Yes, I see it too. It's because of the apostrophe we're using in the strings file.

We need to change that from `’` to `&apos;`. I'll have this merged in for the next release.

**Comment by jonalmeida** [comment] 2018-11-12 17:33
This is fixed in 0.29 of components.

**Comment by lobontiumira** [comment] 2021-12-07 12:27
Verified as fixed on the 12/7 Focus Nightly build with Samsung Galaxy Note 8 (Android 9):

![aaa](https://user-images.githubusercontent.com/40694158/145028932-274a4033-48be-467c-8615-e9a44bb14e75.jpg)

**Closed by lobontiumira** 2021-12-07 12:27 UTC
Labels: bug
