### ISSUE TITLE
Playback does not continue when returning from another tab

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/focus-android#4508] opened 2020-04-09 12:54 UTC
## Steps to reproduce
1. Open youtube.com on Focus and play a video clip;
2. Open a new video tab and play a new video;
3. Go back to the previous tab.
### Expected behavior
Video progress is remembered and playback continues.
### Actual behavior
Video progress is remembered and playback does not continue.
### Notes
[Video](https://drive.google.com/open?id=1DvetAgwQxhF_CNSEIsW9DJkh-qmi04UB)
This is not reproducible on the previous Focus build 8.1.1.
### Device information

* Android device: Pixel 2 (Android 9)
* Focus version: Focus: 8.2.0 Build ID: 340992215 GV 75.0.20200403170909

**Comment by ebalazs-sv** [comment] 2020-05-08 13:37
This issue is reproducible on Focus 8.3.0 (Build #341281936) GV 76.0.20200429185419 with Pixel 2 (Android 9).

**Comment by sflorean** [comment] 2020-05-08 14:03
Reproducible on Focus: 8.3.0 (Build ID: 341281936) with Samsung Galaxy Note10 (Android 10).

**Comment by Diana-Rus** [comment] 2020-06-09 09:17
Reproducible on Focus 8.4.0 with GV 77.0.20200602142841 on Google Pixel 3 XL (Android 9).

**Comment by ebalazs-sv** [comment] 2020-08-28 11:46
This issue is still reproducible on Focus 8.7.2 GV 80.0.20200827204751, from 8/28, with Pixel 2 (Android 9).

**Comment by ebalazs-sv** [comment] 2021-05-05 11:36
This issue is reproducible on Focus 8.15.3 GV 88 with Huawei P9 Lite (Android 7).

**Comment by lobontiumira** [comment] 2022-02-22 14:41
This issue reproduces on the 2/22 Focus Nightly build 99.0 with Samsung Galaxy Note 8 (Android 9).
It is also reproducible for vimeo.com site.

**Comment by ionutbedregeanu** [comment] 2022-06-10 13:42
@jeffreygee Is this expected behaviour or it's a bug?

**Comment by jeffreygee** [comment] 2022-06-22 21:07
@ionutbedregeanu @amedyne after discussing with the UX team, we're going to propose this as a platform fix, so I will be writing up a new scoping ticket for the expected behavior of videos for both Fx and Focus.

**Comment by ionutbedregeanu** [comment] 2022-06-24 10:29
Since a new ticket will be created to address this, I will close this one

**Closed by ionutbedregeanu** 2022-06-24 10:29 UTC
Labels: bug, UX
