### ISSUE TITLE
Images open zoomed-in instead of in overview mode

### ISSUE THREAD

**Issue by phunkular** [mozilla-mobile/focus-android#1416] opened 2017-09-28 19:35 UTC
I susoect that this has appeared since the inclusion of tabs as it's not something that I noticed before.

To reproduce:
1. visit reddit.com
2. open some images
3. notice that large resolution images are fully zoomed in when opened

What's expected:
Images should be opened in overview mode, that is to say, zoomed out fully so that you can see the whole image regardless of size or resolution as soon as it is loaded. Then if you need to, you can zoom in for more detail.

What happens:
Currently,  the image is opened fully zoomed in. This means that if it's a high resolution landscape image then all you see is the dark grey 'nothing' background bars. To see the whole image you must zoom out almost everytime. The current experience is quite disorientating as you miss the context of seeing the whole image first, and often you will have to zoom out and back in again which is very clunky.

thanks

**Comment by pocmo** [comment] 2017-09-29 17:29
Duplicate of #1016

**Closed by pocmo** 2017-09-29 17:29 UTC
