### ISSUE TITLE
Advanced homescreen

### ISSUE THREAD

**Issue by dimqua** [mozilla-mobile/focus-android#1044] opened 2017-07-30 16:56 UTC
In Firefox, you can easly open your favorite website (or two) by using your homescreen's "bookmarks".

I suggest to implement the same feature in Focus.

**Comment by xgear-public** [comment] 2017-07-31 11:51
Agree, it would be grate to have home page with bookmarks.

**Comment by pocmo** [comment] 2017-08-01 07:30
"Add to Home screen" is being worked on in #833. Closing this as a duplicate of #833.

**Closed by pocmo** 2017-08-01 07:30 UTC
