### ISSUE TITLE
"Open in..." option doesn't display the debug Focus builds installed

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5632] opened 2021-10-15 09:14 UTC
## Prerequisites
Make sure you have at least two Firefox Focus builds installed, and at least one of them is a debug build.

## Steps to reproduce
1. Install Beta 94.0.0-beta.1.
2. Open a page, and from the three-dot menu select the "Open in..." option.
3. Observe the installed apps displayed in the "Open in..." dialogue.

### Expected behavior
All the installed apps that are suitable for opening the page are displayed.

### Actual behavior
The Focus debug builds installed are not displayed at all.
I had the latest debug build from main from 10/15, and Firefox Focus Nightly.

### Device information
* Android device: Lenovo Tab M10 (Android 10), Pixel 2 (Android 9)
* Not reproducible on Google Pixel (Android 10)
* Focus version: Beta 94.0.0-beta.1
* Focus Nightly, and the debug build display Focus Beta, but not each other.

![Screenshot_1](https://user-images.githubusercontent.com/40694158/137463173-3c94f050-6632-45d2-a8c6-fece88cc42aa.jpg)

**Comment by pocmo** [comment] 2021-10-15 13:19
Agree, let's see if we can use the implementation from A-C. And yeah, we will have to add the new Focus Nightly/Beta builds to it too.

**Comment by delia-pop** [comment] 2021-11-04 09:46
Tested on Beta 95.0.0-beta.1 build and latest debug build from main 11/04 with Huawei P9 Lite (Android 8).

The issue is verified fixed on the **debug** build. With the debug build set as default browser, on both browser page and custom tab the suitable applications to open the page with are displayed: chrome, beta build and the debug build itself.
 
@ionutbedregeanu Please note that with the **Beta 95.0.0-beta.1** build set as default browser, on both browser page and custom tab only the chrome and Debug build are displayed, without the Beta build itself.

![Capture](https://user-images.githubusercontent.com/89388888/140291876-317150f9-e482-4ee3-a813-d673c316568f.PNG)

**Comment by ionutbedregeanu** [comment] 2021-11-08 13:19
I don't think we should show even the current browser in Open in list. We should log a bug for that.

**Closed** 2021-11-11 15:54 UTC
Labels: bug, a-c, QAVerified

**Comment by lobontiumira** [comment] 2021-12-02 10:25
This issue still reproduces on RC 95.1.0 with Lenovo tab M10 (Android 10), and Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by lobontiumira** [comment] 2021-12-08 09:36
This issue doesn't reproduce in Beta 96.0.0-beta.1, nor in Focus Nightly from 12/7.
It only reproduces on RC 95.1.0 with some devices, like Sony Xperia Z5 Premium (Android 7.1.1), and LEnovo tablet M10 (Android 10):

![open in](https://user-images.githubusercontent.com/40694158/145184517-297209ca-c150-4bfa-a4c3-888f60da6928.png)


**Note:** it does **not reproduce on RC 95.1.0** on the following devices:
* Samsung Galaxy Note10 (Android 11)
* LG G7 fit (Android 8.1.0)
* Xiaomi Redmi Note 8T (Android 9)
