### ISSUE TITLE
Disable X86 UI test 

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#3868] opened 2018-11-09 20:17 UTC
### Why/User Benefit/User Problem
Saves costs
Sim testing doesn't offer significant benefits that device testing cannot
Tablet sim on Firebase is finicky

### What / Requirements
Stop sending the x86 test job to firebase

### Acceptance Criteria (how do I know when I’m done?)
When UI test report only contains ARM test results

**Comment by rpappalax** [comment] 2018-11-30 18:13
dupe of #3987

**Closed by rpappalax** 2018-11-30 18:13 UTC
