### ISSUE TITLE
Allow users to set custom search engines

### ISSUE THREAD

**Issue by vext01** [mozilla-mobile/focus-android#808] opened 2017-06-22 11:55 UTC
Hi,

I'm a new user of firefox focus. I love it, but I would like to use my search engine of choice: startpage.com.

Perhaps we could:

 * Add startpage.com to the list of default search engines.
 * And allow users to add their own search engines.

What do you think? Thanks

**Comment by jpggithub** [comment] 2017-08-28 21:26
Privacy and Google (or Yahoo,...) search engines are paradixal, no?

**Comment by afarsi** [comment] 2017-10-06 21:03
We want at least, www.startpage.com become one of included search engines in Focus. Focus should support secure and open source search engines.
Focus shoudl focus on secure and open source search engines.

**Comment by pocmo** [comment] 2017-10-09 10:08
Closing this as a duplicate of #961. In the next sprint we are exploring options to add/remove custom search engines.

**Closed by pocmo** 2017-10-09 10:08 UTC
Labels: feature
