### ISSUE TITLE
Password Manager autofills password into username field

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#3501] opened 2018-09-27 23:12 UTC
## Steps to reproduce
1. Have an account and login setup on LinkedIn saved in LastPass.
2. Go to http://linkedin.com
3. Click on the password field.
4. Click the popup dialog that shows up from LastPass to auto-fill your password.

### Expected behavior
1. The username is correctly filled in from LastPass.
2. The password is correctly filled in from LastPass.

### Actual behavior
- Both, username and password fields are filled with the password.

### Device information
* Android device: Pixel 2 (Android 9)
* Focus version: 8.0 (Build #322700813 🦎 62.0.3.20180922023437)

> **Note**: This worked perfectly fine before, but a regression seems to have occurred recently.

**Comment by sblatz** [comment] 2018-10-09 19:16
Interesting point: unable to reproduce on Android 6.0 through the notification button.

![notification shade](https://user-images.githubusercontent.com/4400286/46692815-3193a680-cbd6-11e8-9b45-9c7f85f28408.gif)

**Comment by jonalmeida** [comment] 2018-10-09 20:48
Here's video of the issue on Android 9.0 since @sblatz didn't have an Android 9.0 device: https://gfycat.com/ArcticDigitalIndochinesetiger

App Version: 8.0 (Build #322801206 :lizard: 62.0.3.20181001191808)
User-Agent: `Mozilla/5.0 (Android 9; Mobile; rv:62.0) Gecko/62.0 Firefox/62.0`

**Comment by jonalmeida** [comment] 2018-10-12 18:23
I tested this with GV 63 which isn't released yet and I'm still able to reproduce the issue.

**Comment by ekager** [comment] 2018-10-15 23:10
I can also reproduce @jonalmeida with 63, thanks for filing on Bugzilla.

**Comment by sblatz** [comment] 2019-01-01 19:48
Seems like this was fixed for Firefox 64 but is set to ["won't fix" for GV 64](https://bugzilla.mozilla.org/show_bug.cgi?id=1497682#a7114195_430528).

**Comment by cpeterso** [comment] 2019-01-03 22:50
This bug was fixed in GV 65:

https://bugzilla.mozilla.org/show_bug.cgi?id=1497682

**Comment by lobontiumira** [comment] 2021-12-30 08:48
Closing this issue, since it is no longer relevant, and was fixed long time ago.

**Closed by lobontiumira** 2021-12-30 08:48 UTC
Labels: testing, P2, Geckoview🦎, size S
