### ISSUE TITLE
Option to hide FAB button

### ISSUE THREAD

**Issue by Jiack214** [mozilla-mobile/focus-android#890] opened 2017-07-10 12:22 UTC
I'd like an option in settings to hide the floating button and put the erase option in the "3 dot" menu.
Sometimes the FAB button it's annoying and it's functionality could be easily reached in different ways (e.g. from the focus notification)

**Comment by pocmo** [comment] 2017-07-10 15:23
This is a duplicate of #809.

**Closed by pocmo** 2017-07-10 15:23 UTC
