### ISSUE TITLE
Open in Firefox Focus from notifications bar keeps crashing

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/focus-android#4289] opened 2019-05-31 08:40 UTC
Steps to reproduce:

1. Open Focus. Load a web page. Go to the Settings menu.
2. Expand the notification from the notification bar and tap "Open".

Expected behavior
Firefox Focus should open on the settings menu screen.

Actual behavior
Firefox Focus keeps crashing message appears - [video
](https://drive.google.com/file/d/1jyIeofIQhBDXsK6E_E6x-t6bojZr6_RN/view)

Device information
Android device: OnePlus 5T (Android 9); Motorola Nexus 6 (Android 7.1.1)
Focus version: 8.0.12 GeckoView 68.0

[Logcat ](https://drive.google.com/file/d/1BNVWMKuTs8V2arsNd57Z6mB5fzd8gyZq/view)

**Comment by droeh** [comment] 2019-05-31 14:33
Does this reproduce reliably with those steps? I've tried a couple dozen times, both with a local build and the beta release, on both a physical phone (Pixel 2) and x86 emulator without seeing this happen a single time. This looks to be an issue where we're failing to release the display, but tracking down exactly how it happens is going to be difficult without being able to reproduce it on my end :/

**Comment by vesta0** [comment] 2019-05-31 17:51
I just tried on Pixel 3 and I can't reproduce it, mainly because the persistent notification is missing.

**Comment by ebalazs-sv** [comment] 2019-06-03 07:50
@droeh @vesta0 Hi!

I tested this on 8.0.12 GeckoView 68.0 with Google Pixel (Android 9) and it is not reproducible following the steps from my first comment.

This is reproducible on the devices: Samsung Galaxy S8 (Android 9), OnePlus 5T (Android 9); Motorola Nexus 6 (Android 7.1.1).

Thanks!

**Comment by colintheshots** [comment] 2019-06-03 14:46
This is the Display Already Acquired crash. The solution is to avoid loading two browser fragments in any edge case or situation even briefly as it'll crash GeckoView. We struggled with this same issue on Fenix.

**Comment by kbrosnan** [comment] 2020-09-22 23:47
I hit this looking for different crash for @droeh  Looks like older versions of Android might be needed to hit this easily?

* Open Focus and load a website
* Open the 3 dot menu and select settings
* Swipe down the notification shade and select open from the Focus notification
 

https://crash-stats.mozilla.org/report/index/10f74b7b-da73-43e2-9ca3-69a130200922
https://crash-stats.mozilla.org/report/index/139fae23-c848-45ea-b507-291fd0200922

**Comment by kbrosnan** [comment] 2020-09-22 23:59
Might be a dupe of #4342 which has a PR

**Comment by sv-ohorvath** [comment] 2020-11-09 09:55
Still reproducing on Focus 8.8.4 (GV 81.0.2)

**Comment by lobontiumira** [comment] 2021-03-23 12:37
I reproduced this crash on the 8.14.0 build with Samsung Galaxy Note 8 (Android 9).

**Comment by lobontiumira** [comment] 2021-04-21 07:18
Reproducible on 8.15.1 build with Samsung Galaxy Note 8 (Android 9).

**Comment by lobontiumira** [comment] 2021-04-27 09:14
Reproducible on 8.15.2 with Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by ebalazs-sv** [comment] 2021-05-05 11:15
This issue is reproducible on Focus 8.15.3 GV 88 with Huawei P9 Lite (Android 7).

**Comment by lobontiumira** [comment] 2021-05-31 13:30
I was not able to reproduce this issue on the 8.16.0 build with Google Pixel (Android 10), nor with Samsung Galaxy Note 8 (Android 9).

**Comment by lobontiumira** [comment] 2021-07-09 13:24
Reproducible on 8.17.0 Focus build with Google Pixel (Android 10).

**Comment by lobontiumira** [comment] 2022-01-06 15:06
I was not able to trigger the crash on the latest builds: RC 96.1.0, and 1/6 Focus Nightly with Google Pixel (Android 10).
I'll close this ticket.

**Closed by lobontiumira** 2022-01-06 15:06 UTC
Labels: bug, crash 🔥
