### ISSUE TITLE
Firefox Focus tab goes unresponsive

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/focus-android#4463] opened 2020-01-25 23:06 UTC
## Steps to reproduce (that I am not sure about)
1) open one website
2) navigate to one more
3) leave in the background overnight
### Expected behavior
I can resume Focus and go back to the first website
### Actual behavior
That Firefox Focus tab is unresponsive and cannot be recovered. I can usually tell because the website is white and wasn't before. I can either open a new tab by going to Menu>Settings>Mozilla and opening one there or by just wiping everything. Doing the former and then going back to your original tab makes it go to about:blank and pressing back wipes your while history, even if you have more tabs that work properly.
### Device information

* Android device: Galaxy S5
* Focus version: 8.0.25

**Comment by lobontiumira** [comment] 2022-03-04 09:40
I was not able to reproduce this issue on the latest Focus builds.
@Poopooracoocoo I'll close this ticket, but feel free to open a new one if you encounter this behavior again.
Thank you!

**Closed by lobontiumira** 2022-03-04 09:40 UTC
