### ISSUE TITLE
Add predefined list for adding search engines

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/focus-android#1561] opened 2017-10-25 22:12 UTC
What is the problem we’re trying to solve:

Why it’s important:

Acceptance Criteria (how do I know when I’m done?)

-----

To follow up on #961 - let's iterate on this and make it better. 

A few thoughts to capture from my work done on the previous order:
- should we improve on the manual entry screen and make it a bit more understandable
- can we have a top 5 add engines list for a quick add 
- have an icon above the keyboard for easy add 
- examine the smart bookmarks from firefox

**Comment by lime124** [comment] 2018-03-15 00:05
@brampitoyo for consideration and tracking.

**Comment by brampitoyo** [comment] 2018-03-15 04:01
> can we have a top 5 add engines list for a quick add

This makes a lot of sense. Hard-coding a few values in the system is relatively simple – as long as we only truly have few entries! – and they may just include most additional search engines that most users will want to add most of the time.

The question here is curation:

* If we’re to add a top 5, what should they be? Are we concerned with picking favourites and playing favours? This concern is also relevant if we want to add icons above the keyboard for selecting search engines.
* Should we localise the list? E.g. If the UI language is Russian, you should get Yandex as one of these options.

In terms of design, these search engines can be listed before the user sees the form for easy selection. Tap on the option, tap Save, and you’re done.

<img src="https://user-images.githubusercontent.com/51007/37443608-054b7952-2872-11e8-9780-c845889e28ba.png" width="456">

**Comment by pocmo** [comment] 2018-03-15 13:37
> This makes a lot of sense. Hard-coding a few values in the system is relatively simple – as long as we only truly have few entries! 

Don't forget L10N. Even now you only see like 5 search engines, but there are a gazillion configurations:
https://github.com/mozilla-mobile/focus-android/tree/master/app/src/main/assets/search

> If we’re to add a top 5, what should they be? Are we concerned with picking favourites and playing favours? This concern is also relevant if we want to add icons above the keyboard for selecting search engines.

That's a good question. And I wonder if there is a difference between the initial list and the list that shows up here... for the user ("Why are they not just in the previous list to begin with?") and legal.

> Should we localise the list? E.g. If the UI language is Russian, you should get Yandex as one of these options.

Yes, we will have to. The original list of search engines is also localized and may include some of your options here already (e.g. I'm pretty sure Yandex shows up in Russian Focus).

**Comment by ekager** [comment] 2018-03-15 22:17
I'm concerned about the second point, if we're going to make a list of "top/popular search engines", why not just include them in the list to choose from in the first place?

**Comment by lime124** [comment] 2018-03-15 23:00
Totally hear what you’re saying @ekager. There are some search engines we
aren’t allowed to include so this is kind of a loop hole that will
hopefully be cool with legal.

So ya someone should check with legal about that ;)

**Comment by brampitoyo** [comment] 2018-03-19 03:35
@Sdaswani Do you know anybody in the Legal Team that we can ask some questions to about search engines?

Specifically:

* Are we allowed to include more search engines in our default list of selections?
  * Related to this, can the list of default search engines vary by language/region? (For example, if your locale is en-US, you won’t see Baidu, Yandex or Naver).
* If we’re not allowed to include more search engines in the default list, to what extent are we allowed to suggest other search engines in the “Add” interface?
  * For example, we can list those search engines, do keyboard autocomplete, etc.
  * The user can of course still input their own search engines! We just want to make this process easy and less error prone.

**Comment by Sdaswani** [comment] 2018-03-19 04:33
Hey @brampitoyo , I'm going to punt to @bbinto , you may know the answers to this off the top of her head, or can check with Legal and/or make the decision herself.

**Comment by bbinto** [comment] 2018-03-19 13:56
Will email Mika and Jeff G.

**Comment by mkaply** [comment] 2018-03-20 14:25
I'm confused by this discussion. Focus already does switch the default list of engines when you change to a different language/locale. It uses search_configuration.json (It should be using list.json, but that's a different discussion).

All  of the engines that we would offer for a particular locale are already there, so there are no additional engines you would suggest.

And even if we did support adding more engines, how would a user access them? Are we planning to add more than one engine to the main screen similar to Fennec? Or would a user still have to choose a new default?

**Comment by Sdaswani** [comment] 2018-03-23 20:23
@brampitoyo just getting a status check - is the UX for this work done or do you still need time to finalize mocks?

**Comment by brampitoyo** [comment] 2018-03-26 00:03
@Sdaswani There are two parts to this UX.

I just renamed this issue so that it’s focused specifically on the **predefined list that allows you to add a search engine**

What we can include in this list relies on us having approval from Legal.

Although the UX for this work is now finished, the content we can include in this list relies on approval from Legal. So just to be aware: there’s a chance that this issue may not get implemented.

Refer to #2385 for the second way to solve this problem. We can implement the solution there by solely relying on the search engine to use the OpenSearch standard. As most (if not all) search engines already do this, we can safely implement that solution.

If that’s the case, then feel free to put this issue in the backlog, or close it.

**Comment by brampitoyo** [comment] 2018-03-26 01:39
Referring #2385.

**Comment by Sdaswani** [comment] 2018-03-26 04:27
Thanks @brampitoyo - also just wanted to make sure someone answer's @mkaply's comment - any ideas on his thoughts? https://github.com/mozilla-mobile/focus-android/issues/1561#issuecomment-374616715

**Comment by brampitoyo** [comment] 2018-03-26 23:04
@mkaply I hear your frustration loud and clear!

If we were to add a new search engine, my preference is to first and foremost add it to the list of installed search engines. This way, users won’t even need to tap “Add new”.

The problem is, not all search engines want to be included in this installed search engine list. And manual entry is rife with potential errors. The way solve this problem is by having non-installed search engine available to add instantly, but only with user consent.

@mconnormoz and I are happy to elaborate on this sensitive issue privately. Send us an email if you have any question.

**Closed** 2022-04-24 01:49 UTC
Labels: feature, UX, Legal, P4, wontfix
