### ISSUE TITLE
Buddybuild offers downgrade to an older version

### ISSUE THREAD

**Issue by MikkCZ** [mozilla-mobile/focus-android#1740] opened 2017-11-17 17:42 UTC
I have installed Focus for Android Buddybuild 3425 from email today (Focus itself haven't told me). After that the app offered me update back to 3353.

**Comment by pocmo** [comment] 2017-11-17 18:16
Duplicate of #1707. Unfortunately the buddybuild SDK seems to be buggy.

**Closed by pocmo** 2017-11-17 18:16 UTC
