### ISSUE TITLE
Users are not able to give reviews on google form in android Firefox browser

### ISSUE THREAD

**Issue by dev-arjunan** [mozilla-mobile/focus-android#4621] opened 2020-09-07 14:48 UTC
## Issue Description
We are providing a link to Google reviews in our webpage. When users tap on it, it will redirect to google sign-in page. On successful authentication, webpage will show a popup where users can rate/review it.
Users are able to give comments in Firefox browser in desktop site, chrome browser, chrome android browser without any issues. Problem is with Android mobile browser. It shows 404 page :(

## Steps to reproduce
I have created sample demo page to understand much better. Please try to visit the link in Firefox android browser and chrome android browser to understand the issue.
Sample URL: [Google Review Sample URL](https://dev-arjunan.github.io/google-review/)
Direct URL: https://search.google.com/local/writereview?placeid=ChIJj61dQgK6j4AR4GeTYWZsKWw
Note: Direct url of google review page. This is not working when you open it in Firefox android browser but the same works fine in all other browsers without any issues.

### Expected behavior
It should redirect and show a popup and let users to give reviews.

### Actual behavior
Shows 404 error. Issue occurs only in Firefox android browser but actually works in Firefox desktop app and choose "Request desktop site" in Firefox android browser.

### Device information
Browser / Version: Firefox Android Browser
Operating System: Android
* Android device: Redmi Note 6 Pro
* Focus version: All andorid versions
![Firefox issue](https://user-images.githubusercontent.com/50161510/92399276-aca9c280-f147-11ea-97d0-0c54fe2f5e86.png)

**Comment by lobontiumira** [comment] 2022-03-18 10:35
I was not able to reproduce this issue on the latest Focus builds.
I will close this ticket.
Please feel free to file a new one if you encounter it again.

**Closed by lobontiumira** 2022-03-18 10:35 UTC
