### ISSUE TITLE
 'Powered by Firefox Focus' needs color adjustments

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5630] opened 2021-10-15 06:56 UTC
## Steps to reproduce
1. Install Focus, and set the light theme.
2. Make it the default browser.
3. From Gmail, open a custom tab.
4. Tap on the custom's tab three-dot menu and observe the "Powered by Firefox Focus" background color.

### Expected behavior
The background color is like in the Figma design Violet 05 (#E7DFFF):
![Screenshot_1](https://user-images.githubusercontent.com/40694158/137444898-8f77520e-dc61-443a-8055-926d6b986adf.jpg)

### Actual behavior
The background color is white:
![Screenshot_2](https://user-images.githubusercontent.com/40694158/137444987-3cada793-8cfa-4955-baa8-8ebe74514597.jpg)

### Device information
* Android device: all
* Focus version: Beta 94.0.0-beta.1, the latest debug build from main from 10/14
* From https://github.com/mozilla-mobile/focus-android/issues/5589#issuecomment-943919963

**Comment by channingcarter** [comment] 2021-10-18 18:58
@Kate-Galetski is this something you can work on?

**Comment by Kate-Galetski** [comment] 2021-10-18 19:46
@brampitoyo

**Comment by delia-pop** [comment] 2021-11-04 15:16
Verified as fixed on the latest debug build from main 11/04 with Huawei P9 Lite (Android 8).

Please note that the issue is Still Present on the Beta 95.0.0-beta.1 build.

![Color](https://user-images.githubusercontent.com/89388888/140344399-5a855794-ee63-4ffc-b167-7b2c164db83b.PNG)

**Comment by delia-pop** [comment] 2021-11-10 10:56
Please note that the issue is Still Present on the Beta 95.0.0-beta.4 (Build 353140212 GV 95.0-20211109194756).

**Comment by mcarare** [comment] 2021-11-15 16:19
Closing this as it is marked as fixed on the main branch.

**Closed by mcarare** 2021-11-15 16:19 UTC
Labels: bug, a-c, QAVerified, light-theme

**Comment by delia-pop** [comment] 2021-11-17 14:59
The issue is Still Present on the Beta 95.0.0-beta.5 (build 353202152 GV 95.0-20211114185943) with LG G7 fit (Android 8.1.0).

**Comment by delia-pop** [comment] 2021-12-02 09:50
The issue is Still Present on the RC 95.1.0 (Build 353350147 GV 95.0-20211129150630) with LG G7 fit (Android 8.1.0).

![Screenshot (Dec 16, 2021 11 32 07)](https://user-images.githubusercontent.com/89388888/144396171-210cc747-d58d-4a2c-ab55-68f18ffc274c.png)

**Comment by lobontiumira** [comment] 2021-12-08 08:50
Verified as fixed on Beta 96.0.0-beta.1 with Sony Xperia Z5 Premium (Android 7.1.1), and Lenovo Tab M10 (Android 10).
