### ISSUE TITLE
[2.0 RC2] "search privately" then pressing the back button kills both tabs and exits the app

### ISSUE THREAD

**Issue by phunkular** [mozilla-mobile/focus-android#1334] opened 2017-09-18 09:46 UTC
I would expect it to send me to the tab I just came from instead of killing the whole app

**Comment by pocmo** [comment] 2017-09-21 10:28
1. Going back from an externally opened tab (text selection, share, links, ..) always leaves Focus and ideally gets you back to the app (if you haven't performed a bunch of other navigations in between). This is the intended behavior currently.

2. This should only close the current tab and all others should stay intact. Removing all tabs would be a bug.

I tried to reproduce (2) but couldn't. Here's what I tried:
* Open Focus and open a couple of tabs
* Press home and open another app
* Select some text and press "Search privately"
* In Focus press back.
* -> The tab is closed and I'm back in the previous app. When going back to Focus the other tabs are still open.

@phunkular Can you provide me with the exact steps how to reproduce (2)? Also: What Android device and Android version are you using?

**Comment by phunkular** [comment] 2017-09-22 12:53
hi there, to reproduce (happens every time for me):

1. open focus (klar in my case)
2. Search for anything (one tab, not several)
3. highlight any text
4. select search privately
5. on newly opened tab press back
6. Focus closes with a toast saying private data cleared

miui 9 android 6.0.1

**Comment by phunkular** [comment] 2017-09-22 14:54
same issue on 2.0 final

**Comment by MrGeneric** [comment] 2017-09-22 16:00
@phunkular Not sure whether it's the intended behaviour or not but I was able to reproduce using your steps.
Nexus 5x Focus 2.0

**Comment by phunkular** [comment] 2017-09-28 19:47
I believe it's unexpected. Perhaps we're expected to search privately from external apps and not so much from within Firefox focus?.. In any case I have some more to add:

When several tabs are open and I search privately and then press back, I am sent to homescreen with a toast saying that my data has been cleared. However if I return to focus, my other tabs are still there. So to recap; with just one tab open everything disappears and I'm kicked out to homescreen, and; with several tabs I am kicked out to home screen though the other tabs persist.

**Comment by liuche** [comment] 2017-11-06 18:22
Depends on #1569

**Comment by mcomella** [comment] 2017-11-06 18:46
> Depends on #1569 

It could be fixed by this bug too

**Comment by lobontiumira** [comment] 2021-09-28 14:05
Hi all!
The behavior on the latest RC 92.1.1 is this:
- when the user chooses to search privately from Fenix browser, a new tab is opened in Focus - when tapping back, the tab closes, and the user remains in the Focus app,
- when the user chooses to search privately from an opened tab (tab 1) in Focus, a new tab is opened - when tapping back, the newly opened tab is closed, the previous tab is displayed (tab 1).
Tested with Lenovo Tab M10 (Android 10), Samsung Galaxy Note 8 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).

@phunkular could you confirm this behavior?
Thank you!

**Closed** 2022-04-21 00:48 UTC
Labels: bug, P4, wontfix
