### ISSUE TITLE
Current version not available in F-Droid Store

### ISSUE THREAD

**Issue by Krawei** [mozilla-mobile/focus-android#2034] opened 2018-01-05 13:01 UTC
Relating to #1528 and  my last Ticket #1551 the F-Droid's Focus-Version is kinda outdated (v2.5 in Fdroid vs. v4.0.1 in Playstore).

Will there be a newer version or fix available soon?

Kind Regards,

Krawei

**Comment by Biskvit** [comment] 2018-01-19 09:23
That's a problem with F-Droid's build tools,  and it has nothing to do with the devs here.
F-Droid's data regarding Firefox Klar is up-to-date, and 4.0.1 [was attempted to be built on 23.12.2017](https://f-droid.org/wiki/page/org.mozilla.klar/lastbuild_17) but it failed to build. It's happening with [other apps](https://gitlab.com/fdroid/fdroiddata/issues) too. 
As a result, some apps are getting timely updates, and some aren't.

**Comment by Sdaswani** [comment] 2018-01-19 17:34
Closing since @Biskvit notes the problem isn't something we can fix. Thanks all!

**Closed by Sdaswani** 2018-01-19 17:34 UTC
