### ISSUE TITLE
Regression: Back button history gone after changing to another app

### ISSUE THREAD

**Issue by zekooooo** [mozilla-mobile/focus-android#4681] opened 2020-12-17 15:01 UTC
When I go to desktop or change to another app, and then later change back to Firefox Klar, back button doesn't go back anymore but deletes the tab or erases the session if it's the only tab. Previously (I believe my last version was Klar 8.8.x) the back button would go back as usual.

Using Firefox Klar 8.11.1 (downloaded from Github) on Android 7.

**EDIT:** 

It seems it doesn't actually happen every time I change the app but some time has to pass. Perhaps this might be due to some fix for #4584.

**Comment by jonalmeida** [comment] 2020-12-17 21:13
This is a known side-effect of some upgrades that we're unable to resolve just yet until we make some deeper refactoring that will be coming up next.

Thanks for reporting!

**Comment by Poopooracoocoo** [comment] 2020-12-31 04:07
@jonalmeida I feel like I've been waiting for over a year though :( and that's just this bug. I detail my use of Focus and my data loss in #4684 

Focus has been using GV for like two years now. I miss the webview so freaking much.

**Comment by lobontiumira** [comment] 2022-04-04 06:32
I was not able to reproduce this issue lately, on the latest versions of Focus.
I'll close this ticket, but feel free to file a new one if you encounter it again.

**Closed by lobontiumira** 2022-04-04 06:32 UTC
Labels: bug
