### ISSUE TITLE
[Feature Request] Search with audio input

### ISSUE THREAD

**Issue by GammaBurst101** [mozilla-mobile/focus-android#2205] opened 2018-03-02 12:00 UTC
I think the feature of searching with audio input will be great for focus. What do you guys think?

**Comment by pocmo** [comment] 2018-03-02 12:35
Thanks for filling!

This looks like a duplicate of #1155.

**Closed by pocmo** 2018-03-02 12:35 UTC

**Comment by GammaBurst101** [comment] 2018-03-02 13:41
OK
