### ISSUE TITLE
AssertionError: loadSearchEngineListForLocale

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/focus-android#1994] opened 2017-12-12 20:07 UTC
Seen on the beta 4.0 channel:
```
java.lang.AssertionError: 
  at org.mozilla.focus.search.SearchEngineManager.loadSearchEngineListForLocale (Unknown Source)
  at org.mozilla.focus.search.SearchEngineManager.loadFromDisk (Unknown Source)
  at org.mozilla.focus.search.SearchEngineManager.access$000 (Unknown Source)
  at org.mozilla.focus.search.SearchEngineManager$1.run (Unknown Source)
```

Not that many crashes, behind a lot of the webview crashes.

Comment on this Assertion:
```
// Assertion error because this shouldn't happen: We check whether a key exists before
// reading it. An error here would mean the JSON file is corrupt.
```

One completely unsubstantiated idea might be if there are a) locale files that are now being used that weren't used before, b) and they were corrupted but hadn't been used before.

**Comment by grubdragon** [comment] 2018-01-10 15:43
Anything I can do here? @bbinto @mcomella

**Comment by mcomella** [comment] 2018-01-10 22:40
@grubdragon You could try to figure out why this error is happening and fi xit, but if the comment's correct, there might not much we could do here (i.e. if the JSON file is corrupt).

**Comment by ionutbedregeanu** [comment] 2022-02-23 07:27
I will close this ticket since I didn't succeed to reproduce it

**Closed by ionutbedregeanu** 2022-02-23 07:27 UTC
Labels: bug, P5
