### ISSUE TITLE
Scanning a file with Virustotal does not work

### ISSUE THREAD

**Issue by Gitoffthelawn** [mozilla-mobile/focus-android#995] opened 2017-07-23 07:34 UTC
Scanning a file using virustotal.com does not work.  The file picker never appears.

Tested with Focus/Klar v1.1 on Nougat.

**Comment by pocmo** [comment] 2017-07-24 10:04
We do not support uploading files yet. This is tracked in #937. Closing as a duplicate of #937.

**Closed by pocmo** 2017-07-24 10:04 UTC
