### ISSUE TITLE
All Firefox Apps Into F-Driod

### ISSUE THREAD

**Issue by trymeouteh** [mozilla-mobile/focus-android#3992] opened 2018-12-01 03:27 UTC
Please add all the firefox apps on F-Driod. including Firefox, Firefox Nightly, Firefox Reality, etc.

This way we can enjoy Firefox without Google Play Store!

**Comment by vesta0** [comment] 2018-12-11 19:43
Future consideration by @bbinto :)

**Comment by ionutbedregeanu** [comment] 2022-03-09 14:33
@kbrosnan Do you have any information about this?

**Comment by cpeterso** [comment] 2022-11-26 17:46
Closing this issue as a duplicate of https://github.com/mozilla-mobile/focus-android/issues/4182.

**Closed by cpeterso** 2022-11-26 17:46 UTC
Labels: P4, F-Droid
