### ISSUE TITLE
Device soft-keys not visible in light-theme

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#5623] opened 2021-10-14 14:36 UTC
## Steps to reproduce
1. Set up light-theme in Settings>General.
2. On the homescreen, dismiss the keyboard.
3. Go to Settings, observe the device soft-keys.
4. Open a webpage, observe the device soft-keys.
### Expected behavior
The device buttons should be visible.
### Actual behavior
The device buttons are not visible in light mode.
### Device information

* Android device: Pixel 2, Android 9
* Focus version: Nightly 10/14. Not reproducing on 94-beta1

**Comment by brampitoyo** [comment] 2021-10-18 23:52
This doesn’t seem to be an app-related UX or visual design issue, because device soft-keys is something that’s provided by the OS itself.

**Comment by brampitoyo** [comment] 2021-10-19 02:26
Although I too couldn’t reproduct this issue on my test device (OnePlus One, Android 11), I did find some Light Theme issues when trying to document this behaviour in detail:

| | Light Theme | Dark Theme |
| --- | --- | --- |
| Home screen | ![Screenshot_20211019-151016_Firefox_Focus_Nightly](https://user-images.githubusercontent.com/51007/137832214-b50d0423-1ee5-4522-925d-7929629faedd.png) | ![Screenshot_20211019-151153_Firefox_Focus_Nightly](https://user-images.githubusercontent.com/51007/137832266-dfa611cc-c194-44f1-95af-472dfe03440c.png) |
| Settings | ![Screenshot_20211019-151044_Firefox_Focus_Nightly](https://user-images.githubusercontent.com/51007/137832354-20a0d55a-ce76-4787-b09e-6349248c87e9.png) | ![Screenshot_20211019-151326_Firefox_Focus_Nightly](https://user-images.githubusercontent.com/51007/137832398-bfd24a9b-a633-40e3-a96a-f7ce714847f4.png) |
| Website | ![Screenshot_20211019-151108_Firefox_Focus_Nightly](https://user-images.githubusercontent.com/51007/137832470-92890f08-c9d9-457f-86c5-fca3aa2a8131.png) | ![Screenshot_20211019-151409_Firefox_Focus_Nightly](https://user-images.githubusercontent.com/51007/137832489-0f22b0ee-e162-4594-a926-277d4bfaa507.png) |

On Light Theme, a few elements are still coloured as if the theme is still set to Dark. We should fix them, so that they use Light Theme values.

- Status Bar
- Focus Logo
- 3-button/2-button/gesture System Navigation Bar

Feel free to either rename this issue, or spin up a new issue to fix these. Thanks!

**Comment by mcarare** [comment] 2021-10-19 06:21
@brampitoyo The issues pointed out by you are already fixed on the main branch.

**Comment by sv-ohorvath** [comment] 2021-11-05 09:41
> I cannot reproduce this on a Nokia with Android 10 on the main branch.

@mcarare can you reproduce it on a Pixel 2, Android 9 emulator (or physical device)?
Also reproducing on a Huawei P9 lite (Android 8).

**Comment by mcarare** [comment] 2021-11-05 09:46
@sv-ohorvath I can reproduce it on a Huawei P10 device (Android 10). But that same issue is present on multiple apps on that device. Will add this to the backlog.

**Comment by mcarare** [comment] 2021-11-09 12:43
For QA: Please test this on more devices so we can catch any potential edge cases that could still remain.

**Comment by lobontiumira** [comment] 2021-11-11 09:04
Verified as fixed on the latest Focus Nightly build 95.0 (build 353151050 GV 96.0a1-20211110092453) with the following devices:
* Lenovo Tab M10 (Android 10),
* Google Pixel (Android 10),
* OnePlus 5T (Android 10),
* Sony Xperia Z5 Premium (Android 7.1.1),
* Samsung Galaxy Note 8 (Android 9),
* Samsung Galaxy Tab A6 (Android 5.1.1),
* HTC 10 (Android 8), and
* Xiaomi Mi8 Lite (Android 9).

**Comment by lobontiumira** [comment] 2021-11-17 14:51
Verified as fixed on the Beta 95.0.0-beta.5 (build 353202152 GV 95.0-20211114185943) with the following devices:
* Google Pixel (Android 10),
* Sony Xperia Z5 Premium (Android 7.1.1),
* Samsung Galaxy Note 8 (Android 9),
* Oppo Find X3 (Android 11), and 
* LG G7 fit (Android 8.1).

**Comment by lobontiumira** [comment] 2021-12-03 11:48
I re-encountered this issue on the 12/3 Focus Nightly build with Google Pixel (Android 10):

![soft keys](https://user-images.githubusercontent.com/40694158/144597533-c3540116-22c7-4102-98bc-19a2b6350db1.png)


https://user-images.githubusercontent.com/40694158/144597736-50a45a01-f626-41fb-b5b2-8b3fe4bbc243.mp4

**Comment by lobontiumira** [comment] 2021-12-08 10:18
I was not able to reproduce this issue on the 12/8 Focus Nightly anymore, nor on Beta 96.0.0-beta.1, with Google Pixel (Android 10).

I'll close this issue.

**Comment by lobontiumira** [comment] 2021-12-16 13:12
Reproducible on RC 95.2.0 with Lenovo tablet M10 (Android 10):

![5623](https://user-images.githubusercontent.com/40694158/146378146-b50564f8-e85b-4715-ae19-3bdc28e68fa9.jpg)

**Comment by ionutbedregeanu** [comment] 2022-01-10 10:40
@lobontiumira @delia-pop Did you also reproduced this issue in other apps?

**Comment by lobontiumira** [comment] 2022-01-11 07:30
I was not able to reproduce the issue on the latest RC 96.1.1 with Lenovo Tab M10 (Android 10). 
I'll keep testing for a few more days.

**Comment by lobontiumira** [comment] 2022-01-17 08:37
I did not reproduce this issue in a while now.
I'll close this ticket.

**Closed by lobontiumira** 2022-01-17 08:37 UTC
Labels: bug, light-theme
