### ISSUE TITLE
[Bug] Error 0/0 displayed when tapping fast on "Find in page" toolbar's arrows

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5181] opened 2021-08-19 12:07 UTC
## Steps to reproduce
1. Open a page with a lot of text.
2. From the three-dot menu, select the "Find in page" option.
3. Enter some characters, tap the up/down arrows from the "Find in page" search field fast.

### Expected behavior
The match order/number of matches is updated.

### Actual behavior
0/0 is displayed.

### Device information
* Android device: Lenovo Tab M10 (Android 10)
* Focus version: 91.2.2
* This is [#9713](https://github.com/mozilla-mobile/fenix/issues/9713) from Fenix repo

https://user-images.githubusercontent.com/40694158/130065703-b0caa40f-99e9-409a-b904-5775bfdf323b.mp4

**Comment by jonalmeida** [comment] 2021-08-19 15:32
Seems to be timing related: if you tap the next button fast enough and the next find result requires the page to scroll down, we get a 0/0 result initially until you hit the next button again.

**Comment by pocmo** [comment] 2021-08-19 15:51
I think this is a known issue with the underlying API:
https://github.com/mozilla-mobile/android-components/issues/4704

**Comment by lobontiumira** [comment] 2021-09-10 12:59
Reproducible also on 93.0.2 (build 352522329 - GV 93.0a1-20210906031657) with Lenovo Tab M10 (Android 10).

**Comment by delia-pop** [comment] 2021-09-13 06:33
Reproducible also on 93.0.2 (build 352522329 - GV 93.0a1-20210906031657) with Huawei P9 Lite (Android 8).

**Comment by lobontiumira** [comment] 2021-09-29 11:42
Reproducible on RC 93.1.0 with Lenovo Tab M10 (Android 10).

**Comment by lobontiumira** [comment] 2022-04-05 07:09
Reproducible on Beta 100.0.0-beta.1 with Lenovo Tab M10 (Android 10).

**Comment by lobontiumira** [comment] 2022-05-03 14:16
Reproducible on Beta 101.0.0-beta.1 with Oppo Reno 6 (Android 12).

**Comment by lobontiumira** [comment] 2022-05-31 07:04
Reproducible on Beta 102.0.0-beta.1 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment] 2022-06-28 07:55
Reproducible on Beta 103.0.0-beta.1 with Lenovo tablet M10 (Android 10).

**Comment by lobontiumira** [comment] 2022-07-26 08:14
Reproducible on Beta 104.0b1 with Lenovo tablet M10 (Android 10).

**Comment by ionutbedregeanu** [comment] 2022-08-09 15:30
I will close this ticket in favor of https://bugzilla.mozilla.org/show_bug.cgi?id=1587856

**Closed by ionutbedregeanu** 2022-08-09 15:30 UTC
Labels: bug, Geckoview🦎, FindInPageBar
