### ISSUE TITLE
Focus hangs on "about:blank" for a while before loading the site

### ISSUE THREAD

**Issue by cosmic-echo** [mozilla-mobile/focus-android#4191] opened 2019-01-25 23:36 UTC
## Steps to reproduce
1. Open a site. hehe

### Expected behavior
About:blank page not hanging so much. Loading the site could have the responsiveness of the previous version (7.0).

### Actual behavior
About:blank hangs before the site is loaded.

### Device information
* Android device: Moto G4 Play, Android 7.1.1
* Focus version: 8.0.6

**Comment by acreskeyMoz** [comment] 2019-01-28 16:59
I noticed this behavior as well - on the Moto G5 it introduced ~3500ms of delay when loading https://www.tripadvisor.com. 
This may have included url redirection time (to https://www.tripadvisor.ca).

**Comment by Diana-Rus** [comment] 2020-03-11 12:23
Hi, I can still reproduce this issue with Google Pixel 3 XL (Android 9) on build Focus 8.1.0 GV: 74.0-20200309095159 .

**Comment by Diana-Rus** [comment] 2020-03-11 14:30
This seems to be the same issue with https://github.com/mozilla-mobile/focus-android/issues/3473. I think that we can close this and follow the evolution there.

**Closed** 2020-04-06 13:32 UTC
Labels: bug
