### ISSUE TITLE
GeckoView: Links with custom schemes do not work

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/focus-android#2911] opened 2018-07-16 15:40 UTC
(Not Reddit specific, but it is a good example that is easy to show the issue)

Focus + GeckoView from *master* as of July 16.

When using the mobile Reddit site you are encouraged to install their native app. They do this with a button that links to a custom scheme to open the Reddit app. The custom URL scheme triggers the native app. This works in WebView but not in GeckoView.

Steps to reproduce:

- Visit Reddit.com
- If they bug you with the big 'View Reddit in the app' banner, just hit the red Continue button
- If you don't get the banner, tap the the little blue *Use App* button in the top bar

Expected:

- Focus asks if you want to open the link in another app, see screenshot.

Actual

- Nothing happens. No prompt, no navigation.

![screenshot_20180716-113305](https://user-images.githubusercontent.com/28052/42769097-3dbe9cd2-88ef-11e8-8c98-a2d618e8a415.png)

**Comment by bbinto** [comment] 2018-07-17 17:36
@ekager to confirm if this also happens with the latest WV version

**Comment by jashgala** [comment] 2018-07-21 19:20
I tried it out with the latest version and it was able to open the corresponding app correctly.
I was on the latest version pulled from master as of July 22nd.

**Comment by ekager** [comment] 2018-07-24 22:56
Confirmed this works in WV and not in GV. If you copy + paste the custom scheme (for example: reddit://reddit/?link_click_id=550437242878965404) into GV it does work, so we're not getting the url request for these schemes for some reason.

**Comment by ekager** [comment] 2018-08-24 17:26
See https://bugzilla.mozilla.org/show_bug.cgi?id=1478171 it doesn't look like it's been being uplifted to 62 is that correct @cpeterso ?

**Comment by colintheshots** [comment] 2018-08-30 16:07
Technically, this page is not using a "custom scheme." The scheme is HTTPS. The issue is that https://reddit.app.link should be handled by an IntentFilter of the Reddit app. Since HTTPS is a supported scheme, the logic falls through to shouldOverrideUrlLoading in the super class for WebViewClient, which is this:

https://developer.android.com/reference/android/webkit/WebViewClient.html#shouldOverrideUrlLoading(android.webkit.WebView,%20android.webkit.WebResourceRequest)

**Comment by colintheshots** [comment] 2018-08-30 18:30
Oh, I see. The GV team is working on cases where we should handle redirects to the app similarly to WV. We wouldn't want Reddit to intercept all links they handle or it wouldn't be possible to browse the site outside of the app.

**Comment by cpeterso** [comment] 2018-08-30 18:46
> See https://bugzilla.mozilla.org/show_bug.cgi?id=1478171 it doesn't look like it's been being uplifted to 62. is that correct @cpeterso ?

Dylan is uplifting bug 1478171 to GECKOVIEW_62_RELBRANCH for the Focus+GV beta.

**Comment by ekager** [comment] 2018-09-04 20:27
Hey @st3fan are you able to access Reddit from Focus Nightly now? It appears to be working for me

**Comment by ekager** [comment] 2018-09-06 20:41
Closing because I can get the Reddit app to launch from Focus now

**Closed by ekager** 2018-09-06 20:41 UTC
Labels: Klar+Geckoview, automation-TBD, blocked, bug, size S, testing
