### ISSUE TITLE
Please add multiple tab support

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/focus-android#751] opened 2017-06-12 05:57 UTC
Hi,

All Android browsers I use have multiple tabs. Please add the ability to have this in Firefox Focus also.
Having only one page opened at a time makes Firefox Focus hard to use as a main browser.

Thank you

**Comment by pocmo** [comment] 2017-06-12 08:43
I understand where you are coming from. Focus is a "fire & forget" kind of browser - Browse a page, erase and everything is gone. Tabs add a complex layer on top of that. As soon as you start switching between multiple tabs and keeping them open, you want some kind of persistence and not lose tabs. This somehow works against the basic idea behind Focus.

However I've experienced a same desire while reading articles: Sometimes there are interesting links and I would like to visit them after finishing reading the current page. In other browsers I'd open them as a tab in the background. I can't do this in Focus. So I need to finishing reading the page and then somehow go back to the links and follow them.

I think tabs are not the way to go for Focus (but that's not my decision). Instead I would like to see whether we could find a nice way to make following multiple links easier.

**Comment by andreicristianpetcu** [comment] 2017-06-12 16:23
I use Focus since it is faster than Firefox and it is built by a community I trust unlike other WebKit browsers.

**Comment by Jiack214** [comment] 2017-07-10 11:59
In my opinion you could add an option to pin a link in notification on long pressing a link.
I try to explain it better: in addition to "Share link" and "Copy link address" you could add an option to create a notification that if pressed opens the pinned link.
So in this way after reading the current page you can easily read the interesting links found on the page.

**Comment by andreicristianpetcu** [comment] 2017-07-10 12:11
And if you want to visit two unrelated sites and jump between them? If I want to open Wikipedia and Gihtub, how can I do this with the notification system instead of tabs?

**Comment by Jiack214** [comment] 2017-07-10 12:46
Ah, you're right. In this cases I think there's no other solution better than tabs.
Maybe it can be done using two instances of Focus, but I don't know if it's possible and anyway it's probably uncomfortable.

**Comment by sarimak** [comment] 2017-07-12 07:02
I like the idea of putting the links into a list visible from the notification - and loading any item from the list by tapping on the item in the notificaiton (current page can be added to the list => can resume reading it later). When manually typing into the URL bar, I can always return to the original page by hitting the back button (or the "enter URL" screen could contain a checkbox "add the original page to the remembed page list" and the checkbox would remember its checked state across starts of Focus). Yes, the pages need to be reloaded with every "context switch", however local caching could fix it.

**Comment by andreicristianpetcu** [comment] 2017-07-12 08:32
But why no tabs? Tabs are such a simple and intuitive UI feature.

**Comment by bbinto** [comment] 2017-07-20 20:35
see #960

**Comment by pocmo** [comment] 2017-07-21 11:41
Closing this as a duplicate of #960. Thanks for all the feedback so far!

**Closed by pocmo** 2017-07-21 11:41 UTC
