### ISSUE TITLE
Light Theme: when browsing, the colour of menu and delete icons does not have enough contrast

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#5558] opened 2021-10-08 03:57 UTC
## Steps to reproduce
- Go to any website
- Observe the colour of `menu` and `delete` icons

### Expected behavior

- `menu` should be coloured the same as all other icons
- `delete` should be coloured `On-Dark` `Light Grey 05` `#fbfbfe` (identical colour as `delete` on Dark Theme). This is an exception, because the icon sits inside a bright FAB background colour.

<img width="360" alt="Android - Browser - Site@2x-1" src="https://user-images.githubusercontent.com/51007/136495822-31e23f5c-5af8-4d13-9e16-aed1494a251d.png">

### Actual behavior

- `menu` is coloured `white`
- `delete` is coloured the same as all other icons

<img width="360" src="https://user-images.githubusercontent.com/51007/136495659-a57038ab-30d1-4a53-9697-892e5173a495.png">

**Comment by delia-pop** [comment] 2021-10-14 12:42
Verified as fixed on the latest Focus Nightly 95.0 (Build #352870513) 95.0a1-20211007091917). with Huawei P9 Lite (Android 8). 
Please note that the issue is not fixed yet in Beta 94.0.0 (build 352862025 GV 94.0-20211005185813).

![Screenshot_20211014-153749](https://user-images.githubusercontent.com/89388888/137319173-ed4a36e2-dc2f-4c77-8bde-ddaaaedb9923.jpg)

**Closed** 2021-10-20 07:10 UTC
Labels: QAVerified, light-theme
