### ISSUE TITLE
IllegalArgumentException: BrowserFragment.queueDownload

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1501] opened 2017-10-19 11:00 UTC
```
java.lang.IllegalArgumentException: 
  at android.content.ContentResolver.insert (ContentResolver.java:1276)
  at android.app.DownloadManager.enqueue (DownloadManager.java:1425)
  at org.mozilla.focus.fragment.BrowserFragment.queueDownload (BrowserFragment.java:659)
  at org.mozilla.focus.fragment.BrowserFragment.onFinishDownloadDialog (BrowserFragment.java:606)
  at org.mozilla.focus.fragment.DownloadDialogFragment.sendDownloadDialogButtonClicked (DownloadDialogFragment.java:89)
  at org.mozilla.focus.fragment.DownloadDialogFragment$1.onClick (DownloadDialogFragment.java:79)
```

**Comment by theod07** [comment] 2017-10-26 16:06
Hello, I'd like to contribute and am not so familiar with the codebase. user sebastian on IRC mentioned that this might be a good issue to start with. Is there somewhere I should look to see some context for how to reproduce this exception?

**Comment by pocmo** [comment] 2017-10-26 16:18
Sorry, looking at the code I wonder if this is already "fixed". The call to `DownloadManager.enqueue` is wrapped in a try block catching `RuntimeException`.

I'll check Google Play to see if this error is still showing up.

**Comment by pocmo** [comment] 2017-10-26 16:23
There are two similar exceptions showing up:

```
java.lang.IllegalStateException: 
  at android.app.DownloadManager$Request.setDestinationInExternalPublicDir (DownloadManager.java:699)
  at org.mozilla.focus.fragment.BrowserFragment.queueDownload (BrowserFragment.java:653)
  at org.mozilla.focus.fragment.BrowserFragment.onFinishDownloadDialog (BrowserFragment.java:606)
  at org.mozilla.focus.fragment.DownloadDialogFragment.sendDownloadDialogButtonClicked (DownloadDialogFragment.java:89)
  at org.mozilla.focus.fragment.DownloadDialogFragment$1.onClick (DownloadDialogFragment.java:79)
```

```
java.lang.IllegalArgumentException: 
  at android.content.ContentResolver.insert (ContentResolver.java:1213)
  at android.app.DownloadManager.enqueue (DownloadManager.java:1336)
  at org.mozilla.focus.fragment.BrowserFragment.queueDownload (BrowserFragment.java:659)
  at org.mozilla.focus.fragment.BrowserFragment.onFinishDownloadDialog (BrowserFragment.java:606)
  at org.mozilla.focus.fragment.DownloadDialogFragment.sendDownloadDialogButtonClicked (DownloadDialogFragment.java:89)
  at org.mozilla.focus.fragment.DownloadDialogFragment$1.onClick (DownloadDialogFragment.java:79)
```

The line numbers are a bit off (could be Proguard). And it looks like we catch those exceptions already. Weird.

**Comment by ionutbedregeanu** [comment] 2022-02-23 07:22
I will close this ticket since I didn't succeed to reproduce it

**Closed by ionutbedregeanu** 2022-02-23 07:22 UTC
Labels: bug, help wanted, P4
