### ISSUE TITLE
Web content turns black when switching back to Focus; requires restart to continue

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#4599] opened 2020-07-15 21:03 UTC
Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1653097

### Steps to reproduce
1. Go to Developer options in Android.
   - Set 'Background process limit' to 'No background process'.
2. Open Focus and navigate to any site.
3. Switch away from Focus.
4. Switch back to Focus.

### Expected behavior
 - Web content is still there and can be interacted with.

### Actual behavior
 - The screen goes black and you cannot load any new content.
 - The app has to be restarted.

Apparently this happens to some users 1-2 times a day.

### Device information

* Android device: Pixel 3
* Focus version: 8.5.1 (Build #341921932 🦎 78.0.2-20200708170202)

**Comment by sriksm19** [comment] 2020-07-20 09:18
Same here.
Device: oneplus 5T
Android v10 (Stock)
FF Focus v8.5.1 (Build #341921932 🦎 78.0.2-20200708170202)

**Comment by DasBiest** [comment] 2020-07-31 06:30
App doesn't have to be restarted, just the offending tab has to be closed.

**Comment by Myridium** [comment] 2020-08-08 23:54
This is a serious bug. How has it not been fixed for almost a month now?

It happens consistently. Every time I switch away from the app and come back, the screen is black and not even the refresh button works.

It makes this browser unusable. Guess I'll use Chrome again.

**Comment by jonalmeida** [comment] 2020-08-09 16:17
> This is a serious bug. How has it not been fixed for almost a month now?
> 
> It happens consistently. Every time I switch away from the app and come back, the screen is black and not even the refresh button works.
> 
> It makes this browser unusable. Guess I'll use Chrome again.

@Myridium could you provide more details about device?

We've had a tough time reproducing this bug to find it's cause.

**Comment by Myridium** [comment] 2020-08-09 17:52
Okay, maybe I can help then. I have a Samsung Galaxy S8+. Is there a way to capture a log file to the device? I am comfortable with bash scripting and the like, but I do not want to install Android tools on my computer.

**Comment by jonalmeida** [comment] 2020-08-10 01:24
@Myridium I think it should be fine. :)

What Android version are you running on your S8+? Android 9?

**Comment by Myridium** [comment] 2020-08-10 03:40
@jonalmeida yes, I am running Android 9.

**Comment by sriksm19** [comment] 2020-08-10 05:24
Mines oneplus 5t, android 10. Problem still remains, sometimes even after
switching back in 5 seconds

**Comment by jonalmeida** [comment] 2020-08-13 22:59
I was able to reliably reproduce this bug with the following steps below. It seems this isn't related to WebRender as I originally thought.

With the same STR, I can't reproduce the issue on Fenix with GeckoView 81.0a1-20200811091731.

### Steps to reproduce
1. Go to Developer options in Android.
   - Set 'Background process limit' to 'No background process'.
2. Open Focus and navigate to any site.
3. Switch away from Focus.
4. Switch back to Focus.

I need to also investigate _why_ this is happening only now. What changed in the GV upgrades to cause this.

My next guess is to see if changing the initial [`preload` call][0] use the application context will change the lifetime of the engine and stop the issue.

[0]: https://searchfox.org/mozilla-mobile/rev/caf6c9c63a24845399cfac0ddc6c3027974d0adc/focus-android/app/src/main/java/org/mozilla/focus/activity/MainActivity.kt#76

**Comment by Ceiphos** [comment] 2020-08-26 18:21
Same issue on a OnePlus X running Android 6.0.1
I noticed that this seems to be tab specific. When switching back to the app and then switching to a different opened tab, this tab works fine. However when switching back to the "black" tab it now is white with about:blank. Entering a new URL or something else does not work.

I just updated to 8.7.1, will see if the issue is still there.

**Comment by ebalazs-sv** [comment] 2020-09-18 07:58
Verified as fixed on Focus 8.8.0 Build ID: 342620305 GV 81.0.20200917005511 with Pixel 2 (Android 9).

**Closed by ebalazs-sv** 2020-09-18 07:58 UTC
Labels: QAReady, bug

**Comment by DrJeffD** [comment] 2022-02-21 11:42
Marked as closed, yet has persisted for me for many months (Galaxy S9).

**Comment by jonalmeida** [comment] 2022-02-22 18:28
@DrJeffD please file a new bug with updated STR so we can see if it's a regression or not. Thanks!
