### ISSUE TITLE
Share Button does nothing

### ISSUE THREAD

**Issue by hackel** [mozilla-mobile/focus-android#1340] opened 2017-09-19 22:48 UTC
Ever since Focus launched, the share button has been broken.  When opening a link from another app with Focus (so it's in custom tab mode or whatever, where you can't change the URL), pressing the share button does nothing.  When opening Focus manually and entering a URL, then it works fine (from the menu option—there is no button).

Currently running Focus 1.3 on Android 8.

Edit: Just installed 2.0 RC2 and the issue is still present.

**Comment by pocmo** [comment] 2017-09-20 08:26
I'm not able to reproduce this. Can you name one third-party app that is opening such a broken custom tab?

**Comment by Jacquester** [comment] 2017-09-20 08:35
Neither am I, tried it on android 5.1 and 8 from multiple external apps. @hackel could you possibly share the link as well ?

**Comment by bbinto** [comment] 2017-10-30 15:19
@pocmo - Should we just close this, and keep an eye out for a similar issue in the future?

**Comment by pocmo** [comment] 2017-10-30 15:23
Yeah, this is not actionable.

**Comment by hackel** [comment] 2017-11-10 21:33
Apologies for taking so long to get back to this issue.  The place where I am noticing this still happening (with Focus 2.3) is the Google News & Weather app.  It also happens with Firefox 57, which seems to have its own custom tab implementation now.

**Comment by pocmo** [comment] 2017-11-13 11:25
> Apologies for taking so long to get back to this issue. The place where I am noticing this still happening (with Focus 2.3) is the Google News & Weather app. 

I can't reproduce this with the News & Weather app on my phone. @npark-mozilla can you give it a try?

**Comment by npark-mozilla** [comment] 2017-11-13 14:08
I ran it on Pixel, Android 8, Focus beta build (2.4) and could not repro it with Google News & Weather / Firefox.  Perhaps Focus might need a clean uninstall just in case the share intent is stale?

**Comment by bbinto** [comment] 2018-04-13 17:52
Let's close this as it's not actionable.

**Closed by bbinto** 2018-04-13 17:52 UTC
Labels: P3, bug

**Comment by bbinto** [comment] 2018-04-13 17:53
If this is still happening to you, please provide "steps to reproduce"
