### ISSUE TITLE
On Fresh install, opening new tab displays on foreground, not on background

### ISSUE THREAD

**Issue by nojunpark** [mozilla-mobile/focus-android#3544] opened 2018-10-01 20:39 UTC
## Steps to reproduce
Found this while debugging UI Test failure on MultitasktingTest.java
1. Remove Focus app from the device.
2. Debug `testVisitingMultipleSites` test, with breakpoint on line 126.
3. Start the test, and when it reaches line 126, press "step to next line"

### Expected behavior
After opening tab 2 from the context menu, it should remain in tab 1.

### Actual behavior
After opening tab 2, it shows tab 2. but when tapping the tab list button, it shows that it is in tab 1 page, which is not true

### Device information

* Android device: Moto G5
* Focus version: commit 7991dc2f858346da72040d6670caf9b742928901

What's interesting is that this only happens on fresh install, but once this happens, on the next run, the test does not fail.

**Comment by ekager** [comment] 2018-10-02 10:01
I can also reproduce this on master, the first tab you open opens in the foreground.. Looking into it

**Comment by ekager** [comment] 2018-10-19 23:15
Hi @pocmo (and AC team) I did some testing of this, and it looks like even if I pass a hardcoded `selected = false`, on the first tab on the first run, it will always be selected. Is this is a bug in the `SessionManager` `add` function where the first ever session is not being selected properly?

**Comment by Sdaswani** [comment] 2018-10-26 17:30
@st3fan this likely requires an a-c fix.

**Comment by pocmo** [comment] 2018-10-26 17:42
I'll investigate.

> Hi @pocmo (and AC team) I did some testing of this, and it looks like even if I pass a hardcoded selected = false, on the first tab on the first run, it will always be selected.

Yes, this is the expected behavior. If there are sessions then there will always be one selected. In this case it's the first that is added.

This part seems fine here. There seems to be a mismatch between what is actually selected and what's displayed as selected. This may be something that can get fixed in Focus directly. I'll see what's causing this.

**Comment by pocmo** [comment] 2018-10-26 18:20
Inside `SessionManager` everything seems to be fine. The second. `Session` does not get selected. This is consistent with what the tabs tray and the toolbar shows (still on tab1.html).

**Comment by ekager** [comment] 2018-10-26 18:33
Did you do a fresh install? On a fresh install (on master) running this test I'm seeing it switch to Tab2

**Comment by pocmo** [comment] 2018-10-29 08:57
Yeah, I can reproduce it. However it doesn't seem to actually switch the tab (inside `SessionManager`). It looks like it is loading the URL inside the current WebView (in addition to opening a tab in the background!) - which is super weird. It almost looks like a WebView bug? I'll need to investigate if there's something odd happening our context menu implementation.

**Comment by vesta0** [comment] 2018-11-09 19:57
@jonalmeida are you working on this?

**Comment by jonalmeida** [comment] 2018-11-09 20:14
@vesta0 yes, I'm currently debugging the issue to find the cause. 

I've confirmed that this only happens on a fresh install (or deleting app data), but so far I haven't found what the difference is between adding a new session after a fresh install and during a regular one.

**Comment by jonalmeida** [comment] 2018-11-13 15:05
What I've gathered so far:
- Reverting 7991dc2 and it's parent still fails the test.
- I don't see any noticeable changes in the contextmenu impl in Focus, so diverted my attention to the a-c code in session manager.
- The changes made to the `add` session call also seem relatively minor (adding a parent ID) and shouldn't be affecting this issue.

I'm going to try reverting that to see if it solves the issue as well.

**Comment by jonalmeida** [comment] 2018-11-15 02:51
@csadilek and I spent _a long time_ debugging this and we concluded **this isn't a components issue**:

When Focus is first run, it's making a request somewhere in the app (we're unable to figure out where this is because **we don't see any session callbacks being invoked**). We verified this after realizing that the reason we see 'Tab 2' is because the mockWebServer has enqueued a set of requests to respond to and the second one is being called, which causes the mockWebServer to serve the second enqueued request (Tab 2). If you add an extra enqueue call before it that serves Tab 1 again, the test passes.

```diff
diff --git a/app/src/androidTest/java/org/mozilla/focus/activity/MultitaskingTest.java b/app/src/androidTest/java/org/mozilla/focus/activity/MultitaskingTest.java
index ffe419e0..ff853602 100644
--- a/app/src/androidTest/java/org/mozilla/focus/activity/MultitaskingTest.java
+++ b/app/src/androidTest/java/org/mozilla/focus/activity/MultitaskingTest.java
@@ -87,6 +87,7 @@ public class MultitaskingTest {
     public void startWebServer() throws Exception {
         webServer = new MockWebServer();

+        webServer.enqueue(createMockResponseFromAsset("tab1.html"));
         webServer.enqueue(createMockResponseFromAsset("tab1.html"));
         webServer.enqueue(createMockResponseFromAsset("tab2.html"));
         webServer.enqueue(createMockResponseFromAsset("tab3.html"));

```

What we believe might be the cause is a lifecycle issue where a new fragment or existing fragment is re-requesting Tab 1 when the context menu is completed. By adding a break point in the test after the first tab is loaded, opening `chrome://inspect` for the tab, and continuing the test; we see a second request for tab1.html there.

Another possibility: While breaking on `FocusWebViewClient#onLoadResource` we also noticed that the two requests for loading Tab 1 where hitting that code with different callstacks. 

The first directly by Espresso's `doPerform` which I believe is from `EspressoHelper#pressImeActionButton` via `navigateToMockWebServer`:

```
onLoadResource:87, FocusWebViewClient (org.mozilla.focus.webview)
onLoadResource:150, Ap (com.android.webview.chromium)
handleMessage:15, AwContentsClientCallbackHelper$MyHandler (org.chromium.android_webview)
dispatchMessage:106, Handler (android.os)
loopAndInterrogate:160, Interrogator (android.support.test.espresso.base)
loopUntil:472, UiControllerImpl (android.support.test.espresso.base)
loopMainThreadUntilIdle:381, UiControllerImpl (android.support.test.espresso.base)
doPerform:215, ViewInteraction (android.support.test.espresso)
access$100:62, ViewInteraction (android.support.test.espresso)
call:149, ViewInteraction$1 (android.support.test.espresso)
call:146, ViewInteraction$1 (android.support.test.espresso)
run:266, FutureTask (java.util.concurrent)
handleCallback:873, Handler (android.os)
dispatchMessage:99, Handler (android.os)
loop:193, Looper (android.os)
main:6669, ActivityThread (android.app)
invoke:-1, Method (java.lang.reflect)
run:493, RuntimeInit$MethodAndArgsCaller (com.android.internal.os)
main:858, ZygoteInit (com.android.internal.os)
```

The second from a rogue Espresso `sendSingleTap`:

```
onLoadResource:87, FocusWebViewClient (org.mozilla.focus.webview)
onLoadResource:150, Ap (com.android.webview.chromium)
handleMessage:15, AwContentsClientCallbackHelper$MyHandler (org.chromium.android_webview)
dispatchMessage:106, Handler (android.os)
loopAndInterrogate:160, Interrogator (android.support.test.espresso.base)
loopUntil:472, UiControllerImpl (android.support.test.espresso.base)
loopUntil:419, UiControllerImpl (android.support.test.espresso.base)
injectMotionEvent:240, UiControllerImpl (android.support.test.espresso.base)
sendUp:138, MotionEvents (android.support.test.espresso.action)
sendUp:119, MotionEvents (android.support.test.espresso.action)
sendSingleTap:153, Tap (android.support.test.espresso.action)
access$100:33, Tap (android.support.test.espresso.action)
sendTap:44, Tap$1 (android.support.test.espresso.action)
perform:128, GeneralClickAction (android.support.test.espresso.action)
perform:356, ViewInteraction$SingleExecutionViewAction (android.support.test.espresso)
doPerform:241, ViewInteraction (android.support.test.espresso)
access$100:62, ViewInteraction (android.support.test.espresso)
call:149, ViewInteraction$1 (android.support.test.espresso)
call:146, ViewInteraction$1 (android.support.test.espresso)
run:266, FutureTask (java.util.concurrent)
handleCallback:873, Handler (android.os)
dispatchMessage:99, Handler (android.os)
loop:193, Looper (android.os)
main:6669, ActivityThread (android.app)
invoke:-1, Method (java.lang.reflect)
run:493, RuntimeInit$MethodAndArgsCaller (com.android.internal.os)
main:858, ZygoteInit (com.android.internal.os)
```

The latter issue might be a more likely probable cause.

Unrelated to this, we also noticed a minor error in the test:
```diff
diff --git a/app/src/androidTest/assets/tab3.html b/app/src/androidTest/assets/tab3.html
index d8a08c58..56f0909c 100644
--- a/app/src/androidTest/assets/tab3.html
+++ b/app/src/androidTest/assets/tab3.html
@@ -7,9 +7,9 @@

     <h1 id="content">Tab 3</h1>

-    <a href="tab2.html" id="tab1">Tab 1</a>
+    <a href="tab1.html" id="tab1">Tab 1</a>

-    <a href="tab3.html" id="tab2">Tab 2</a>
+    <a href="tab2.html" id="tab2">Tab 2</a>

 </body>
 </html>
```

Side note: using `browser-engine` would avoid these regressions. :wink:

**Closed** 2022-04-23 12:11 UTC
Labels: bug, needs investigation, P2, size S, wontfix
