### ISSUE TITLE
Firefox Focus drawing under android status bar

### ISSUE THREAD

**Issue by KazaHesto** [mozilla-mobile/focus-android#2275] opened 2018-03-10 08:40 UTC
Device: Essential PH-1
Android version: 7.1.1
Firefox Focus version: 4.1 (Build 11)

**Steps to reproduce:**
1. Open any other app
2. Long-press recent apps button to enter multi-window
3. Open Firefox Focus in the lower part of the screen
4. Drag window separator up to have Firefox Focus take the whole screen

**Actual results:**
Firefox Focus draws into the status bar

**Expected results:**
A margin is kept so content is below the status bar

**Screenshot**
![screenshot_20180310-193548](https://user-images.githubusercontent.com/19279387/37240094-5e82867c-249a-11e8-9c6b-1a62c23c4b24.png)

Maybe this is related to  #2047?

**Comment by fercarcedo** [comment] 2018-03-10 13:04
It's a problem with the cache implementation of my last pull request. The problem is now fixed. I'm going to send a pull request with the solution

**Comment by pocmo** [comment] 2018-03-12 09:19
Thank you for taking care of this, @fercarcedo!

**Comment by vivekkrish** [comment] 2018-03-13 17:05
Hi Everyone,

Not sure if this might be related, but running Focus (4.1 Build #11) in multi-window mode (Random app ABOVE, Focus BELOW), we see a static bar equivalent to the height of default status bar.

Please see screenshot below:
![image](https://user-images.githubusercontent.com/711637/37357558-248686ea-26bf-11e8-8c31-aeaf3f4e7284.png)

Would this have been addressed by either of the 2 commits above?

Thank you!

**Comment by fercarcedo** [comment] 2018-03-13 17:13
Yes, this is addressed by the commit I submitted

**Closed** 2018-03-16 12:14 UTC
Labels: P1, bug
