### ISSUE TITLE
Clicking Language setting crashes app

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#3796] opened 2018-10-29 19:01 UTC
## Steps to reproduce
- Go to settings, general, language
### Expected behavior
- Language list opens
### Actual behavior
- App crashes with:
```
java.lang.IllegalAccessError: Interface org.mozilla.focus.widget.LocaleListPreference$EntriesListener implemented by class org.mozilla.focus.settings.GeneralSettingsFragment$onDisplayPreferenceDialog$1 is inaccessible (declaration of 'org.mozilla.focus.settings.GeneralSettingsFragment$onDisplayPreferenceDialog$1' appears in /data/app/org.mozilla.focus.debug-3pfxifo0fslM9ZmBp81Q-w==/base.apk!classes2.dex)
at org.mozilla.focus.settings.SettingsFragment.onPreferenceTreeClick(SettingsFragment.kt:44)
at android.support.v7.preference.Preference.performClick(Preference.java:1173)
at android.support.v7.preference.Preference.performClick(Preference.java:1148)
at android.support.v7.preference.Preference$1.onClick(Preference.java:172)
at android.view.View.performClick(View.java:6297)
at android.view.View$PerformClick.run(View.java:24797)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6626)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

### Device information

* Android device: Moto G5
* Focus version: latest master (176316cf39931a0f8c50ad9e56000fe1908155e2)

**Comment by colintheshots** [comment] 2018-10-29 19:02
Dupe of #3789. Closing.

**Closed by colintheshots** 2018-10-29 19:02 UTC
