### ISSUE TITLE
Add Reader View

### ISSUE THREAD

**Issue by thybooklust** [mozilla-mobile/focus-android#2095] opened 2018-02-10 11:30 UTC
add [reader view](https://support.mozilla.org/en-US/kb/firefox-reader-view-clutter-free-web-pages)

**Comment by Sdaswani** [comment] 2018-02-11 06:12
Dupe of https://github.com/mozilla-mobile/focus-android/issues/802

**Closed by Sdaswani** 2018-02-11 06:12 UTC
