### ISSUE TITLE
[crash]  java.lang.IllegalStateException: Invalid png detected

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5197] opened 2021-08-24 05:26 UTC
## Steps to reproduce
1. Build a debug build, and install it on your device.
2. Go to three-dot menu -Settings - Mozilla - About Firefox Focus.

### Expected behavior
The user can see the About Firefox Focus page.

### Actual behavior
```
2021-08-24 08:18:16.053 14148-14148/org.mozilla.focus.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.focus.debug, PID: 14148
    java.lang.IllegalStateException: Invalid png detected
        at org.mozilla.focus.utils.HtmlLoader.loadPngAsDataURI(HtmlLoader.java:82)
        at org.mozilla.focus.browser.LocalizedContent.loadAbout(LocalizedContent.kt:49)
        at org.mozilla.focus.engine.AppContentInterceptor.onLoadRequest(AppContentInterceptor.kt:30)
        at mozilla.components.browser.engine.gecko.GeckoEngineSession$createNavigationDelegate$1.maybeInterceptRequest(GeckoEngineSession.kt:570)
        at mozilla.components.browser.engine.gecko.GeckoEngineSession$createNavigationDelegate$1.onLoadRequest(GeckoEngineSession.kt:492)
        at org.mozilla.geckoview.GeckoSession.lambda$shouldLoadUri$4$GeckoSession(GeckoSession.java:1760)
        at org.mozilla.geckoview.GeckoSession$$ExternalSyntheticLambda2.run(Unknown Source:8)
        at org.mozilla.gecko.util.ThreadUtils.runOnUiThread(ThreadUtils.java:53)
        at org.mozilla.geckoview.GeckoSession.shouldLoadUri(GeckoSession.java:1758)
        at org.mozilla.geckoview.GeckoSession.load(GeckoSession.java:1700)
        at mozilla.components.browser.engine.gecko.GeckoEngineSession.loadUrl(GeckoEngineSession.kt:175)
        at mozilla.components.concept.engine.EngineSession.loadUrl$default(EngineSession.kt:566)
        at mozilla.components.browser.state.engine.middleware.LinkingMiddleware$performLoadOnMainThread$1.invokeSuspend(LinkingMiddleware.kt:111)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7399)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
```

### Device information
* Android device: Lenovo Tab M10 (Android 10), and Nexus 9 (Android 9) emulator
* Focus version: debug build from 8/24

**Comment by mcarare** [comment] 2021-08-24 07:11
Duplicate of https://github.com/mozilla-mobile/focus-android/issues/5197.

**Closed by mcarare** 2021-08-24 07:11 UTC
Labels: bug, crash 🔥

**Comment by maryammsd** [comment] 2022-02-23 10:38
I wanna this bug for my research. I cannot reproduce it on the release version [Focus / Klar v91.3.0](https://github.com/mozilla-mobile/focus-android/releases/tag/v91.3.0). Can you let me know which version is affected by it?

**Comment by Mugurell** [comment] 2022-02-23 18:16
@maryammsd I see #5185 was verified as fixed in 93, in August last year. The solution for this can be found in that ticket.
