### ISSUE TITLE
Video exit full screen mode when device orientation is changed

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla-mobile/focus-android#1926] opened 2017-12-06 15:56 UTC
Devices:
Nexus 5 (Android 6.0.1)
Nexus 6 (Android 7.1.1)
build: Focus 4.0 Beta Build #3691

Steps to reproduce:

Go to video sites like ted.com 
Click on full screen button
Change device orientation from portrait to landscape a couple of times.

Expected results:
The video is still in full screen mode.

Actual results:
The video exit full screen mode when the device orientation is changed. Remains full screen only in landscape mode and the button is changing as well.

See video: https://youtu.be/2GnL94-oRoA

**Comment by pocmo** [comment] 2017-12-06 16:01
This doesn't happen on all sites. So I almost wonder if that's something the site is doing on purpose.

* Vimeo never leaves fullscreen.
* YouTube only leaves fullscreen when going from landscape to portrait mode. The other way around it stays in fullscreen mode.

**Comment by liuche** [comment] 2017-12-07 19:09
Talked to @Sdaswani, not a release blocker.

**Comment by ekager** [comment] 2018-09-07 23:48
This does not happen with GV

**Comment by lobontiumira** [comment] 2021-07-01 12:00
I was not able to reproduce this issue lately, on a debug build 8.13.1 (#1191.0a1-20210608091819), and 8.16.0 with Samsung Galaxy Note 8 (Android 9), and with Google Pixel (Android 10).
I'll close this issue.

**Closed by lobontiumira** 2021-07-01 12:00 UTC
