### ISSUE TITLE
GeckoView in custom tab can be accessed through regular app after deleting data

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#3596] opened 2018-10-09 20:18 UTC
## Steps to reproduce
- With no session open in focus
- Open app with custom tabs (e.g. gmail)
- Click link to open custom tab
- Go home, open focus
- Go to a website (e.g. apple.com)
- Delete data

### Expected behavior
Goes to home screen, custom tab remains in separate task

### Actual behavior
Goes to custom tab screen in Focus task. Custom tab screen can also be accessed in original task in app switcher

### Device information
* Android device: Pixel 2, Android P
* Focus version: 8.0 #322801206, 62.0.3.20181001191808

fwiw, while trying to reproduce this, I noticed a lot of non-deterministic behavior in opening GeckoView tabs and interacting with a separate GeckoView task so I think we may have race conditions in these code paths. This was especially funky when using the app switcher.

**Comment by lobontiumira** [comment] 2022-02-22 14:05
I was not able to reproduce the issue on the latest Focus Nightly build 99.0 from 2/22, using an Oppo Find X3 Lite (Android 11).
I'll close this ticket.

**Closed by lobontiumira** 2022-02-22 14:05 UTC
Labels: P3
