### ISSUE TITLE
Logo Check

### ISSUE THREAD

**Issue by umertanvir** [mozilla-mobile/focus-android#1369] opened 2017-09-22 12:08 UTC
Firefox Focus has different logo at two different places 
1 the main logo is updated with new logo  great
2 the open with menu still showing old logo of focus please fix it

**Comment by pocmo** [comment] 2017-09-22 12:26
You might have an old build of Focus installed. We hide Focus from "Open with" if it is the same build.

**Comment by umertanvir** [comment] 2017-09-22 13:46
![21685944_2053286138241112_1808177196930991239_n](https://user-images.githubusercontent.com/13235124/30747306-4a302638-9fc6-11e7-9181-bafbea890e3b.jpg)
![21687091_2053286181574441_3063265791644638774_o](https://user-images.githubusercontent.com/13235124/30747305-49839e5e-9fc6-11e7-9221-bfc2b6240e8c.jpg)

**Comment by umertanvir** [comment] 2017-09-22 13:47
Here is screenshot to support the issue.

**Comment by umertanvir** [comment] 2017-09-22 13:51
![pla](https://user-images.githubusercontent.com/13235124/30747498-ea8b1ee4-9fc6-11e7-8c4e-a86d82b002d2.png)
Look @pocmo  I am using the latest version.

**Comment by umertanvir** [comment] 2017-09-22 14:05
@pocmo  I am using version 1.3
 @![pla](https://user-images.githubusercontent.com/13235124/30748178-e746c178-9fc8-11e7-8bd3-2cbdc4993253.png)

**Comment by umertanvir** [comment] 2017-10-09 06:57
@bbinto  still not resolved

**Comment by mcomella** [comment] 2017-10-19 18:39
@umertanvir I hate to ask this, but would it be possible for you to uninstall and reinstall Focus to see if you can still reproduce? I think Android, or the app launching other apps, could be caching the old application icon.

Don't forget to reset any preferences you might have changed when you reinstall!

**Comment by grubdragon** [comment] 2018-01-09 05:19
Can I look into this?

**Comment by mcomella** [comment] 2018-01-09 21:01
@grubdragon We're unable to reproduce this and there hasn't been any additional reproduction information so I'm actually going to close the issue. Thanks for checking in though! Sorry that so many issues have been no goes – let me know if you need help finding more issues!

**Closed by mcomella** 2018-01-09 21:01 UTC
Labels: P5, bug, needs investigation
