### ISSUE TITLE
Going to some about: URIs crash Focus

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/focus-android#4062] opened 2018-12-21 15:53 UTC
## Steps to reproduce
Go to any of
* about:about
* about:buildconfig
* about:checkerboard
* about:config
* about:crashes
* about:license
* about:telemetry

### Expected behavior
error page or the about: page is loaded

### Actual behavior
Crash
### Device information

* Android device: Pixel 3
* Focus version: 8.0.4 (Build #323541226 🦎 64.0.20181214004633)

**Comment by npark-mozilla** [comment] 2018-12-28 19:37
stacktrace:
```
12-28 14:35:29.471  5958  5958 E AndroidRuntime: FATAL EXCEPTION: main
12-28 14:35:29.471  5958  5958 E AndroidRuntime: Process: org.mozilla.focus, PID: 5958
12-28 14:35:29.471  5958  5958 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	... 1 more
12-28 14:35:29.471  5958  5958 E AndroidRuntime: Caused by: java.net.MalformedURLException: unknown protocol: about
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at java.net.URL.<init>(URL.java:608)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at java.net.URL.<init>(URL.java:498)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at java.net.URL.<init>(URL.java:447)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at org.mozilla.focus.telemetry.TelemetryWrapper.addLoadToHistogram(TelemetryWrapper.kt:336)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at org.mozilla.focus.observer.LoadTimeObserver$addObservers$1.onLoadingStateChanged(LoadTimeObserver.kt:53)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at mozilla.components.browser.session.Session$$special$$inlined$observable$4$lambda$1.invoke(Session.kt:159)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at mozilla.components.browser.session.Session$$special$$inlined$observable$4$lambda$1.invoke(Session.kt:22)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:101)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at mozilla.components.browser.session.Session.notifyObservers(Unknown Source:7)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at mozilla.components.browser.session.Session.notifyObservers(Session.kt:297)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at mozilla.components.browser.session.Session.access$notifyObservers(Session.kt:22)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at mozilla.components.browser.session.Session$$special$$inlined$observable$4.afterChange(Delegates.kt:72)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:41)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at mozilla.components.browser.session.Session.setLoading(Unknown Source:11)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at org.mozilla.focus.session.SessionCallbackProxy.onPageFinished(SessionCallbackProxy.kt:38)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at org.mozilla.focus.web.GeckoWebViewProvider$GeckoWebView$createProgressDelegate$1.onProgressChange(GeckoWebViewProvider.kt:428)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoSession$3.handleMessage(GeckoSession.java:439)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoSession$3.handleMessage(GeckoSession.java:426)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:79)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:356)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
12-28 14:35:29.471  5958  5958 E AndroidRuntime: 	... 3 more
12-28 14:35:29.472  5958  5958 I mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.RuntimeException: java.lang.reflect.InvocationTargetException)
12-28 14:35:29.472  5958  5958 I mozac/CrashReporter: Showing prompt
```

**Comment by colintheshots** [comment] 2018-12-29 01:47
Based on that stacktrace, this is a duplicate of #4044. The fix is in master.

**Closed by colintheshots** 2018-12-29 01:47 UTC
Labels: Geckoview🦎, P1, crash 🔥
