### ISSUE TITLE
Unexpected behaviours after a screen orientation change (reported by activity)

### ISSUE THREAD

**Issue by datalossdetector** [mozilla-mobile/focus-android#4324] opened 2019-08-06 14:28 UTC
I developed an automatic test case generation tool and it detected these problems in your app.
I would like to know if you consider them as failures and, if not, why. Thanks for your collaboration.

1) When I change the orientation of the device screen, MainActivity changes its state. Below there are different examples: the screenshots were taken before and after the screen orientation change and they are paired (before, after), (before, after) ...

-- first case --
It loses the scroll position
![2019-07-31 20-09-21_before](https://user-images.githubusercontent.com/53469180/62358868-ead0bd80-b515-11e9-816c-17f022e01b07.png)
![2019-07-31 20-09-21_after](https://user-images.githubusercontent.com/53469180/62358869-ead0bd80-b515-11e9-93e3-d81d2b2c49b9.png)

-- second case --
The text written in the first TextEdit shifts left
![2019-07-31 19-47-44_before](https://user-images.githubusercontent.com/53469180/62358872-eb695400-b515-11e9-9c64-169c56dd5e79.png)
![2019-07-31 19-47-44_after](https://user-images.githubusercontent.com/53469180/62358873-eb695400-b515-11e9-988a-74609821c722.png)

**Comment by lobontiumira** [comment] 2022-03-04 09:28
@datalossdetector thak you for your report!
Is this still an issue?

**Comment by lobontiumira** [comment] 2022-07-13 06:36
I will close this ticket because I was not able to reproduce on any device, on the latest Focus nightly build 104.0a1.
Feel free to open a new ticket if this behavior occurs again.

**Closed by lobontiumira** 2022-07-13 06:36 UTC
