### ISSUE TITLE
Domain autocomplete doesn't work for first letter

### ISSUE THREAD

**Issue by thebnich** [mozilla-mobile/focus-android#305] opened 2017-03-20 21:51 UTC
STR:
1. Open Focus and go to any page.
2. Tap the URL bar.
3. Type a single letter (e.g., "g").

After 3, I expect to see autocomplete results for that letter (e.g., "google.com"), but nothing happens.

**Comment by ahunt** [comment] 2017-03-20 23:06
From IRC:
- keyboard in use is gboard (I can't reproduce on other devices with gboard, so this probably isn't the issue)
- on the Moto X Pure Edition
- Also happens in Fennec (which is where the autocomplete code came from)

I can't reproduce on an N5 with Android 6, or N6P running Android 7.1.2. Both of those devices are also running gboard.

**Comment by pocmo** [comment] 2017-03-28 13:37
I can reproduce this with a Moto E2. I wasn't able before but after updating the system and all apps this is now happening here too.

**Comment by pocmo** [comment] 2017-04-13 14:53
Somehow I can't reproduce this on the same Moto E2 anymore. @thebnich can you try again on your device?

**Comment by ahunt** [comment] 2017-04-20 18:47
I wonder if this is somehow related to the Editor bugs on Android 6 (see e.g. the crash that bnicholson had in #458). I'll try to do some more testing on the Android 6 devices I have.

**Comment by pocmo** [comment] 2017-06-06 15:58
Tried again and can't reproduce this on my phones - @npark-mozilla Do you have access to other phones to test this?

**Comment by npark-mozilla** [comment] 2017-06-06 16:02
was able to repro this with latest master on my z3c with 6.0.1.  It does show autocompletion from 2nd letter though.

**Comment by pocmo** [comment] 2017-06-06 19:10
@npark-mozilla Can you confirm that this is fixed for you too?

**Comment by npark-mozilla** [comment] 2017-06-06 19:20
yes it's fixed now!

**Closed** 2017-06-06 19:20 UTC
Labels: bug, v1.0
