### ISSUE TITLE
"Erase and Open" string truncates in en-US and localizations

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/focus-android#1189] opened 2017-08-22 22:53 UTC
This is the string used for DeleteHistory_NotificationBar: "Erase and Open" truncates a lot.
As you can see, only "Erase" appears - truncating entirely "and open"

* Screenshot for en-US: https://github.com/npark-mozilla/npark-mozilla.github.io/blob/master/en-US/images/phoneScreenshots/DeleteHistory_NotificationBar_1503431377134.png
* And French as example: https://github.com/npark-mozilla/npark-mozilla.github.io/blob/master/fr/images/phoneScreenshots/DeleteHistory_NotificationBar_1503424559104.png

**Comment by pocmo** [comment] 2017-08-23 08:56
We discussed this in #870. This seems to only happen on small devices with older versions of Android (Unfortunately that's exactly what @npark-mozilla uses for the screenshots). Newer versions do not show the icon and have a layout that allows longer text. Back in #870 we decided to live with this issue on older devices. But I'll flag this for our next triage meeting to re-discuss.

This is how the notification looks like on a modern device:
![notification](https://user-images.githubusercontent.com/89638/29580034-e93ab226-8774-11e7-9be0-8836be1a93f4.png)

**Comment by pocmo** [comment] 2017-08-23 08:56
This new action landed in Aqua. I'll update the issue title!

**Comment by bbinto** [comment] 2017-08-28 17:27
Confirm what Android version this started to happen, then let's get some telemetry to find out how many users are effected.

**Comment by bbinto** [comment] 2017-09-06 17:30
Android 5 & 6 users are affected (~50%)

**Comment by lobontiumira** [comment] 2022-02-18 09:22
This is how the notification is displayed on a Samsung Galaxy Tab A6 (Android 5.1.1):

<img src="https://user-images.githubusercontent.com/40694158/154654157-88780057-4c1f-4486-b368-4a0043bb82f6.png" width="300" height="550" />

And this is on a Xiaomi mi4i (Android 5.0.2):

<img src="https://user-images.githubusercontent.com/40694158/154654282-1293227b-8f51-47ed-866c-5075a9627c6c.png" width="300" height="550" />

**Comment by lobontiumira** [comment] 2022-05-11 12:26
The "Erase and Open" string is still truncated on the latest Focus Nightly build 102.0a1 from 5/11 on Xiaomi mi4i (Android 5.0.2).
The white buttons is described in #6627.

![Screenshot_1](https://user-images.githubusercontent.com/40694158/167849415-23d83ee1-542e-41c0-8a84-820b7576ed73.jpg)

**Comment by iorgamgabriel** [comment] 2022-07-22 10:28
Android does not allow such long text in the notification and so the text is automatically clipped.
The only feaseable solution is to use a smaller text that would fit in the space Android allows.
@Jeff Can you help with another smaller text? Should we accept the issue since it reproduces only on Android 5.0 ?

**Comment by cpeterso** [comment] 2022-11-24 00:57
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802254

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed** 2022-11-24 08:12 UTC
Labels: UX, blocked, P5
