### ISSUE TITLE
Can't switch build to using GeckoView on some devices

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3306] opened 2018-09-04 15:16 UTC
## Steps to reproduce
1. Install the Focus Beta build.
2. Go to focus:test and turn the switch on.
3. Check in focus:about that the build ID is reflecting the switch. Also, the Report site issue is an indicator that the switch is working.

### Expected behavior
The build ID should reflect the change.

### Actual behavior
On Pixel (Android 9) and LG Nexus 5 (Android 6.0.1) I wasn't able to get the GV build.
"Report site issue" didn't appear in the app menu either.

### Device information
* Focus version: 7.0 Beta 2

**Comment by sblatz** [comment] 2018-09-04 15:56
Might be related to #3305

**Comment by colintheshots** [comment] 2018-09-04 19:59
I haven't been able to reproduce from a release beta build from the latest master. I'll see if I can download an older APK and reproduce the issue.

**Comment by colintheshots** [comment] 2018-09-04 20:02
I have a theory that this is related to the ABI used and that the affected devices are all ARM64 attempting to use an ARM64 build.

**Comment by ekager** [comment] 2018-09-04 20:50
This happens to me sometimes with my Pixel which is Aarch and I believe it is related to #3305, but I closed it as a dupe. Should I reopen if its a different issue?

**Comment by colintheshots** [comment] 2018-09-06 19:29
I don't believe the "fix" is a fix. I accepted it because the logic is clearer and easier to read, but it does the same thing in terms of boolean logic.

**Comment by colintheshots** [comment] 2018-09-06 19:53
The real issue is a race condition. If the user changes the switch and browses away too quickly, the sharedpreferences.edit()...apply() hasn't finished yet. This was why I moved the logic from the switch to when you browse away from the settings page in the first place. I have a proposed fix PR I'll post.

**Comment by colintheshots** [comment] 2018-09-06 19:54
Note that the best fix is probably to update Fretboard to add a setOverrideNow() function which uses sharedpreferences.edit()...commit() instead of apply().

**Closed** 2018-09-08 06:56 UTC
Labels: bug, review, size M
