### ISSUE TITLE
Page zoom problem on some pages. Horizontal scrolling

### ISSUE THREAD

**Issue by smartfonreddit** [mozilla-mobile/focus-android#837] opened 2017-06-30 05:16 UTC
Example page :
https://bugzilla.mozilla.org/show_bug.cgi?id=1311790

The page scrolls horizontally and then text isn't optimized for mobile. No problem on Furfix.

**Comment by smartfonreddit** [comment] 2017-06-30 05:19
(sorry I hit enter without a description on mobile)

Example page :
https://bugzilla.mozilla.org/show_bug.cgi?id=1311790

The page scrolls horizontally and then text isn't optimized for mobile. No problem on Furfix.

**Comment by lobontiumira** [comment] 2021-09-22 08:35
I am not able to reproduce this issue on the latest RC 92.1.1 build, nor on the latest 93.0 debug build from main from 9/22, using a Samsung Galaxy Note 8 (Android 9).
Closing this issue.
@smartfonreddit feel free to open a new issue, if you encounter this behavior again.

**Closed by lobontiumira** 2021-09-22 08:35 UTC
Labels: bug, P5
