### ISSUE TITLE
Video chat can not be initialized at omegle.com

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/focus-android#6801] opened 2022-03-31 07:21 UTC
## Steps to reproduce
1. Navigate to: https://www.omegle.com/.
2. Tap on the "Video" button.
3. Check the boxes.
4. Tap on the "Confirm and Continue" button.
5. Observe the result.

### Expected behavior
A pop-up modal requesting permission is displayed.

### Actual behavior
A message regarding the usage of the camera not being allowed is displayed in the page footer.

### Device information

* Android device: Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)
                           Google Pixel 3 (Android 12) -1080 x 2160 pixels, 18:9 ratio (~443 ppi density)
* Focus version: Firefox Focus Nightly 100.0a1 (360891709-🦎100.0a1-20220330093158🦎)

**Notes:**

1. Reproducible regardless of the status of ETP.
2. Not reproducible using the latest build of Firefox Nightly in Normal Browsing Mode and in Private Browsing Mode.
3. Reproducible on both Release and Nightly Version of Firefox Focus.
4. Screenshot attached:

Focus Nightly:
![Screenshot_1](https://user-images.githubusercontent.com/75027050/160999935-38afcd4f-7654-45ea-9eb8-8431a9b38b03.png)

Fenix Nightly:

![Screenshot_2](https://user-images.githubusercontent.com/75027050/160999947-1bf62192-3658-4982-b525-4ee7116b91c0.png)
![Screenshot_3](https://user-images.githubusercontent.com/75027050/160999945-fc4aee9b-75a8-4cd0-bba1-bde5ebec39c9.png)

**Comment by ionutbedregeanu** [comment] 2022-03-31 10:39
It will be addressed by https://github.com/mozilla-mobile/focus-android/issues/6504

**Comment by iorgamgabriel** [comment] 2022-06-14 13:20
https://user-images.githubusercontent.com/8118371/173587085-3c8abd5f-433d-4f86-812f-50742f35bb39.mp4

**Comment by lobontiumira** [comment] 2022-06-16 12:38
I was not able to reproduce either.
Tested on the latest Focus Nightly 103.0a1 build from 6/16 with Google Pixel (Android 10), and Lenovo Tab M10 (Android 10).
@softvision-raul-bucata could you please test on your devices, as well?
Thank you!

**Comment by softvision-raul-bucata** [comment] 2022-06-16 13:18
I was not able to reproduce the issue using the latest build of Firefox Focus Nightly and Release. The video chat can be initialized



**Tested with:**


Browser / Version: Firefox Focus Release 101.2.0 (361600005-🦎101.0.1-20220608170832)/ Firefox Fenix Nightly 103.0a1 (2015886699-🦎103.0a1-20220615093700🦎)
Operating System: Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)
Operating System: Google Pixel 3 (Android 12) -1080 x 2160 pixels, 18:9 ratio (~443 ppi density)

**Closed** 2022-06-16 13:20 UTC
Labels: QAVerified
