### ISSUE TITLE
Going to https://mozilla.org causes 'secure connection failed error'

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2656] opened 2018-05-24 01:15 UTC
### Steps to reproduce
- Open Focus, go to https://mozilla.org

### Expected behavior
- redirects properly to https://www.mozilla.org

### Actual behavior
- Shows "Secure Connection Failed' error

### Device information
- Pixel 2, Android simulators

I believe this is a regression, since it was found when running the automated UI tests.  When tests were first written, they were able to open mozilla website properly.

**Comment by ekager** [comment] 2018-05-24 16:56
Both @pocmo

**Comment by ekager** [comment] 2018-05-24 18:55
In Lightning Browser you encounter the same thing they just give an opportunity to ignore the certificate error and we don't.

![screenshot_20180524-115107](https://user-images.githubusercontent.com/25442310/40505503-3ffce3de-5f49-11e8-84fc-eeb923f92b92.png)

**Comment by ekager** [comment] 2018-05-24 18:59
And if you choose to proceed anyway, it then redirects to the correct site.

**Comment by april** [comment] 2018-05-24 20:18
Fairly certain that this is because mozilla.org isn't including the intermediate certificate in its certificate chain, when you connect to it.

Desktop browsers will do AIA chasing (or often already have it cached), but it can lead to this error in cases where that isn't available. Let me track someone down.

**Comment by fox2mike** [comment] 2018-05-24 20:31
Thanks for the ping, @april. We're looking into it and will keep you folks posted. This change was made about 9 days ago FWIW.

**Comment by ziegeer** [comment] 2018-05-24 20:38
Intermediate cert is in place now, thanks for catching that.  It works for me now, can someone else verify?

**Comment by ekager** [comment] 2018-05-24 20:40
Confirmed that it works! Thanks everyone :)
Closing

**Closed by ekager** 2018-05-24 20:40 UTC
Labels: bug
