### ISSUE TITLE
Notification erase does not work

### ISSUE THREAD

**Issue by eiffel-fl** [mozilla-mobile/focus-android#2096] opened 2018-02-12 17:32 UTC
Hello.

I am using Firefox Klar 4.0.2 build #18 from F-Droid on a Nexus 5 with Lineageos 14.1-20180207.

I noticed that using the notification to erase data does not work.
Indeed, if you connect to a website, push the erase button and go to the same website you will see that you are still connected.

Happily, the bottom left corner trash button works perfectly.
If I can provide you more data do not hesitate to ask me I will try give them back.

Good bye and thank you.

**Comment by mcomella** [comment] 2018-02-12 19:08
@eiffel-fl Thanks for reporting – it'd be helpful to have specific steps to take so we can reproduce. Here are some questions to use as a prompt: you mentioned, "go to the same website you will see that you are still connected." What website did you go to? What do you expect to see on the website when you delete? What do you actually see?

**Comment by eiffel-fl** [comment] 2018-02-12 20:55
Hello @mcomella 

I first notice the bug by going to outlook.com to see my mails but I try it with numerama.com to be sure that the bug is not linked to outlook.com.
So the generic step are:
1. Go to a website W
1. Connect to this website
1. Access your profile (or whatever data that need you to be connect to be seen)
1. Use the notification to clear you navigation
1. Go to W again

Expected behavior:
You should reconnect to see your profile.

Actual behavior:
You do not need to reconnect to see your profile.

**Comment by mcomella** [comment] 2018-02-13 18:36
@npark-mozilla Can you reproduce?

**Comment by npark-mozilla** [comment] 2018-02-13 19:19
Yes I can reproduce this issue on Pixel 2 device. I wonder whether it's a regression of https://github.com/mozilla-mobile/focus-android/issues/1306

**Comment by Sdaswani** [comment] 2018-02-13 20:09
Thanks @eiffel-fl  - we will triage this soon so if you can't get to it, no worries.

**Comment by grubdragon** [comment] 2018-02-13 23:51
Hey, I'll look into this one too. Do comment your approach if you fix it! :)

**Comment by GammaBurst101** [comment] 2018-02-23 04:48
Firefox Focus for android:
The bug is only present with the notification erase.
The app works fine with the trash icon erase and erasing through tapping the 'back' button.

Device: Samsung Galaxy J7 Prime (Android: 7.0)
Version: Firefox Focus - Play store version - 4.0.2 (Build #20112247)

**Comment by Sdaswani** [comment] 2018-02-23 04:49
Thanks for the verification @GammaBurst101 !

**Comment by AniketSK** [comment] 2018-03-06 07:06
Has this been resolved but not released yet? If I download from the play store, the issue exists. However, running the latest master, it does not.
I followed the steps that @eiffel-fl mentioned:
1. Logging into Outlook email with the "keep me signed in" ticked.
2. Click erase and open from the notification.
3. Go to outlook.com
Doing that, shows me the sign in option. It does not record me as previously logged in.

However, looking at the code, I can see that [the cleanup() function is called](https://github.com/mozilla-mobile/focus-android/blob/c7cbb53737e02af4fe86d38f1f8e462d601916d0/app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.java#L768) on the webview when pressing back, by the BrowserFragment, but a different mechanism seems to be used in the [MainActivity](https://github.com/mozilla-mobile/focus-android/blob/d206962eee57f0245b961cb6ce051690db376008/app/src/main/java/org/mozilla/focus/activity/MainActivity.java#L159) when it's handling an intent to erase. This is the same mechanism that is used by the [SessionNotificationService](https://github.com/mozilla-mobile/focus-android/blob/c7cbb53737e02af4fe86d38f1f8e462d601916d0/app/src/main/java/org/mozilla/focus/session/SessionNotificationService.java#L65).
The MainActivity and SessionNotificationService call `SessionManager.getInstance().removeAllSessions();` but don't seem to call cleanup on the webview.
I'm probably missing something and don't see how the two are equivalent since Sessions seem a temporary value anyway.

Here's the deal though. [performNewBrowserSessionCleanup](https://github.com/mozilla-mobile/focus-android/blob/d206962eee57f0245b961cb6ce051690db376008/app/src/main/java/org/mozilla/focus/activity/MainActivity.java#L84) in MainActivity, again clears all data when a new session is started.

So there seem to be two ways to completely erase data. The first in the cleanup() function and the second in the performNewBrowserSessionCleanup, which appears to be triggered in a roundabout way.

Should these be consolidated or am I missing something ? Could you have a look as well  @mcomella ?

**Comment by Sdaswani** [comment] 2018-03-06 15:05
@AniketSK - @mcomella is super busy on another project.

@pocmo do you have any idea if the issue was fixed on master?

**Comment by pocmo** [comment] 2018-03-06 15:39
> @pocmo do you have any idea if the issue was fixed on master?

Not intentional afaik.

> However, running the latest master, it does not.

Which flavor are you building?

I can't reproduce this locally. @npark-mozilla Can you try if you can still reproduce this?

**Comment by Sdaswani** [comment] 2018-03-06 15:43
@pocmo i just tried on my Galaxy S8 and I can reproduce too - trash button works, system notification doesn't.

**Comment by AniketSK** [comment] 2018-03-06 15:55
Play store version doesn't work, building and running from master does for
my LG G4 (marshmallow), A Nokia 6 (Nougat) and an Oreo emulator.

**Comment by npark-mozilla** [comment] 2018-03-06 16:06
@pocmo interesting, it's not reproducible anymore on current master (focusWebviewUniversalDebug) . But yes, the release version would still have this bug.

**Comment by Sdaswani** [comment] 2018-03-06 16:18
to be clear i reproduced on the play store version

**Comment by pocmo** [comment] 2018-03-09 13:19
I did run git-bisect and this issue was "fixed" by fbc2e4999e7d0f074fe546fbff3b5bd9f873dbf8 (#1875).

**Comment by pocmo** [comment] 2018-03-14 14:48
Closing this -> The problem described here is fixed. I filed a new issue (#2301) because I wonder whether we need to do more in performNewBrowserSessionCleanup()

**Closed by pocmo** 2018-03-14 14:48 UTC
Labels: P1, bug, help wanted

**Comment by eiffel-fl** [comment] 2018-03-16 17:19
it is perfect if the problem is solved !

But I agree that it would be better if we know how it was solved.
Good job to the one who solved it though.
