### ISSUE TITLE
[Bug] Open in app dialog displayed repeatedly

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#5183] opened 2021-08-19 12:36 UTC
## Steps to reproduce
1. Go to 9gag.com or reddit.com
2. On the app promo banner, tap the continue in app button.
3. On the Focus redirect dialog tap Cancel.
### Expected behavior
A dialog is shown by Focus to continue redirecting to another app. Canceling it will dismiss it and return to the webpage.
### Actual behavior
Canceling the redirect will show the dialog again once or more times. 
### Device information

* Android device: Pixel 2, Android 9
* Focus version: 91.2.2

**Comment by pocmo** [comment] 2021-08-19 14:45
On reddit.com I see two dialogs, one for `reddit.app.link` and one for `intent://reddit`. Interestingly in Fenix, in private mode, I see only one dialog for `intent://reddit`. 🤔

**Comment by pocmo** [comment] 2021-08-19 14:54
On 9gag I always only get one dialog.

**Comment by sv-ohorvath** [comment] 2021-08-19 15:21
> On 9gag I always only get one dialog.

I got an infinite number

**Comment by rvandermeulen** [comment] 2021-08-19 15:22
@sv-ohorvath Can you confirm that this is a new issue in 91.2.2 vs. 91.2.0 currently live @ 100% rollout?

**Comment by jonalmeida** [comment] 2021-08-19 15:27
@rvandermeulen this has to be in 91.2.2 which is where we enabled app links.

**Comment by rocketsroger** [comment] 2021-08-19 16:47
I'll take a look.

**Comment by rvandermeulen** [comment] 2021-08-20 03:02
This should be fixed in the 91.3.0 release.

**Comment by lobontiumira** [comment] 2021-08-20 13:39
We were not able to reproduce this on the 91.3.0 release build with Lenovo Tab M10 (Android 10), OnePlus 6T (Android 9), nor with Google Pixel 2 (Android 9).

**Closed by lobontiumira** 2021-08-20 13:39 UTC
Labels: bug, a-c
