### ISSUE TITLE
[meta][ux] iterate on the onboarding experience

### ISSUE THREAD

**Issue by jenn-chaulk** [mozilla-mobile/focus-android#1552] opened 2017-10-24 16:09 UTC
From focus-android created by [lime124](https://github.com/lime124) : mozilla-mobile/focus-android#1506  

As we saw during the work week, retention numbers are not ideal. One area we identified was to improve our onboarding experience. 

[ ] UX ticket #1507

**Comment by jenn-chaulk** [comment] 2017-10-24 16:12
Kamino cloned this issue to mozilla-mobile/focus-android

**Comment by liuche** [comment] 2017-10-25 00:37
@jenn-chaulk I remember that we talked about having labels for UX issues - can you also add the UX label to new [ux] bugs you add?

**Comment by bbinto** [comment] 2017-10-27 19:43
dupe of #1507

**Closed by bbinto** 2017-10-27 19:43 UTC
Labels: P2, UX
