### ISSUE TITLE
[A11y] Klar freezes while using TalkBack

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#2946] opened 2018-07-20 08:30 UTC
## Steps to reproduce
1. Double tap to activate the trash button - Klar freezes.
OR
1. Open a webpage.
2. Open the menu and select to share via copy to clipboard. 
The confirmation snackbar "copied to clipboard" is read after a while (5-10 seconds) - Klar freezes.

### Device information

* Android device: 
LG Nexus 5 (Android 6.0.1)
Google Pixel (Android P beta)
* Focus version: 6.3

**Comment by ekager** [comment] 2018-09-12 21:37
I cannot reproduce this off of master with a Pixel 2. Maybe this was a P Beta issue?
Closing, please reopen if still an issue.

**Closed by ekager** 2018-09-12 21:37 UTC
Labels: Klar+Geckoview, P1, size S, testing
