### ISSUE TITLE
Entering full screen video in a custom tab crashes

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#6416] opened 2022-02-12 16:16 UTC
## Steps to reproduce
1. Open a custom tab in a third party app (Youtube is the site that crashed for me).
2. Click on a video to start playing.
3. Press the full screen button.

### Expected behavior
- Don't crash.

### Actual behavior
- 💥

### Device information

* Android device: Android 12, Pixel 3
* Focus version: Nightly 98.0 (Build #360400511
99.0a1-20220208070047)

Crash log: https://sentry.prod.mozaws.net/operations/focus-android-nightly/issues/18119393/?query=is%3Aunresolved%20illegalstateexception

**Comment by lobontiumira** [comment] 2022-02-21 11:01
I was not able to reproduce the crash with Oppo Find X3 Lite (Android 11), nor with Lenovo Tab M10 (Android 10), on the latest Focus Nightly build 99.0 (360520510 with GV 99.0a1-20220220070007).
Closing the ticket as verified.

**Closed by lobontiumira** 2022-02-21 11:01 UTC
Labels: QAReady, crash 🔥
