### ISSUE TITLE
Crashes when opening link in custom tab

### ISSUE THREAD

**Issue by andreasbovens** [mozilla-mobile/focus-android#3298] opened 2018-09-03 16:58 UTC
## Steps to reproduce
1. Set Focus as default
2. Tap on a link in e.g. Slack

### Expected behavior
Linked webpage opens in a Focus-powered custom tab.

### Actual behavior
Focus crashes
At first, intermittently, but now all the time.

### Device information

* Android device: OnePlus 5
* Focus version: 7.0 (Build 322411212)

**Comment by fercarcedo** [comment] 2018-09-03 22:18
Just in case it helps: I was experiencing the same behavior on the same Focus version and build on Android Pie (I was going to open an issue for this), and I managed to get the log (shown below). However, now on Focus version 7.0 (Build 322461206) it seems to be working just fine.

`java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{org.mozilla.focus/org.mozilla.focus.activity.CustomTabActivity}: kotlin.UninitializedPropertyAccessException: lateinit property customTabId has not been initialized
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2843)
 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
 	at android.os.Handler.dispatchMessage(Handler.java:106)
 	at android.os.Looper.loop(Looper.java:193)
 	at android.app.ActivityThread.main(ActivityThread.java:6669)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property customTabId has not been initialized
 	at org.mozilla.focus.activity.CustomTabActivity.access$getCustomTabId$p(CustomTabActivity.kt:16)
 	at org.mozilla.focus.activity.CustomTabActivity$customTabSession$2.invoke(CustomTabActivity.kt:19)
 	at org.mozilla.focus.activity.CustomTabActivity$customTabSession$2.invoke(CustomTabActivity.kt:16)
 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
 	at org.mozilla.focus.activity.CustomTabActivity.getCustomTabSession(Unknown Source:7)
 	at org.mozilla.focus.activity.CustomTabActivity.<init>(CustomTabActivity.kt:46)
 	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
 	at android.support.v4.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43)
 	at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2831)
 	... 11 more`

**Comment by ekager** [comment] 2018-09-04 00:15
Hey @andreasbovens ! If you update to the newest Nightly this should be fixed. Let me know if it's not!

**Comment by andreasbovens** [comment] 2018-09-04 12:06
It seems to work indeed!

**Closed** 2018-09-04 12:06 UTC
