### ISSUE TITLE
Current version not available in F-Droid Store

### ISSUE THREAD

**Issue by Krawei** [mozilla-mobile/focus-android#1551] opened 2017-10-24 16:08 UTC
Dear team,

when I take a look in the play store the current version is 2.2, in tbe F-Droid store the current version is 2.0. What's the reason for this gap? Is there a bug in thr build process? 

Please fix this.

Kind Regards,

Krawei

**Comment by pocmo** [comment] 2017-10-24 17:42
The reason for that is #1528. Closing as a duplicate of #1528.

**Closed by pocmo** 2017-10-24 17:42 UTC
