### ISSUE TITLE
Remote debugging does not work when enabled

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#5875] opened 2021-11-15 17:50 UTC
## Steps to reproduce
- Go to Advanced settings.
- Turn on Remote Debugging

### Expected behaviour
- Focus is seen in about:debugging on desktop.

### Actual behaviour
- No changes are seen.

### Device information

* Android device: All devices
* Focus version: Focus Nightly 96/Beta 95 (and probably Release too but I haven't verified)

**Comment by jonalmeida** [comment] 2021-11-15 17:51
I don't see anything in [`AdvancedSettingsFragment.kt`](https://github.com/mozilla-mobile/focus-android/blob/d920e91cd37b027640964990c91091a2e01ba632/app/src/main/java/org/mozilla/focus/settings/AdvancedSettingsFragment.kt) that suggests we're enabling the setting.

**Comment by lobontiumira** [comment] 2021-11-16 07:43
This is a dupe of #5624

**Closed** 2021-11-16 08:29 UTC
Labels: bug
