### ISSUE TITLE
[META] "Accept cookies" pop-up issues

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/focus-android#6046] opened 2021-12-13 08:48 UTC
It was observed on many websites, that the cookie policy can not be accepted or modified.

## Steps to reproduce
1. Navigate to a webpage (e.g. https://www.theguardian.com or https://www.twitter.com).
2. Wait until the "Cookie Policy" pop-up is displayed.
3. Accept or modify the "Cookie Policy".
4. Observe the result.

### Expected behavior
The "Cookie Policy" pop-up can be closed or managed.

### Actual behavior
The "Cookie Policy" pop-up can not be closed or managed.

### Device information

* Android device:  Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)

* Focus version:  Firefox Focus 95.1.0 (353350148 -lizard95.0.20211129150630)

**Notes:**
1. Not reproducible on the latest build of Firefox Nightly.
2. Not reproducible using "Private Browsing" mode.
3. The functionality of the buttons inside the pop-up is not working.

**Comment by kelimuttu** [comment] 2021-12-13 10:21
We received similar reports on Google Play Store: 
- https://play.google.com/store/apps/details?id=org.mozilla.focus&reviewId=gp:AOqpTOEprqKKWmwYuPHLJ9t6Dusoqd_ahtY2DUffTxeoKCV0QHxSOTRnEV6TG3M-4XM8Xtd9yGE3n8KQcN8yzJk
- https://play.google.com/store/apps/details?id=org.mozilla.focus&reviewId=gp:AOqpTOEOQ1qorheCj4MdJ3Lnpb-0ajBzq8vl78kZ8dM9QNjmvyWZ3CZZiccy9QVdm4zuZ-QgHKX0rloqB3x-tzM
- https://play.google.com/store/apps/details?id=org.mozilla.focus&reviewId=gp:AOqpTOHSSFp8_ZDRBdz37NA4RFiwgTXR6nmlOpE6wjbfo-4yKKye5XhCrfwyTDagGjsILaAW533F_6oudKpi7aI

**Comment by softvision-raul-bucata** [comment] 2021-12-13 14:34
See also: mozilla-mobile/focus-android#6029 (where a similar issue is presented) and mozilla-mobile/focus-android#5998(where the original issue was first reported)

**Comment by ionutbedregeanu** [comment] 2021-12-14 12:00
I think this was fixed in [this pr](https://github.com/mozilla-mobile/focus-android/pull/5932) that's why can't be reproduced on Firefox Nightly

**Comment by amedyne** [comment] 2021-12-14 19:59
@lobontiumira Can you validate that this is not reproducible on Focus Nightly? 
@ionutbedregeanu @mcarare  If this is indeed fixed on Nightly, i think we have to uplift to 96Beta. What are the risks of uplifting to 95 Prod release? I think there has been enough reports about this to consider a 95 dot release.

@Amejia481 @pocmo FYI.

**Comment by gahujipo** [comment] 2021-12-15 07:39
I just installed v96.0.0-beta.2. the issue does not exist in that version.

**Comment by mcarare** [comment] 2021-12-15 07:56
@amedyne The [mentioned](https://github.com/mozilla-mobile/focus-android/issues/6046#issuecomment-993469800) fix is already included in 96 Beta.

**Comment by ionutbedregeanu** [comment] 2021-12-15 08:55
@delia-pop Can you please try to reproduce this bug on Focus Nightly and help us with a second validation? 
On my side I didn't succeed to reproduce it

**Comment by amedyne** [comment] 2021-12-15 20:54
> @amedyne The [mentioned](https://github.com/mozilla-mobile/focus-android/issues/6046#issuecomment-993469800) fix is already included in 96 Beta.

Thanks for the update @mcarare

**Comment by rvandermeulen** [comment] 2021-12-16 05:26
The fix was uplifted for Focus 95.2.0 also.

**Comment by ionutbedregeanu** [comment] 2022-01-05 13:23
Since all scenarios can't be reproduced anymore I will close this ticket

**Closed by ionutbedregeanu** 2022-01-05 13:23 UTC
