### ISSUE TITLE
Shortcuts saved on the device launcher screen are opened multiple times. 

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#5744] opened 2021-10-29 13:30 UTC
There are numerous reports of users tapping on the shortcuts and resulting in the respective page being open multiple times.

It is not mentioned in the reviews if users are tapping the icon multiple times (this would mean the app is slow to start ) or it happens after just one tap.

Can QA also try to reproduce this? Thank you!

**Comment by LaurentiuApahideanSV** [comment] 2021-11-01 13:11
I tested the issue and was able to reproduce it on Focus 93.1.1 using the following steps:
1. Add a webpage on the Home screen;
2. In Focus tap the Erase browsing history;
3. Close Focus;
4. Tap on the Home screen shortcut added at step 1.
I am unable to reproduce it on Focus 94.1.1.
### Device used:
- Oppo Find X3 (Android 11

https://user-images.githubusercontent.com/50983519/139676884-c244691d-6395-4758-a066-0c1e5c63d6f2.mp4

**Comment by ionutbedregeanu** [comment] 2021-11-09 13:57
I didn't succeed to reproduce it on  Focus 95
Device Pixel 3a API 30

**Comment by ionutbedregeanu** [comment] 2021-11-09 14:35
@LaurentiuApahideanSV Since you didn't succeed to reproduce it on 94 and me neither on 95 I will close this ticket

**Closed by ionutbedregeanu** 2021-11-09 14:35 UTC
Labels: bug, needs investigation
