### ISSUE TITLE
Pages do not load and all have an insecure connection

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/focus-android#4362] opened 2019-09-22 05:34 UTC
## Steps to reproduce
Type anything in the url bar
### Expected behavior
Page navigation or search
### Actual behavior
Nothing appears on screen
Insecure connection
### Device information

* Android device: Galaxy S5
* Focus version: 8.0.19 (Build #332631850 🦎 71.0a1-20190920094918)
No DNS. No VPN. Default Marshmallow.

**Comment by guimspace** [comment] 2019-09-22 10:20
Duplicate of #4360.

**Closed** 2019-09-22 16:51 UTC
