### ISSUE TITLE
The account is not disconnected when tapping the trashcan icon or swiping away the app from Recent Apps

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/focus-android#4687] opened 2021-01-06 13:33 UTC
## Steps to reproduce
1. Launch Focus;
2. Go to google.com and login;
3. Tap Trashcan button/ Swipe away the app from Recent Apps;
4. Navigate back to google.com;
### Expected behavior
You are not logged in.
### Actual behavior
You are logged in.

### Note
This is also reproducible on twitter.com;
This is also reproducible when  the "Trackers blocked" toggle is disabled;
Clearing data solves the issue.

### Device information

* Android device: Pixel 2 (Android 9)
* Focus version: Focus 8.11.3 GV 84 from 1/5; Focus 8.11.2 GV 84 from 12/24;

**Comment by st3fan** [comment] 2021-01-06 15:23
I have a mixed result here:

### STR

 - Sign in to news.ycombinator.com
 - Tap the crash can button
 - Open news.ycombinator.com again

### Expected

I am signed out of the website

### Actual

I am signed out of the website

**Comment by st3fan** [comment] 2021-01-06 15:55
The previous test was with _tap the crash can button_ - below is _swipe the app away_

### STR

 - Sign in to news.ycombinator.com
 - Swipe Focus away from recent apps
 - Open news.ycombinator.com again

### Expected

I am signed out of the website

### Actual

I am signed out of the website ✅

**Comment by st3fan** [comment] 2021-01-06 15:56
@ebalazs-sv would you mind doing a bit more testing and also to check if there is a difference between Focus and Klar?

**Comment by m-ad** [comment] 2021-01-07 08:19
Cannot reproduce this for Twitter and Firefox Klar 8.11.2. App behaves as expected, i.e. I'm logged out after login, clearing, closing and restarting.

**Comment by ebalazs-sv** [comment] 2021-01-07 09:05
I had investigated this issue and I found that this behavior is triggered by another existing issue: https://github.com/mozilla-mobile/focus-android/issues/4605.
This is also reproducible on Focus Klar 8.11.3.

So this issue to be reproduced, the **steps to reproduce** are:

1. Set Focus as default browser;
2. Launch Focus;
3. Open a Custom Tab in Gmail;
4. Tap the Recent app device button;
5. Swipe away (kill) Focus and tap on the custom tab;
6.  Swipe away (kill) the custom tab;
7. Re-launch Focus;
8. Go to google.com and login;
9. Tap Trashcan button/ Swipe away the app from Recent Apps;
10. Navigate back to google.com;

**Steps 1 to 6 i**s issue https://github.com/mozilla-mobile/focus-android/issues/4605;
**Steps 7 to 10** is the current issue.

As mentioned in the first comment, a workaround for this issue is clearing data.


![20210107_110118](https://user-images.githubusercontent.com/48799384/103872999-d237e000-50d7-11eb-8da9-5a80529d12e9.gif)

**Comment by Nils-Bernsdorf** [comment] 2021-01-15 16:56
I had a similar issue where youtube.com kept recommending me videos I watched in a previous session. As @ebalazs-sv suggested clearing all app data helpt.
I can reproduce his updated steps on Firefox Klar 8.11.3 (Galaxy A71, Android 10).

**Comment by keunes** [comment] 2021-02-06 11:11
I can replicate this on Firefox Focus 8.12.0 (Build #350192154 🦎 85.0-20210118153634) on Fairphone 3 with https://firebase.google.com

Does this mean not all cookies are trashed when hitting the trashcan? Is it linked to some intended behaviour to maintain certain cookies to improve the user experience?

**Comment by ebalazs-sv** [comment] 2021-02-18 13:20
This issue is still reproducible on Focus 8.13.0 GV 86 with Pixel 2 (Android 9).

**Comment by lobontiumira** [comment] 2021-04-21 10:22
This is reproducible on 8.15.1 build with Samsung Galaxy Note 8 (Android 9).

**Comment by lobontiumira** [comment] 2021-04-27 12:46
Reproducible with 8.15.2 Focus build with Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by gpoole** [comment] 2021-04-30 08:57
Seeing this in Focus 8.15.1 on Pixel 4a Android 11. Clearing the browsing history does not seem to remove cookies for YouTube in my case and I see recommendations based on previous videos I've watched. I also had the same problem with Firefox Klar (not sure which version) on the same phone. I've found that clearing the app's cache and force stopping it fixes it temporarily, but it eventually starts happening again.

**Comment by ebalazs-sv** [comment] 2021-05-05 12:33
This issue is reproducible on Focus 8.15.3 GV 88 with Huawei P9 Lite (Android 7).

**Comment by lobontiumira** [comment] 2021-07-13 13:06
This issue no longer reproduces on 8.17.1 Focus release with Xiaomi Mi8 Lite Android 9), nor with Google Pixel (Android 10).
I'm closing this,

**Closed by lobontiumira** 2021-07-13 13:06 UTC
Labels: bug

**Comment by gpoole** [comment] 2021-07-30 23:09
Had this problem happen again in 8.17.1 on Pixel 4a Android 11. Tapping trash icon did not clear cookies and I was getting recommendations on YouTube from previous sessions. Force stopping Firefox seemed to fix it.
