### ISSUE TITLE
Geckoview not blocking trackers but webview is

### ISSUE THREAD

**Issue by rtMis** [mozilla-mobile/focus-android#4188] opened 2019-01-25 13:18 UTC
## Steps to reproduce
1. Open focus nightly build with geckoview enabled.
2. Select block ad, analytics, other content trackers and block web fonts.
3. Search for apkmirror firefox focus using duckduckgo.
4. Observe the tracker count.
5. open focus release build using webview.
6.  Select block ad, analytics, other content trackers and block web fonts.
7. Search for apkmirror firefox focus using duckduckgo.
8. Observe tracker count.

### Expected behavior
1. Tackers blocked count should be same for both webview and geckoview build.
2. Web fonts blocked should be same on both webview and geckoview build.

### Actual behavior
1. Nightly build using geckoview is not blocking either tackers or web fonts.
2. Geckoview build shows tracker count 0 and favicons not being blocked.
3.Webview build shows tracker count  4 and favicons being blocked.

Webview
![webview](https://user-images.githubusercontent.com/45932228/51747690-35263d00-20a2-11e9-81ec-f4cb297aadd2.png)

Geckoview
![geckoview](https://user-images.githubusercontent.com/45932228/51747623-f5f7ec00-20a1-11e9-9d5c-1853cf131b14.png)

![settingwebview](https://user-images.githubusercontent.com/45932228/51748197-926ebe00-20a3-11e9-8ee9-2e6c723fe4cc.png)

### Device information
Geckoview
* Android device: 9 (Moto g5 plus Arrow os)
* Focus version: 9.0(Build#330171230 geckoview#64.0.20190111134233)

Webview
* Android device: 9 (Moto g5 plus Arrow os)
* Focus version: 8.0.6(Build#330111642)
* Webview version: Bromite webview v72.0.3626.73

**Comment by vesta0** [comment] 2019-02-26 19:11
@rtMis thanks for reporting this. Could you please let us know if you can reproduce this issue with the newest release version of Focus (8.0.8) which is using a newer version of GeckoView (65)? Thanks in advance!

**Comment by rtMis** [comment] 2019-02-28 13:31
@vesta0 thanks for replying. I would like to clarify something first.
I installed focus nightly from  [and](http://bit.ly/focus-nightly-buildsl) then to about page there is a gecko/lizard icon after the build number. When installed from the release branch there is no gecko/lizard icon after the build number.
So the absence of gecko/lizard icon should identify it is using system webview right!

**Comment by lobontiumira** [comment] 2022-01-04 13:35
I am closing this ticket, since there is no longer Webview version of Focus.

**Closed by lobontiumira** 2022-01-04 13:35 UTC
