### ISSUE TITLE
bugzilla.mozilla.org - "Block Web Fonts" breaks icons

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [mozilla-mobile/focus-android#4511] opened 2020-04-21 12:17 UTC
First reported here: https://github.com/webcompat/web-bugs/issues/51763

Browser / Version: Firefox Focus iOS 8.1.4
Operating System: iOS 13.3.1
Tested Another Browser: Yes Chrome

Problem type: Design is broken
Description: Items not fully visible
Steps to Reproduce:
I enabled Block Web Fonts, which the documentation says should improve load times without breaking functionality. However, the search icon renders as a box instead of a magnifying glass.

**Comment by abodea** [comment] 2022-03-08 14:11
Closing this as I was not able to reproduce it on the latest Focus build 9000 (11380) with iPhone 13 Pro Max (15.1.1).

**Closed by abodea** 2022-03-08 14:11 UTC
