### ISSUE TITLE
NullPointerException in HomeScreen.createShortcutIntent

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/focus-android#1611] opened 2017-10-31 00:30 UTC
Seeing a few crashes in 2.2 and 2.3.

```
java.lang.NullPointerException: 
  at android.net.Uri$StringUri.<init> (Uri.java:475)
  at android.net.Uri$StringUri.<init> (Uri.java:465)
  at android.net.Uri.parse (Uri.java:437)
  at org.mozilla.focus.shortcut.HomeScreen.createShortcutIntent (HomeScreen.java:66)
  at org.mozilla.focus.shortcut.HomeScreen.installShortCutViaManager (HomeScreen.java:57) 
  at org.mozilla.focus.shortcut.HomeScreen.installShortCut (HomeScreen.java:34)
  at org.mozilla.focus.fragment.AddToHomescreenDialogFragment$2.onClick (AddToHomescreenDialogFragment.java:95)
  at android.view.View.performClick (View.java:5217)
  at android.view.View$PerformClick.run (View.java:21349)
  at android.os.Handler.handleCallback (Handler.java:739)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:148)
  at android.app.ActivityThread.main (ActivityThread.java:5585)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:730)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:620)
```

**Comment by jonalmeida** [comment] 2017-10-31 03:09
I took at a peek at this and the tracing seems interesting.

`Uri#parse` fails because we're getting a null url, but at the same time we're getting a non-null/non-empty title from the parent call `installShortCut` (since we're not hitting `generateTitleFromUrl` which would also calls `Uri#parse`). So that would mean a user was able to hit the 'Add to Homescreen' menu button before we're able to get a url from the webview. 

I haven't had a good look at when we're enabling the menu option, but I believe the right way is to enable it when the our webview callback hits `onPageFinished` which is when we're guaranteed to have a url. Scouring the internet seems to show that it is possible otherwise to get a null url from a webview instance when it is isn't complete.

Next step would be to look what enables the `Add to Homescreen` button.

**Comment by mcomella** [comment] 2017-10-31 21:51
Thanks for the analysis, @jonalmeida! To be explicit, will be continuing to work on this issue?

**Comment by jonalmeida** [comment] 2017-10-31 21:54
@mcomella Yeah, I'll continue this evening.

**Comment by jonalmeida** [comment] 2017-11-09 00:30
Just for an update. Things came up that made me push back looking at this further.

**Comment by jonalmeida** [comment] 2017-11-10 00:21
So I followed the chain of calls from `MenuItemViewHolder#bind` which checks if the page is loading before enabling the 'Add to Homescreen' since my assumption was that, a user was able to click the menu option before the page finished loading.

In the view holder, this call is made:
```java
final boolean isLoading = browserFragment.getSession().getLoading().getValue();
```
I confirmed that the `loading` flag in Session is correctly set in the `SessionCallbackProxy#onPageFinished`. Bind is also called every time you click the menu dots, so the session is checked every time. Which means I've run out of ideas of what else this could be caused by.. 🤔 

If we just wanted to catch the nullptr, then the best place is do it is right in the the listener:
```java
screenDialogConfirmButton.setOnClickListener( new View.OnClickListener() {
    @Override
    public void onClick(View v) {
        if (url != null) { // <-- added this check here
            HomeScreen.installShortCut(getContext(), IconGenerator.generateLauncherIcon(getContext(), url), url,
                    editableTitle.getText().toString().trim(), blockingEnabled);
            TelemetryWrapper.addToHomescreenShortcutEvent();
        }
        dismiss();
}});
```

This doesn't feel like an optimal solution though..

Looking for thoughts.

**Comment by guruprasath-b** [comment] 2018-07-18 12:17
@mcomella can I work on this?

**Comment by ekager** [comment] 2018-07-18 17:12
Sure @gupta1anubhav , feel free to investigate this issue

**Comment by unicorn-io** [comment] 2019-05-05 09:26
should I try doing this?

**Comment by shmarquez** [comment] 2019-07-06 15:17
I think I'm gonna investigate this

**Comment by josharsh** [comment] 2020-02-19 18:22
If it is not being actively worked upon, can I give it a shot?

**Comment by ayushpsc** [comment] 2020-03-22 08:47
Hi,

I would like to work on this.

**Comment by ionutbedregeanu** [comment] 2022-02-23 11:19
I will close this ticket since can't be reproduced anymore

**Closed by ionutbedregeanu** 2022-02-23 11:19 UTC
Labels: bug, help wanted, P5
