### ISSUE TITLE
Unable To Access LAN Services On Non-Standard Ports

### ISSUE THREAD

**Issue by whispy** [mozilla-mobile/focus-android#4629] opened 2020-09-25 00:04 UTC
Issue: I am trying to access services on my LAN. An example URI is 192.168.0.105:5078.

Actual Behavior: I navigate to the URI and...nothing. The tab does not navigate anywhere. No error message is shown.

Expected Behavior: The tab would navigate to the requested URI. If unable to open, it should display an editor.

Notes: I tried to load `about:config` to check if the issue was non-standard ports being blocked. This resulted in an error and about:config not opening.

**Comment by whispy** [comment] 2020-09-26 13:03
I dug around some more and it appears the issue is actually from not specifying protocol in the URI. It is the same issue as https://github.com/mozilla-mobile/focus-android/issues/989.

**Comment by lobontiumira** [comment] 2022-03-18 14:19
As per the second comment, I'll close this ticket as a dupe of #989.

**Closed by lobontiumira** 2022-03-18 14:19 UTC
