### ISSUE TITLE
No padding between top sites and toolbar

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#5716] opened 2021-10-27 12:43 UTC
Pixel 4a, Android 12.

![Screenshot_20211027-123343](https://user-images.githubusercontent.com/89638/139067658-5e7438f5-a261-4c9c-b3e6-031cdd608949.png)

**Comment by lobontiumira** [comment] 2021-11-01 13:19
We were not able to reproduce this on Google Pixel 4 (Android 11), nor with Google Pixel 4a (Android 11) on Focus Nightly 95, nor on the latest debug build from main from 11/1.
I'll close this ticket.

**Closed by lobontiumira** 2021-11-01 13:19 UTC
Labels: bug, QAReady
