### ISSUE TITLE
Klar+GevkoView fails to open certain links 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#2227] opened 2018-03-05 15:00 UTC
Build: Klar+GeckoView 4.0
Devices:
Google Pixel (Android 8.0)
HTC Desire 820 (Android 6.0.1)

STR:
1. Go to https://daleharvey.github.io/testapp
2. Tap the Email and the Telephone links.
3. Go to wikipedia.com, tap the "View full list of available Wikipedia apps" link.

Expected results:
2. The links should launch the email and the phone apps.
3. A new Wikipedia page is opened.

Actual result: Nothing happens. 
Log attached. Same error in both cases (step 2 & 3): [JavaScript Error: "uncaught exception: 2147500036" {file: "resource://gre/modules/GeckoViewNavigation.jsm" line: 149}]
[email&tel links error.txt](https://github.com/mozilla-mobile/focus-android/files/1781275/email.tel.links.error.txt)

**Comment by sv-ohorvath** [comment] 2018-03-05 15:07
The same error appears in the logcat when I try to download a file from https://www.thinkbroadband.com/download. 
Error shown on the page:
![screenshot_20180305-163609](https://user-images.githubusercontent.com/4037709/36982069-8ad2100a-2097-11e8-9d99-8efa283d330a.png)

**Comment by pocmo** [comment] 2018-03-05 15:13
Download error is tracked in #2221 - Seems like we use the same download test page :)

**Comment by vladioan3** [comment] 2018-03-22 17:14
I made an investigation for this issue using latest changes from master branch and I was unable to reproduce it.

Devices:
Google Pixel (Android 8.0)
HTC Desire 820 (Android 6.0.1)
Samsung galaxy S7(7.1.2)

**Comment by pocmo** [comment] 2018-03-22 17:28
@npark-mozilla Can you confirm this for a GeckoView build?

**Comment by pocmo** [comment] 2018-03-22 17:37
Thank you. Closing this.

**Closed by pocmo** 2018-03-22 17:37 UTC
Labels: Klar+Geckoview, bug
