### ISSUE TITLE
Focus 8.0.17 GV 71 crashes at start

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/focus-android#4358] opened 2019-09-20 06:52 UTC
## Steps to reproduce
1. Install Focus 8.0.17 GV 71;
2. Launch Focus;

### Expected behavior
Focus is launched.

### Actual behavior
Focus crashes.

### Device information

* Android device: Pixel 2 (Android 9), Samsung Galaxy S8 (Android 9)
* Focus version: Focus 8.0.17 GV 71

[Crash report](https://drive.google.com/file/d/1ZnwiPljLxI4Fm6IguhD-SESKRTe4OiWF/view)

A Bugzilla bug was filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1582560

**Comment by TPS** [comment] 2019-09-20 11:56
Duplicates #4357?

**Comment by colintheshots** [comment] 2019-09-20 17:44
Yes, this is a duplicate of #4357. 8.0.18 has been pushed, but there will be an 8.0.19 for a blank white page issue as well soon.

**Closed by colintheshots** 2019-09-20 17:44 UTC
