### ISSUE TITLE
IllegalStateExceptionandroid.support.v7.preference.ListPreferenceDialogFragmentCompat in onCreate

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/focus-android#3609] opened 2018-10-09 23:49 UTC
```
IllegalStateException

ListPreference requires an entries array and an entryValues array.

    android.support.v7.preference.ListPreferenceDialogFragmentCompat in onCreate at line 53
    android.support.v4.app.Fragment in performCreate at line 2414
    android.support.v4.app.FragmentManagerImpl in moveToState at line 1418
    android.support.v4.app.FragmentManagerImpl in moveFragmentToExpectedState at line 1784
    android.support.v4.app.FragmentManagerImpl in moveToState at line 1852
    android.support.v4.app.BackStackRecord in executeOps at line 802
    android.support.v4.app.FragmentManagerImpl in executeOps at line 2625
    android.support.v4.app.FragmentManagerImpl in executeOpsTogether at line 2411
    android.support.v4.app.FragmentManagerImpl in removeRedundantOperationsAndExecute at line 2366
    android.support.v4.app.FragmentManagerImpl in execPendingActions at line 2273
    android.support.v4.app.FragmentManagerImpl$1 in run at line 733
    android.os.Handler in handleCallback at line 869
    android.os.Handler in dispatchMessage at line 101
    android.os.Looper in loop at line 206
    android.app.ActivityThread in main at line 6784
    java.lang.reflect.Method in invoke
    com.android.internal.os.Zygote$MethodAndArgsCaller in run at line 240
    com.android.internal.os.ZygoteInit in main at line 852
```

**Comment by sblatz** [comment] 2018-10-17 19:30
Some initial investigation notes:
- This crash is **only** happening on Android devices running 5.0 - 5.1.1
- It is likely an issue inside of one of these:
    - CookiesPreferences
    - LocaleListPreferences
    - GeneralSettingsFragment

as these are the files that use the ListPreference library.

**Comment by colintheshots** [comment] 2018-10-22 18:40
There are several crash entries in Sentry for this affecting all supported versions of Android. I believe they show different OS versions affected due to slight changes in the message or implementation. Almost all of the crashes only occurred in nightly. This definitely points at something new that was added recently.

**Comment by colintheshots** [comment] 2018-10-22 21:13
This crash began appearing in Sentry about two months ago. My theory is this commit caused it: https://github.com/mozilla-mobile/focus-android/commit/c8fb435474a0987c1d0eabffdfc18b8b21edd5a2

**Comment by colintheshots** [comment] 2018-10-23 15:55
Here's the merged Sentry issue: https://sentry.prod.mozaws.net/operations/focus-android/issues/4562804/

**Comment by colintheshots** [comment] 2018-10-23 20:04
I still can't find steps to reproduce. From Sentry, it appears that nearly all users experiencing the crash were in Nightly. I tried going to Settings from homescreen tips on the off-chance that caused the issue, but it didn't crash. I'm going to add a custom Sentry tag for the Locale tag and see if that helps identify the root cause.

**Comment by ekager** [comment] 2018-10-23 23:20
Did a bit more investigation and was able to produce an equivilant crash log by adding a `cancel(true)` into `getUsableLocales` in the `BuildLocaleListTask` in `LocaleListPreference`, so I am going to try to figure out why this would happen and protect us from crashing. 

> 2018-10-23 16:16:49.457 2827-2827/org.mozilla.klar.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.klar.debug, PID: 2827
    java.lang.IllegalStateException: ListPreference requires an entries array and an entryValues array.
        at android.support.v7.preference.ListPreferenceDialogFragmentCompat.onCreate(ListPreferenceDialogFragmentCompat.java:53)
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2414)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by ekager** [comment] 2018-10-23 23:28
I can also reproduce this by sleeping for a few seconds in `doInBackground` and going right to the locale list when the app starts.

**Comment by ekager** [comment] 2018-10-24 01:45
It looks like we currently don't handle the cancel case, we just return and don't set any entries/entryvalues, but for slower phones, this could be an issue. 
I'm working on converting this file to Kotlin and cleaning it up a bit.

**Comment by colintheshots** [comment] 2018-10-24 02:42
I think the quickest fix might be just initializing both arrays with empty values in onPreExecute. I had a fix prepared like this, but couldn't get it to reproduce, so held off on committing it.

**Comment by colintheshots** [comment] 2018-10-24 02:46
I'm not a fan of AsyncTask for many safety and performance-related reasons and had prepared to update to the latest coroutines with coroutineScopes and an IO and Main Dispatcher, but it required too much of an app rewrite. We can tackle the problem with the simple solution first.

**Comment by colintheshots** [comment] 2018-10-24 03:10
My easy solution won't let you lazy load items after the fact if the phone is slow. An empty list isn't much better than a crash. I think the best option is to override onPrepareDialogBuilder() to set an adapter which starts empty, but loads from the AsyncTask. I'll implement that.

Thanks so much for the STR and the assist @ekager !

**Comment by colintheshots** [comment] 2018-10-25 18:40
Initializing the array with empty values wasn't a valid fix. The list adapter would not update after the new values were set and it isn't exposed by Android. Any fix that updated available locales on-the-fly would require too much custom code and opportunities for bad edge cases to occur.

In the proposed PR, I simply set a callback and displayed a ProgressBar if the locales aren't loaded yet. This seems like the simplest solution.

**Closed** 2018-10-25 18:49 UTC
Labels: crash 🔥, review, size M
