### ISSUE TITLE
Option to diable Pull-Down-Refresh

### ISSUE THREAD

**Issue by mikevelasquez02** [mozilla-mobile/focus-android#2093] opened 2018-02-09 04:46 UTC
This is the second time I had to rewrite everything in this comment because of this!! I have been testing FFocus, and since the Pull-Down-Refresh feature was added it has become kind of anoying using the browser. I have refreshed pages many many times by mistake when scrolling and the refresh is triggered (case in point, this post). I was wondering about the possibility of adding an option in settings to disable Pull-Down-Refresh, or at least decrease the sensisbility of this feature so users have the option to react and cancel the refresh (and prevent losing text written in forms). I have seen other users comment about issues when using GMaps or playing games. I can comment here on github for example, while writing this post, if I want to scroll up in the text, I have to use DPAD arrows, otherwise the page refreshes (as the first time I was writng)

**Comment by Sdaswani** [comment] 2018-02-09 04:52
@mikevelasquez02 we have pull-down-to-refresh enabled _only_ for debug builds, and this is in fact very annoying. @ekager maybe we should just disable it for debug builds since it's something we want to do for the Geckoview builds too?

**Comment by pocmo** [comment] 2018-02-20 10:23
Closing this as duplicate of #1776.

**Closed by pocmo** 2018-02-20 10:23 UTC
