### ISSUE TITLE
Gecko: Do not scroll while moving text selection handles

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2194] opened 2018-03-01 09:40 UTC
When selecting text the current page scrolls too.

Bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1442176

I first thought that's GeckoView and filed the Bugzilla bug above - but this might be caused by our NestedGeckoView implementation.

**Comment by ekager** [comment] 2018-03-09 00:57
If we remove NestedGeckoView this doesn't happen.

**Comment by pocmo** [comment] 2018-03-09 09:42
Thank you for verifying this. :)

We recently updated NestedGeckoView to support pinch-to-zoom. I wonder if this has caused this or if this problem was there all the time.

**Comment by ekager** [comment] 2018-03-09 22:49
I just tried with the older version of NestedGeckoView and it still has the bug.

**Comment by ekager** [comment] 2018-07-04 00:02
Do we somehow disable the coordinated scrolling behavior if WebView is being selected? Would that break the scrolling of the WebView though...?

**Comment by ekager** [comment] 2018-08-17 23:12
Seems like this is a problem with the CoordinatorLayout and NestedGeckoView scrolling. Do we think we could adjust this inside GV to not send scroll events when text selection handles are present?

**Comment by cpeterso** [comment] 2018-08-24 17:53
Note that there is a chance this is a Focus bug because text selection handle dragging works correctly in Fennec browser and in GeckoView-powered Custom Tabs. Text selection handle dragging is broken in GeckoView-powered Focus browser and Focus-powered Custom Tabs.

**Comment by pocmo** [comment] 2018-08-26 09:02
> Note that there is a chance this is a Focus bug because text selection handle dragging works correctly in Fennec browser and in GeckoView-powered Custom Tabs. Text selection handle dragging is broken in GeckoView-powered Focus browser and Focus-powered Custom Tabs.

Fennec uses a different "dynamic toolbar". We are using the Android framework implementation which seems to work fine with WebView and other scrollable views. It is possible that GV reports scrolling events differently which confuses CoordinatorLayout.

**Comment by boek** [comment] 2018-09-10 22:19
So I was able to reproduce the problem with WebView: https://cloudup.com/cuLP2oRwQ3U

@ekager was able to fix it by adding

```
android:focusable="true"
android:focusableInTouchMode="true"
```

to `IWebView` in `fragment_browser.xml`, but it didn't change the behavior at all for GeckoView.
I wonder if WebView is doing anything special with how it reports touch events while in text selection mode.

Any other ideas?

**Comment by boek** [comment] 2018-09-11 18:00
This is getting fixed with GV 63 — [1442176](https://bugzilla.mozilla.org/show_bug.cgi?id=1442176)

**Comment by cpeterso** [comment] 2018-09-25 17:35
The fix was also uplifted to the GV 62 relbranch last week: https://bugzilla.mozilla.org/show_bug.cgi?id=1442176#c37

**Comment by darchons** [comment] 2018-10-01 20:37
#3543 is the fix on the Focus end to fix this issue.

**Closed** 2018-10-02 09:08 UTC
Labels: Geckoview🦎, P1, blocked, size M, testing
