### ISSUE TITLE
Wrong values populated in LastPass form

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#1872] opened 2017-12-01 13:43 UTC
- Lastpass Beta
- Firefox Focus Beta via BB
- Pixel, Android 8

STR:
1) altitude.aircanada.com
2) Added my aerolan number + password, hit enter
3) Got snackbar if I wanted to save to LastPass
4) Said yes
5) Form pre-populated in Lastpass with wrong info

Expected behaviour:
5) Form populated in Lastpass with aeroplan number and password

![screenshot_20171201-054246](https://user-images.githubusercontent.com/122897/33485235-a0d33442-d673-11e7-87a4-53161c6bc4ba.png)

**Comment by pocmo** [comment] 2017-12-01 13:56
@bbinto 

* Only the release build of Focus is whitelisted to work with Lastpass. From the URL it looks like this was with a Beta build of Focus.

* If you still see this then this needs to be filed with Lastpass. This data is exchanged between WebView <--Autofill API--> Lastpass. We are not directly involved.

**Comment by bbinto** [comment] 2017-12-05 16:55
@Sdaswani -- would you mind raising this with them. Thanks

**Comment by pocmo** [comment] 2017-12-05 16:55
I saw this too with the release version. In my case I saved the credentials from Twitter and the form in the LastPass app said facebook.com.

**Comment by Sdaswani** [comment] 2017-12-05 18:47
I have an email out to them, will chase them daily.

**Comment by lobontiumira** [comment] 2022-02-22 08:00
I was not able to reproduce this on the latest builds of Focus.
I'll close this ticket.

**Closed by lobontiumira** 2022-02-22 08:00 UTC
Labels: bug, blocked
