### ISSUE TITLE
Switching on/off URL Autocomplete features does not change the icons

### ISSUE THREAD

**Issue by facyber** [mozilla-mobile/focus-android#1830] opened 2017-11-29 11:11 UTC
Build ID: 3542 - Focus for Android
User Agent: Mozilla/5.0 (Linux; Android 6.0)

When I click on switch icons to turn on or off the new URL Autocomplete features, Focus does enables them, but the switch icons are not changed.

Steps to reproduce:
1. Open Focus > Settings > URL Autocomplete
2. Press any switch icon (Default URL List or Custom URL)

What should happens: Switch icon should change to the blue and feature would be enabled.
What actually happens: Switch icon does not change, but features are enabled.

![focus-switch-bug](https://user-images.githubusercontent.com/8742227/33372402-34199416-d4fe-11e7-8fb0-d3414a66e736.png)

**Comment by pocmo** [comment] 2017-11-29 14:01
Thank you for the report!

I can't reproduce this on a Pixel XL with Android 8.1. I'll try some other configurations.

**Comment by pocmo** [comment] 2017-11-29 14:09
I can reproduce it on an API 21 emulator. Will work on a patch.

**Comment by facyber** [comment] 2017-11-29 15:33
No problem! Soon as the new update come I will test it again to check if it works. 👍

**Comment by pocmo** [comment] 2017-11-30 13:13
@facyber This should be fixed in upcoming builds.

**Closed** 2017-11-30 13:13 UTC
Labels: bug, Jasmine, P1
