### ISSUE TITLE
IllegalAccessError: SessionManager.getSessionByUUID()

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1376] opened 2017-09-22 20:08 UTC
```
java.lang.IllegalAccessError: 
 
  at org.mozilla.focus.session.SessionManager.getSessionByUUID (SessionManager.java:136)
 
  at org.mozilla.focus.fragment.UrlInputFragment.onCreate (UrlInputFragment.java:129)
 
  at android.support.v4.app.Fragment.performCreate (Fragment.java:2329)
 
  at android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1377)
 
  at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState (FragmentManager.java:1740)
 
  at android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1809)
 
  at android.support.v4.app.FragmentManagerImpl.dispatchStateChange (FragmentManager.java:3217)
 
  at android.support.v4.app.FragmentManagerImpl.dispatchCreate (FragmentManager.java:3166)
 
  at android.support.v4.app.FragmentController.dispatchCreate (FragmentController.java:181)
 
  at android.support.v4.app.FragmentActivity.onCreate (FragmentActivity.java:312)
 
  at android.support.v7.app.AppCompatActivity.onCreate (AppCompatActivity.java:84)
 
  at org.mozilla.focus.locale.LocaleAwareAppCompatActivity.onCreate (LocaleAwareAppCompatActivity.java:38)
 
  at org.mozilla.focus.activity.MainActivity.onCreate (MainActivity.java:53)
 
  at android.app.Activity.performCreate (Activity.java:6021)
 
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1105)
 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2298)
 
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2405)
 
  at android.app.ActivityThread.access$800 (ActivityThread.java:155)
 
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1323)
 
  at android.os.Handler.dispatchMessage (Handler.java:102)
 
  at android.os.Looper.loop (Looper.java:135)
 
  at android.app.ActivityThread.main (ActivityThread.java:5376)
 
  at java.lang.reflect.Method.invoke (Native Method)
 
  at java.lang.reflect.Method.invoke (Method.java:372)
 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:908)
 
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:703)
```

**Comment by pocmo** [comment] 2017-10-06 13:08
I'm unable to reproduce this. I tried various scenarios with "Don't keep activities" and killing the app in the background.

From the stacktrace it looks like the UrlInputFragment for a session gets re-created but the session does not exist anymore.

**Comment by mcomella** [comment] 2017-10-07 00:32
I investigated but could not reproduce. My understanding is that the MainActivity is destroyed (1) but the fragments, specifically `UrlInputFragment`, remain in the application's state and is the top-most fragment (2).

`UrlInputFragment` gets a session UUID from `Fragment.getArguments` to restore its session, but the UUID isn't found in the sessionManager, so somehow that's getting cleared. afaict, `UrlInputFragment` can only be created with a session in the following ways (3):
1. `BrowserFragment.onClick` (when browsing, click on the URL bar)
1. `UrlInputFragment.applyLocale` (haven't researched yet)

**Code understanding questions:**
1. With Do Not Keep Activities, if you browsing, click the URL bar (creating UrlInputFragment with a session), hit home, erase history via the notification, and reopen the app, UrlInputFragment is called as expected but `getArguments()` returns an empty Bundle: why? Where do we ever override the bundle that this fragment is returning? If we can figure this out, maybe we can find out why the bundle is not null is some cases.
1. What are all the ways the sessions can be erased? The ones I know about:
    1. `LiveData` is black-magic to me: could something be happening there?
    1. User input: trash bin (x2: single tab and multi-tab), notification shade (x2: erase and erase & open)
    1. Could we have a situation where the service is killed so we lose a session but the Activity/Fragment state is preserved? (I haven't researched the session lifecycle yet so this may not be possible)
    1. Are there any custom tab interactions that could clear our sessions?

**Paths to investigate:**
1. Locale switching
1. Race condition with Erase & Open?
1. Restoring the MainActivity (after sessions are deleted) from another app, custom tabs, or the back stack (e.g. from another Activity in this app)
1. Can Google Play developer console given us the message with the exception so we know the UUID that's causing errors? e.g. if it's the empty string somehow

(1) `MainActivity.onCreate` is being called. But perhaps the app is initially launched from somewhere else, e.g. via Settings, and the user presses back?
(2) It's being created from the `onCreate` call stack.
(3) from `UrlInputFragment.createWithSession`

**Comment by pocmo** [comment] 2017-10-23 15:51
There are two stack traces for this error:

> java.lang.IllegalAccessError: 
>   **at org.mozilla.focus.session.SessionManager.getSessionByUUID (SessionManager.java:144)**
>   **at org.mozilla.focus.fragment.UrlInputFragment.onCreate (UrlInputFragment.java:130)**
>   at android.support.v4.app.Fragment.performCreate (Fragment.java:2329)
>   at android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1377)
>   at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState (FragmentManager.java:1740)
>   at android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1809)
>   at android.support.v4.app.FragmentManagerImpl.dispatchStateChange (FragmentManager.java:3217)
>   at android.support.v4.app.FragmentManagerImpl.dispatchCreate (FragmentManager.java:3166)
>   at android.support.v4.app.FragmentController.dispatchCreate (FragmentController.java:181)
>   at android.support.v4.app.FragmentActivity.onCreate (FragmentActivity.java:312)
>   at android.support.v7.app.AppCompatActivity.onCreate (AppCompatActivity.java:84)
>   **at org.mozilla.focus.locale.LocaleAwareAppCompatActivity.onCreate (LocaleAwareAppCompatActivity.java:38)**
>   **at org.mozilla.focus.activity.MainActivity.onCreate (MainActivity.java:53)**
>   at android.app.Activity.performCreate (Activity.java:6272)
>   at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1108)
>   at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2387)
>   at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2494)
>   at android.app.ActivityThread.access$900 (ActivityThread.java:157)
>   at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1356)
>   at android.os.Handler.dispatchMessage (Handler.java:102)
>   at android.os.Looper.loop (Looper.java:148)
>   at android.app.ActivityThread.main (ActivityThread.java:5551)
>   at java.lang.reflect.Method.invoke (Native Method)
>   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:730)
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:620)

And:

> java.lang.IllegalAccessError: 
>   **at org.mozilla.focus.session.SessionManager.getSessionByUUID (SessionManager.java:144)**
>   **at org.mozilla.focus.fragment.UrlInputFragment.onCreate (UrlInputFragment.java:130)**
>   at android.support.v4.app.Fragment.performCreate (Fragment.java:2329)
>   at android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1377)
>   at android.support.v4.app.FragmentTransition.addToFirstInLastOut (FragmentTransition.java:1109)
>   at android.support.v4.app.FragmentTransition.calculateFragments (FragmentTransition.java:996)
>   at android.support.v4.app.FragmentTransition.startTransitions (FragmentTransition.java:99)
>   at android.support.v4.app.FragmentManagerImpl.executeOpsTogether (FragmentManager.java:2364)
>   at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute (FragmentManager.java:2322)
>   at android.support.v4.app.FragmentManagerImpl.execPendingActions (FragmentManager.java:2229)
>   at android.support.v4.app.FragmentManagerImpl$1.run (FragmentManager.java:700)
>   at android.os.Handler.handleCallback (Handler.java:751)
>   at android.os.Handler.dispatchMessage (Handler.java:95)
>   at android.os.Looper.loop (Looper.java:154)
>   at android.app.ActivityThread.main (ActivityThread.java:6123)
>   at java.lang.reflect.Method.invoke (Native Method)
>   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:867)
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:757)

**Comment by ekager** [comment] 2018-10-02 13:35
We no longer use SessionManager so I'm going to say this bug no longer exists :P , closing

**Closed by ekager** 2018-10-02 13:35 UTC
Labels: P5, bug, help wanted
