### ISSUE TITLE
"Open with Firefox" should open in private browsing

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#195] opened 2017-03-08 20:06 UTC
We should probably match the iOS behaviour here? 

@bbinto ?

**Comment by pocmo** [comment] 2017-03-09 10:02
Let's talk about this (Setting triage label). I'm note even sure whether Fennec supports opening private tabs from third-party apps right now.

What's the user story behind this? Personally I'd be annoyed to switch to my actual browser and still not being able to use my cookies because I'm in private browsing now. I have to manually copy the URL and open a regular tab. But I'm not an actual user and you might have other use cases in mind.

**Comment by bbinto** [comment] 2017-03-09 14:30
Let's first figure out if it's possible, then we can decide, Sebastian. If it's not possible, we don't have to do it for v1.

I agree with you, the feature was added to the product without really talking through it with product or users. I'm not sure if it's the best solution, however for consistency, I'd be ok with reproducing the same thing on Android and waiting for feedback.

In general, it would be great to understand the use cases better why people pop out of Focus:

- To use existing cookies etc? --> No PB
- Because the site is broken in Focus due to block list? --> Either or works
- To follow-up on a site, e.g. to bookmark it --> probably No PB
...?

**Comment by pocmo** [comment] 2017-03-09 14:42
It looks like this is not supported currently:
https://dxr.mozilla.org/mozilla-central/source/mobile/android/base/java/org/mozilla/gecko/Tabs.java#914

It seems to be easy to add. However this means we need to uplift / ride the trains. And an old Firefox version would still open a normal tab.

**Comment by pocmo** [comment] 2017-03-09 14:48
Interestingly Chrome has an option to open an incognito tab but doesn't allow third-party apps to use it: http://bit.ly/2lHuQRC

**Comment by bbinto** [comment] 2017-03-10 07:13
Too bad. 

I'm ok to make this a v1+ and not v1.0 considering our dependencies with the Fennec team. 

Sebastian, would you mind filing a bug for the work that has to be done in Fennec and I'll loop in Joe and the TDC team.

Thanks.

**Comment by pocmo** [comment] 2017-03-15 15:02
Fennec Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1347583

**Comment by pocmo** [comment] 2017-03-23 11:16
See #339: It would be interesting to add this ability for other browsers too - although so far I don't know if there's any that allows opening a private/incognito tab from a third-party app.

**Comment by sultanahamer** [comment] 2017-04-02 06:06
Hi everyone I am a user of Firefox Android. I use it everyday and for me, Firefox would have been much better if it exposes functionality to open a link in private mode. I get lots of whatsapp or telegram kinda social media messages linking to some news or any website. I want to always open them in incognito. As soon as I click on a link it opens in normal mode then I have to stop loading it, copy link and open incognito mode myself and paste it.
I would also like to point that not everyone would like to open everything in private mode hence lets expose both functionalities open link in private mode and also in normal mode. Android users can select an option they like and set it  default. That should help it.
I am a developer myself not quite great in Android but if Android stops an app from exposing two similar functionalities(open link in private and open link in normal coz its going to be one type of intent from 3rd party app) from same app then may be we can just expose one that says open link in Firefox and then in Firefox we can handle that asking user whether to enter incognito or normal.

**Comment by pocmo** [comment] 2017-04-24 15:39
We just landed a patch for this in Firefox:
https://bugzilla.mozilla.org/show_bug.cgi?id=1347583

**Comment by pocmo** [comment] 2017-08-10 14:07
FYI: The patches for this are in Firefox 55 which was released this week.

**Comment by s-ankur** [comment] 2020-09-30 19:54
Hi, firefox now has an option on whether to open external links in private mode or not. And currently focus respects that. It should continue to respect that in my opinion

**Closed** 2022-04-21 18:59 UTC
Labels: feature, needs strings, P5, wontfix
