### ISSUE TITLE
build success but install failed

### ISSUE THREAD

**Issue by xm2017** [mozilla-mobile/focus-android#4233] opened 2019-03-17 13:29 UTC
## Steps to reproduce
not install to android 8.0.
### Expected behavior
install success.
### Actual behavior
I pull this project to study code.and it is build success,but it dose install failed.
and i use all variant about x86 ,all is not install.

### Device information
```
$ adb shell am start -n "org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Error while executing: am start -n "org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity }
Error type 3
Error: Activity class {org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity} does not exist.
```

Error while Launching activity* Android device: android8.0 x86
* Focus version: new version

**Comment by mauryat** [comment] 2019-03-21 00:24
Can I work on this?

Curious what's happening. When I try the repro steps, I see an UnsatisfiedLinkError pointing to not being able to find libmozglue.so

**Comment by mauryat** [comment] 2019-03-23 05:19
No longer having the issue with UnsatisfiedLinkError. I was trying it on Windows. Looks like the project is configured only for running on Unix?

**Comment by mauryat** [comment] 2019-03-23 05:58
Not able to reproduce.

@xm2017 see if you can get verbose logs using logcat.

**Comment by sijanr** [comment] 2019-03-29 06:20
@xm2017 It might be because the app doesn't have native libraries for your CPU architecture. Try this as your workaround.
In your module's build.gradle add the following lines after android {
splits {
    abi {
        enable true
        reset()
        include 'x86', 'armeabi-v7a'
        universalApk true
    }
  }

**Comment by lobontiumira** [comment] 2021-07-05 14:12
I'm closing this issue since it is no longer valid.

**Closed by lobontiumira** 2021-07-05 14:12 UTC
