### ISSUE TITLE
Splash: Update ProTips design for the Splash screen

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#4925] opened 2021-06-09 22:23 UTC
Update Pro Tips design for Splash screen: https://www.figma.com/file/2V6wgf9fRFdYfLaf5c3oPj/MVP---iOS%2FAndroid---Product-UI?node-id=804%3A11

**Comment by jonalmeida** [comment] 2021-06-16 14:59
Duplicate of https://github.com/mozilla-mobile/focus-android/issues/4949

**Closed by jonalmeida** 2021-06-16 14:59 UTC
Labels: E5
