### ISSUE TITLE
[L10N] The "Open links in apps" option is not translated 

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5727] opened 2021-10-28 12:45 UTC
## Steps to reproduce
1. Set the device's language to any language (DE, FR, zh-CN, BRPT etc.).
2. Go to Settings - Advanced.
3. Observe the "Open links in apps" option.

### Expected behavior
The "Open links in apps" option should be translated in the language of the device.

### Actual behavior
The "Open links in apps" option is not translated.

### Device information
* Android device: all
* Focus version: RC 94.1.0 ( Build 352991926 GV 94.0-20211025220926)/Beta 94.0.0-beta.2.

![Screenshot_20211028-153941](https://user-images.githubusercontent.com/89388888/139257658-c0f11a0a-2532-4728-b33c-0b9742e0eb9f.jpg)

**Comment by lobontiumira** [comment] 2021-11-03 09:28
On Beta 95.0.0-beta.1 the issue is reproducible on Romana (Romanian) language with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by Delphine** [comment] 2021-11-11 21:24
I think we're blocked on import because of an error at this time: https://github.com/mozilla-mobile/focus-android/pull/5836
Once I can fix it, and the l10n import happens, this should be fixed.
Thanks!

**Comment by Delphine** [comment] 2021-12-14 21:45
I see this as fixed now. Please confirm, thanks

**Comment by lobontiumira** [comment] 2021-12-15 07:31
We did not encounter this issue on the following languages: 
* German, English (UK), 
* French, 
* Chinese simplified, 
* Portuguese (Brazil), 
* Spanish (Argentina), 
* Spanish (Chile), 
* Spanish (Mexico), 
* Hungarian, 
* Italian, 
* Turkish, 
* Ukrainian, 
* Japanese, 
* Dutch, 
* Corsican, 
* Occitan, 
* Sundanese, 
* Swedish, 
* Vietnamese, 
* Interlingua, 
* Kabyle, 
* Norwegian Nynorsk, 
* Slovak, 
* Lower Sorbian, 
* Upper Sorbian, 
* Welsh, and 
* Chinese (Taiwan)

**Closed by lobontiumira** 2021-12-15 07:31 UTC
Labels: bug, l10n
