### ISSUE TITLE
Execution failed for task ':app:buildBlocklists'. > Process 'command 'python'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by AnkS4** [mozilla-mobile/focus-android#578] opened 2017-05-11 07:41 UTC
https://gist.github.com/AnkS4/8641b300ed525b7c671a115ab3e9fbe3

**Comment by Calfredop** [comment] 2017-05-11 10:34
Hello,
Had the same issue, you need to use Python 2.

**Comment by ahunt** [comment] 2017-05-11 17:20
Closing as duplicate of #215, I'm hopefully fixing that today by removing our python dependency for generating blocklists.

**Closed by ahunt** 2017-05-11 17:20 UTC
Labels: build

**Comment by ahunt** [comment] 2017-05-11 19:05
And #215 just landed, so you should no longer need python for the main build
