### ISSUE TITLE
Web pages language doesn’t match user preferred locale

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla-mobile/focus-android#4154] opened 2019-01-18 15:32 UTC
## Steps to reproduce

Use Android in French (or select French in the Focus language settings), then open `mozilla.org`. The issue happen with both the locale set to “Use OS preferred locale” or explicitly set to French.

### Expected behavior

Web page language matches UI locale, and `mozilla.org` redirects to `mozilla.org/fr/`

### Actual behavior

`mozilla.org` redirects to `mozilla.org/en-US/`

### Device information

* Android device: `Sony Xperia Z3C, Android 6.0.1`
* Focus version: `9.0 (Build #330171230 🦎 64.0.20190111134233)`

**Comment by Delphine** [comment] 2019-01-22 18:43
I confirm this happens to me as well on my Pixel 2 (running Android v9), on Focus version: 9.0 (Build #330221220 🦎 65.0.20190114172331)

**Comment by lobontiumira** [comment] 2021-07-05 09:40
This is still reproducible on the 8.16.0 build with Samsung Galaxy Note 8 (Android 9).

**Comment by Delphine** [comment] 2021-09-14 20:41
@TheoChevalier Is this still reproducible for you?
I get to mozilla.org/fr now from my Pixel 2 device, both when I set the language to French from the browser explicitly - and when I choose the “Use OS preferred locale”.

**Comment by TheoChevalier** [comment] 2021-09-15 12:06
Unfortunately this Android device stopped working, so I can’t tell 😬

**Comment by lobontiumira** [comment] 2021-12-29 09:46
I was able to reproduce this issue on Focus Nightly 97.0 (build 353631136 GV 97.0a1-20211228034259) with Sony Xperia Z5 Premium (Android 7.1.1), in both situations:
* setting the devce to French, and
* setting Focus to French.

On Google Pixel (Android 10), on the same Focus Nightly version from 12/29 I was able to reproduce the issue only when setting Focus to French. When I set the device to French, mozilla.org/fr was loaded.

**Comment by lobontiumira** [comment] 2022-06-28 09:11
Hi @Delphine 
I was not able to reproduce this issue anymore on the latest Focus Nightly 104.0a1 builds.
Tested with Sony Xperia Z5 Premium (Android 7.1.1), and Lenovo tablet M10 (Android 10).
I will close this ticket.
Thank you!

**Closed by lobontiumira** 2022-06-28 09:11 UTC
Labels: bug, l10n
