### ISSUE TITLE
IllegalStateException: You need to call install() on your CrashReporter instance from Application.onCreate().

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/focus-android#3929] opened 2018-11-16 21:03 UTC
@boek: @npark-mozilla provided a [Nimbledroid log file](https://github.com/mozilla-mobile/focus-android/files/2589934/klar13.txt) in issue #3918 that logs four instances of this exception. It looks like Focus is not initializing the CrashReporter component correctly:

```
E/AndroidRuntime( 8371): FATAL EXCEPTION: IntentService[CrashHandlerService]
E/AndroidRuntime( 8371): Process: org.mozilla.klar:mozilla.components.lib.crash.CrashHandler, PID: 8371
E/AndroidRuntime( 8371): java.lang.IllegalStateException: You need to call install() on your CrashReporter instance from Application.onCreate().
E/AndroidRuntime( 8371): 	at mozilla.components.lib.crash.CrashReporter$Companion.getRequireInstance$lib_crash_release(CrashReporter.kt:171)
E/AndroidRuntime( 8371): 	at mozilla.components.lib.crash.handler.CrashHandlerService$logger$2.invoke(CrashHandlerService.kt:18)
E/AndroidRuntime( 8371): 	at mozilla.components.lib.crash.handler.CrashHandlerService$logger$2.invoke(CrashHandlerService.kt:17)
E/AndroidRuntime( 8371): 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
E/AndroidRuntime( 8371): 	at mozilla.components.lib.crash.handler.CrashHandlerService.getLogger(CrashHandlerService.kt)
E/AndroidRuntime( 8371): 	at mozilla.components.lib.crash.handler.CrashHandlerService.onHandleIntent(CrashHandlerService.kt:28)
E/AndroidRuntime( 8371): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/AndroidRuntime( 8371): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 8371): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 8371): 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by boek** [comment] 2018-11-20 00:55
@cpeterso This is a strange one. I think there might be a race condition somewhere that is triggered by something trying to send a crash report while Focus is restarting due to a crash. I wonder what Nimbledroid is doing that triggers it 100%?

**Comment by npark-mozilla** [comment] 2018-11-20 03:47
@boek so I tried running the test on nexus 5 via remote testkit virtual adb.  The test doesn't fail as often as nimbledroid's, but it still does. It crashes even before the test runner has a chance to press skip button on for first run dialog, so it seems to fail immediately, way before entering URL.  I think this *may* be memory related, as I was only able to repro it well after the test started.  Nimbledroid devices are not completely reset like remote testkit devices, so they may have less memory available (that is my speculation).  So far that's the only thing I can think of.  I wonder whether we have telemetry that shows startup crash of focus + geckoview.

Oh btw, nimbledroid doesn't trigger it 100%.  a scenario may pass or fail depending on the run.  But on every run, there is at least 5-6 scenarios that fails, and they are random.

**Comment by npark-mozilla** [comment] 2018-11-28 17:59
#3918 is no longer reproducible, closing until it reappears.

**Closed by npark-mozilla** 2018-11-28 17:59 UTC
Labels: In Progress
