### ISSUE TITLE
Autocomplete entry editing is ignored

### ISSUE THREAD

**Issue by 4ut0-M-4t** [mozilla-mobile/focus-android#4445] opened 2019-12-08 19:55 UTC
***If one edits autocomplete entry in the address bar, changes are ignored***

## Steps to reproduce
1. Open Focus and start typing saved URL in the address bar (URL manually added to the  autocomplete list before). 
2. Edit the suggested autocomplete entry. 
3. Tap "Go" ("Enter") on your keyboard.
### Expected behavior
Manual editing is respected.
### Actual behavior
Manual editing is ignored.
### Device information

* Android device: Android 7.0
* Focus version: 8.0.24 (Build #333101653 GV 71.0a1-20191003093956)

### Additional info:  
Both "Top sites" and links manually added to the autocomplete list are affected.  
This issue does not occur in Focus v9.0 (Build #331691211 GV 65.0.20190125143011).  
Autocomplete does not save full addresses with connection protocol specified, but domain names. Thus Focus attempts to connect via `http` even if the web resource supports secure connection (regardless of HSTS header being set). Full contents of `http` request are exposed to the middleman (ISP, hotspot provider, etc.). It's sorta separate issue, but one is unable to maually add `https`, because it gets ignored. It's UC.

**Comment by lobontiumira** [comment] 2022-02-28 08:22
I was not able to reproduce this issue on the latest Focus builds.
I'll close this ticket.

@4ut0-M-4t thank you for the report! Feel free to file a new issue if you encounter this behavior again.

**Closed by lobontiumira** 2022-02-28 08:22 UTC
