### ISSUE TITLE
Tab stops loading if quick switched to other tabs

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/focus-android#3550] opened 2018-10-02 11:50 UTC
## STR 
1.Open firefox focus.
2.Search keywords or url. (tab A)
3. Open another link to the new tab.(tab B)
4. Switch to the new tab(B) which will start loading address as you switch to the tab.
5. Go back to the previous tab(A) while the page(tab B)is loading.( stage- page at initial point)
6. Go back to the new tab(B) which have been switched while page was loading.
### Expected Result 
The page is still loading or is fully loaded.
### Actual Result 
The tabs stops loading as we switch to another tab and after returning to the page it still not loads the page and progress bar is struck at the point when the tab was switched.

### Device information

* Android device: 8.0.0
* Focus version: 8.0 (Build #322741758 🦎 62.0.3.20180928184514)

**Comment by theLimitBreaker** [comment] 2018-10-03 15:08
Can I work on this issue

**Comment by boek** [comment] 2018-10-05 17:13
@theLimitBreaker Definitely! Let me know if you need anything 👍

**Comment by sblatz** [comment] 2018-11-08 15:43
@theLimitBreaker are you still working on this or can I jump on it?

**Comment by theLimitBreaker** [comment] 2018-11-08 16:21
Yes I am working .

**Comment by theLimitBreaker** [comment] 2018-11-11 18:30
@boek  Can you please tell me some leading files which handle creating tabs and switch to new tabs. ?

**Comment by Scripterr** [comment] 2018-11-12 03:33
@theLimitBreaker l think you are using release version of focus or it is pie but l'm not seeing any reloading while switching tab, but if you have setting to open tabs in background then the tab only starts loading when opened for first time.
I'm using Firefox focus nightly 8.0 (Build #323151211 64.0.20181105164654)
On Android 8.0.0
Device- lenovo k8 note
But now some pages doesnt loads but the progress bar still is struck at the initial point. And some with some websites the address bar shows about:blank
## Screenshots
![screenshot_20181112-084728 2](https://user-images.githubusercontent.com/42364681/48325026-92762a80-e62b-11e8-95fd-9d0d9bdf0b21.png)
![screenshot_20181112-084718 2](https://user-images.githubusercontent.com/42364681/48325030-97d37500-e62b-11e8-8109-8ac195f5c2c9.png)

**Comment by rpappalax** [comment] 2018-11-14 22:04
I tried same STR using some content heavy news sites (cnn, mnsnbc) and switching back and forth between tabs, however, I'm unable to repro this issue.

Android 8.0.0, Nexus 6P
Firefox Focus 8.0 (Build #11)

**Comment by vesta0** [comment] 2018-11-15 20:15
I also just tried a few different sites and could not reproduce this so it may have been fixed in 8.0 nightly.

**Closed by vesta0** 2018-11-15 20:15 UTC
Labels: P2, bug, needs investigation, size S, testing
