### ISSUE TITLE
Visited Reddit link is greyed out after erasing / restarting Focus

### ISSUE THREAD

**Issue by nojunpark** [mozilla-mobile/focus-android#1220] opened 2017-08-28 18:23 UTC
Device:
Simulators, Z3C device

STR:
Go to reddit.com
choose to stay in mobile site
click one of the link, and open the link
Click Erase button, and go back to reddit.
Actual:
The visited link is greyed out
Expected:
The visited link should not be greyed out

Above also happens when the app is killed (by pressing X on recent apps list) and restarted.  The history is removed when the phone is rebooted. 

![screen shot 2017-08-28 at 12 07 04 pm](https://user-images.githubusercontent.com/6930774/29787271-57f28cd0-8bfc-11e7-884c-6849eb78022f.png)

('Amazon Cuts Prices' and 'No Tipping' were visited before the app was restarted)

**Comment by npark-mozilla** [comment] 2017-09-06 17:55
On Firefox private tab, reddit asks the user to log in to view mobile site.
On Chrome, it does not remember the visited links - it even pops up the mobile app suggestion banner each time the site is visited, which Focus does not do.
So this issue seems to be only happening on Focus at the moment.

**Comment by pocmo** [comment] 2017-09-08 14:37
I noticed two issues:
* On reddit.com our workaround is not working (Removing visited link color)
* At least with multiprocess webview the visited links memory cache stays alive when Focus is killed - until the chrome process is stopped. This makes this worse.

@npark-mozilla Does the link color survive killing the Focus app on all devices or only Android 8+ (with multiprocess webview)?

**Comment by npark-mozilla** [comment] 2017-09-08 14:42
@pocmo it happens on Android 6,7,8

**Comment by the-n3i** [comment] 2017-09-08 17:35
mcomella directed me here from the mozilla bug tracker. I found another website where the css workaround doesn't work: http://blog.fefe.de

The blog uses plain html and no CSS. If I understood the workaround correctly it only works for websites which use css but not for those that don't.
I think it should be made compatible with plain html sites, instead of relying on a site to use css.

**Comment by pocmo** [comment] 2017-09-11 08:40
The "plain HTML and no CSS" case is known - and there's nothing we can do here. The actual issue has to be fixed by Google in WebView (See #990).

**Comment by npark-mozilla** [comment] 2017-11-02 16:17
In Android 8.0, (Pixel 2) the links are ungreyed now when I restart the app after killing it from recent apps list.  Perhaps something to do with #1306 fix?

**Comment by bbinto** [comment] 2017-11-10 12:00
Can we close this now @npark-mozilla?

**Comment by npark-mozilla** [comment] 2017-11-10 15:04
It still shows the site as visited even after pressing 'Erase,' so I think the issue is still valid.  I'll also test it on other android versions as well.

**Comment by kbrosnan** [comment] 2021-05-18 17:00
GV has made this obsolete

**Closed by kbrosnan** 2021-05-18 17:00 UTC
Labels: P5, bug
