### ISSUE TITLE
Page Zoom-The bottom scroll bar is not displayed when horizontal scrolling on a page

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/focus-android#4475] opened 2020-02-24 13:34 UTC
## Steps to reproduce
1. Open app and go to "planet.mozilla.org". 
2. Zoom in the page.
3. Scroll horizontally.

### Expected behavior
At the bottom of the page a scroll bar is present. 

### Actual behavior
The scroll bar from the bottom part of the page is activated only when the user scrolls vertically and only from top to down.

### Device information
* Android device: Google Pixel 3a (Android 9)
* Focus version: Firefox Focus 8.0.26 GV 73.0.1

Note:
- The issue doesn't reproduces only for the page mentioned at step 1.

**Comment by jonalmeida** [comment] 2020-02-24 16:14
If the toolbar at the top is hidden, do you see the horizontal scrollbar then?

**Comment by Diana-Rus** [comment] 2020-02-26 14:28
Hi, yes, the horizontal scrollbar is displayed when the toolbar is hidden. When the toolbar isn't hidden than the scrollbar is not displayed.

**Comment by jonalmeida** [comment] 2020-02-26 19:04
This can be closed as a duplicate of https://github.com/mozilla-mobile/focus-android/issues/3815 in that case. :)

**Closed by jonalmeida** 2020-02-26 19:04 UTC
Labels: bug
