### ISSUE TITLE
[A11y] First run tour navigation is difficult

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#2942] opened 2018-07-20 08:00 UTC
## Steps to reproduce
Activate Talkback.
1. On the First run tour tap next on the first slide.
2. Swipe right/left until you reach the end of the visible content.

### Expected behavior
Talkback should read only the visible content and should start reading the new slide (or indicate that the content was changed).

### Actual behavior
1. goes to 2nd slide and doesn't read automatically the next slide, the user has no indication that the slide is changed
2. swiping right/left on one slide reads the content from the previous/next slides that are not displayed

### Device information
* Android device: 
LG Nexus 5 (Android 6.0.1)
Google Pixel (Android P beta)

* Focus version: 6.3

**Comment by ekager** [comment] 2018-07-24 17:56
Dupe of #2780

**Closed by ekager** 2018-07-24 17:56 UTC
Labels: Klar+Geckoview
