### ISSUE TITLE
Tapping on external links on torrentz2.eu with auto opening popups causes Focus to navigate to blank page

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/focus-android#4301] opened 2019-06-23 20:21 UTC
## Steps to reproduce

1. Navigate to https://torrentz2.eu/1d5ccc5139c4ce6814772371478b8560c155ef42
2. Tap link to "linuxtracker.org"

### Expected behavior

http://linuxtracker.org/index.php?page=torrent-details&id=1d5ccc5139c4ce6814772371478b8560c155ef42 is opened

### Actual behavior

Focus navigate to blank page. 

It looks like the popup blocker swallows the request to the link I actually wanted to go to. If I deny the popup opening in Reference Browser or Fenix, the link opens correctly. 

### Device information

* Android device: Pixel 2
* Focus version: 9.0 (Build #331731218 :lizard: 65.0.20190125143011)

**Comment by lobontiumira** [comment] 2021-07-09 13:30
@yoasif I was not able to reproduce this issue, mainly because the link is invalid. Tested on the 8.17.0 build with Google Pixel (Android 10).

**Comment by lobontiumira** [comment] 2022-01-10 13:54
Closing this ticket because the reporter hadn't provide new information.
Thank you!

**Closed by lobontiumira** 2022-01-10 13:54 UTC
