### ISSUE TITLE
Tabs: Implement the old Tabs Tray from Fenix into Focus

### ISSUE THREAD

**Issue by WKSuperPower** [mozilla-mobile/focus-android#4578] opened 2020-06-26 09:39 UTC
### Why/User Benefit/User Problem

Focus can not open multiple tabs. 

### What / Requirements

Focus should support opening several tabs, since it is a browser!

### Acceptance Criteria (how do I know when I’m done?)

I can manage tabs on Focus like in Fenix versions prior to 5.2.

**Comment by cadeyrn** [comment] 2020-06-26 10:04
> Focus should support opening several tabs, since it is a browser!

Focus works different by design. A few days ago there was a feature request for add-on support, now Focus should get the tab behaviour of other browsers. Really, if Mozilla would do all that then there would no longer be a reason to use Focus because then Focus is just another browser. There is already Fenix if you want a full featured browser. The differences are the USP of Focus.

**Comment by WKSuperPower** [comment] 2020-06-26 10:17
Focus works different by design. A few days ago there was a feature request for add-on support, now Focus should get the tab behaviour of other browsers. Really, if Mozilla would do all that then there would no longer be a reason to develop Focus because then Focus is just another browser. There is already Fenix if you want a full-featured browser. Things like this very special (non-) tab concept are part of the core concept and the USP of Focus.
> 
> (btw. there is already support for multiple tabs in Focus but not in the classical way and - as I said - that's by design)

Fucus will be more powerfull with support for  multiple tabs. Also, Focus is already getting several features from Fenix in the AC integration.

**Comment by lobontiumira** [comment] 2022-03-18 09:22
Hello all!
The user has the option of opening multiple tabs, and close one at a time, on all Focus builds available (RC, Beta, and Nightly).
I'll close this ticket as obsolete.

**Closed by lobontiumira** 2022-03-18 09:22 UTC
