### ISSUE TITLE
Website fails to load: blog.xamarin.com

### ISSUE THREAD

**Issue by danielgjackson** [mozilla-mobile/focus-android#2478] opened 2018-04-18 20:35 UTC
Firefox Focus for Android "Mozilla/5.0 (Linux; Android 8.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/4.1 Chrome/66.0.3359.106 Mobile Safari/537.36" fails to load the site:

    https://blog.xamarin.com/

(With or without "trackers blocked"), with the message:

```
Secure connection failed
This could be a problem with the server’s configuration, or it could be someone trying to impersonate the server.
If you have connected to this server successfully in the past, the error may be temporary, and you can try again later.
Try Again
```

...while Firefox for Android "Mozilla/5.0 (Android 8.0.0; Mobile; rv:59.0) Gecko/59.0 Firefox/59.0" loads the site fine, both in normal- and private-browsing mode.

Chrome on Android "Mozilla/5.0 (Linux; Android 8.0.0; SM-G955F Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.106 Mobile Safari/537.36" also works.

So too does Samsung Internet "Mozilla/5.0 (Linux; Android 8.0.0; SAMSUNG SM-G955F Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/7.0 Chrome/59.0.3071.125 Mobile Safari/537.36".

If this is a misconfigured website, it would still be useful if Focus provided enough information to explain the exact cause of the issue.

**Comment by ekager** [comment] 2018-04-18 21:15
Happens with GV builds too with error:
`loadURI: uri=about:certerror?e=nssBadCert&u=https%3A//blog.xamarin.com/&c=UTF-8&f=regular&d=%20 where=1 flags=0`
Looks like a bad cert so I'm not sure why it works with other browsers?

**Comment by lobontiumira** [comment] 2021-10-05 09:03
This issue is no longer reproducible on the latest RC 93.1.1 build with Lenovo Tab M10 (Android 10), and Xiaomi mi4i (Android 5.0.2).
I'll close the issue.

**Closed by lobontiumira** 2021-10-05 09:03 UTC
Labels: bug, needs investigation, P5
