### ISSUE TITLE
Focus re-opens erased session

### ISSUE THREAD

**Issue by Keyikedalube** [mozilla-mobile/focus-android#4623] opened 2020-09-16 06:21 UTC
## Steps to reproduce

1. Load and Add *m.youtube.com* to Home screen
2. Close the session
3. Now open that saved link from Home screen
4. Erase session
5. Close Firefox Focus
6. Re-open app from recent (three-dashed line) button

### Expected behavior

7. Focus opens a new session

### Actual behavior

7. Focus reopens erased session (m.youtube.com)

### Device information

* Android device: Samsung Galaxy M30s
* Focus version: 8.7.2
![Screenshot_20200916-114217_Firefox Focus](https://user-images.githubusercontent.com/24214509/93299067-12661080-f812-11ea-9a62-5e7506b02397.jpg)

**Comment by lobontiumira** [comment] 2022-03-18 10:42
I was not able to reproduce this issue on the latest Focus Nightly build 100.0a1 from 3/18 with a samsung Galaxy Note 8 (Android 9) device.
Closing this ticket.

**Closed by lobontiumira** 2022-03-18 10:42 UTC
