### ISSUE TITLE
Every first try to downlod any file lets firefox crash

### ISSUE THREAD

**Issue by sandoxy** [mozilla-mobile/focus-android#7065] opened 2022-05-20 06:45 UTC
## Steps to reproduce
Go e.g. to https://github.com/mozilla-mobile/focus-android/releases and try to download an apk.

The next try succeeds.

On almost every website.

### Expected behavior
Download starts.

### Actual behavior
Browser crashes.

### Device information

* Android device: Android 11, Xoaomi Redmi Note 9s
* Focus version: 100.2.0

**Comment by delia-pop** [comment] 2022-05-20 08:26
Hello, @sandoxy , 
I was not able to reproduce this issue on RC 100.2.0, nor 100.3.0 with Xiaomi Redmi Note 8T (Android 9) and Motorola Moto G30 (Android 11).

**Comment by sandoxy** [comment] 2022-05-20 08:55
> Hello, @sandoxy , 
> I was not able to reproduce this issue on RC 100.2.0, nor 100.3.0 with Xiaomi Redmi Note 8T (Android 9) and Motorola Moto G30 (Android 11).
> 
>  
Ok, thank you. This issue occures for at least one ear and also occured on my last device.

**Comment by amedyne** [comment] 2022-05-23 14:02
@sandoxy can you attach the crash logs here?

**Comment by sandoxy** [comment] 2022-05-23 14:50
> @sandoxy can you attach the crash logs here?

How do I create or find a crash log?

**Comment by ionutbedregeanu** [comment] 2022-05-24 06:07
@sandoxy I attached a video which will help you to send us the crash id

https://user-images.githubusercontent.com/11731652/169960032-7294e2aa-32d5-4ac7-a076-d0665281b716.mp4

You can find the steps [here](https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information) for Fenix, but which can be applied to Focus also

**Comment by sandoxy** [comment] 2022-05-24 15:06
Thank you!

Starting 19.08.21 there are a lot of reports:

![Screenshot_2022-05-24_17-03-27.png](https://user-images.githubusercontent.com/38521726/170068738-e4170647-aa6e-4b06-a1eb-be696cf39c47.png)

Here is the last report:

`3e72a2b1-0523-4c6a-ab26-d1aa75eb6692
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{b302527 u0 org.mozilla.klar/org.mozilla.focus.downloads.DownloadService}
----
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{b302527 u0 org.mozilla.klar/org.mozilla.focus.downloads.DownloadService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2043)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7861)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
`

**Comment by sandoxy** [comment] 2022-05-24 15:13
Maybe it matters: I am using only this file manager https://github.com/zhanghai/MaterialFiles

**Comment by ionutbedregeanu** [comment] 2022-06-10 12:29
Hi, @sandoxy 👋 
I also tried to reproduce this bug and unfortunately I didn't succeed, so we still need your help to find the main cause
I searched all those reports ids from the attached photo but I didn't find them in [here](https://crash-stats.mozilla.org/search/?signature=~RemoteServiceException&version=100.0.2&date=%3E%3D2022-05-10T12%3A02%3A00.000Z&date=%3C2022-06-10T12%3A02%3A00.000Z&_facets=signature&page=1&_sort=-date&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-signature)
Can you please follow the [steps](https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information) again to send the reports?
Also can you please try to download  a file without any file manager and tell us if it's still reproducible?

**Comment by ionutbedregeanu** [comment] 2022-08-10 14:35
@sandoxy I will close this ticket since seems an isolated case and we can't reproduce it, but please feel free to reopen it if you still reproduce it and you can help us with some extra details

**Closed by ionutbedregeanu** 2022-08-10 14:35 UTC
Labels: crash 🔥
