### ISSUE TITLE
The page menu bar does not stay stuck to the footer of the page if scrolling is performed at npr.org

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/focus-android#5823] opened 2021-11-09 10:00 UTC
## Steps to reproduce
1. Access : https://www.npr.org/?t=1636451687272
2. Scroll the page 
3. Observe the bottom menu navigation bar

### Expected behavior
The menu bar has a fixed position

### Actual behavior
The menu bar changes the position

### Device information

* Android device: Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)
* Focus version: Firefox Focus 94.1.2 (353121860 🦎94.0-20211028161635🦎)

**Notes:**

1. Attaching relevant screen recordings:

![nav bar focus](https://user-images.githubusercontent.com/75027050/140903183-31a66fa5-25c9-4c55-bb30-6e4f4cec7384.gif)

2. Might be related to : https://github.com/mozilla-mobile/focus-android/issues/5452
3. Works as expected on the latest build of Firefox Nightly
4. Works as expected in "Private" browsing mode

**Comment by softvision-raul-bucata** [comment] 2021-11-26 09:46
See also: https://github.com/mozilla-mobile/focus-android/issues/5705

**Comment by softvision-raul-bucata** [comment] 2021-11-26 09:49
See also: https://github.com/mozilla-mobile/focus-android/issues/5705

**Comment by lobontiumira** [comment] 2022-05-30 14:28
This issue is a duplicate of #5701.
Closing.

**Closed by lobontiumira** 2022-05-30 14:28 UTC
Labels: wontfix
