### ISSUE TITLE
Black screen when returning browser to front

### ISSUE THREAD

**Issue by romuald** [mozilla-mobile/focus-android#4573] opened 2020-06-18 21:09 UTC
## Steps to reproduce

Returning to Firefox Focus after a while (**not** having cleared the history), using the Android activity selector

### Expected behavior

The tabs reopens with the URL that was previously shown. Possibly reloading it

### Actual behavior

The web content view stays **black** (actually fades to black)
A manual reload is  action does not fix this

Note that it seems to be related to a low memory situation (possibly because some memory was reclaimed by the OS)

I will try to make a video showing the issue. This only occurred for a few weeks

### Device information

* Android device: Sony XPeria X compact (F5321)
* Android version: 8.0.0
* Focus version: 0.4.8

**Comment by romuald** [comment] 2020-06-18 21:30
Here is a small video showing the issue: https://chivil.com/firefox-focus-black-screen.mp4

Confirmed (from my POV) that this is resource related, as launching an app requiring lots of memory will "instantly" trigger the issue

**Comment by romuald** [comment] 2020-06-18 21:39
Here are some logs from adb (those are logged **before** trying to resume the activity)

```
06-18 23:34:35.628  3576 30899 I ActivityManager: Process org.mozilla.focus:tab0 (pid 7083) has died: cch  CACC
06-18 23:34:35.628  3576 30899 W ActivityManager: Scheduling restart of crashed service org.mozilla.focus/org.mozilla.gecko.process.GeckoChildProcessServices$tab0 in 1000ms
06-18 23:34:35.641 31658 31701 D GeckoViewProgress: observe: topic=oop-frameloader-crashed
06-18 23:34:35.645 31658 31701 D GeckoViewContent: observe: oop-frameloader-crashed
06-18 23:34:35.648 31658 31701 D GeckoViewProgress: observe: topic=oop-frameloader-crashed
06-18 23:34:35.650 31658 31701 D GeckoViewContent: observe: oop-frameloader-crashed
06-18 23:34:35.651 31658 31701 D GeckoViewProgress: observe: topic=oop-frameloader-crashed
06-18 23:34:35.651 31658 31701 D GeckoViewContent: observe: oop-frameloader-crashed
06-18 23:34:35.651 31658 31701 D GeckoViewProgress: observe: topic=oop-frameloader-crashed
06-18 23:34:35.652 31658 31701 D GeckoViewContent: observe: oop-frameloader-crashed
06-18 23:34:35.655 31658 31701 D GeckoViewContent: observe: ipc:content-shutdown
06-18 23:34:35.658 31658 31701 I chatty  : uid=10007(u0_a7) Gecko identical 2 lines
06-18 23:34:35.659 31658 31701 D GeckoViewContent: observe: ipc:content-shutdown
06-18 23:34:35.659 31658 31712 I Gecko   : [Parent 31658, Unnamed thread 735a844240] WARNING: waitpid failed pid:7083 errno:10: file /builds/worker/checkouts/gecko/ipc/chromium/src/base/process_util_posix.cc, line 237
06-18 23:34:35.899 31658 31701 E GeckoConsole: [JavaScript Error: "TypeError: this.messageManager is null" {file: "resource://gre/modules/GeckoViewContent.jsm" line: 83}]
06-18 23:34:35.899 31658 31701 E GeckoConsole: onDisable@resource://gre/modules/GeckoViewContent.jsm:83:5
06-18 23:34:35.899 31658 31701 E GeckoConsole: set enabled@chrome://geckoview/content/geckoview.js:435:18
06-18 23:34:35.899 31658 31701 E GeckoConsole: init/</<@chrome://geckoview/content/geckoview.js:94:9
06-18 23:34:35.899 31658 31701 E GeckoConsole: forEach@chrome://geckoview/content/geckoview.js:125:19
06-18 23:34:35.899 31658 31701 E GeckoConsole: init/<@chrome://geckoview/content/geckoview.js:93:12
```

**Comment by lennyhans** [comment] 2020-06-19 17:17
Second this

**Comment by meus** [comment] 2020-07-03 14:04
same here
Nokia 7.1, Android 10, Firefox Klar 8.4.0

**Comment by brunocreginato** [comment] 2020-07-12 22:50
same here!
GalaxyS9, Android 10

**Comment by reactorcoremeltdown** [comment] 2020-08-17 15:20
Still happening, Android 9, Xiaomi A1

**Comment by jonalmeida** [comment] 2020-09-18 02:23
Duplicate of #4599

Thanks for the logs, that was helpful in solving this bug! I'm closing this issue as a duplicate since there is an active discussion and we have reproducible steps on it.

**Closed by jonalmeida** 2020-09-18 02:23 UTC
