### ISSUE TITLE
java.lang.IllegalStateException: WebView is expected to always supply a valid URL

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#457] opened 2017-04-13 09:32 UTC
```
java.lang.IllegalStateException: WebView is expected to always supply a valid URL
Frame	module	Crash Details
0	org​.mozilla​.focus​.utils	UrlUtils.java ​Line ​81
UrlUtils.stripUserInfo
	
1	org​.mozilla​.focus​.fragment	BrowserFragment.java ​Line ​81
BrowserFragment.updateURL
	
2	org​.mozilla​.focus​.fragment	BrowserFragment.java ​Line ​36
BrowserFragment.access$500
	
3	org​.mozilla​.focus​.fragment	BrowserFragment.java ​Line ​185
BrowserFragment$1.onURLChanged
	
4	org​.mozilla​.focus​.web	WebViewProvider.java ​Line ​275
WebViewProvider$WebkitView$2.onProgressChanged
```

`app/src/main/java/org/mozilla/focus/utils/UrlUtils.java` line `81`

```java

                return url;
            }

            if (BuildConfig.DEBUG) {
                // WebView should always have supplied a valid URL
                throw new IllegalStateException("WebView is expected to always supply a valid URL"); <-- CRASHED
            } else {
                return url;
            }
        }
    }
```

[View File](https://github.com/mozilla-mobile/focus-android/blob/1230d32cc6aa04ff67942a5f71f069d3233ccc37/app/src/main/java/org/mozilla/focus/utils/UrlUtils.java#L81) | [View Full Crash Details](https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/crashreport/0bc41cbd3662d94034bf0c98f3e9d4b8)

**Comment by pocmo** [comment] 2017-04-13 10:02
#464 might be causing this.

**Comment by ahunt** [comment] 2017-04-14 18:40
Also a dupe of #414 and #464 : ) - it's fixed in the latest master builds, we just haven't pushed that to our bigger group of testers yet.

**Closed** 2017-04-14 18:41 UTC
Labels: bug, v1.0
