### ISSUE TITLE
Need for a widget app.

### ISSUE THREAD

**Issue by itsrahul** [mozilla-mobile/focus-android#1395] opened 2017-09-26 10:57 UTC
There should be a widget app, which allows the user to directly search in the browser.

**Comment by pocmo** [comment] 2017-09-26 11:51
What would be different than pressing the launcher icon where you also can immediately perform a search?

**Comment by itsrahul** [comment] 2017-09-28 07:49
It would be easier as the user would directly enter the query from home screen, rather than opening the app.

**Comment by bbinto** [comment] 2017-10-03 15:14
Is this similar to #505?

**Comment by pocmo** [comment] 2017-10-04 08:08
Yeah, I think so. Closing this as a duplicate of #505.

**Closed by pocmo** 2017-10-04 08:08 UTC
Labels: feature, needs triage
