### ISSUE TITLE
No option to report content crash or to restore / close crashed tab.

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/focus-android#6677] opened 2022-03-16 11:45 UTC
Seen while testing https://github.com/mozilla-mobile/android-components/pull/11872/

Focus [should support](https://github.com/mozilla-mobile/focus-android/blob/1f72163dbe3e36c6b9775815bacbd0a7917e8eea/app/src/main/java/org/mozilla/focus/activity/MainActivity.kt#L153-L159) content crashes but the app is just left with an empty tab:

https://user-images.githubusercontent.com/11428869/158582599-89a74507-6e14-4a45-9bc1-8ac1aec1644d.mp4

**Comment by jamienicol** [comment] 2022-03-16 12:04
@Mugurell is this caused by my patch, or did you just notice it while testing it?

**Comment by Mugurell** [comment] 2022-03-16 12:34
This happens in the current releases without the patch from https://github.com/mozilla-mobile/android-components/pull/11872 which after being applied brings the functionality needed for GPU crashes without seemingly any impact (good or bad) for the current functionality.

**Comment by lobontiumira** [comment] 2022-03-16 12:51
This is a dupa of #6512

**Comment by ionutbedregeanu** [comment] 2022-03-29 10:27
Close this ticket since is a duplication of https://github.com/mozilla-mobile/focus-android/issues/6512

**Closed by ionutbedregeanu** 2022-03-29 10:27 UTC
Labels: bug
