### ISSUE TITLE
Previous links stay purple after clearing.

### ISSUE THREAD

**Issue by doublez13** [mozilla-mobile/focus-android#1392] opened 2017-09-25 17:31 UTC
Tested on Android O on Pixel

For example...
1. Go to Wikipedia
2. Browse a link
3. Press the trash can to clear everything
4. Browse back to Wikipedia
5. Viewed link still appears purple

Pressing the trash can, then closing the app seems to actually clear the viewed links.

**Comment by pocmo** [comment] 2017-09-25 17:41
Thank you for filing this issue. Can you help me answer the following questions so that I can try to reproduce this issue?

* What device are you using?
* What Android version is installed on your device?
* What's the browser user agent if you go to this URL: http://www.whoishostingthis.com/tools/user-agent/

**Comment by doublez13** [comment] 2017-09-25 18:01
Google Pixel running Android 8.0.0

Mozilla/5.0 (Linux; Android 8.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/2.0 Chrome/61.0.3163.98 Mobile Safari/537.36

**Comment by doublez13** [comment] 2017-09-25 18:09
Here's an exact test case that I've confirmed
1. Open Firefox Focus
2. Go to wiki.kernel.org
3. Tap the rt link (first link on the list)
4. Tap trash can
5. Go to wiki.kernel.org
6. rt link still appears purple

**Comment by ekager** [comment] 2017-10-03 19:41
#322 is where this issue was discussed previously. There doesn't seem to be much action in the [Chromium bug we filed. ](https://bugs.chromium.org/p/chromium/issues/detail?id=709627&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=) So I will try to work on the CSS injection bit because I don't think we're doing anything wrong in how we clear history, cache, cookies, etc.

**Comment by pocmo** [comment] 2017-10-20 10:03
@ekager Have you been able to reproduce this for Wikipedia? That's something I'm still unable to.

For wiki.kernel.org: They do not appear to use a style for links at all (default browser colors). That's not covered by our workaround and a known issue. This might be a duplicate of #990 (Fix in WebView required).

**Comment by liuche** [comment] 2017-11-30 18:38
Duping this to #1600

**Closed by liuche** 2017-11-30 18:38 UTC
Labels: bug, Jasmine, P1
