### ISSUE TITLE
filterlists?

### ISSUE THREAD

**Issue by runboy93** [mozilla-mobile/focus-android#1806] opened 2017-11-26 15:27 UTC
https://filterlists.com/

Easylist + Adguard mobile filters would do nice work.

Privacy:

WebRTC (your IP is shown to everything) is not disabled on Firefox Focus? This is quite must option for privacy browser.

Adblocker feature:

Filterlists should be included on your adblocker feature (easylist, adguard mobile...), if does support them.
Pop-ups are not hidden/blocked.
Ads / trackers are being blocked, but yeah not many as it should be (just example, some websites include around 100+ ads, Firefox Focus block around 16-25 ads, you can ask me for websites)

Settings:

There are some settings already, but somehow I feel it does need more (like for blocking pop-ups)

In general I do like your privacy browser, but few things need upgrades, like told above.

**Comment by pocmo** [comment] 2017-11-27 10:14
Thanks!

Duplicate of #953.

**Closed by pocmo** 2017-11-27 10:14 UTC
