### ISSUE TITLE
Using some keyboards, typing in form inputs duplicates letters

### ISSUE THREAD

**Issue by tie-rack** [mozilla-mobile/focus-android#2840] opened 2018-07-03 02:04 UTC
### Steps to reproduce

1. Install [AnySoftKeyboard](https://play.google.com/store/apps/details?id=com.menny.android.anysoftkeyboard&hl=en)
2. Navigate to a page with text input (&lt;input&gt; or &lt;textarea&gt;), e.g. [Google](https://www.google.com/)
3. Using AnySoftKeyboard, type in a form input

### Expected behavior

The individual letters you type appear once each time you type it.

### Actual behavior

Each letter in a word reinserts every letter from before. So, if you type "test" into a text input, what gets inserted is "ttetestest".

### Device information

* Android device: Pixel XL
* Focus version: 6.2 (Build #221791209 62.0.20180625141512)
* AnySoftKeyboard version: 1.9.2055, version-code 4630

### Other information

I do not see this behavior:
* in the address bar in Firefox Focus with AnySoftKeyboard (so it's not _all_ typing in Firefox Focus that exhibits this, just in-page typing)
* in Firefox Focus with Gboard, the standard Android keyboard (so it's not _all_ keyboards)
* in Firefox Nightly with AnySoftKeyboard (so it's not _just_ AnySoftKeyboard... though I guess it still could be a problem in AnySoftKeyboard that other apps just happen to work around accidentally)

**Comment by cpeterso** [comment] 2018-07-03 17:53
We have a GeckoView bug filed about duplicated text ("BBeBerBerlBerliBerlin" when typing "Berlin")

https://bugzilla.mozilla.org/show_bug.cgi?id=1470786

**Comment by ekager** [comment] 2018-07-14 05:19
Dupe of #2807, Closing

**Closed by ekager** 2018-07-14 05:19 UTC
Labels: Klar+Geckoview, P5, blocked, bug
