### ISSUE TITLE
Context menu does not disappear after searching selected text

### ISSUE THREAD

**Issue by initrd** [mozilla-mobile/focus-android#3317] opened 2018-09-05 06:39 UTC
## Steps to reproduce
1. Open https://www.mozilla.org/
2. Select "Firefox"
3. From the context menu, choose "Search  privately"
4. Search opens in a new tab

### Expected behavior
Context menu should disappear

### Actual behavior
Context menu lingers around
![screenshot_20180904-233310](https://user-images.githubusercontent.com/1941695/45075309-928e0300-b09b-11e8-9f7a-a598af3bfe50.png)

Haven't found any way to clear the context menu, other than selecting some text and choosing Copy from the context menu

### Device information

* Android device: Google Pixel, Android 9.0
* Focus version: 7.0 (Build #322471206 🦎 62.0.20180829133835)

**Comment by SubhrajyotiSen** [comment] 2018-09-05 09:29
I can confirm this bug

**Comment by SubhrajyotiSen** [comment] 2018-09-05 17:14
I was unable to reproduce this when I built from the latest source

**Comment by ekager** [comment] 2018-09-05 17:37
Some history: We previously saw this in #2633

**Comment by cpeterso** [comment] 2018-09-13 18:01
@ekager - The GV bug was closed because Jim says this is probably a Focus issue, not a GV issue. The toolbar is Focus UI, so Focus should track when GeckoView is destroyed. If you disagree, please reopen the GV bug. :)

**Comment by vesta0** [comment] 2018-09-18 12:16
@Sdaswani yes that is fine, I wouldn't consider it a blocker for 7.0

**Comment by ekager** [comment] 2018-09-21 18:14
Closed by #3459 in latest 62 Rel Branch.

**Closed by ekager** 2018-09-21 18:14 UTC
Labels: Klar+Geckoview, P2, blocked, bug
