### ISSUE TITLE
Backgroud animation does not load at retrobottega.caffe-design.it

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/focus-android#5750] opened 2021-11-01 15:44 UTC
## Steps to reproduce

1. Navigate to : https://retrobottega.caffe-design.it/
2. Observe the result

### Expected behavior
Background animation loads

### Actual behavior
Background animation does not load

### Device information

* Android device:  Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)
* Focus version:   94.1.1(353012322 🦎94.0-20211028161635🦎)

**Notes:**
1. Not reproducible on the latest build of Firefox Nightly  95.0a1 (2015843115 -🦎95.0a1-20211028094021🦎)
2. Not reproducible in Incognito mode on Firefox Nightly
3. Originally reported in: https://github.com/webcompat/web-bugs/issues/91741

**Comment by softvision-raul-bucata** [comment] 2021-11-01 15:45
Firefox Focus:




![Screenshot_83](https://user-images.githubusercontent.com/75027050/139699573-8cd738a0-4d81-40ad-9587-4f2bd8b57dff.png)

Firefox Nightly:


![Screenshot_82](https://user-images.githubusercontent.com/75027050/139699542-e1ec5edd-80b9-4e51-aff1-b2905c78b528.png)

**Comment by Mugurell** [comment] 2021-11-01 15:52
The same happens on Fenix if blocking video autoplay.

**Comment by Mugurell** [comment] 2021-11-01 16:06
Seems like the website plays https://www.youtube.com/watch?v=V0DWNyTVB-o in a loop.

**Comment by Mugurell** [comment] 2021-11-01 16:15
Should be "fixed" by https://github.com/mozilla-mobile/focus-android/issues/5743

**Comment by Mugurell** [comment] 2021-11-02 07:08
Based on [Bram's comment](https://github.com/mozilla-mobile/focus-android/issues/5743#issuecomment-957043253) that Focus should block audio and video autoplay the issue reported here seems like the intended behavior. Closing as wontfix.

**Closed by Mugurell** 2021-11-02 07:08 UTC

**Comment by softvision-raul-bucata** [comment] 2021-11-02 07:25
@Mugurell Thank you for the quick update. Will keep this in mind for future references.
