### ISSUE TITLE
When a tab crashes, all others are crashed too

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4006] opened 2018-12-07 09:38 UTC
## Steps to reproduce
1. Open a few webpages in different tabs.
2. Go to about:crashcontent in one of the tabs.
3. Close crashed tab.
4. Open the other tabs.
### Expected behavior
Since the crash reporter refers to a single tab, the others should still be functional(?).
### Actual behavior
All other tabs are showing blank pages.
### Device information

* Android device: 
Huawei Nexus 6P (Android 8.1.0), Motorola Nexus 6 (Android 7.1.1)
* Focus version: 8.0.1 GV.

**Comment by rpappalax** [comment] 2018-12-15 00:37
I'm unable to repro, however, when I go to about:crashcontent, I get redirected to about:blank (white page)??   All other tabs working as expected.

Android device:
Huawei Nexus 6P (Android 8.0.0)
Klar version: 8.0.3

**Comment by Sdaswani** [comment] 2018-12-18 18:16
Clearing @boek from assignee since he is on PTO.

**Comment by sblatz** [comment] 2018-12-19 17:37
I'm getting the same results as @rpappalax. I believe about:blank showing is correct behavior (see [this change](https://github.com/mozilla-mobile/focus-android/commit/e49774a92d772f21466abee10879b105846957bd#diff-16b7ab9d46296b79c83bb860edef2231R381)). 

What's confusing is that the crash reporter is not displaying at all. @sv-ohorvath are you able to get the crash reporting fragment to appear in any circumstance? It should have been implemented in #3074.

**Comment by sv-ohorvath** [comment] 2018-12-20 09:51
On Klar GV the crash reporter doesn't show up indeed. I'll file a new bug for that.
On Focus, GV, the issue is still reproducible, but now the other tabs are closed and all is left is an about:blank page. (It used to keep the tabs but show blank on all of them.)

I made 2 recordings with the latest release builds from taskcluster:
* Klar 8.0.4 GV (build#323512256 GV 64.0.20181214004633) : https://drive.google.com/file/d/1MFIwsTRBD1NX9IDLEPWA85kZjspLPiar/view?usp=sharing

* Focus 8.0.4 GV (build#323512256 GV 64.0.20181214004633): https://drive.google.com/file/d/1eavPRgx-RQJ7QXqXTIULIcHMisMlPlzR/view?usp=sharing

**Comment by sblatz** [comment] 2018-12-20 15:24
Okay so I'm noticing a few different issues here.

1. In android emulator (Pixel 2 XL API 28, Focus 8.0.4 GV) I'm unable to get the crash report page. The current tab becomes about:blank, and the rest stay open.
2. On physical device (Moto G Play 6.0.1, Focus 8.0.4 GV) when I crash one tab it crashes them all. I get crash reporter, but once I press "close tab" I'm stuck on about:blank. Pressing the erase button **does nothing** so I must force close the app.
![demo](https://user-images.githubusercontent.com/4400286/50293297-42b42b80-0441-11e9-980a-5fbe93236f1a.gif)

3. On physical device (Klar 8.0.4 GV) all the tabs become about:blank and crash reporter is not shown.

Seems like this ticket may be rather convoluted and entangled with multiple issues?

**Comment by sblatz** [comment] 2019-01-01 19:41
@vesta0 how do we want to handle this? It seems like three different issues are occurring related to this one ticket. I would argue that the second one I mentioned is the most concerning as it leaves the user in a state where they must force close the app. 

I think it would also be helpful if people with more physical devices could follow the STR to see if they're getting any different cases other than the ones I mentioned above.

**Comment by vesta0** [comment] 2019-01-02 16:44
@npark-mozilla could we have QA try to replicate the above scenarios?

**Comment by npark-mozilla** [comment] 2019-01-02 20:49
@sblatz so I tested this on release 7.0 WV, (I'm not part of the other 50%)  and I see 1.  When I change the renderer to GV, then I see 2.

**Comment by sblatz** [comment] 2019-01-03 15:49
Spoke with @npark-mozilla and he will be testing a locally built master on more devices as well once master is building again. 

My *hunch* is that we should break out one more ticket: crash reporter "close tab" leaves app in unusable state.

**Comment by npark-mozilla** [comment] 2019-01-03 16:02
I also tested on local build of 8.0.5,(on moto g5) and it shows the same behavior.
On webview, it shows about:blank, no crashes
on GV, it shows crah dialog, all tabs become about:blank, but I can click trash can and retype the URL to see webpages.

**Comment by sblatz** [comment] 2019-01-03 16:24
### Example from @npark-mozilla's device

![crash no-jun](https://user-images.githubusercontent.com/4400286/50648780-11ac1e80-0f4a-11e9-89d5-1e4eee4dd64c.gif)

**Comment by vesta0** [comment] 2019-01-03 19:52
@sblatz I agree that we need to track this as 2 separate issue, prioritizing the issue with open blank tabs having to be forces closed.

A few observations to help narrow down the issue:
-This is only an issue when more than one tab is open. Crash reporter shows up AND closes the tab when we only have one tab:
-If I open 2 tabs, and try crashing the **second** tab, the crash reporter works as expected - no force closing required.

**Comment by sv-ohorvath** [comment] 2019-01-04 13:32
@vesta0 It's true, it happens only if there are at least 2 tabs opened and the first crashes. I tried to narrow it down in #4090. On nightly, it behaves differently now than Release.

**Comment by vesta0** [comment] 2019-01-04 19:55
@sblatz let's confirm that none of these issues impact a single tab

**Comment by sblatz** [comment] 2019-01-08 16:33
On Moto G4 (6.0.1) I am having the following results with a **single tab**

### Master
1. WebView: about:crashcontent sends me directly to about:blank without a crash reporter
2. GV: about:crashcontent gives me the "Firefox Focus has stopped" message and gives me about:blank **without a crash reporter**

### Nightly (8.0.4)
1. WebView: about:crashcontent sends me directly to about:blank without a crash reporter
2. GV: about:crashcontent gives me the crash reporter and works as expected

Essentially this looks like it only affects WebView or builds off of master, so I don't think it's an issue with single tabs. @boek--any insight as to why crash reporter would not be showing on a build off master but _does on nightly; is this something to be concerned about (#3854)?

**Comment by cpeterso** [comment] 2019-08-23 17:15
GeckoView doesn't use a separate content process for each tab yet (aka "e10s-multi": https://bugzilla.mozilla.org/show_bug.cgi?id=1530770). So if one tab crashes, then it is expected that all tabs will crash in Focus using GV.

**Comment by ebalazs-sv** [comment] 2020-12-10 13:20
This issue is reproducible on Focus 8.11.0 GV 84 with Pixel 2 (Android 9).

**Comment by lobontiumira** [comment] 2021-04-21 10:33
This issue still reproduces on 8.15.1 build with Samsung Galaxy Note 8 (Android 9).

**Comment by lobontiumira** [comment] 2021-04-27 13:06
This is still reproducible on 8.15.2 build with Sony Xperia Z5 Premium (Android 7.1.1).
I had 4 tabs opened, triggered about:crashcontent on one of them, closed the tab, and the three tabs remaining were blank.

**Comment by cpeterso** [comment] 2021-04-27 17:39
This bug should be (partially) fixed when Android e10s-multi is rides the trains in https://bugzilla.mozilla.org/show_bug.cgi?id=1699464. Fenix will then have multiple tab (content) processes, but I think all the tabs will need to share three content processes. If you have many tabs open and one crashes, then all the tabs sharing that same content process (so probably about 1/3 of your tabs) will also crash.

**Comment by lobontiumira** [comment] 2021-05-31 13:28
This is still reproducible on 8.16.0 build with Google Pixel (Android 10).

**Comment by lobontiumira** [comment] 2021-07-08 12:53
I was able to reproduce it on Focus 8.17.0 with GV 90, with OnePlus 5T (Android 10), and Google Pixel (Android 10), following these STR:
1. Open cnn.com.
2. Long-tap on a linked text, and select to open a new tab.
3. Don't switch to the newly opened tab.
4. In the URL bar insert about:crashcontent, and select to close the tab.
5. The latest opened tab remains blank, unusable.

Note: If I switch to the newly opened tab search bar, insert about:crashcontent, select to close the tab, then I'm redirected to the previous page, which works as expected.

**Comment by lobontiumira** [comment] 2021-08-06 07:00
Reproducible on 91.1.0 Focus build with [these scenarios](https://github.com/mozilla-mobile/focus-android/issues/4006#issuecomment-876413917), using a Google Pixel (Android 10).

**Comment by LaurentiuApahideanSV** [comment] 2021-08-19 14:03
The issue is still reproducible on Focus 91.2.2 following these steps:
1. Open cnn.com;
2. Open several links in new tabs by long tapping on them;
3. Don't switch to the newly opened tab;
4. In the URL bar insert about:crashcontent, and select to close the tab;
5. One of the tabs opened at step 2 will become blank and unusable.

###Device used:
- OnePlus 6T (Android 9)

**Comment by lobontiumira** [comment] 2021-09-10 13:02
I was able to reproduce this issue on the 93.0.2 (build 352522329 - GV 93.0a1-20210906031657) with Lenovo Tab M10 (Android 10).

**Comment by mcarare** [comment] 2021-09-14 11:44
@lobontiumira Is this behaviour different in Fenix?

**Comment by lobontiumira** [comment] 2021-09-14 12:02
Yes. On the 94.0a1 Nightly from 9/14, after closing the crashed tab, the other tabs are loading, and can be visited without issues.

**Comment by Sdaswani** [comment] 2021-09-16 04:56
Glad this was finally fixed!

**Comment by lobontiumira** [comment] 2021-09-16 06:13
Verified as fixed on the latest debug build from main from 9/16 (build 11 - GV 93.0a1-20210906031657) with OnePlus 5T (Android 10), and Samsung Galaxy Note 8 (Android 9).

**Closed by lobontiumira** 2021-09-16 06:13 UTC
Labels: bug, testing, P3, QAReady

**Comment by lobontiumira** [comment] 2021-09-20 08:40
Verified also on 93.0.3 build with Lenovo Tab M10 (Android 10).
