### ISSUE TITLE
Update "erase" icon (photon)

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1349] opened 2017-09-21 10:01 UTC
Follow-up from #938.

**Comment by antlam** [comment] 2017-10-04 19:10
This was intended to be a low priority follow-up item for UX. A Photon-style Focus-specific Erase icon is in the backlog but its not high priority ATM so we shouldn't really be targeting a release Milestone yet. More of a nice-to-have ATM. 

Moving this out of Folly.

**Comment by liuche** [comment] 2017-11-06 18:21
@antlam do you have an icon to attach? If you do, can you add the help-wanted label :)

**Comment by antlam** [comment] 2017-11-06 18:30
@liuche not yet, most of the focus here on the visual design side has been on getting Photon polished, buffed, and shined for next week!

**Comment by bbinto** [comment] 2018-06-25 18:17
@brampitoyo can this be closed in favour of our upcoming redesign / Android P?

**Comment by brampitoyo** [comment] 2018-06-25 22:39
Yes. This should be closed because it’s a dupe of #2682.

**Closed by brampitoyo** 2018-06-25 22:39 UTC
Labels: P4, UX
