### ISSUE TITLE
Focus "Pull to refresh" makes playing Canvas games impossible 

### ISSUE THREAD

**Issue by alperakgun** [mozilla-mobile/focus-android#1779] opened 2017-11-22 08:59 UTC
On firefox focus:  swipe down triggers refresh of the page, despite the CSS rule of "user-select: none"

https://www.zestoy.com/patriotic/reveal-pad/zgmzzyzt/1/national-motto-of-thailand-is.html

**Comment by pocmo** [comment] 2017-11-22 09:51
Thanks for reporting this. I'm going to close this as a duplicate of #1776.

**Closed by pocmo** 2017-11-22 09:51 UTC
