### ISSUE TITLE
Firefox Focus crashes while loading an SF Examiner article comment section

### ISSUE THREAD

**Issue by smartfonreddit** [mozilla-mobile/focus-android#2080] opened 2018-02-01 23:25 UTC
Load http://www.sfexaminer.com/suspected-auto-burglar-strikes-sfpd-officer-vehicle/
or
Open the SF Examiner homepage and load an article.

Firefox Focus crashes every time it tries to automatically load the comment section. If instead of automatically loading comment it shows a "Click to load comments" button, clicking that will crash the browser.
Updated the Android WebView 18 hours ago,  and Google App few hours ago. LG G5 with Android 7.0.

**Comment by Sdaswani** [comment] 2018-03-27 18:19
@smartfonreddit we can't reproduce - is it still happening for you?

**Comment by smartfonreddit** [comment] 2018-03-27 18:24
It is still happening. I can't open SF Examiner pages.

**Comment by Sdaswani** [comment] 2018-03-27 21:23
@npark-mozilla do we have access to a LG G5 anywhere - maybe Softvision does?

**Comment by npark-mozilla** [comment] 2018-03-27 21:31
@Sdaswani Unfortunately it's not in SV's device list -perhaps we can get logcat from @smartfonreddit when trying to load this website?

**Comment by smartfonreddit** [comment] 2018-03-27 22:30
The LG G5 is running on LineageOS 14.1, but at the time of filing this bug I _believe_ it was on stock ROM. Here is the cat file https://pastebin.com/ZApvz9Rq

Line 769 mentions something about the notification system. At the time of creating this log, the Focus notification was disabled to get rid of the persistent reminder to wipe data in the notification center. Just now, I reinstalled Focus to make sure the notifications are visible again and that everything is default,  and it still crashed on Examiner.
It also crashes if all 4 content blocking options are disabled in Settings. 

Focus behavior: Open an article. Article loads and is displayed for 3 seconds, while the progress bar gets stuck at 99% mark. It doesn't load the comments/polls below the article. Crash.

Firefox behavior: Open an article. Article loads and is displayed for 3 seconds, while the progress bar gets stuck at 80% mark. In a few more seconds the comments/polls load below the article, and the progress bar disappears. No crash.

**Comment by Sdaswani** [comment] 2018-03-27 22:36
Thanks for the info @smartfonreddit!

**Comment by smartfonreddit** [comment] 2018-03-27 22:40
Thanks for looking into this. I'm 100% sure this also happens with the stock LG G5 ROM, because in my initial report it said "7.0". The LineageOS is never x.0

**Comment by lobontiumira** [comment] 2021-07-01 12:14
@smartfonreddit do you still reproduce this crash on your device?
I was not able to reproduce it with Samsung Galaxy Note 8 (Android 9) on 8.16.0 build.

**Comment by lobontiumira** [comment] 2021-09-23 07:18
I will close this issue, since the reporter has not responded, and we do not have any matching device to retest.
We are not able to reproduce this crash on any other device.

**Closed by lobontiumira** 2021-09-23 07:18 UTC
Labels: bug, P5
