### ISSUE TITLE
"Search privately" does not start a browsing session

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#3598] opened 2018-10-09 20:43 UTC
## Steps to reproduce
- Open an app with text (e.g. gmail)
- Highlight some text
- Click 3-dot, "Search privately"

### Expected behavior
Focus opens a search with the highlighted text

### Actual behavior
Focus opens the home screen

### Device information

* Android device: Pixel 2, andy P
* Focus version: 6.0, #322801206 62.0.3.20181001191808

**Comment by ekager** [comment] 2018-10-09 22:03
Closing, dupe of #3564 which has a PR :)

**Closed by ekager** 2018-10-09 22:03 UTC
Labels: bug
