### ISSUE TITLE
Invalid icons of share buttons on Nytimes video section

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#927] opened 2017-07-14 14:09 UTC
Devices:
Huawei Honor 8 (Android 6.0) 
Samsung Galaxy Note 4 (Android 5.0.1)
build: Focus 1.1. Beta Build #2202

Steps to reproduce:
1. Open Focus and go to nytimes.com/video.
2. Scroll down to see the share buttons under each video.

Expected results:
The sharing icons are displayed.

Actual results:
There are invalid icons under the video titles. See screenshot:

![screenshot_2017-07-14-16-50-28](https://user-images.githubusercontent.com/4037709/28214966-fe618230-68b4-11e7-95db-e496f2e38108.png)

**Comment by npark-mozilla** [comment] 2017-07-14 14:54
I actually saw this as well in www.thestar.com site occasionally. (It shows chinese character instead of a graphical icon).  This goes away when I reinstall the app, and it's not clear when the icon gets replaced with asian chars.

**Comment by pocmo** [comment] 2017-07-14 14:57
What trackers are you blocking in settings? This is often caused by blocking web fonts.

**Comment by npark-mozilla** [comment] 2017-07-14 15:00
Icons that gets replaces with asian chars are usually social media icons (facebook, twitter, etc.) and I just confirmed that blocking web fonts causes it on thestar.com.  (perhaps a warning would be nice?)

**Comment by pocmo** [comment] 2017-07-14 15:04
Yeah. There's also #834 for improving the explanations.

**Comment by sv-ohorvath** [comment] 2017-07-14 15:04
Turned off all trackers in Settings and this still occurs.

**Comment by npark-mozilla** [comment] 2017-07-14 15:06
hmm, sv-orhorvath is right, this is different from thestar.com issue. chinese chars show when web font blocking is disabled.

**Comment by pocmo** [comment] 2017-07-14 15:07
Oh, right. And it doesn't happen on Chrome.

**Comment by mcomella** [comment] 2017-07-14 18:15
I think the problem is we're blocking cookies: I can reproduce on Chrome with cookies disabled.

**Comment by npark-mozilla** [comment] 2017-07-14 19:17
on iOS, it just doesn't display anything where icons should be- we should file a mirror bug in iOS as well

**Comment by ekager** [comment] 2017-07-14 22:09
I fixed this by enabling dom storage in settings in WebViewProvider. Is this something that we would want to do in general? Not sure what else dom storage is used for, but I assume we clear it with WebStorage.getInstance().deleteAllData() ?

**Comment by ekager** [comment] 2017-07-14 23:22
Here's some more information I found about dom storage API. I am not sure if there are any security concerns or extra steps we would have to take to clear storage after the session. I think WebStorage.getInstance().deleteAllData() would take care of this? 

https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API
http://viralpatel.net/blogs/introduction-html5-domstorage-api-example/

**Comment by pocmo** [comment] 2017-07-17 12:41
@ekager I wrote an automated test to make sure we are clearing the session store after every session (Set you as a reviewer). This test passes with your patch: We store and keep the value and remove it after the session has been erased. Can you create a PR for your patch? :)

**Comment by pocmo** [comment] 2017-07-17 14:18
Merged!

**Closed by pocmo** 2017-07-17 14:18 UTC
Labels: bug, v1.1, webview
