### ISSUE TITLE
The original searched term is not present in the URL bar after a search is executed

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/focus-android#4400] opened 2019-10-10 11:09 UTC
## Steps to reproduce
1. Open Firefox Focus.
2. Tap in the URL bar.
3. Insert "hello" and make the search.
4. Tap on URL bar.
### Expected behavior
"hello" world is displayed in the URL bar and is highlighted.
### Actual behavior
The searched word is not displayed. The URL bar displays "https://www.google.com?search?=hello..."
### Device information

* Android device: Google Pixel 2
* Focus version: Focus / Klar - v8.0.22

**Comment by Abhisek2090** [comment] 2019-10-10 14:57
I'd like to work on it.

**Comment by sv-ohorvath** [comment] 2021-03-24 13:27
The bug is still reproducing but only with the other search engines, not with Google.
Build: master 8.13.1

**Comment by lobontiumira** [comment] 2021-09-21 07:32
Reproducible on 93.0.3 Focus build with Lenovo Tab M10 (Android 10), and OnePlus 5T (Android 10).

**Comment by lobontiumira** [comment] 2021-09-29 11:35
Reproducible on RC 93.1.0 with Lenovo Tab M10 (Android 10).

**Comment by lobontiumira** [comment] 2021-11-04 08:11
Reproducible on Beta 95.0.0-beta.1 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment] 2022-01-12 09:20
Reproducible on Beta 97.0.0-beta.1 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment] 2022-03-10 07:38
Reproducible on Beta 99.0.0-beta.1 with Xiaomi mi4i (Android 5.0.2).

**Comment by lobontiumira** [comment] 2022-04-06 07:23
Reproducible on Beta 100.0.0-beta.1 with Lenovo Tab M10 (Android 10).

**Comment by lobontiumira** [comment] 2022-04-19 06:10
Reproducible on Focus Nightly 101.0a1 from 4/19 with Oppo Find X3 Lite (Android 11).

**Comment by jonalmeida** [comment] 2022-06-16 11:07
This bug is a lot bigger than just being on Focus and needs to be fixed in AC carefully. If the search term triggers a redirect, like the cookie consent page or the search engine itself redirects, it clears out the search term from the toolbar.

The bug will always be seen in EU countries as a result because of the consent banner.

**Comment by ionutbedregeanu** [comment] 2022-06-16 11:48
Yeah, this happens every time with google engine selected. 
From what I noticed Fenix it behaves as expected with Ebay, DuckDuckGo, etc. but on the other side, Focus searchTerms still remains empty even if `requireComponents.store.dispatch(ContentAction.UpdateSearchTermsAction(tabId, searchTerms))` is called and I don't know yet why

**Comment by jonalmeida** [comment] 2022-06-16 17:34
Interesting - in Fenix they used to use a separate toolbar and did some different behaviour. I thought that code was removed so that we had a consistent experience.

**Comment by Mugurell** [comment] 2022-06-17 05:37
Also saw this.
Fenix will have two toolbars in layout:
- one still containing the full URL. Set to "gone" in Fenix, "visible" in Focus
- one shown from `SearchDialogFragment` which shows the search terms. This functionality does not exist in Focus.

So it seems like we have two issues on Focus:
- the search terms not appearing after a search redirect (also exists as an issue on Fenix). This scenario probably wasn't easy to get into in 2019 when this issue was filed.
- the search terms not appearing at all while they do appear on Fenix. 
While having a fix in AC for both browsers that seems like a bigger change (and refactoring in all 3 projects) so maybe Focus could also look into using a new toolbar / search UX similar to the approach from Fenix. 
At least as a temporary solution, until the UI is migrated to Compose and the whole functionality can be rethought?

**Comment by ionutbedregeanu** [comment] 2022-06-17 12:20
I'm a bit confused.
I found the [pull request](https://github.com/mozilla-mobile/android-components/pull/3454) which updates the searchTerms to an empty string if the request is triggered by redirect(as you said in the above comment, @jonalmeida)
By making some debug on this ticket scenario I noticed that `triggeredByRedirect = true` and searchTerms is updated to ""
These being said my question is: Is this scenario, from ticket specs, expected?

**Comment by ionutbedregeanu** [comment] 2022-06-20 14:29
Fenix shows the searched term only when DuckDuckGo is used, for the rest of engines it behaves as Focus, it redirects the request and shows the url
Focus doesn't show the searched terms for DuckDuckGo because is added as [exception](https://github.com/mozilla-mobile/focus-android/blob/8e8944dd3224ce3defa07f413552fbb1f8498b0e/app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt#L342), so it redirects the request for all engines
Now my question is: Which one is the expected behaviour?
^^ @amedyne @jeffreygee

**Comment by amedyne** [comment] 2022-06-21 15:31
Based on discussion today, we clarified that the behavior should be changed for Focus and follow Fenix.  The exception was implemented before and should have been changed after the fix in GeckoView.

**Comment by lobontiumira** [comment] 2022-06-23 08:38
Verified as fixed on the latest Focus Nightly builds 103.0a1 from 6/23 with the following devices:
- Google Pixel (Android 10),
- Sony Xperia Z5 Premium (Android 7.1.1),
- Samsung Galaxy Tab A6 (Android 5.1.1), and
- Xiaomi mi4i (Android 5.0.2).

On the Android 5 devices, there is a crash when trying to search a term/URL. Filed #7269. Might be a regression.

**Closed by lobontiumira** 2022-06-23 08:38 UTC
Labels: bug, QAReady
