### ISSUE TITLE
Intermittent UI test failure - < EnhancedTrackingProtectionSettingsTest. blockAdTrackersTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7751] opened 2022-09-26 16:53 UTC
### Firebase Test Run: 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6901192661223762107/executions/bs.f0f1869153442ace/testcases/2)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6901192661223762107/executions/bs.2a6e5257697d88d0/testcases/2)

### Stacktrace: 
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyTrackingProtectionAlert(BrowserRobot.kt:54)
	at org.mozilla.focus.activity.EnhancedTrackingProtectionSettingsTest$blockAdTrackersTest$4.invoke(EnhancedTrackingProtectionSettingsTest.kt:90)
	at org.mozilla.focus.activity.EnhancedTrackingProtectionSettingsTest$blockAdTrackersTest$4.invoke(EnhancedTrackingProtectionSettingsTest.kt:89)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.EnhancedTrackingProtectionSettingsTest.blockAdTrackersTest(EnhancedTrackingProtectionSettingsTest.kt:89)

**Comment by AndiAJ** [comment] 2022-09-26 16:54
Disabled in #7737

**Comment by AndiAJ** [comment] 2022-10-07 12:38
Can't re-enable it due to https://github.com/mozilla-mobile/focus-android/issues/7821

**Comment by sv-ohorvath** [comment] 2022-11-21 11:17
Closing as dupe of https://github.com/mozilla-mobile/focus-android/issues/7816

**Closed by sv-ohorvath** 2022-11-21 11:17 UTC
Labels: eng:ui-test, eng:intermittent-test, eng:disabled-test
