### ISSUE TITLE
[L10N] The "Theme" section in General is not translated

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5679] opened 2021-10-21 08:34 UTC
## Steps to reproduce
1. Change your device language to any language.
2. Go to Settings ->General.
3. Notice that the "Theme" section is not translated.

### Expected behavior
The "Theme" section title and the 3 options should be fully translated in the language of the device/selected language from app.

### Actual behavior
The "Theme" title and the 3 options remain displayed in default English language.
Please note that the strings are localized on https://pontoon.mozilla.org/ and the section is translated on the debug build from main. 
Entering this ticket for visibility.

### Device information
* Android device: all.
* Focus version: Beta 94.0.0-beta.2 (build 352922038 GV 94.0-20211017185800).
![Screenshot_20211021-110523](https://user-images.githubusercontent.com/89388888/138241262-fac38296-b70a-4f86-a080-bea2a01e4b12.jpg)

**Comment by lobontiumira** [comment] 2021-11-03 09:29
On Beta 95.0.0-beta.1 the issue is reproducible on Romana (Romanian) language with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment] 2021-12-14 09:44
Reproducible on Beta 96.0.0-beta.2 with Wolof, and Romanian languages.

**Comment by lobontiumira** [comment] 2021-12-29 10:52
Closing the ticket as per the comment above.

**Closed by lobontiumira** 2021-12-29 10:52 UTC
Labels: bug, l10n

**Comment by lobontiumira** [comment] 2022-01-11 15:56
I was able to reproduce this on Japanese on RC 96.1.1:

![Screenshot_20220111-174044](https://user-images.githubusercontent.com/40694158/148976456-c544d658-0323-4c74-bfc4-44179ccd1a7e.png)

**Comment by lobontiumira** [comment] 2022-02-08 13:32
Reproducible on Beta 97.0.0-beta.6 with Lenovo Tab M10 (Android 10):

![Screenshot_3](https://user-images.githubusercontent.com/40694158/152997291-b53d105b-98f3-401f-bc3a-2a38d4acee38.jpg)

**Comment by Delphine** [comment] 2022-02-08 19:22
This hasn't been localized yet in Japanese: https://pontoon.mozilla.org/ja/focus-for-android/mozilla-mobile/focus-android/app/src/main/res/values/strings.xml/?search=theme&string=233021
Please see my comment [earlier above](https://github.com/mozilla-mobile/focus-android/issues/5679#issuecomment-994069998) on how to check this on Pontoon directly for all locales.
(but note I did get the locale code wrong in the initial comment: I put wolof "wo", instead of Persian "fa" :)
