### ISSUE TITLE
Address GDPR changes in product, e.g onboarding (A/B test)

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#2327] opened 2018-03-19 17:45 UTC
Why
- Signal to user that our product is already hel

What

Acceptance Criteria (how do I know when I’m done?)

-----

Enforcement date: May 25.

We will be doing some comms related stuff to highlight how Klar has been an app that supports most of the GDPR regulations. 

Some ideas
- GDPR badge somewhere during onboarding?
- Onboarding 1 slide update how Klar + GDPR work well together
- 80/20 A/B test with 80% of users receiving the info

**Comment by brampitoyo** [comment] 2018-03-19 22:49
Just to be aware that UserTesting doesn’t allow us to recruit test respondents living in Germany specifically:
 
<img src="https://user-images.githubusercontent.com/51007/37626356-90486ff4-2c34-11e8-8171-9799fe745a09.png" width="568">

**Comment by pocmo** [comment] 2018-03-20 10:45
https://www.eugdpr.org/

**Comment by bbinto** [comment] 2018-03-20 11:34
pinging @BrianNJones to provide a heads-up that's coming

**Comment by bbinto** [comment] 2018-03-20 12:08
Some background: 

Firefox Klar is a product worth featuring in the course of the GDPR implementation in order to provide users with a better understanding of the overall matter and improve their knowledge about personal data and privacy. At the same time, making the connection between Klar and GDPR enables us to draw attention to the product and our mission while, at the same time, demonstrating expertise on this highly topical policy issue.

Goal:
Define Klar as THE GDPR-optimized mobile browser/mobile browser product for 2018, for privacy enthusiasts as well as people who don’t want to rack their brains about the consequences of sharing personal data (because with Klar, they just don’t share any while enjoying a high-quality browsing experience)

**Comment by bbinto** [comment] 2018-03-20 12:09
@Sdaswani we might have to consider doing something light and quick for iOS as well.

**Comment by Sdaswani** [comment] 2018-03-20 22:00
If so @bbinto we need to figure out _who_ can do this work.

**Comment by brampitoyo** [comment] 2018-03-21 00:47
Examples of some  quick things we can do, which will apply to both iOS and Android:

* Add a menu item on settings (under the Mozilla section) called something like “Firefox Focus is GDPR-optimised”. When tapped, link to a SUMO article about GDPR launches.
* Add a new item in onboarding (for new users) or a single-page onboarding (just once, for existing users – but be aware that they may complain, too) saying that we support Privacy by Design and the Right to be Forgotten.
* Put some information about GDPR under the “What’s New” SUMO article, then subtly alert user about what’s new (I think we currently flag the menu icon with a purple dot? Only on Android?).

**Comment by bbinto** [comment] 2018-03-21 11:08
I think doing all would be great. @brampitoyo, do expect a lot more work if you'd UI this for iOS as well? @Sdaswani could ask Joey to help with iOS eng

**Comment by BrianNJones** [comment] 2018-03-21 16:25
There's quite a bit to think about here in terms of context. This feels like an awareness campaign inside the app; that may collide with users who expect to feel "invisible" inside Klar. Think we need to define goals for what we want to accomplish with this in-app messaging and work back from there. @bbinto, will comms and marketing be collaborating on this? If so, we should be involved in that.

**Comment by Sdaswani** [comment] 2018-03-21 16:26
Flagging @st3fan as this may be a good opportunity for his team to pick up Focus iOS work.

**Comment by brampitoyo** [comment] 2018-03-22 03:18
@bbinto I would like iOS and Android to be in sync in terms of any marketing message we show them.

My concern with iOS is that deploying these messages (even if only to the `de` locale) will require us to trigger a new app store update. I’m afraid that downloading an update solely to get a message without actually getting any new features or bugfixes will draw ire.

Otherwise, I do agree with @BrianNJones. For us, GDPR is about awareness and marketing rather than any specific privacy feature.

Do you think that it’s a good idea to loop in the Marketing and Communications team? For instance, they may already plan a snippet in the `de` Firefox that will promote Focus app, or promote Private Browsing. They may also plan an online communication strategy (Twitter/Facebook posts) with the same message, that will promote our product.

I’m not sure if they’re planning a marketing message test in the German/European market. It never hurts to ask, because it would be nice if Focus can be included!

**Comment by bbinto** [comment] 2018-03-22 15:21
@brampitoyo and @BrianNJones thanks for your comments and concerns.

- I don't think we will make Klar iOS users upset with an update that makes them potentially "feel safer"
- I don't think including this awareness piece inside the app will collide with users who expect to feel "invisible" inside Klar. To me it's the same as any update or feature announcement inside the app.
- This idea is actually a result of a chat I initiated with our comms and policy team in US, DE and Europe (Marshall, Reagan, Alice) (I've added you to the comms plan document, Brian)
- The "block 3rd party cookies feature" #2330 is an additional feature that Marshall recommended to make our app more private

User story:
As a user, I want to feel confident that Klar covers all aspects of the GDPR changes

Goal:
Convey to the user that Mozilla especially Klar has been GDPR "approved" already, and we didn't have to make any major changes, remind them how we deal with privacy (iOS + Android), and for Klar Android specifically, we've even added another helpful protection feature to the product (#2330)

**Comment by Sdaswani** [comment] 2018-03-23 20:24
@brampitoyo just getting a status check - is the UX for this work done or do you still need time to finalize mocks?

**Comment by brampitoyo** [comment] 2018-03-26 01:55
@Sdaswani Although the implementation details are pretty straightforward, we have yet to write, user test or finalise the GDPR-specific strings The work on this issue will still need time.

**Comment by Sdaswani** [comment] 2018-03-26 04:19
Understood @brampitoyo so then should this be assigned to you?

**Comment by brampitoyo** [comment] 2018-03-26 22:52
Yes. Thanks for the reminders! Although note that we will have to perform user testing in Germany for these messages, and I won’t be able to do it.

**Comment by Sdaswani** [comment] 2018-03-26 22:54
@brampitoyo you mean you need some from UR to help you with user testing? @lime124 any tips on how Bram can get help with that?

**Comment by bbinto** [comment] 2018-04-01 19:14
@brampitoyo, I don’t think we need/should do UR / use usertesting.com for this. 

I know we can do a coin flip thingy for iOS Klar, but I assume doing a/b on boarding test for Klar Android might not be possible, @sdaswani?

**Comment by Sdaswani** [comment] 2018-04-02 05:26
I think it's possible - we can probably do a 'better coin flip' (use client id to put use in a bucket) via the telemetry library. It's something to talk to @pocmo about and @boek and @ekager can handle the implementation.

**Comment by pocmo** [comment] 2018-04-11 13:35
Yeah, we can hack something together for this. Especially as onboarding is a one-time thing I'm less concerned about having a temporary solution for that.

**Closed** 2018-04-26 15:15 UTC
Labels: P2, UX, feature, needs strings
