### ISSUE TITLE
Compare website loading performance on Webview vs. GeckoView

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2201] opened 2018-03-01 20:57 UTC
We need to create Espresso tests that compares the loading time of popular websites (100 or so) on FocusWebviewDebug vs. KlarGeckoViewDebug build variant. 

James Wilcox says the measurement should be made between GeckoView's Onpagestop and Onpagestart, (supposedly they are being used by progresslistener) and the counterparts on Webview.

@pocmo , @ekager what would be the best way to detect above two signals on Espresso test?  James suggested waiting on callbacks, and if that's the case, I would need to find out how to do that on a test.  If we're going to use callbacks, then I'll probably need to wait for it with a custom implementation of Custom Idling Resources.

**Comment by npark-mozilla** [comment] 2018-03-05 20:40
- [ ] Add bookends in the client code
- [ ] Create UI Test scripts 
- [ ] Update taskcluster script to submit master builds to nimbledroid

**Comment by Sdaswani** [comment] 2018-06-01 17:29
a dupe of something that was closed. closing.

**Closed by Sdaswani** 2018-06-01 17:29 UTC
Labels: automation, testing
