### ISSUE TITLE
Open with a Chromium browser is broken, open with not listing all installed browsers

### ISSUE THREAD

**Issue by codebam** [mozilla-mobile/focus-android#2074] opened 2018-01-29 19:34 UTC
I'd like to be able to open externally in chromium, chromium swe, chrome, or another webview based browser.

I understand that maybe it's set to only allow opening externally in Mozilla based browsers when they're installed for market share reasons or whatever, but to be honest Firefox for Android right now is really slow and buggy.

I'll do the pull request myself or maintain my own fork if someone tells me where to look to change this.

**Comment by mcomella** [comment] 2018-01-29 23:02
Focus currently supports this: Settings -> Open with...

I think you meant to file this against Firefox for Android so I filed this for them: https://bugzilla.mozilla.org/show_bug.cgi?id=1434097

**Comment by codebam** [comment] 2018-01-30 01:38
I didn't make a mistake. When Focus is set to the default browser it's not possible to open in an external browser other than one with "Firefox" in the name.

**Comment by codebam** [comment] 2018-01-30 02:08
Wait I'm not wrong. I can't open in Chromium

**Comment by codebam** [comment] 2018-01-30 02:10
Steps to reproduce:

1. Install Focus, Chromium/Chromium CAF, and any other Firefox variant or chrome
2. Set Focus as your default browser
3. Open a link in Focus and click Open with

Result: Chromium browsers aren't listed
Expected Result: All browsers on the system would be listed

**Comment by buttercookie42** [comment] 2018-01-30 08:26
In theory it seems like [this should already handle that case](https://github.com/mozilla-mobile/focus-android/blob/0fa19ab7e88797228919f6df08610ad049082a7f/app/src/main/java/org/mozilla/focus/utils/Browsers.java#L86), although it only works with [a hard-coded list of known browsers](https://github.com/mozilla-mobile/focus-android/blob/0fa19ab7e88797228919f6df08610ad049082a7f/app/src/main/java/org/mozilla/focus/utils/Browsers.java#L26-L56). At least Chrome should work though, so something is probably broken here?

On a side note I'd like to add that hard-coding and maintaining a list of known browsers might not actually be necessary - https://github.com/tasomaniac/OpenLinkWith manages to offer the full list of apps supporting a particular link regardless of the current default app settings.

**Comment by Sdaswani** [comment] 2018-01-30 14:23
Thanks for the bug report @codebam and suggestion @buttercookie42 - we will triage this soon and get it fixed up.

**Comment by pocmo** [comment] 2018-02-20 13:56
https://github.com/tasomaniac/OpenLinkWith/blob/master/app/src/main/java/com/tasomaniac/openwith/redirect/BrowserIntentChecker.kt

**Comment by Sdaswani** [comment] 2018-03-27 18:25
Thanks @pocmo for the possible solution here: https://github.com/mozilla-mobile/focus-android/issues/2074#issuecomment-366984673

If a contributor can do some investigation and see if it works, that would be great. Please ping @sdaswani if you need more details.

**Comment by kai-chi** [comment] 2018-05-28 19:49
what is the status of it? I'd like to take that but I can't reproduce the issue on my phone. I've tried with a plethora of browsers and they all get listed. Is there any specific that I can try with?

Phone: Huawei p10 lite
Android: 7.0
Focus: 5.0

**Comment by Sdaswani** [comment] 2018-05-29 04:32
@codebam any advice on how to repro? Maybe @npark-mozilla has reproduced this?

**Comment by codebam** [comment] 2018-05-29 08:10
@Sdaswani I put fairly clear steps in the 3rd comment from the top. Is there something else you need?

**Comment by codebam** [comment] 2018-05-29 08:21
Yeah okay, I just reproduced it. Using [chromium-caf](https://forum.xda-developers.com/android/apps-games/app-chromium-snapdragon-t3600159) and [chromium](https://chromium.woolyss.com).

I'd assume other browsers on F-Droid and the like are unsupported as well.

Expected behavior would be that all browsers would be supported, not just the ones that are whitelisted

**Comment by kai-chi** [comment] 2018-05-29 08:55
@codebam, I went through all the steps with chromium-caf and everything works. The browser is listed and opens any link. 
Also, other browsers that I downloaded and are not in the hardcoded list are visible - Kiwi, Yu, Brave...

**Comment by pocmo** [comment] 2018-05-29 14:12
> I went through all the steps with chromium-caf and everything works. The browser is listed and opens any link.

This depends on the Android version. On some versions the system query we use returns all browser and on some it does not (that's why we check against our hard-coded list).

**Comment by kai-chi** [comment] 2018-05-30 08:09
@pocmo, is it a known list of Android versions that doesn't list all the browsers?
@codebam, can you write your configuration so I can try it on a simulator?

**Comment by codebam** [comment] 2018-05-30 08:49
@kai-chi I'm currently on Android P Preview on Pixel XL, but I had this issue back in January on 8.1 as well

**Comment by pocmo** [comment] 2018-05-30 09:35
It should be Android 6+. This blog posting describes the issue we have been seeing:
https://medium.com/google-developer-experts/intent-resolving-in-android-m-c17d39d27048

**Comment by codebam** [comment] 2018-05-30 20:57
So from my understanding all Android versions from 6.0 have issues querying the list of browsers using the method that's in Focus? @pocmo 

Can the new method be used instead as explained in that article?

**Comment by kai-chi** [comment] 2018-06-06 08:44
apparently not all because I don't have this problem with 7.0.

I couldn't reproduce the issue on my phone, nor the emulator so if anyone else with a different device is keen on taking it then feel free. I could take it once I'll have another device to test

**Comment by buttercookie42** [comment] 2018-06-10 15:32
@kai-chi AFAIK you need to have set a default browser in order to observe that behaviour. Is that true in your case?

**Comment by kai-chi** [comment] 2018-06-10 21:45
@buttercookie42 yes, Focus is set as the default browser and I still get listed the other browsers
here are my screens: https://imgur.com/a/JHRVhnf

**Comment by TPS** [comment] 2019-09-08 14:35
Could this be expanded to _all_ native apps to handle the URL?  That would fall inline w/ @tasomaniac  _(Would you be interested in helping out?)_ [OpenLinkWith](https://github.com/tasomaniac/OpenLinkWith)'s handling (https://github.com/mozilla-mobile/focus-android/issues/2074#issuecomment-361511952 & https://github.com/mozilla-mobile/focus-android/issues/2074#issuecomment-366984673) of such, while not leaking ifF, e.g., OpenWith were to be natively incorporated.

**Comment by tasomaniac** [comment] 2019-09-10 06:26
@TPS thanks for mentioning me here. @pocmo I believe the behavior described in my blog post has been changed after some API level. At least at API level 27+, Android now returns all apps if you use MATCH_ALL flag. That's what I observed at least while working on Open Link With.

**Comment by pocmo** [comment] 2019-09-10 15:11
Thank you @tasomaniac!

I filed this as an issue in our Android Components repository:
https://github.com/mozilla-mobile/android-components/issues/4369

As part of this issue we should migrate Focus to use the component instead of its own implementation.

**Comment by tasomaniac** [comment] 2019-09-12 06:24
Sounds good

**Comment by TPS** [comment] 2019-10-16 01:34
The recent versions (IDK whether beta or actual release) I've downloaded seem to do this quite well.  Does anyone else see anything different anymore for > v. 8.0.22?

**Closed** 2022-04-21 18:59 UTC
Labels: help wanted, P3, wontfix
