### ISSUE TITLE
Page title not included in share

### ISSUE THREAD

**Issue by jfmcbrayer** [mozilla-mobile/focus-android#1252] opened 2017-08-30 18:51 UTC
When you share from Fennec to another app, the page title is available to the receiving application as well as the URL. So a mail app can use the title in the Subject field, or a social media app can format the link "The example page: https://www.example.org/".

When sharing from Focus, only the URL is shared.

This is a superset of #1154: I just wanted to make it clear that not only email apps are affected.

**Comment by pocmo** [comment] 2017-09-04 09:08
Thank you for filing this. The mechanism used to fix #1154 should work for all kind of apps. I'll close this as a duplicate of #1154 and link both bugs.

**Closed by pocmo** 2017-09-04 09:08 UTC
