### ISSUE TITLE
Turning the screen on to the finger printer dialog crashes the app

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#4160] opened 2019-01-20 14:48 UTC
## Steps to reproduce
1. Enable finger print support
2. Go to any website (e.g. reddit.com)
3. Switch out of the app
4. Come back to Focus and observe the fingerprint dialog.
5. Turn the screen of/on.

### Expected behavior
After step 5, the finger print dialog should be visible when the phone screen is turned back on.

### Actual behavior
The browser crashes and the crash reporter is seen.

### Device information

* Android device: Android 9 (Pixel 2)
* Focus version: 9.0 (Build #330191217 :lizard: 65.0.20190114172331)

Maybe related to #4086

**Comment by KWierso** [comment] 2019-01-24 02:01
Came here to report this. I can reproduce, also on a Pixel 2 running android 9. 

For me, step 5 has to be "unlock with the fingerprint reader" to turn the screen back on. If I just push the power button and unlock with the gesture, it seems to work okay. Focus reopens and says something like "fingerprint timed out" below the fingerprint image.

**Comment by lobontiumira** [comment] 2021-07-09 12:07
I was not able to reproduce the crash on the 8.17.0 build with Google Pixel (Android 10).
I'll close this issue.

**Closed by lobontiumira** 2021-07-09 12:07 UTC
Labels: crash 🔥
