### ISSUE TITLE
Attempting to change search providers crashes

### ISSUE THREAD

**Issue by lexcyn** [mozilla-mobile/focus-android#1784] opened 2017-11-22 19:35 UTC
Building via the latest code from git. If you go into Settings and select Search, it will force close and crash Focus. You cannot change the search provider.

**Comment by pocmo** [comment] 2017-11-23 08:19
* Are you building the focusWebviewDebug variant?
* What's the stacktrace of the crash?

**Comment by lexcyn** [comment] 2017-11-23 13:59
I'm building the Beta variant. I will get a stacktrace for you later today.

**Comment by bbinto** [comment] 2017-11-28 16:57
Is this related to this #1819 , @lexcyn ?

**Comment by lexcyn** [comment] 2017-11-28 18:23
@bbinto yes that seems to be the same info. I was not able to get a stacktrace of the issue on my phone but that seems to be what's happening. Can you merge this into that issue?

**Comment by pocmo** [comment] 2017-11-28 19:15
Closing as duplicate of #1819

**Closed by pocmo** 2017-11-28 19:15 UTC
