### ISSUE TITLE
Add "Paste & Go" context menu to URL entry

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#125] opened 2017-02-28 18:33 UTC
Similar to what fennec does: a "paste & go" context menu item would be nice to have, for URL entry both on the main screen, and when browsing. (This is probably primarily useful while testing, I'm not sure if there's much value for typical users.)

We should check fennec telemetry (if available) to see whether "paste & go" is regularly used there.

**Comment by pocmo** [comment] 2017-03-01 15:24
For testing you could also add an additional run configuration to Android Studio that starts the app with a VIEW intent.

**Comment by pocmo** [comment] 2017-03-15 17:02
For testing I added in Android Studio an additional Run Configuration with Launch Flags: "-a android.intent.action.VIEW -d https://www.mozilla.org"

**Comment by Sdaswani** [comment] 2017-03-22 05:08
Sorry for the newb question, but how can I access the 'Paste & Go' menu is Firefox for Android?

**Comment by pocmo** [comment] 2017-03-30 11:06
We moved the string freeze and release date. I landed a "Paste & Go" string (R.string.context_menu_paste_go) as part of PR #361. So this feature could land in v1.

**Comment by Sdaswani** [comment] 2017-03-30 16:14
Dropped my assignment in case someone else wants to pick it up for v1.

**Comment by ahunt** [comment] 2017-05-11 17:05
I've got patches which add this to the home screen. That leaves the actual browser screen. We could show the same context menu (which is what firefox does), or we could try using Chrome's behaviour (long-press expands the URL bar into editing mode AND triggers the text copy/paste/etc menu - that doesn't have a paste & go option though).

**Comment by bbinto** [comment] 2017-06-07 17:15
![](https://github.trello.services/images/mini-trello-icon.png) [Add "Paste & Go" context menu to URL entry](https://trello.com/c/Dsb93LHs/46-add-paste-go-context-menu-to-url-entry)

**Comment by ekager** [comment] 2017-06-12 20:21
Hi @ahunt ! Were you working on this specific issue for the non-testing features? If so could you push all of the code to a branch?
I started to work on the issue before seeing this thread, as I was working off of this description/specs https://bugzilla.mozilla.org/show_bug.cgi?id=1310265

**Comment by pocmo** [comment] 2017-06-12 22:01
There's a pull request with the code open. It's waiting for testing and reviewing after v1 has been released.

**Comment by antlam** [comment] 2017-07-03 06:08
@bbinto did we forget to include this in V2? if not, feel free to remove the 'needs triage' label :)

**Comment by pocmo** [comment] 2017-07-03 08:39
@antlam If we re-structure the UI so that the keyboard is always up by default then we would not need this, I think? You could just long-press the input and get an overflow toolbar with paste etc.

**Comment by antlam** [comment] 2017-07-05 16:28
@pocmo good point. we could hold off on this for now.

**Comment by hackel** [comment] 2018-05-11 00:04
Just wanted to add that I'm a "typical user" and this feature is definitely missed when using Focus.  Sure, it's just one or two extra clicks, but on mobile that's a big deal, since it involves hunting for the enter button, moving your finger all the way to the bottom of the (increasingly larger) display, etc.

**Comment by bbinto** [comment] 2018-08-17 12:50
@brampitoyo let me know your take on this, please

**Comment by brampitoyo** [comment] 2018-08-20 05:56
@bbinto We can do either one of these ideas, or both of them:

1. Add a context menu item called “Paste & Go” (if clipboard contains URL) or “Paste & Search” (if clipboard contains non-URL string), in both of these situations:
    * When the URL bar is currently in Focus
    * When the URL bar is not in Focus (there’s already a context menu here. It contains “Copy” and “Add Custom URL”. We will add either “Paste & Go” or “Paste & Search” depending on the clipboard content.

2. Show clipboard URL as user starts typing (#1118).

Both of these solutions solve the same problem (“I have a URL ready to go. I don’t want to have to hunt for the ‘Enter’ key”), and I recommend doing them.

**Comment by ekager** [comment] 2018-09-12 23:12
@EmmanuelMess are you working on this?

**Comment by EmmanuelMess** [comment] 2018-09-13 00:09
@ekager Ok, I ran out of ideas, `onCreateContextMenu` doesn't seem to work correctly (when in a subclass of `InlineAutocompleteEditText` doesn't get called) and an `ActionMode` for this doesn't really make sense. 

You can assign yourself to this if you want.

**Comment by ekager** [comment] 2018-09-13 23:04
After doing some investigation today I'm not sure that the first context menu bullet is possible/desired in active state as mentioned above @brampitoyo . We can override the system context menu from appearing and replace the behavior with our own menu, but from what I can tell, I don't think we can add our menu items to theirs. I'm not sure we should override the system menu; it could have unexpected behavior for the user. You'll notice Chrome, Fennec, etc do not override this menu when the URL bar is focused (typing state). If we were to override it, it *would* be possible to create a context menu that contains "Paste" and "Paste + Go"/"Paste + Search", but again, I'm not sure if we should do this.

The second bullet is more straightforward, we can add "Paste+Go" and "Paste+Search" to the long press on the URL Bar (when inactive) along with the existing "Add Custom URL" for autocomplete quick add.

Let me know how you want to proceed.

**Comment by EmmanuelMess** [comment] 2018-09-14 01:35
> The second bullet is more straightforward, we can add "Paste+Go" and "Paste+Search" to the long press on the URL Bar (when inactive) along with the existing "Add Custom URL" for autocomplete quick add.

It seems that this is less intuitive for the user to find. I think that the context menu is more intuitive and looks better. I think that some more "hacky" approach would be warranted for this feature.

**Comment by EmmanuelMess** [comment] 2018-09-19 04:03
@brampitoyo Done, thanks for your input!
Updated screenshots:

<img src="https://user-images.githubusercontent.com/10991116/45730327-6009fd00-bba7-11e8-9a35-fa69f77ba25d.png" width="200px"/> <img src="https://user-images.githubusercontent.com/10991116/45730326-6009fd00-bba7-11e8-98cf-8e0c7f35b466.png" width="200px"/> <img src="https://user-images.githubusercontent.com/10991116/45730325-5f716680-bba7-11e8-8a57-aba6bb4705b0.png" width="200px"/> <img src="https://user-images.githubusercontent.com/10991116/45730323-5f716680-bba7-11e8-9e81-95082719115f.png" width="200px"/> <img src="https://user-images.githubusercontent.com/10991116/45730322-5f716680-bba7-11e8-964c-969441339ce1.png" width="200px"/>

**Comment by ekager** [comment] 2018-09-19 04:15
Hey @brampitoyo just some additional history about this feature and the above option before we make final decisions. IIRC when we added a similar clipboard entry option to iOS we got some user backlash for grabbing and displaying in our views what some users feel is "private". The "Paste + Go" Action is vague, but users may not like the display of what is on their clipboard. We may want to also open the discussion to product.

**Comment by brampitoyo** [comment] 2018-09-19 04:48
Thanks so mcuh for bringing it up, @ekager.

Up to this point, I didn’t know that we received backlash on iOS for showing the content of the clipboard. I thought that this was a feature that will make Firefox Focus even more convenient to use. I didn’t realise that revealing clipboard was a really big deal for so many users.

So it was my mistake for not checking the context first!

Unfortunately, this means that this feature should probably not be shipped on the Release channel.

But like the first commenter wrote, it’s still useful for testing. Is it worth it to make this a Nightly and Beta-only feature?

**Comment by Sdaswani** [comment] 2018-09-19 04:51
We could put it behind a A/B on nightly.

**Comment by EmmanuelMess** [comment] 2018-09-19 15:46
Maybe make it opt-in as with the search suggestions?

**Comment by Poopooracoocoo** [comment] 2019-07-22 04:36
I think it should have a clipboard icon. I'm really used to tapping and holding on the url bar to paste and go

**Closed** 2022-04-23 12:11 UTC
Labels: feature, UX, needs strings, P3, wontfix
