### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by GPHemsley** [mozilla-mobile/focus-android#4300] opened 2019-06-21 11:01 UTC
## Steps to reproduce
1. Open Firefox Focus.
2. Wait a few seconds.

### Expected behavior
Browser stays up and available for interaction.

### Actual behavior
Browser disappears without doing anything.

### Device information

* Android device: 5.1.1
* Focus version: latest? (I just updated)

**Comment by lobontiumira** [comment] 2021-07-09 13:25
I'll close this issue, since I was not able to reproduce it since the 8.13.0 Focus version.

**Closed by lobontiumira** 2021-07-09 13:25 UTC
