### ISSUE TITLE
Show the broken lock icon when visiting a HTTP site

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/focus-android#5369] opened 2021-09-10 18:33 UTC

**Comment by lobontiumira** [comment] 2021-09-17 07:52
@Amejia481, I've encountered a situation on the OnePlus 5T (Android 10) device: trying to access http://permission.site loads an unusable page, trying to load http://muntzomani.ro loads a blank insecure page. Not reproducible on 93.0.2 build.

![OnePlus](https://user-images.githubusercontent.com/40694158/133745295-48640cf6-7a08-486a-8c25-fc98ed26c669.png)

Not reproducible on Samsung Galaxy Note 8 (Android 9), nor on Lenovo Tab M10 (Android 10).
I'll remove the QAReady label for now.

**Comment by Amejia481** [comment] 2021-09-17 13:27
> @Amejia481, I've encountered a situation on the OnePlus 5T (Android 10) device: trying to access http://permission.site loads an unusable page, trying to load http://muntzomani.ro loads a blank insecure page. Not reproducible on 93.0.2 build.
> 
> ![OnePlus](https://user-images.githubusercontent.com/40694158/133745295-48640cf6-7a08-486a-8c25-fc98ed26c669.png)
> [logcat.txt](https://github.com/mozilla-mobile/focus-android/files/7183734/logcat.txt)
> 
> Not reproducible on Samsung Galaxy Note 8 (Android 9), nor on Lenovo Tab M10 (Android 10).
> I'll remove the QAReady label for now.

Is this also reproduceable in Fenix?

**Comment by Nickoriginal** [comment] 2021-09-18 06:37
@lobontiumira do you have JavaScript disabled? Broken error page due to disabled JavaScript is a known issue.
<img src = https://user-images.githubusercontent.com/85299944/133878978-85f289ee-a391-41f3-baeb-fa1bd309a286.jpg width=35%>

**Comment by lobontiumira** [comment] 2021-09-20 07:48
@Amejia481 this does not reproduce on Fenix Nightly 94.a01 from 9/20 with the same device.
But I am unable to reproduce it again on the debug build (352581202 with GV 93.0a1-2021090631657).
Not reproducible on 93.0.3 build either.
I'm closing the issue.

**Closed by lobontiumira** 2021-09-20 07:48 UTC
Labels: E3
