### ISSUE TITLE
Status bar in Onboarding screen is not visible in dark theme

### ISSUE THREAD

**Issue by indurs** [mozilla-mobile/focus-android#6670] opened 2022-03-15 11:04 UTC
## Steps to reproduce

1. Have the latest Focus Nightly installed
2. Set dark theme in device settings
1 & 2 in any order

3. Open Focus Nightly
4. Onboarding screen will be displayed. Observe the status bar

### Expected behavior
Status bar has to be visible in both dark and light themes
### Actual behavior
Status bar is visible only when light theme is set in device settings 
### Device information

* Android device: ? Pixel 3a
* Focus version: ? 100.0

![Screenshot_20220315-064250](https://user-images.githubusercontent.com/12825812/158364220-71ba110e-38ea-4d68-b655-9d856e955737.png)

**Comment by lobontiumira** [comment] 2022-03-15 13:44
I can confirm this issue on the latest Focus Nightly build 360740511 with GV 100.0a1-20220314094248 with Lenovo Tab M10 (Android 10).

**Comment by indurs** [comment] 2022-03-16 06:44
@Mugurell , we can use the accompanist library for Jetpack Compose. It has a SystemUIcontroller library for modifying status bar

Added the following code in OnboardingContent composable
```
       val systemUiController = rememberSystemUiController()
        SideEffect {
            systemUiController.setSystemBarsColor(
                color = Color.Transparent,
                darkIcons = true
            )
        }
```
https://user-images.githubusercontent.com/12825812/158531676-b2a2e35e-5b9b-40dd-9eb5-7107ef3b0514.mp4

**Comment by Mugurell** [comment] 2022-03-16 10:28
@indurs Instead of adding a new dependency I think we can follow their implementation - https://github.com/google/accompanist/blob/b9a44ab8623018e00a49299b6ccbeb33a4ee90ee/systemuicontroller/src/main/java/com/google/accompanist/systemuicontroller/SystemUiController.kt#L115-L128 to only get the functionality we need, specifically suited for our usecase with afterwards us easily being able to easily support and adapt the code when needed.

**Comment by indurs** [comment] 2022-03-16 10:53
Sure, we can do that. I'll make the changes. Thank You

**Comment by indurs** [comment] 2022-03-18 05:56
@ionutbedregeanu , Just wanted to know about the requirement of the status bar  color for onboarding screen.

**Comment by ionutbedregeanu** [comment] 2022-03-18 07:03
Should looks as for light theme. Probably this is a regression of https://github.com/mozilla-mobile/focus-android/issues/6585

**Comment by indurs** [comment] 2022-03-18 07:57
Is it white color?

**Comment by indurs** [comment] 2022-03-18 08:36
Just wanted to confirm its white before making the change..

**Comment by ionutbedregeanu** [comment] 2022-03-18 08:59
> Is it white color?

Should be the color of OnboardingFragment background

**Comment by indurs** [comment] 2022-03-18 09:21
Ok.

**Comment by indurs** [comment] 2022-03-21 10:36
@Mugurell , @ionutbedregeanu, I've made some changes related to status bar for the Onboarding screen. Please let me know your suggestions.
@Mugurell, as you suggested I went through the  accompanist's systemuicontroller library and added/modified the functionality for our usecase.


```
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

package org.mozilla.focus.fragment.onboarding

import android.app.Activity
import android.content.Context
import android.content.ContextWrapper
import android.os.Build
import android.os.Bundle
import android.transition.TransitionInflater
import android.view.*
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.material.Button
import androidx.compose.material.ButtonDefaults
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.SideEffect
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.*
import androidx.compose.ui.platform.ComposeView
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalView
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.dp
import androidx.constraintlayout.compose.ConstraintLayout
import androidx.constraintlayout.compose.Dimension
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsControllerCompat
import androidx.fragment.app.Fragment
import mozilla.components.ui.colors.PhotonColors
import org.mozilla.focus.GleanMetrics.Onboarding
import org.mozilla.focus.R
import org.mozilla.focus.ext.requireComponents
import org.mozilla.focus.ui.theme.FocusTheme
import org.mozilla.focus.ui.theme.focusColors
import org.mozilla.focus.ui.theme.focusTypography

class OnboardingFragment : Fragment() {

    private lateinit var onboardingInteractor: OnboardingInteractor

    override fun onAttach(context: Context) {
        super.onAttach(context)

        val transition =
            TransitionInflater.from(context).inflateTransition(R.transition.firstrun_exit)
        exitTransition = transition
        Onboarding.pageDisplayed.record(Onboarding.PageDisplayedExtra(0))
    }

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        onboardingInteractor = OnboardingInteractor(requireComponents.appStore)
        return ComposeView(requireContext()).apply {
            setContent {
                FocusTheme(darkTheme = false) {
                    val view = LocalView.current
                    val windowInsetsController = ViewCompat.getWindowInsetsController(view)
                    val darkTheme = isSystemInDarkTheme()
                    ### OnBoardingStatusBar(windowInsetsController)
                    OnboardingContent(
                        onboardingInteractor,
                        resetDarkTheme = { resetDarkTheme(windowInsetsController = windowInsetsController,darkTheme = darkTheme) }
                    )
                }
            }
        }
    }

    @Composable
    @Suppress("LongMethod")
    fun OnboardingContent(
        onboardingInteractor: OnboardingInteractor,
       ###  resetDarkTheme: () -> Unit
    ) {

        Box(
            modifier = Modifier
                .background(color = focusColors.secondaryBackground)
        ) {
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .fillMaxHeight()
                    .verticalScroll(rememberScrollState())
                    .background(color = focusColors.background)
                    .padding(top = 72.dp, start = 24.dp, end = 24.dp, bottom = 52.dp),
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                Image(
                    painter = painterResource(R.drawable.onboarding_logo),
                    contentDescription = getString(R.string.app_name),
                    modifier = Modifier.size(60.dp, 60.dp)
                )
                Text(
                    text = stringResource(id = R.string.onboarding_title, stringResource(id = R.string.app_name)),
                    style = focusTypography.onboardingTitle,
                    modifier = Modifier.padding(top = 16.dp, bottom = 20.dp)
                )
                Text(
                    text = stringResource(id = R.string.onboarding_description),
                    style = focusTypography.onboardingDescription,
                    modifier = Modifier.padding(bottom = 20.dp)
                )
                Column(
                    verticalArrangement = Arrangement.spacedBy(20.dp),
                    modifier = Modifier.padding(bottom = 36.dp)
                ) {
                    KeyFeatureCard(
                        iconId = R.drawable.mozac_ic_private_browsing,
                        titleId = R.string.onboarding_incognito_title,
                        descriptionId = R.string.onboarding_incognito_description
                    )
                    KeyFeatureCard(
                        iconId = R.drawable.ic_history,
                        titleId = R.string.onboarding_history_title,
                        descriptionId = R.string.onboarding_history_description2
                    )
                    KeyFeatureCard(
                        iconId = R.drawable.mozac_ic_settings,
                        titleId = R.string.onboarding_protection_title,
                        descriptionId = R.string.onboarding_protection_description
                    )
                }
                Button(
                    onClick = {
                        ### resetDarkTheme()
                        Onboarding.finishButtonTapped.record(Onboarding.FinishButtonTappedExtra())
                        onboardingInteractor.finishOnboarding(
                            requireContext(),
                            requireComponents.store.state.selectedTabId
                        )
                    },
                    modifier = Modifier
                        .width(232.dp)
                        .height(36.dp),
                    colors = ButtonDefaults.buttonColors(backgroundColor = focusColors.onboardingButtonBackground)
                ) {
                    Text(
                        text = stringResource(id = R.string.onboarding_start_browsing),
                        modifier = Modifier
                            .align(Alignment.CenterVertically),
                        style = focusTypography.onboardingButton,
                    )
                }
            }
        }
    }

### 
    @Composable
    fun OnBoardingStatusBar(windowInsetsController: WindowInsetsControllerCompat?){
        val window = LocalContext.current.findWindow()
        SideEffect{
            setStatusBarColor(
                color = Color.Transparent,
                colorAlt = PhotonColors.Ink20A48,
                window = window,
                windowInsetsController = windowInsetsController,
            )
        }
    }
### 

    @Composable
    fun KeyFeatureCard(iconId: Int, titleId: Int, descriptionId: Int) {
        ConstraintLayout(modifier = Modifier.fillMaxWidth()) {
            val (image, title, description) = createRefs()
            Image(
                painter = painterResource(iconId),
                colorFilter = ColorFilter.tint(color = focusColors.onboardingKeyFeatureImageTint),
                contentDescription = getString(R.string.app_name),
                modifier = Modifier.constrainAs(image) {
                    top.linkTo(parent.top)
                    start.linkTo(parent.start)
                }
            )
            Text(
                text = stringResource(id = titleId),
                modifier = Modifier
                    .constrainAs(title) {
                        top.linkTo(image.top)
                        start.linkTo(image.end, margin = 16.dp)
                        bottom.linkTo(image.bottom)
                    },
                style = focusTypography.onboardingSubtitle
            )
            Text(
                text = stringResource(id = descriptionId, getString(R.string.onboarding_short_app_name)),
                modifier = Modifier.constrainAs(description) {
                    top.linkTo(title.bottom)
                    start.linkTo(title.start)
                    end.linkTo(parent.end)
                    width = Dimension.fillToConstraints
                },
                style = focusTypography.onboardingDescription
            )
        }
    }

    companion object {
        const val FRAGMENT_TAG = "firstrun"
        const val ONBOARDING_PREF = "firstrun_shown"

        fun create(): OnboardingFragment {
            val arguments = Bundle()

            val fragment = OnboardingFragment()
            fragment.arguments = arguments

            return fragment
        }
    }

### 
    private fun Context.findWindow(): Window? {
        var context = this
        while (context is ContextWrapper) {
            if (context is Activity) return context.window
            context = context.baseContext
        }
        return null
    }

    private fun setStatusBarColor(
        color: Color,
        colorAlt: Color,
        window:Window?,
        windowInsetsController: WindowInsetsControllerCompat?,
    ) {
        if (Build.VERSION.SDK_INT > Build.VERSION_CODES.M) {
            windowInsetsController?.isAppearanceLightStatusBars = true
            window?.statusBarColor = color.toArgb()
        }else{
            window?.statusBarColor = colorAlt.toArgb()
        }

    }

    private fun resetDarkTheme(
        windowInsetsController: WindowInsetsControllerCompat?,
        darkTheme: Boolean
    ){
        windowInsetsController?.isAppearanceLightStatusBars = !darkTheme
    }
### 


}

```

**Comment by Mugurell** [comment] 2022-03-22 11:28
@indurs Nice work! Seems we are close to have a solution.
I see here that we'd only set a statusBar color but on `accompanist` for such a scenario the navigationBar color is set at the same time. Thinking we should do the same?
To make collaboration easier could you open draft PRs for the proposed changes?
(open PRs as normal, then mark them as draft with an option in the PR page on Github)

**Comment by indurs** [comment] 2022-03-23 02:10
Thank You @Mugurell . I will open a draft PR

**Comment by ionutbedregeanu** [comment] 2022-03-30 13:33
I will close this ticket since dark theme support was implemented
https://github.com/mozilla-mobile/focus-android/issues/6787

**Closed by ionutbedregeanu** 2022-03-30 13:33 UTC
Labels: bug
