### ISSUE TITLE
Downloads Do Not Save With Correct File Extenstion

### ISSUE THREAD

**Issue by gdevitis** [mozilla-mobile/focus-android#1712] opened 2017-11-13 15:55 UTC
For example, if you open this link : 
http://www.giappichelli.it/index.php?znfModule=public&znfAction=loadIndice&idArticolo=11173681
you obtain an "index.pdf" file in Firefox Focus and an "indice_9210787.pdf" file in other mobile/desktop browsers. Is this solvable without changing the security and privacy standards provided by browser?

**Comment by gdevitis** [comment] 2017-11-13 20:48
why "help wanted" label? maybe "bug" label is more correct.

**Comment by mcomella** [comment] 2017-11-30 23:43
> why "help wanted" label? maybe "bug" label is more correct.

"help wanted" means we don't have enough engineering resources to tackle this bug in a timely fashion and so we're requesting help from our contributor community. :)

**Comment by mcomella** [comment] 2017-11-30 23:46
To fix this bug, take a look at the URL given at the top and verify you can reproduce this issue. If it's reproducible, I think Focus is either:
1. Downloading the wrong file
1. Changing the file name when downloading

Figure out what's going wrong and fix the issue! :)

**Comment by pocmo** [comment] 2017-12-01 09:26
Some additional hints:

DownloadUtils is determining the file name based on the content disposition header or if absent based on the URL:
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/utils/DownloadUtils.java

There are unit tests for DownloadUtils. Please extend the unit test to cover this case (assuming the problem is in DownloadUtils):
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/test/java/org/mozilla/focus/utils/DownloadUtilsTest.java

**Comment by siddware** [comment] 2018-01-03 08:13
Thanks for the hints @pocmo :) The problem stems from the fact that the aforementioned URL has inline in its content disposition instead of attachment. As a result, we get a null [here](https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/utils/DownloadUtils.java#L57) and the method resorts to guessing the name instead of using the filename in content disposition. This pattern seems to be [based on WebKit](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/webkit/URLUtil.java) (Line: 387). [A browser](https://github.com/anthonycr/Lightning-Browser) using the same engine suffers from the same issue. But Chrome seems to work fine and so does Firefox(Gecko?). Should we change the pattern to handle inline as well?

**Comment by mcomella** [comment] 2018-01-05 16:57
@siddware Just a few questions to get more context:

> The problem stems from the fact that the aforementioned URL has inline in its content disposition instead of attachment.

What does "has inline in its content disposition instead of attachment" mean? Like, there's an attribute that requests we parse the content disposition from the URL rather than as an http header?

By "change the pattern to handle inline as well", do you mean that if contentDisposition is null [here](https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/utils/DownloadUtils.java#L57), we'd try to pull it out inline (from the URL)?

**Comment by siddware** [comment] 2018-01-05 21:33
Sorry, that was my fault, linked you the wrong line of code. 
[Content Disposition](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) can be either inline or attachment. This is the value that's being returned for the link specified by @gdevitis 
`inline; filename="indice_9210787.pdf"`
The [Pattern](https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/utils/DownloadUtils.java#L138) right now only  supports attachment as of now so the method parseContentDisposition returns null, and filename [here is null](https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/utils/DownloadUtils.java#L58)(which is what I meant to link earlier) and we resort to guessing by URL even though the filename is provided as part of the header.
Hope it gives you a bit more context, let me know if you need anything else :)

**Comment by mcomella** [comment] 2018-01-08 23:03
@siddware Thanks for the thorough explanation!

> Should we change the pattern to handle inline as well?

Yes, sounds good to me!

**Comment by bbinto** [comment] 2018-02-16 13:44
@Sdaswani quick check-in on milestone assignment? Is this done?

**Comment by Sdaswani** [comment] 2018-02-16 14:30
I don’t think it is finished yet - up to you if you want it prioritized in 5.0 @bbinto

**Comment by gdevitis** [comment] 2018-02-16 14:49
I am the one who reported the bug here. I think this bug is important. How long will it be fixed?

**Comment by siddware** [comment] 2018-02-21 07:51
I've submitted a PR #2040 a few weeks ago, will that work?

**Comment by Sdaswani** [comment] 2018-02-21 12:48
@pocmo will probably get around to looking at #2040 soon @siddware .

**Comment by gdevitis** [comment] 2018-04-18 21:37
In Firefox Focus 4.2, the problem is still presente.

**Comment by gdevitis** [comment] 2018-05-23 18:40
In Firefox Focus 5.0, the problem is still present.

**Comment by boek** [comment] 2018-05-23 19:22
Hey @gdevitis, I have this on my list of things for [5.2](https://github.com/mozilla-mobile/focus-android/milestone/23) and should go out in the next release!

**Comment by boek** [comment] 2018-05-25 16:39
closing this in favor of  mozilla-mobile/android-components#229

PR open: https://github.com/mozilla-mobile/android-components/pull/230

**Closed by boek** 2018-05-25 16:39 UTC
Labels: P5, help wanted
