### ISSUE TITLE
Users are not unenrolled from Focus for Android Nimbus experiments if they disable “Send usage data”

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/focus-android#6083] opened 2021-12-16 17:43 UTC
**[Affected Versions]:**
- Firefox Focus 96.0.0-beta2 (Build #353491706, 96.0.20211212185725)

**[Affected Platforms]:**
- Samsung Galaxy S8

**[Prerequisites]:**
- Be enrolled in at least one Nimbus study for Focus.

**[Steps to reproduce]:**
1. Go to Settings > Privacy & Settings and disable “Send usage data”.
2. Close and reopen the app. 
3. Go Settings > Privacy & Settings > Studies and observe if you are still enrolled in a study.

**[Expected result]:**
- You have been unenrolled from the study.

**[Actual result]:**
- You are still enrolled in the study.

**[Notes]:**
- The issue is not reproducible for Firefox for Android.
- The issue is also reproducible for Firefox for Desktop.

**Comment by ionutbedregeanu** [comment] 2021-12-17 08:54
Closing as duplicate of https://github.com/mozilla-mobile/focus-android/issues/6084

**Comment by ionutbedregeanu** [comment] 2021-12-17 10:36
After a discussion with @heres-maria we decided that this ticket should be reopened since expose a different scenario

**Comment by ionutbedregeanu** [comment] 2021-12-20 08:58
@amedyne @jonalmeida Should we be unrolled from studies and switch Studies to off if Send usage data is disabled?
I also took a look in Fenix and I noticed that we don't do that, we can disable "Usage and technical data", "Marketing data" without affect the state of Studies.

**Comment by jonalmeida** [comment] 2021-12-21 16:08
I'd say, that we should follow what Fenix does in that case.

**Comment by ionutbedregeanu** [comment] 2021-12-23 08:36
So I will close this ticket since is not the expected behaviour

**Closed by ionutbedregeanu** 2021-12-23 08:36 UTC
