### ISSUE TITLE
Hiding navbar messes with the site's content.

### ISSUE THREAD

**Issue by CrimsonFork** [mozilla-mobile/focus-android#936] opened 2017-07-14 19:56 UTC
When the navbar is shown it makes the equally big part of the actual site at the bottom not being shown.

The biggest problematic here comes with sites wich have elements sowing up only if one scrolls up, like [this one](https://designschool.canva.com/blog/visual-hierarchy/).

My suggestion here is to either make the navbar style="position: fixed;"-like or actually rather show it the whole time, like ff, orfox and icecat do, it doesn't require that much space, even on my 480x854 screen.

**Comment by bbinto** [comment] 2017-11-21 17:06
Is this still an issue for you or can we close this issue. Thanks

**Comment by OffifialMITX** [comment] 2017-11-22 08:45
Now there are no problems with unhiding it but it can't completely hide, which is still better than it was before.![A](https://i.imgur.com/IR5GhjM.png) ![B](https://i.imgur.com/UaWfdpo.png)

**Comment by lobontiumira** [comment] 2021-11-26 07:53
@CrimsonFork is this an issue for you on the latest Focus build?
The behavior on the Focus Nightly from 11/26 with Google Pixel (Android 10) is:

https://user-images.githubusercontent.com/40694158/143545973-0f3ed12d-352b-44a6-9604-b28e106dae79.mp4

Thanks!

**Comment by CrimsonFork** [comment] 2021-11-26 11:42
The issue may or may not be gone, in the 95.0.0 beta5 build it visually seems fine however there seems to still be difficulty interacting with bottom elements. E.g. on the given site I couldn't click the accept cookies button other than by clicking its top left corner wile in landscape.

Enabling layout bounds in developer settings suggests that it may be the trashcan icon.

Furthermore, trying to select text within that blue window selects text noticeably above the finger position, a behavior absent elsewhere.

I can't be sure whether it's still the same issue though.

Android 6 tablet @1280x800, unknown DPI

**Comment by lobontiumira** [comment] 2022-02-18 09:05
@CrimsonFork the trashcan has been moved now to the toolbar, so the interactions with the pages should be without issues.
I will close this ticket, since the initial issue is no longer reproducible.

Please feel free to file a new issue regarding the text selection.
Thank you!

**Closed by lobontiumira** 2022-02-18 09:05 UTC
Labels: P5
