### ISSUE TITLE
BUG: Browsing history cleared when returning to Focus at multitasking menu

### ISSUE THREAD

**Issue by huuhaa** [mozilla-mobile/focus-android#2004] opened 2017-12-17 15:01 UTC
This might be part of #2005 

How to reproduce:

1) Read some article by using Firefox Focus
2) Switch to another app, maybe lock the screen for a while, open screen and use tjat anorher app (ie. Whatsapp) for a while
3) Open multitasking menu and  tap Focus (you can see the page is open ,not using stealh mode) and when tappinng to open Focus with that site again you just get messaga Browsing history s cleared (or similar).

This doesn't happen all the time, in fact most of times everything works as should, but once in a while this is the result.

PS. Sorry if there's a report for this already, didn't find with quick search.

**Comment by mcomella** [comment] 2017-12-19 21:06
Note: following up in the related issue: https://github.com/mozilla-mobile/focus-android/issues/2005#issuecomment-352886151

**Comment by lobontiumira** [comment] 2021-10-04 13:59
I was not able to reproduce this behavior for several months now.
I'll close this issue.
Please feel free to open a new one if you encounter this issue again.

**Closed by lobontiumira** 2021-10-04 13:59 UTC
Labels: P5
