### ISSUE TITLE
Klar+GeckoView: fails to display a date picker

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#2226] opened 2018-03-05 14:47 UTC
Build: Klar+GeckoView 4.0
Devices:
Google Pixel (Android 8.0)
Samsung Galaxy S8 (Android 7.0)
HTC Desire 820 (Android 6.0.1)

STR:
1. Go to https://daleharvey.github.io/testapp
2. There are 2 date/time pickers under the "Get location" button. Observe the first.

Expected result: A date picker should be displayed.

Actual result: The first date picker is not displayed.

**Comment by ekager** [comment] 2018-03-07 19:38
I cannot reproduce with most recent master

**Comment by sv-ohorvath** [comment] 2018-03-09 09:04
I can still reproduce this with any device on the latest Klar+Gecko build (app-klar-gecko-arm-beta-signed-aligned.apk)

![klar gecko](https://user-images.githubusercontent.com/4037709/37199119-5c4e0294-2389-11e8-87bd-9dc683f53ce1.png)
![focus](https://user-images.githubusercontent.com/4037709/37199120-5c6c8002-2389-11e8-8550-e940cb76bf6a.png)

**Comment by ekager** [comment] 2018-03-09 19:01
Hey @snorp it looks like GV doesn't currently support just Date prompts? (The first drop down).
The second is a Date+Time picker which is supported.

**Comment by ekager** [comment] 2018-03-15 23:32
https://bugzilla.mozilla.org/show_bug.cgi?id=1446202

**Comment by ekager** [comment] 2018-04-18 21:51
Should be closed by #2380 :)

**Closed by ekager** 2018-04-18 21:51 UTC
Labels: Klar+Geckoview, bug
