### ISSUE TITLE
Navigating to Settings=>Mozilla=>About Firefox Focus returns a blank page

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/focus-android#4335] opened 2019-08-19 20:54 UTC
## Steps to reproduce
-Open Focus on GeckoView
-Go to Settings=>Mozilla=>About Firefox Focus

### Expected behavior
-See the about page

### Actual behavior
-Returns a blank page

**This is a [GV bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1556540) but we can address it with a workaround **

**Comment by cadeyrn** [comment] 2019-08-19 20:58
Duplicate of #4299.

**Comment by vesta0** [comment] 2019-09-13 18:36
This is also fixed. @colintheshots can we close this?

**Comment by colintheshots** [comment] 2019-09-20 17:47
Yes, this was fixed. Closing.

**Closed by colintheshots** 2019-09-20 17:47 UTC
Labels: Geckoview🦎, P1, Upcoming release
