### ISSUE TITLE
about:blank appears in the URL bar before a site loads and places it's actual URL (Focus with GeckoView)

### ISSUE THREAD

**Issue by MkllTech** [mozilla-mobile/focus-android#4081] opened 2019-01-01 16:35 UTC
## Steps to reproduce
Open Firefox Focus with GeckoView enabled and load any webpage.
### Expected behavior
Firefox Focus should display the proper URL for the loading webpage and keep it there while loading and after rendering.
### Actual behavior
Firefox Focus shows about:blank in the URL bar during initial navigation to webpage, then when the page renders about:blank is replaced by the webpage's actual URL.
### Device information

* Android device: Samsung Galaxy On5 (Android 6.1 Marshmallow)
* Focus version: 8.0.5 (Build #323663040 - 64.0.20181214004633)

**Comment by cpeterso** [comment] 2019-01-02 17:56
I filed a GeckoView bug:

https://bugzilla.mozilla.org/show_bug.cgi?id=1517289

**Comment by cpeterso** [comment] 2019-01-02 19:20
@vesta0 We can close this issue as a dupe of Focus issue #3473 and existing GeckoView bug https://bugzilla.mozilla.org/show_bug.cgi?id=1447406.

**Closed** 2019-01-02 19:31 UTC
Labels: Geckoview🦎, P2
