### ISSUE TITLE
Cannot open deep links

### ISSUE THREAD

**Issue by Noitidart** [mozilla-mobile/focus-android#1757] opened 2017-11-21 00:05 UTC
Links that pop open apps are not working in Firefox focus. I only tested with my app which I am currently developing.

About deep links with a nice 5min video - https://developer.android.com/studio/write/app-link-indexing.html

**Comment by pocmo** [comment] 2017-11-21 10:45
We do not pop out of Focus on purpose. Does your app show up in the "Open with.." overlay?

**Comment by Noitidart** [comment] 2017-11-21 14:27
@pocmo
Oh I see. Should I close this out? - yes when clicking on a link in other browsers it shows "Open with". and gives options.

**Comment by pocmo** [comment] 2017-11-21 15:19
We can close this as a duplicate of #829.

We do not switch to other apps immediately to avoid "leaking" the current browsing session to other apps without the user's consent.

**Closed by pocmo** 2017-11-21 15:19 UTC
